### ISSUE TITLE
Graph interpretation

### ISSUE THREAD

**Issue by Itrustsecurity** [securestate/king-phisher#102]
Hello, 
On the Compagne Dashboard, whats the meaning of :  
Unique visits Graph
Unique credentials Graph

We are preparing for  a phishing compagne , and we will send emails to a distribution adresse liste ( on exchange server) isit preferable to use @liste or by user email @adresse, and whats the difference
Let you know that we've a great number of users

**Comment by zeroSteiner** [comment]
Unique means not repeated. If a user clicks the link in a message multiple times then it will increment the over all visit counter, but *not* the unique visit count. Same thing for credentials, unique credentials are counted separately from over all. I'll add this to the wiki documentation.

For the second question, I would recommend sending to the individual email addresses. The reason why is you'll know exactly who opened the email etc. Also if you have their name available then it can be used in the templates automatically.
