### ISSUE TITLE
Emergency King-phisher error 

### ISSUE THREAD

**Issue by Itrustsecurity** [securestate/king-phisher#105]
## Issue Description
i've create a phishing compagne 
KP work good befor starting 
when i restart the service , the error below is returned , and unable to start the service : 

i've change the kin_phisher user postgres password and reload the config but the same error appear
```
[root@www king-phisher]# sudo ./KingPhisherServer -L DEBUG server_config.yml
DEBUG    king phisher version: 1.3.0-beta (rev: 3102b148) python version: 2.7.5
INFO     listening on 0.0.0.0:80
INFO     0.0.0.0:80 - serving files has been enabled
INFO     initializing database connection with driver postgresql
DEBUG    postgresql service is already running via systemctl
[root@www king-phisher]# Traceback (most recent call last):
  File "./KingPhisherServer", line 216, in <module>
    sys.exit(main())
  File "./KingPhisherServer", line 168, in main
    king_phisher_server = server.build_king_phisher_server(config)
  File "/opt/king-phisher/king_phisher/server/server.py", line 98, in build_king_phisher_server
    server = ServerClass(config, HandlerClass, address=address, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/opt/king-phisher/king_phisher/server/server.py", line 761, in __init__
    self.database_engine = db_manager.init_database(config.get('server.database'), extra_init=True)
  File "/opt/king-phisher/king_phisher/server/database/manager.py", line 237, in init_database
    inspector = sqlalchemy.inspect(engine)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/inspection.py", line 63, in inspect
    ret = reg(subject)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 139, in _insp
    return Inspector.from_engine(bind)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 134, in from_engine
    return bind.dialect.inspector(bind)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 1870, in __init__
    reflection.Inspector.__init__(self, conn)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/reflection.py", line 109, in __init__
    bind.connect().close()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2018, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 72, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2104, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 318, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  Ident authentication failed for user "king_phisher"
```
Let you know that i've verify the data base and the user king_phisher is the owner of the data base king_phisher, i've  changed the database user passeword and update the config_file , but the same error is returned  
can you help us to troubleshoot the probleme we've started the compagnemail sending  and we are on the begining of the liste

**Comment by zeroSteiner** [comment]
It's a problem with the Postgresql authentication. You need to double check the credentials and the pg_hba.conf file. Details of how the pg_hba.conf file is supposed to be setup are in the wiki on the Database page.

**Comment by Itrustsecurity** [comment]
i know i've a good configuration but i dont know why its not authentified
postgresql://king_phisher:rootkp1234@localhost/king_phisher

can you tell me more about troubleshooting the probleme

**Comment by zeroSteiner** [comment]
Whatever changes have been made between when the King Phisher server ran last and now need to be reverted. It's clearly a failure in the Postgresql authentication. In the `pg_hba.conf` file you need to make sure there is a line similar to `host     king_phisher    king_phisher   127.0.0.1/32            md5`. Additionally you'll want to restart the posgresql service to ensure that changes take affect.

**Comment by Itrustsecurity** [comment]
he line exist,  how can i test the connexion to postgres;

**Comment by Itrustsecurity** [comment]
i've changed the king_phisher user password and then update it , and restart the services
but the probleme persiste,

**Comment by zeroSteiner** [comment]
I'm not going to be able to assist you much more than I have. The issue is with your database connection. You need to look at trouble shooting that with the help of the Postgresql documentation. Once again, if the server worked recently (as it appeared to have last week) you should look at undoing any changes that have been made since then.

I did a quick Google search for "psycopg2 ident authentication failed for user" and the [first result from stackoverflow](http://stackoverflow.com/questions/23915877/postgresql-ident-authentication-failed-for-user-different-than-dbuser) seems relevant. Additionally I do know that the postgresql server configuration file can be picky about the order in which the definitions are made. Another thing you can try is allowing md5 authentication for all users and all databases:
```
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                     md5
```

Finally, once again I would like to remind you that being an open source project we can't always provide troubleshooting support.

**Comment by Itrustsecurity** [comment]
i've succed to correct the connexion db error see attached file but the probleme persist the server not started
![pg connexion](https://cloud.githubusercontent.com/assets/18242158/14787837/22e1d3ba-0afd-11e6-90ae-97fc321703fd.PNG)

**Comment by zeroSteiner** [comment]
That doesn't make sense. You succeeded to correct the connection db error but the problem persists? In the screen host it shows that psql throws an `Ident authentication failed` error the first time but then not the second. Presumably whatever changes caused it to work the second time would have fixed the ident error you were experiencing with the server.

**Comment by Itrustsecurity** [comment]
Hello @zeroSteiner 
i've create new DB user and new DB on postgres, i've add the config lines, here is the configuration fil 
---------------------
#
# King-Phisher Server Configuration
#

logging:
  file: /var/log/king-phisher.log
  level: warning
  console: false

server:
  # Bind address information
  address:
    host: 0.0.0.0
    port: 80

  # Server RPC authentication related settings
  #authentication:
    # How long to cache authentication information in the server process
    #cache_timeout: 10m
    # Require authenticating users to be a member of the specified group
    #group: king-phisher
    # The service to use for PAM authentication
    #pam_service: sshd
    # How long an authenticated RPC session should be valid for after no
    # requests have been received.
    #session_timeout: 30m

  # A cookie to retrieve the client's IP from, useful when a proxy is in place
  # client_ip_cookie: X-Real-IP

  # The name of the cookie used to track users
  cookie_name: KPID

  # Specify an additional search path for server data files
  data_path: /opt/king-phisher

  # The SQLite3 database file to use, the folder needs write permissions
  # WARNING: SQLite3 is not fully supported as of version 0.1.6, see
  # https://github.com/securestate/king-phisher/wiki/Database#sqlite for more
  # details
  # database: sqlite:////var/king-phisher/king-phisher.db

  # The Postgres database to use
  # database: postgresql://king_phisher:rootkp1234@localhost/king_phisher
  # database: postgresql://king:root123456kp@localhost/kingdb
  # database: postgresql://king_phisher:rootkp1234@localhost/king_phisher
  # database: postgresql://king_phisher:rootkp1234@localhost/king_phisher
    database: postgresql://kingphisher:pass1234kp@localhost/kingphisher

  # Fork the server process into the background
  fork: true

  geoip:
    # The location of the GeoLite2 City database
    database: /var/king-phisher/geoip.mmdb

  # Set a file to write the PID to
  pid_file: /var/run/king-phisher.pid

  # Require an ID associated with a campaign to load pages
  require_id: false

  rest_api:
    enabled: false
    # Networks which are authorized to use the REST API
    networks:
      - 10.0.0.0/8
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 10.100.0.0/24
    # When null the token will be randomized at run time
    token: null

  # Configure the server header value
  #server_header: Apache/2.4.9 (Unix)

  # Set the opened timestamp on the first visit if it's null
  set_message_opened_on_visit: true

  # Drop privileges to the specified user
  setuid_username: nobody

  # SSL settings
  #ssl_cert: /path/to/ssl.crt
  #ssl_key: /path/to/ssl.key

  # Configure the image file name used to track opened emails
  tracking_image: email_logo_banner.gif

  # Use subfolders in the web_root which correspond to vhost names
  vhost_directories: false
  web_root: /var/www/html

-------------------------------------------
i've add  to pg_hba.conf file  the following line:

host     kingphisher    kingphisher   127.0.0.1/32            md5

find attached the error
![error 26042016](https://cloud.githubusercontent.com/assets/18242158/14810376/9296facc-0b8a-11e6-9ed1-c1e548c77b7c.PNG)

**Comment by zeroSteiner** [comment]
The error message is now complaining that your configuration file is incorrectly formatted.

**Comment by Itrustsecurity** [comment]
really i dont know whats the probleme exaclty because i didn't change great thing, just data base line on the config file ,
Ok , i have a question i want to run just one compagne ( for 14000users) and i want to use sqlit , because i reinstall KP and it works good using SQLite,
does the SQLit support data from 14000 users  i dont know what contain the database but i know that sql lit support until 2gb of data  please return me ASAP

**Comment by zeroSteiner** [comment]
Probably, but using SQLite is not recommended. I'm glad to hear that you got it working though! Good luck in your testing.
