### ISSUE TITLE
Add Jinja variable for tracking number of credentials submitted

### ISSUE THREAD

**Issue by coldfusion39** [securestate/king-phisher#113]
Add a Jinja variable that can be used to determine if a client has submitted credentials. Either return True or False and/or return the number of unique credentials the client has submitted.

Ideally this would be used like the "client.visit_count" variable to show different page content if the client has submitted credentials or has submitted > X unique credentials.

**Comment by zeroSteiner** [comment]
@wolfthefallen This should be added as `client.credential_count`. It will require changes in the following locations.

* The value should be added [here](https://github.com/securestate/king-phisher/blob/master/king_phisher/server/server.py#L276-281).
* Then the wiki Templates page will need to be updated.
* The [page_variables.txt](https://github.com/securestate/king-phisher/blob/master/data/server/king_phisher/page_variables.txt) demo file should be updated with the new var.

**Comment by zeroSteiner** [comment]
Added in commit 12c7456, thanks for the suggestion @coldfusion39!
