### ISSUE TITLE
Jinja Error

### ISSUE THREAD

**Issue by bucky67gto** [securestate/king-phisher#120]
Server is running and tested.  Now looking to implement.

get the following error in log:

2016-06-13 10:47:36,502 AdvancedHTTPServer                                 ERROR    jinja2 template /var/www/index.html render failed: UndefinedError 'inline_image' is undefined
2016-06-13 10:51:46,524 AdvancedHTTPServer                                 ERROR    jinja2 template /var/www/index.html render failed: UndefinedError 'inline_image' is undefined
2016-06-13 10:57:44,681 AdvancedHTTPServer                                 ERROR    jinja2 template /var/www/index.html render failed: UndefinedError 'url' is undefined
2016-06-13 10:57:53,594 KingPhisher.Server                                 WARNING  processing shutdown request
2016-06-13 10:58:06,669 AdvancedHTTPServer                                 ERROR    jinja2 template /var/www/index.html render failed: UndefinedError 'url' is undefined

web page i:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Sorry</title>

  </head>
<!DOCTYPE html>
<html>
    <body style="background:#1C2127; height:700px;">
        <table style="width:900px; border:1px solid #666; border-radius:5px; background:#DDD; margin:0 auto; text-align:center; height:500px;">
            
            <tr>
                <td style="font-size:24px; padding:20px;"><img src="sorry.jpg" /></td>
                <td style="font-size:24px; padding:20px;">you did not win, but thanks for all you do</td>
            </tr>
                        
        </table>
    </body>
    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /> 
    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
    {{ url.tracking_dot }}
</html>

I am sure it is something simple.  works fine with straight html, but fails the jinja

thanks

**Comment by guitarmanj** [comment]
Try adding the inline image by right clicking in the editor window on King Phisher, use {{ inline_image(path.to.img) }} instead of the url.



[https://www.securestate.com/Media/images/default-source/Team/jschoeneman_email.png]
[https://www.securestate.com/Media/images/default-source/gallery/ss_securestate.png]

Jeremy Schoeneman

Senior Analyst

SecureState

p:

216.927.8237  m: 440.532.3634

w:

www.securestate.com<http://www.securestate.com>  e: jschoeneman@securestate.com<mailto:jschoeneman@securestate.com>

[https://www.securestate.com/Media/images/default-source/gallery/ss_twitter_email.png]<https://twitter.com/__Shad0wman__>  [https://www.securestate.com/Media/images/default-source/gallery/ss_linkedin_email.png] <http://%20%20%20%20https://www.linkedin.com/in/jeremy-schoeneman-59662331>



________________________________

**Comment by bucky67gto** [comment]
no dice, but even if it worked, would that have provided the tracking of clicks on the email?

**Comment by zeroSteiner** [comment]
That's a message template and it looks like you're trying to render it as a page template. It's specifically complaining that `url` is undefined which is because it's a message variable not a page variable.

**Comment by bucky67gto** [comment]
thanks,  that makes sense, What would I need to add to the message template and also to the page template so that they link and I get clickbacks?

**Comment by zeroSteiner** [comment]
I would recommend using one of the basic templates in the king-phisher-templates repository. There's also additional details on creating templates for a campaign in the wiki.

**Comment by bucky67gto** [comment]
Worked Like a champ.  thanks
