### ISSUE TITLE
Sending with postfix

### ISSUE THREAD

**Issue by bucky67gto** [securestate/king-phisher#121]
I can send to individual email accounts fine, but when I use a csv file I get the following:

Skipped checking the SPF policy because the SMTP server address could not be detected.

is this a postfix issue?

**Comment by zeroSteiner** [comment]
It's not a postfix issue. I'm assuming that you are running the postfix server on your local host?

**Comment by bucky67gto** [comment]
yes.  tried changing the client SPF record check type with no results - also no error, just a 0 messages sent.  Only does this with csv.

**Comment by zeroSteiner** [comment]
Unless the SPF check is set to strict, (which isn't the default) a fail should not prevent messages from being sent. I would double that check the format of your CSV file is correct with all three required columns. Invalid lines that miss one or more fields are skipped and it sounds like that may be happening here.

**Comment by bucky67gto** [comment]
csv format is set similar to below:

joe,smith,jsmith@none.com
sam,edwards,sedwards@none.com
bill,jones,bjones@none.com

should they all be in one string or in this format with one entry per line.  also, there are no spaces after the comma if that makes any difference.

**Comment by bucky67gto** [comment]
the file was corrupted and had some very strange characters in it.  I removed them and it is fine.  thanks for pointing me in the right direction.

can close

**Comment by zeroSteiner** [comment]
No you must have the name fields although they can be blank. There is an optional fourth field that can be omitted however which is the target user's department name like IT, HR etc.

**Comment by bucky67gto** [comment]
Thanks for pointing me in the right direction and answers to questions.....
