### ISSUE TITLE
Website Cloning not capturing credentials

### ISSUE THREAD

**Issue by b3nny0** [securestate/king-phisher#122]
## Issue Description
After cloning a webpage and deploying a campaign using it as the landing page, user credentials are not being captured.  The campaign is recording the click from the email, but the credentials are not captured.  I added in the <script src="/kp.js" type="text/javascript"></script> line into the header, but still no luch

## Reproduction Steps
1. Log into KingPhisher
2. Tools | Clone Webpage
3. Target URL = http://website.com
4. Move cloned site to /var/www
5. Set the Web Server URL to the newly cloned site
6. Send the email with the link to the cloned site
7. Open my email, click the link, the cloned page comes up.  Enter credentials, and am redirected to the actual page.
8. Go into View Campaign | Credentials, nothing is captured

## Environment Details
Host OS: Ubuntu 14.04LTS

## Error Details / Stack Trace
No errors, just nothing captured

**Comment by zeroSteiner** [comment]
The HTML login form most likely needs to have the parameter names changed. They need to be username and password. Things like email, login etc. need to be changed.

**Comment by anhp11** [comment]
@zeroSteiner: Spencer, would you mind looking at my landing page? I have changed all the necessary values from userid to username, and I'm still not seeing any credentials. Also, my password field is correctly identified as 'password', shouldn't I still be able to see that regardless of username?

`<!DOCTYPE html>
<html  lang="en-us">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	


	<title>Sign in to Concur | Concur Solutions</title>
	<link rel="stylesheet" type="text/css" href="/csscache/minified/565258b69cdc3f8b5743b7c60bde530c0611580f_dd1f06e2a5af33ce21d7843e9d84c3e6ea0d57cea0.css?fn=/static/less/cnqr-view/signin.less&amp;cachekilla=DD1F06E2A5AF33CE21D7843E9D84C3E6EA0D57CEA0">
<link rel="stylesheet" type="text/css" href="/csscache/minified/ebfe82176487d8a31b24a49fc5013de31c8688fb_dd1f06e2a5af33ce21d7843e9d84c3e6ea0d57cea0.css?fn=/static/less/cnqr-global/manifest-bootstrap-3.3.1-11.less&amp;cachekilla=DD1F06E2A5AF33CE21D7843E9D84C3E6EA0D57CEA0">
<link rel="stylesheet" type="text/css" href="/csscache/minified/050c8a2c291c0b45eac6e2f47b9fa8d2ee6dcf4f_dd1f06e2a5af33ce21d7843e9d84c3e6ea0d57cea0.css?fn=/static/less/cnqr-global/manifest-cnqr-11.less&amp;cachekilla=DD1F06E2A5AF33CE21D7843E9D84C3E6EA0D57CEA0">
<link rel="stylesheet" type="text/css" href="/csscache/minified/fe464731024c39aacf3468e5149f8aa903b503d2_dd1f06e2a5af33ce21d7843e9d84c3e6ea0d57cea0.css?fn=/static/less/cnqr-javascript/manifest-prototypejs-11.less&amp;cachekilla=DD1F06E2A5AF33CE21D7843E9D84C3E6EA0D57CEA0">

	
<script type="text/javascript">

	if (!window.CNQR) {window.CNQR = {}}
	var pageStartTime = new Date();
	var userDatePreference = 0;
	var userMilitaryTime = 0;
	var userTimePreference = 0;
	var userNumberPreference = 0;
	var negativeNumberFormat = 0;
	var negativeCurrencyFormat = 0;
	var currencySymbolLocation = 0;
	var defaultEmpCurrencyCode = 'USD';
	var userWeekDayStartPreference = 1;
	var sessionLockTime = 0;
	var sessionLogoutTime = 7200;


	var OT_DateFormat_MDY_slash = 0;
	var OT_DateFormat_MDY_dot = 1;
	var OT_DateFormat_MDY_hyphen = 2;
	var OT_DateFormat_DMY_slash = 3;
	var OT_DateFormat_DMY_dot = 4;
	var OT_DateFormat_DMY_hyphen = 5;
	var OT_DateFormat_YMD_slash = 6;
	var OT_DateFormat_YMD_dot = 7;
	var OT_DateFormat_YMD_hyphen = 8;

	var otUseStrict = true;
	var otCacheKilla = '14F20EE28E190B4C94123D9D369FC21BB89E1A3FA0';
	var disableCookies = 0;
	CNQR.IsGovtSite = ('False' == 'True');
	CNQR.isOldIE = false;
	CNQR.IPMForOldIEDisabled = false;
	CNQR.disableMetrics = false;

	CNQR.cgeUIVersion = '0';
	CNQR.ConcurAccessible = ('False' == 'True');
	CNQR.ProdStatus = 'prod';
	CNQR.noConflict = ('' == 'True');
	if (!CNQR.config) {CNQR.config = {}}
	CNQR.config.localizationMode = false;
	CNQR.IsGateway = true;
	CNQR.Environment = "ASP";
	CNQR.companyName = "";
	CNQR.analyticsId = ''; 
	CNQR.gatewayPreviewDaysRemaining = 0;
	CNQR.disableJSLogger = ('False' == 'True');

	

	CNQR.automationMode = 0;
	CNQR.brandingId = 11;
	CNQR.ipmEnabled = ('False' == 'True');	
	CNQR.logIpmActionEnabled = ('False' == 'True');
	//ipmOverlaysPermitted determines whether we can show ipm popups/tooltips - it will be set to false later if a non-ipm popup is displayed (e.g. gateway tourtip or tripitpro sign-up)
	CNQR.ipmOverlaysPermitted = ('False' == 'True');
</script>
<script src="/jscache/usermessage.js?cachekilla=DBE19FCA55EF43A05E4433AE942798E8E54A0623A0" type="text/javascript"></script>
<script charset="UTF-8" src="/i18n/F7380A90DA91E22841F27558B07842F0CDD641D3_en-us.js?lang=en%2Dus&amp;cat=common%2Csmalljs&amp;msk=F7380A90DA91E22841F27558B07842F0CDD641D3" type="text/javascript"></script>
<script src="/jscache/minified/DC90B7630B00FA9776263F279313287A43C3D1EE_14F20EE28E190B4C94123D9D369FC21BB89E1A3FA0.js?jslist=/j/functions.js&amp;cachekilla=14F20EE28E190B4C94123D9D369FC21BB89E1A3F" type="text/javascript"></script>

	<script type="text/javascript">
		otLogFrame();
	</script>

	

	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<meta name="description" content="Welcome to Concur. Log in to your world class Concur solution here and begin managing business travel and expenses." />
	
		<meta name="apple-itunes-app" content="app-id=335023774">
	
	<link rel="SHORTCUT ICON" href="https://www.concursolutions.com/favicon.ico?manualcachekilla=20151130"/>
	

</head>

<body  lang="en-us" id="cnqrBody" class="signin signin-5 cnqr-theme-11">


<div id="overDiv" aria-haspopup="true" aria-live="assertive" style="position:absolute; visibility:hidden;z-index:1;" tabindex="-1"></div>

	
<div class="container cnqr-app-header">
		<div class="row">
	



		<div id="cnqr-navbar-primary">
		
		
		<div class="navbar-outer">
			<ul class="nav navbar-nav">
				<li class="cnqr-nav-logo">
							<i class="icon-logotype" aria-hidden="true"></i>
				</li>
			</ul>
		</div>
	</div>

		</div>
	</div>
	


<form class="nomargins" name="frmMain" id="frmMain" action="https://www.concursolutions.com/verify_login.asp" method="POST" onsubmit='return false;' target='_top' autocomplete='off'>
	

	

	<div class="container cnqr-app-content" id="cnqr-app-content">
		<div class="row">
			
			
				<div class="col-xs-12">
					<h1 class="screen-reader-only">Sign in to Concur | Concur Solutions</h1>
					


<input type="hidden" name="framed" value="" />
<input type="hidden" name="screenres" value="" />
<input type="hidden" name="langClicked" value="" />
<input type="hidden" name="loginurl" value="/signin.asp" />
<input type="hidden" name="hpo" value="" />
<input type="hidden" name="cte" value="" />
<input type="hidden" name="logindomain" id="logindomain" value="" />
<input type="hidden" name="entity" value="" />



<div class="row">
	 <div class="col-md-4 col-sm-5 col-xs-12" id="sidebar1">
		<div class="h1">Sign In</div>

						       

		<div id="cnqr-validation-error" class="field-validation-error" style="display:none"></div>
			
		<div class="cred-container">
			<div class="cred-container-row">
				<label for="username">User Name</label><br>
				<input name="username" id="username" type="textusername" value="" maxlength="128" class="form-control input-lg cnqr-full-width cnqr-capscheck-username">
			</div>

			<div class="cred-container-row">
				<label for="password">Password</label><br>
				<input id="password" name="password" type="password" maxlength="60" class="form-control input-lg cnqr-full-width cnqr-capscheck-password" />
			</div>

			<div id="cnqr-capswarning" class="field-validation-error" style="display:none">
				Warning: CapsLock is On!<br />
				Passwords are case sensitive.
			</div>

			
			<div class="cred-container-row">
					
				<input id="rememberLogin" name="rememberLogin" type="checkbox" >
				<label for="rememberLogin">Remember user name on this computer</label>
			</div>
			

			<div class="cred-container-row clearfix">
				<div class="pull-right">
					
					<input id="btnSubmit" name="btnSubmit" class="btn btn-lg btn-primary" type="button" value="Sign In" onclick="checkUserid();">
				</div>
			</div>
		</div>

		<p><a role="button" href="javascript:forgotPassword(1)">Forgot your user name?</a></p>
		<p><a role="button" href="javascript:forgotPassword()">Forgot your password?</a></p>

		
		<div class="lang-container">
		
	<label for="selectLang" id="lblselectLang">Change language</label><br>
	<select id="selectLang" class="form-control cnqr-full-width" onchange="return selectLanguage(this.options[this.selectedIndex].value)">
	
            <option  selected value="en-us">English (US)</option>
        
            <option  value="en-gb">English (UK)</option>
        
            <option  value="cs">Čeština</option>
        
            <option  value="da">Dansk</option>
        
            <option  value="de">Deutsch</option>
        
            <option  value="fr">Français</option>
        
            <option  value="fr-ca">Français canadien</option>
        
            <option  value="es">Español</option>
        
            <option  value="es-la">Español (Latinoamérica)</option>
        
            <option  value="it">Italiano</option>
        
            <option  value="hu">Magyar</option>
        
            <option  value="nl">Nederlands</option>
        
            <option  value="no">Norsk</option>
        
            <option  value="pl">polski</option>
        
            <option  value="pt-br">Português (Brasil)</option>
        
            <option  value="fi">Suomi</option>
        
            <option  value="ru">Русский</option>
        
            <option  value="sv">Svenska</option>
        
            <option  value="ja">日本語</option>
        
            <option  value="zh-tw">繁體中文</option>
        
            <option  value="zh-cn">中文</option>
        
            <option  value="ko">한국어</option>
        </select>
		</div>
		

	 </div>

	 
</div>




				</div>
			
		</div>
	</div> 

	
		

	<script type="text/javascript">

		otLogFrame(true);

		bSubmittedAlready = false;

		var domainpattern = /^(.+)@(.+)$/; // used in several places

		var d = new Date();
		if (d.getMonth() == 5 && d.getDate()==4){
			document.getElementsByTagName('body')[0].className+= " may4";
		}

		function getLoginID() {
			var theForm = document.frmMain;
			var username = theForm.username.value;	
			
			
	
			return username;
		}

		function checkUserid() {
			if (bSubmittedAlready){
				return;
			}

			var theForm = document.frmMain;
			var username = getLoginID();

			if (theForm){
				if (username == "") {
					showValidationError('Please enter a user name.');
					tryFocus(theForm.username);
					return false;
				} else if ((domainpattern.test(username) == false) && ("" == "" )) {  /* basic check for "@domain" */
					showValidationError('The user name is invalid. Please try again.');
					tryFocus(theForm.username);
					return false;
				} else if (theForm.password.value == ""){
					showValidationError('Please enter a password.');
					tryFocus(theForm.password);
					return false;
				} else {
					var bAllowSubmitPage = true;

					var rndBusyNum = false;
					if (rndBusyNum) {
						bAllowSubmitPage = false;
					}

					if (!bAllowSubmitPage) {
						var busyMsg = "The server is busy. Please retry your request in a few minutes.";
						showValidationError(busyMsg);
						return false;

					} else {
						theForm.screenres.value = screen.width + 'x' + screen.height;	
						theForm.submit();
						bSubmittedAlready = true;
					}
				}
			}
		}

		function dosubmit() {
			checkUserid();
		}

		// Enable enter key to submit form
		function userLogin(e) {
			e = (e || window.event);

			if (e.keyCode == 13) {
				checkUserid();
				return false;
			}
			return true;
		}

		function SetCursor() {
			var uname = $('username');
			if (!uname.value) {
				tryFocus($('username'));
			} else {
				tryFocus($('password'));
			}
		}
		
		function showValidationError(msg) {
			
			var _loginmsg = $("cnqr-login-error");
			if (_loginmsg) {
				_loginmsg.style.visibility = 'hidden';
				_loginmsg.style.display = 'none';
			}
			
			var _validationmsg = $("cnqr-validation-error");
			if (_validationmsg) {
				_validationmsg.innerHTML = msg;
				_validationmsg.style.visibility = 'visible';
				_validationmsg.style.display = 'block';
			}
		}

		function forgotPassword( forgotName ) {
			

			var parameters = {
				forgotName: ( !forgotName ? 0 : 1 ),	//	Ensure the sole argument is either 0 or 1:
				txtLoginID: getLoginID()				//	Grab the user's login id from the form & encode it:
			};

			

			CNQR.post( 'https://www.concursolutions.com/profile/send_password_hint.asp', parameters );
		}

		function selectLanguage(langCode){
			if (langCode){
				var url = document.location.href;
				if (url.indexOf("?") > 0 )	{
					if ( url.indexOf("lang=") > 0 ){
						url = updateUrlParameter(url, "lang", langCode);
					} else {
						url = url + '&' + "lang=" + langCode;
					}
				} else {
					url = url + '?' + "lang=" + langCode;
				}
				document.location.href = url
			}
		}

		function updateUrlParameter(url, param, value){
			var regex = new RegExp('('+param+'=)[^\&]+');
			return url.replace( regex , '$1' + value);
		}

		function redirectToIntuitLogin() {
			location = 'https://www.concursolutions.com/Net2/OpenId/IntuitOpenIdLogin.aspx';
		}

		
		function failNoticeOnload() {
			if ($('loginfailed')) {
				tryFocus($('loginfailed'));
			} else {
				if ($('govtext')) {
					tryFocus($('govtext'));
				}
			}
		}
		addEvent(window, "load", failNoticeOnload);

		

		(function(){
			function checkCapsLock(e){
				var 
					_e			= window.event || e,
					_kc 		= _e.charCode ? _e.charCode: (_e.keyCode ? _e.keyCode : _e.which),  
					_sk 		= _e.shiftKey?_e.shiftKey:((_kc == 16)?true:false),
					_msg 		= $("cnqr-capswarning"),
					letter		= String.fromCharCode(_kc),
					upper		= letter.toUpperCase(),
					lower		= letter.toLowerCase(),
					shift_key	= _e.shiftKey
				alt_key	= _e.altKey
				; 
			
				function _on(){if(_msg){_msg.style.visibility = 'visible';_msg.style.display= 'block';}}
				function _off(){if(_msg){_msg.style.visibility = 'hidden'; _msg.style.display= 'none';}}

				// If the upper and lower case characters are the same, then we have no way to know if capslock is on
				if(upper !== lower) {
					if( letter === upper && !shift_key ) {
						if(!alt_key){_on();}					
					} else if( letter === lower && !shift_key ) {
						_off();
					} else if( letter === lower && shift_key) {
						// Must be a Windows user!
						_on();
					} else if( letter === upper && shift_key ) {
						// Either caps lock is off, or the caps lock is on and they are on a Mac
						if( navigator.platform.toLowerCase().indexOf("win") !== -1 ) {
							// You are on Windows, so we know caps lock is off
							_off();
						} 
					} 
				} 
			};
			document.getElementById("username").onkeypress = function(e){checkCapsLock(e);} 
			document.getElementById("password").onkeypress = function(e){checkCapsLock(e);userLogin(e);} 
			SetCursor();
		})();

		// CORUI-362 'Thread was being aborted' errors after SU121 release
		// don't use pageIdleControl on the signin.asp page
		sessionLogoutTime = 0;
	</script>
	








<div class="container cnqr-app-footer">
	<div class="row cnqr-first">
		<div class="col-xs-12 col-md-6">
					<h6 class="cnqr-first"><span class="screen-reader-only">Concur</span><i data-icon="" class="icon-logotype" aria-hidden="true"></i></h6>

		</div>
		<div class="col-xs-12 col-md-6">
			
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-md-6">
			
		</div>
		<div class="col-xs-12 col-md-6 text-right">
				<p>&copy; Copyright 2016 - Concur - All Rights Reserved</p>
	<div id="login-history-popup"></div>

		</div>
	</div>

	

	
</div> 
	
		
<div id="endOfPage" class="end-of-page"><a href="#cnqrBody" class="screen-reader-only-focusable">End of page. Go to top of page</a></div></form>


</body>
</html>`

**Comment by zeroSteiner** [comment]
@anhp11 A username will be recorded without a password, but a password will not be recorded without a username. This is by design as a password isn't as useful without a username where as a username can be recorded without a password for King Phisher users that do not want to record passwords.

Your action on line 123 needs to be updated, it's POSTing your credentials to `https://www.concursolutions.com/verify_login.asp`.

**Comment by anhp11** [comment]
@zeroSteiner: Thanks Spencer! That worked. Sorry I kept raising these questions, but I've been able to pretty solidly grasp King-Phisher with your help these past 2 days!

**Comment by zeroSteiner** [comment]
I haven't gotten a response from the original poster in over a week so I'm going to close this out.
