### ISSUE TITLE
King Phisher not posting any information back when running campaign

### ISSUE THREAD

**Issue by anhp11** [securestate/king-phisher#125]
## Issue Description
I'm able to successfully set up a phishing campaign but was unable to get any information back (site tracking, username, password, etc.) when viewing the campaign. The only information available was the email message that I sent out. 

I have tried with a custom page cloned using the site cloner, and also with one of the Credentials attack template provided in this git and both failed.

Is there anything specific that I'm missing in terms of setting up the campaign and the phishing email?

## Environment Details
Server: Ubuntu 16.04 LTS
Client: Ubuntu 16.04 LTS (Also tried Windows client)

## Error Details / Stack Trace
![screen shot 2016-06-16 at 8 50 44 am](https://cloud.githubusercontent.com/assets/8727495/16117316/7d034eee-339f-11e6-868e-1e1cba777325.png)
![screen shot 2016-06-16 at 8 50 49 am](https://cloud.githubusercontent.com/assets/8727495/16117319/815fedda-339f-11e6-9b9e-a508be5caf73.png)
![screen shot 2016-06-16 at 8 50 55 am](https://cloud.githubusercontent.com/assets/8727495/16117324/843b5b48-339f-11e6-9070-3d7f33654f44.png)
![screen shot 2016-06-16 at 8 51 00 am](https://cloud.githubusercontent.com/assets/8727495/16117326/876a4ce8-339f-11e6-9a3a-42d794c0610a.png)

**Comment by zeroSteiner** [comment]
It sounds like the link you sent out in the one message was not clicked. For clarification, what were you expecting to be shown, do you have reason to believe that your landing page was visited and people submitted credentials?

Also did you verify that the link in your email was correctly set to your landing page? You could also check the server logs, which would contain information regarding any errors involving tracking.

**Comment by anhp11** [comment]
I tested going to the landing page directly, and also through the embedded link the email and I was able to go to both successfully. I sent the phishing test to my own email address, and was able to click, follow the link and enter my test credentials. However, when I go back to the client to view the campaign, I don't see anything posting back.

Does the email have to be specially crafted, besides the embedded hyberlink?

**Comment by zeroSteiner** [comment]
The landing page sets a cookie in the browser so subsequent visits do not require the message id. This  cookie is referred to as the visit id. You must always visit the page with a valid message id by clicking the link in order for the metrics to be tracked. Additionally, you probably want to double check that the message id with which you visited the page with is associated with the campaign you're currently looking at.

**Comment by anhp11** [comment]
So I did visit the page with clicking the link in the email message I created. But I still don't see anything posted back. I've used a few different tools, including Social Engineering Toolkit and I know that for their in-email tracking to work, I need to append a random string to the end of the embedded phishing URL. Is that something that I need to do in my crafted email here as well? I've been trying to look up documentation and can't hardly find anything specific to crafting emails.

My email.html file is as simple as this:
<a href="http://lbkingphisher/login">click here</a>

**Comment by zeroSteiner** [comment]
Kind of, King Phisher creates the ID for you and exposes it as a Jinja [template variable](https://github.com/securestate/king-phisher/wiki/Templates). You need to change your link to: `<a href="{{ url.webserver }}">click here</a>`. That will include the UID automatically and take the web page from the setting in the Message Configuration tab.

**Comment by anhp11** [comment]
That worked. So I assume we have to use variables in our email template instead of direct values.

**Comment by anhp11** [comment]
That worked on a built-in template. In the custom clone campaign, I got the tracking and statistic info, but not the username and password. 

here is the landing page:
`<!DOCTYPE html>
<html  lang="en-us">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	


	<title>Sign in to Concur | Concur Solutions</title>
	<link rel="stylesheet" type="text/css" href="/csscache/minified/565258b69cdc3f8b5743b7c60bde530c0611580f_dd1f06e2a5af33ce21d7843e9d84c3e6ea0d57cea0.css?fn=/static/less/cnqr-view/signin.less&amp;cachekilla=DD1F06E2A5AF33CE21D7843E9D84C3E6EA0D57CEA0">
<link rel="stylesheet" type="text/css" href="/csscache/minified/ebfe82176487d8a31b24a49fc5013de31c8688fb_dd1f06e2a5af33ce21d7843e9d84c3e6ea0d57cea0.css?fn=/static/less/cnqr-global/manifest-bootstrap-3.3.1-11.less&amp;cachekilla=DD1F06E2A5AF33CE21D7843E9D84C3E6EA0D57CEA0">
<link rel="stylesheet" type="text/css" href="/csscache/minified/050c8a2c291c0b45eac6e2f47b9fa8d2ee6dcf4f_dd1f06e2a5af33ce21d7843e9d84c3e6ea0d57cea0.css?fn=/static/less/cnqr-global/manifest-cnqr-11.less&amp;cachekilla=DD1F06E2A5AF33CE21D7843E9D84C3E6EA0D57CEA0">
<link rel="stylesheet" type="text/css" href="/csscache/minified/fe464731024c39aacf3468e5149f8aa903b503d2_dd1f06e2a5af33ce21d7843e9d84c3e6ea0d57cea0.css?fn=/static/less/cnqr-javascript/manifest-prototypejs-11.less&amp;cachekilla=DD1F06E2A5AF33CE21D7843E9D84C3E6EA0D57CEA0">

	
<script type="text/javascript">

	if (!window.CNQR) {window.CNQR = {}}
	var pageStartTime = new Date();
	var userDatePreference = 0;
	var userMilitaryTime = 0;
	var userTimePreference = 0;
	var userNumberPreference = 0;
	var negativeNumberFormat = 0;
	var negativeCurrencyFormat = 0;
	var currencySymbolLocation = 0;
	var defaultEmpCurrencyCode = 'USD';
	var userWeekDayStartPreference = 1;
	var sessionLockTime = 0;
	var sessionLogoutTime = 7200;


	var OT_DateFormat_MDY_slash = 0;
	var OT_DateFormat_MDY_dot = 1;
	var OT_DateFormat_MDY_hyphen = 2;
	var OT_DateFormat_DMY_slash = 3;
	var OT_DateFormat_DMY_dot = 4;
	var OT_DateFormat_DMY_hyphen = 5;
	var OT_DateFormat_YMD_slash = 6;
	var OT_DateFormat_YMD_dot = 7;
	var OT_DateFormat_YMD_hyphen = 8;

	var otUseStrict = true;
	var otCacheKilla = '14F20EE28E190B4C94123D9D369FC21BB89E1A3FA0';
	var disableCookies = 0;
	CNQR.IsGovtSite = ('False' == 'True');
	CNQR.isOldIE = false;
	CNQR.IPMForOldIEDisabled = false;
	CNQR.disableMetrics = false;

	CNQR.cgeUIVersion = '0';
	CNQR.ConcurAccessible = ('False' == 'True');
	CNQR.ProdStatus = 'prod';
	CNQR.noConflict = ('' == 'True');
	if (!CNQR.config) {CNQR.config = {}}
	CNQR.config.localizationMode = false;
	CNQR.IsGateway = true;
	CNQR.Environment = "ASP";
	CNQR.companyName = "";
	CNQR.analyticsId = ''; 
	CNQR.gatewayPreviewDaysRemaining = 0;
	CNQR.disableJSLogger = ('False' == 'True');

	

	CNQR.automationMode = 0;
	CNQR.brandingId = 11;
	CNQR.ipmEnabled = ('False' == 'True');	
	CNQR.logIpmActionEnabled = ('False' == 'True');
	//ipmOverlaysPermitted determines whether we can show ipm popups/tooltips - it will be set to false later if a non-ipm popup is displayed (e.g. gateway tourtip or tripitpro sign-up)
	CNQR.ipmOverlaysPermitted = ('False' == 'True');
</script>
<script src="/jscache/usermessage.js?cachekilla=DBE19FCA55EF43A05E4433AE942798E8E54A0623A0" type="text/javascript"></script>
<script charset="UTF-8" src="/i18n/F7380A90DA91E22841F27558B07842F0CDD641D3_en-us.js?lang=en%2Dus&amp;cat=common%2Csmalljs&amp;msk=F7380A90DA91E22841F27558B07842F0CDD641D3" type="text/javascript"></script>
<script src="/jscache/minified/DC90B7630B00FA9776263F279313287A43C3D1EE_14F20EE28E190B4C94123D9D369FC21BB89E1A3FA0.js?jslist=/j/functions.js&amp;cachekilla=14F20EE28E190B4C94123D9D369FC21BB89E1A3F" type="text/javascript"></script>

	<script type="text/javascript">
		otLogFrame();
	</script>

	

	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
	<meta name="description" content="Welcome to Concur. Log in to your world class Concur solution here and begin managing business travel and expenses." />
	
		<meta name="apple-itunes-app" content="app-id=335023774">
	
	<link rel="SHORTCUT ICON" href="https://www.concursolutions.com/favicon.ico?manualcachekilla=20151130"/>
	

</head>

<body  lang="en-us" id="cnqrBody" class="signin signin-5 cnqr-theme-11">


<div id="overDiv" aria-haspopup="true" aria-live="assertive" style="position:absolute; visibility:hidden;z-index:1;" tabindex="-1"></div>

	
<div class="container cnqr-app-header">
		<div class="row">
	



		<div id="cnqr-navbar-primary">
		
		
		<div class="navbar-outer">
			<ul class="nav navbar-nav">
				<li class="cnqr-nav-logo">
							<i class="icon-logotype" aria-hidden="true"></i>
				</li>
			</ul>
		</div>
	</div>

		</div>
	</div>
	


<form class="nomargins" name="frmMain" id="frmMain" action="https://www.concursolutions.com/verify_login.asp" method="POST" onsubmit='return false;' target='_top' autocomplete='off'>
	

	

	<div class="container cnqr-app-content" id="cnqr-app-content">
		<div class="row">
			
			
				<div class="col-xs-12">
					<h1 class="screen-reader-only">Sign in to Concur | Concur Solutions</h1>
					


<input type="hidden" name="framed" value="" />
<input type="hidden" name="screenres" value="" />
<input type="hidden" name="langClicked" value="" />
<input type="hidden" name="loginurl" value="/signin.asp" />
<input type="hidden" name="hpo" value="" />
<input type="hidden" name="cte" value="" />
<input type="hidden" name="logindomain" id="logindomain" value="" />
<input type="hidden" name="entity" value="" />



<div class="row">
	 <div class="col-md-4 col-sm-5 col-xs-12" id="sidebar1">
		<div class="h1">Sign In</div>

						       

		<div id="cnqr-validation-error" class="field-validation-error" style="display:none"></div>
			
		<div class="cred-container">
			<div class="cred-container-row">
				<label for="userid">User Name</label><br>
				<input name="userid" id="userid" type="text" value="" maxlength="128" class="form-control input-lg cnqr-full-width cnqr-capscheck-userid">
			</div>

			<div class="cred-container-row">
				<label for="password">Password</label><br>
				<input id="password" name="password" type="password" maxlength="60" class="form-control input-lg cnqr-full-width cnqr-capscheck-password" />
			</div>

			<div id="cnqr-capswarning" class="field-validation-error" style="display:none">
				Warning: CapsLock is On!<br />
				Passwords are case sensitive.
			</div>

			
			<div class="cred-container-row">
					
				<input id="rememberLogin" name="rememberLogin" type="checkbox" >
				<label for="rememberLogin">Remember user name on this computer</label>
			</div>
			

			<div class="cred-container-row clearfix">
				<div class="pull-right">
					
					<input id="btnSubmit" name="btnSubmit" class="btn btn-lg btn-primary" type="button" value="Sign In" onclick="checkUserid();">
				</div>
			</div>
		</div>

		<p><a role="button" href="javascript:forgotPassword(1)">Forgot your user name?</a></p>
		<p><a role="button" href="javascript:forgotPassword()">Forgot your password?</a></p>

		
		<div class="lang-container">
		
	<label for="selectLang" id="lblselectLang">Change language</label><br>
	<select id="selectLang" class="form-control cnqr-full-width" onchange="return selectLanguage(this.options[this.selectedIndex].value)">
	
            <option  selected value="en-us">English (US)</option>
        
            <option  value="en-gb">English (UK)</option>
        
            <option  value="cs">Čeština</option>
        
            <option  value="da">Dansk</option>
        
            <option  value="de">Deutsch</option>
        
            <option  value="fr">Français</option>
        
            <option  value="fr-ca">Français canadien</option>
        
            <option  value="es">Español</option>
        
            <option  value="es-la">Español (Latinoamérica)</option>
        
            <option  value="it">Italiano</option>
        
            <option  value="hu">Magyar</option>
        
            <option  value="nl">Nederlands</option>
        
            <option  value="no">Norsk</option>
        
            <option  value="pl">polski</option>
        
            <option  value="pt-br">Português (Brasil)</option>
        
            <option  value="fi">Suomi</option>
        
            <option  value="ru">Русский</option>
        
            <option  value="sv">Svenska</option>
        
            <option  value="ja">日本語</option>
        
            <option  value="zh-tw">繁體中文</option>
        
            <option  value="zh-cn">中文</option>
        
            <option  value="ko">한국어</option>
        </select>
		</div>
		

	 </div>

	 
</div>




				</div>
			
		</div>
	</div> 

	
		

	<script type="text/javascript">

		otLogFrame(true);

		bSubmittedAlready = false;

		var domainpattern = /^(.+)@(.+)$/; // used in several places

		var d = new Date();
		if (d.getMonth() == 5 && d.getDate()==4){
			document.getElementsByTagName('body')[0].className+= " may4";
		}

		function getLoginID() {
			var theForm = document.frmMain;
			var loginID = theForm.userid.value;	
			
			
	
			return loginID;
		}

		function checkUserid() {
			if (bSubmittedAlready){
				return;
			}

			var theForm = document.frmMain;
			var loginID = getLoginID();

			if (theForm){
				if (loginID == "") {
					showValidationError('Please enter a user name.');
					tryFocus(theForm.userid);
					return false;
				} else if ((domainpattern.test(loginID) == false) && ("" == "" )) {  /* basic check for "@domain" */
					showValidationError('The user name is invalid. Please try again.');
					tryFocus(theForm.userid);
					return false;
				} else if (theForm.password.value == ""){
					showValidationError('Please enter a password.');
					tryFocus(theForm.password);
					return false;
				} else {
					var bAllowSubmitPage = true;

					var rndBusyNum = false;
					if (rndBusyNum) {
						bAllowSubmitPage = false;
					}

					if (!bAllowSubmitPage) {
						var busyMsg = "The server is busy. Please retry your request in a few minutes.";
						showValidationError(busyMsg);
						return false;

					} else {
						theForm.screenres.value = screen.width + 'x' + screen.height;	
						theForm.submit();
						bSubmittedAlready = true;
					}
				}
			}
		}

		function dosubmit() {
			checkUserid();
		}

		// Enable enter key to submit form
		function userLogin(e) {
			e = (e || window.event);

			if (e.keyCode == 13) {
				checkUserid();
				return false;
			}
			return true;
		}

		function SetCursor() {
			var uname = $('userid');
			if (!uname.value) {
				tryFocus($('userid'));
			} else {
				tryFocus($('password'));
			}
		}
		
		function showValidationError(msg) {
			
			var _loginmsg = $("cnqr-login-error");
			if (_loginmsg) {
				_loginmsg.style.visibility = 'hidden';
				_loginmsg.style.display = 'none';
			}
			
			var _validationmsg = $("cnqr-validation-error");
			if (_validationmsg) {
				_validationmsg.innerHTML = msg;
				_validationmsg.style.visibility = 'visible';
				_validationmsg.style.display = 'block';
			}
		}

		function forgotPassword( forgotName ) {
			

			var parameters = {
				forgotName: ( !forgotName ? 0 : 1 ),	//	Ensure the sole argument is either 0 or 1:
				txtLoginID: getLoginID()				//	Grab the user's login id from the form & encode it:
			};

			

			CNQR.post( 'https://www.concursolutions.com/profile/send_password_hint.asp', parameters );
		}

		function selectLanguage(langCode){
			if (langCode){
				var url = document.location.href;
				if (url.indexOf("?") > 0 )	{
					if ( url.indexOf("lang=") > 0 ){
						url = updateUrlParameter(url, "lang", langCode);
					} else {
						url = url + '&' + "lang=" + langCode;
					}
				} else {
					url = url + '?' + "lang=" + langCode;
				}
				document.location.href = url
			}
		}

		function updateUrlParameter(url, param, value){
			var regex = new RegExp('('+param+'=)[^\&]+');
			return url.replace( regex , '$1' + value);
		}

		function redirectToIntuitLogin() {
			location = 'https://www.concursolutions.com/Net2/OpenId/IntuitOpenIdLogin.aspx';
		}

		
		function failNoticeOnload() {
			if ($('loginfailed')) {
				tryFocus($('loginfailed'));
			} else {
				if ($('govtext')) {
					tryFocus($('govtext'));
				}
			}
		}
		addEvent(window, "load", failNoticeOnload);

		

		(function(){
			function checkCapsLock(e){
				var 
					_e			= window.event || e,
					_kc 		= _e.charCode ? _e.charCode: (_e.keyCode ? _e.keyCode : _e.which),  
					_sk 		= _e.shiftKey?_e.shiftKey:((_kc == 16)?true:false),
					_msg 		= $("cnqr-capswarning"),
					letter		= String.fromCharCode(_kc),
					upper		= letter.toUpperCase(),
					lower		= letter.toLowerCase(),
					shift_key	= _e.shiftKey
				alt_key	= _e.altKey
				; 
			
				function _on(){if(_msg){_msg.style.visibility = 'visible';_msg.style.display= 'block';}}
				function _off(){if(_msg){_msg.style.visibility = 'hidden'; _msg.style.display= 'none';}}

				// If the upper and lower case characters are the same, then we have no way to know if capslock is on
				if(upper !== lower) {
					if( letter === upper && !shift_key ) {
						if(!alt_key){_on();}					
					} else if( letter === lower && !shift_key ) {
						_off();
					} else if( letter === lower && shift_key) {
						// Must be a Windows user!
						_on();
					} else if( letter === upper && shift_key ) {
						// Either caps lock is off, or the caps lock is on and they are on a Mac
						if( navigator.platform.toLowerCase().indexOf("win") !== -1 ) {
							// You are on Windows, so we know caps lock is off
							_off();
						} 
					} 
				} 
			};
			document.getElementById("userid").onkeypress = function(e){checkCapsLock(e);} 
			document.getElementById("password").onkeypress = function(e){checkCapsLock(e);userLogin(e);} 
			SetCursor();
		})();

		// CORUI-362 'Thread was being aborted' errors after SU121 release
		// don't use pageIdleControl on the signin.asp page
		sessionLogoutTime = 0;
	</script>
	








<div class="container cnqr-app-footer">
	<div class="row cnqr-first">
		<div class="col-xs-12 col-md-6">
					<h6 class="cnqr-first"><span class="screen-reader-only">Concur</span><i data-icon="" class="icon-logotype" aria-hidden="true"></i></h6>

		</div>
		<div class="col-xs-12 col-md-6">
			
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-md-6">
			
		</div>
		<div class="col-xs-12 col-md-6 text-right">
				<p>&copy; Copyright 2016 - Concur - All Rights Reserved</p>
	<div id="login-history-popup"></div>

		</div>
	</div>

	

	
</div> 
	
		
<div id="endOfPage" class="end-of-page"><a href="#cnqrBody" class="screen-reader-only-focusable">End of page. Go to top of page</a></div></form>


</body>
</html>
`

**Comment by zeroSteiner** [comment]
Your login form uses `userid` instead of `username`, you need to update it. I'm going to close this out as the original issue has been resolved and your follow up question is a duplicate of #122.

**Comment by mjunaidzafar** [comment]
hello i am also not able to see the compagin status
