### ISSUE TITLE
Feature request: attach multiple files to email

### ISSUE THREAD

**Issue by Ocraz** [securestate/king-phisher#126]
## Issue Description
Currently it's only possible to add only 1 file as an attachment to an email.

## Request Description
Will you consider to add the posibility to add more than 1 attachment?

The reason I would like to add more than 1 attachment is that when creating a nice template with images only works when attaching the images because remote images are blocked by almost all email clients. Using only 1 attachment, the possibilities are limited.

If there a way to do that in the current version using a work-around, I'd be much obliged to hear it :)

**Comment by zeroSteiner** [comment]
So you're correct in that King Phisher limits you to attaching one arbitrary file right now. However, you should be able to embed as many images as you'd like using the inline technique outlined in the [embedding local images](https://github.com/securestate/king-phisher/wiki/Creating-Message-Content#embedding-local-images) wiki section. These images will all be automatically attached when the message is sent, in addition to which ever one file you might have selected as the arbitrary attachment.

**Comment by Ocraz** [comment]
And thanks again!
I didn't get that from the text in the wiki...

A very short issue this time ;)
Case closed!
