### ISSUE TITLE
Support for Red Hat 7 or Centos 7

### ISSUE THREAD

**Issue by dsieradski** [securestate/king-phisher#13]
Our organization would like to use KingPhisher but our server admins prefer to build only Red Hat 7 or Centos 7 servers to limit the number of Linux versions they have to support.  Could you please add support for one of these Linux versions?

**Comment by zeroSteiner** [comment]
It should work just fine on these systems now. The install script however does not automate the installation process yet. I'll look into adding support for this soon. Thanks!

**Comment by zeroSteiner** [comment]
Alright so I just merged support for this into the master branch.
The King Phisher Server is now supported in the automated install script for CentOS 7.

To get started, from your CentOS 7 server:
```
[root@localhost ~]# yum install -y -q git
[root@localhost ~]# git clone https://github.com/securestate/king-phisher.git /opt/king-phisher
[root@localhost ~]# cd /opt/king-phisher/
[root@localhost king-phisher]# tools/install.sh
```

More details on the installation process can be found in the [INSTALL file](https://github.com/securestate/king-phisher/blob/master/INSTALL.md).

**Comment by zeroSteiner** [comment]
Thanks for using King Phisher and if you have any other questions just open up another ticket. I'm going to go ahead and close now.
