### ISSUE TITLE
Trained

### ISSUE THREAD

**Issue by kgrabows** [securestate/king-phisher#133]
Hello, 
Can you give me the code you need to put on a webpage so the "Trained" column gets populated in the "View Campaign" section of the client? 
Ex. Once a user visits the training website I created, I want that trained column to be populated.

**Comment by zeroSteiner** [comment]
Yes, it doesn't look like this is very clear in the wiki so I'll update that this week.

Basically you need to pass a parameter of `trained=true` in your web request and King Phisher will handle the rest.

Example:
```html
      <form action="./trained.html">
        <p style="text-align: center;">
          <em>Please click "I Agree" to complete this education.</em>
          <input type="hidden" name="trained" value="true">
          <input id="trained-input" type="submit" value="I Agree" />
        </p>
      </form>
```

Another example in a full page is available in the [templates repository](https://github.com/securestate/king-phisher-templates/blob/5dc65139257615fcb8e39f3943b6baebc2089a0a/Website_Templates/Training/Phishing_Awareness/www/register#L69-78).

**Comment by zeroSteiner** [comment]
Additional details have been posted to the wiki in a new [Pages For Training](https://github.com/securestate/king-phisher/wiki/Creating-Server-Content#pages-for-training) section.
