### ISSUE TITLE
client.message_id and client.visit_count

### ISSUE THREAD

**Issue by smscjim** [securestate/king-phisher#134]
While in "View Campaign" and then "Visits" I noticed the "First Visit" and "Last Visit" are always identical dates and times.  The "Visit Count" column seems to only update if I refresh the landing page in my browser.   If  I close the browser and then go back and click on the link in the email, the visit count remains the same.  Is this by design or maybe a cache or cookie setting I have in my browser??   I've been digging through the wiki page and I'm wondering if I need to define either the client.message_id or client.visit_count somewhere on my landing page.  

Ultimately I'm wanting to know if a user clicked on the link in the email and went to the landing page, but then closed out of the browser or didn't proceed to provide any other information at that specific time.  Then later in time that same user decided to go back to the email and click the link.  I'm wanting to see the difference between "First Visit" and "Last Visit" dates and times and total "Visit Count" for that specific user.  

![image](https://cloud.githubusercontent.com/assets/19981512/16844017/833e0eac-49b1-11e6-8777-1dd8dfaa9019.png)

**Comment by zeroSteiner** [comment]
If your browser is clearing it's cookies when you exit and you have the server configured with `require_id: false` then the visit count will remain the same. The visit count is incremented only when a landing page associated with the campaign is requested with an existing visit id. The id that is presented in emails is a message ID which when passed to a landing page will create a new visit ID and set that visit ID in a cookie within the users browser.

What is the value of your server's `require_id` setting?

**Comment by smscjim** [comment]
require_id is set to true

**Comment by zeroSteiner** [comment]
Then I'd suggest you check your server logs and increase the verbosity if no relevant information is available. Furthermore make sure you've refreshed the view in the client (`F5` will handle this or there's a refresh button).

**Comment by smscjim** [comment]
I have tried hitting the refresh button.  The Visit Count will only change if I hit refresh on my browser, then refresh in the campaign.  This screen shot is from a test campaign I've been using.  I sent one email to myself.  And opened it with three different browsers.  The UID has been the same but its reporting it as if I sent emails to multiple people.  
![image](https://cloud.githubusercontent.com/assets/19981512/16844837/ae97eb7e-49b4-11e6-9df6-56723374025b.png)

**Comment by zeroSteiner** [comment]
What you're describing is the intended behavior. If you open the same email and click the link in 3 different browsers and refresh the page 2x in one, then you should have exactly 3 visits from the same target email and the visit count should be 3 for one in which the page was refreshed and 1 for the others.

The reason we do it this way is that every time the page is opened in a new browser or on a different device such as a mobile device, the opportunities for an attacker grow. Consider a situation in which a single user is spear-phished and then forwards their email to a distribution group leading to 10 more people clicking the link. We want to track all of that separately, hence their logically grouped into "Visits".

**Comment by zeroSteiner** [comment]
Also FYI, the visits tab will automatically refresh ever 5 minutes, but this is something that we're looking to change in the future to keep it updated in real time. Probably a v1.5 change to be available much later this year.

**Comment by smscjim** [comment]
Ok well that part makes sense.  But if I dont switch browsers,  and just use the default.  Shouldn't the "First Visit" and "Last Visit" times change if I visit the landing page at separate times??

**Comment by zeroSteiner** [comment]
Ok so I was able to reproduce and fix this in commit a1c7e87d7b881ce8e2bac17df6fd8f30a0380c95. Turns out the server was not updating the last visit timestamp. The fix is available in the dev branch, you can either wait until 1.4.0 is released or you can opt into the beta-testing program to get the changes now by following the instructions in the [wiki](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

Thanks for reporting this.

**Comment by zeroSteiner** [comment]
Should also be noted that unfortunately, this fix will not be able to retroactively set the last_visit timestamp for all of your existing visits. It will only be able to accurately record it moving forward.

**Comment by smscjim** [comment]
Ok awesome!!! thanks!!!
