### ISSUE TITLE
PLS HELP HOW DO I GET KING PHISHER TO WORK i CANT UNDERSTAND THE PROCESS OF PROGRESQL LOGIN

### ISSUE THREAD

**Issue by cyberleox** [securestate/king-phisher#136]
## Issue Description
i cant seem to get King phisher to sign in i have been trying to do it with most of the examples on here but i need a detailed information on setting up the database proper with progresql what options do i have and what are the correct way to do it from scratch,i know am asking for much but i will be glad to have someone mentor me through this A-z
![screenshot from 2016-07-22 02-06-00](https://cloud.githubusercontent.com/assets/20588413/17044792/53fb4cd0-4fbb-11e6-9839-76e7081143c3.png)

**Comment by zeroSteiner** [comment]
Please refer to the documentation provided in the wiki.

Specifically note the FAQ section on there not being default credentials, in addition to the entire page dedicated to the database.

**Comment by cyberleox** [comment]
Hello Thank you for your response but i couldnt find anything that helped i even removed and re-installed it back changed the user and password for postgresqls,it is really a bit of a confusion as i havent really done anything with ssh before i would like and appreciate if you could walk me through it.Regards Sir.

**Comment by guitarmanj** [comment]
Cyber Leon,
First, King Phisher defines it's own username and password for postgresql during setup. You'll have to run the setup again.

Next, you have to make sure ssh is installed and running g on your server. The credentials you use are your ssh credentials.

Out of the box, this is how it works


Thanks



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by cyberleox** [comment]
Hi i am trying to change the postgresql user and password but getting this errors
cyberleox@cyberleox:/etc/ssh$ sudo update-rc.d -f ssh enable 2 3 4 5
cyberleox@cyberleox:/etc/ssh$ sudo nano /etc/motd
cyberleox@cyberleox:/etc/ssh$ sudo service postgresql start
cyberleox@cyberleox:/etc/ssh$ sudo -su postgres
postgres@cyberleox:/etc/ssh$ createuser cyberleox -P -S -R -D
Enter password for new role: 
Enter it again: 
createuser: could not connect to database postgres: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
postgres@cyberleox:/etc/ssh$ 
![screenshot from 2016-07-22 11-36-14](https://cloud.githubusercontent.com/assets/20588413/17054746/af575aca-5000-11e6-97d3-a43fc45d7b8f.png)

**Comment by guitarmanj** [comment]
You aren't supposed to mess with the postgresql configuration including usernames and passwords. The setup script does all of the work for you. You authenticate purely through ssh.... You'll have to Rerun the setup script.

The steps used to set up king phisher are documented thoroughly in the wiki.



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by cyberleox** [comment]
ok Thanks i will go try again and report back what i find,you guys are been very helpful here...by the way would like a means of reaching you..would like some mentoring as i am on the learning part.

**Comment by cyberleox** [comment]
this was the error message i got after installing king-phisher again and it tried to start
![screenshot from 2016-07-22 12-06-10](https://cloud.githubusercontent.com/assets/20588413/17055447/aef4da4a-5004-11e6-954f-4298dd5b767b.png)

**Comment by wolfthefallen** [comment]
@cyberleox this error generally occurs when the postgresql database has not been initialized after installation to correct this issue please run ` sudo postgresql-setup --initdb` then rerun tools/install.sh script.

**Comment by cyberleox** [comment]
postgresql-setup Command Not Found

**Comment by wolfthefallen** [comment]
cyberleox you ill need to verify that you have the postgresql database initialized. Once that is completed please stop all service running on port 80. Then rerun the tools/install.sh to have king-phisher installed correctly on your system.

**Comment by wolfthefallen** [comment]
@cyberleox have you resolved your issues with initializing the PostgreSQL database and successfully installing King Phisher with the tools/install.sh script?

**Comment by zeroSteiner** [comment]
This hasn't been updated in over a week so I'm going to close it.

**Comment by hwac121** [comment]
> Wow, this program really sucks. Why would Kali include it at all and not a program that actually works?

Just because you have no idea what you are doing does not mean the program sucks...
This is one of the best phishing campaign programs built actually. A lot of work goes into this app, it is complicated, and open source so BE GRATEFUL!
