### ISSUE TITLE
Kali client not showing visits but Win client does

### ISSUE THREAD

**Issue by Catzpanz** [securestate/king-phisher#138]
## Issue Description
I have run multiple campaigns successfully using a Win7 Pro client (KingPhisher client 1.1.0). 

A colleague is trying to set up the 1.1.0 client on Kali. Everything seems to work fine except when viewing the campaign or downloading the campaign as an Excel file the Visits data is missing. However when I log in on my Win7 machine I can see it. The Kali client successfully displays the Messages and Credentials data, it's just missing the Visits data.

## Environment Details
Host OS: Ubuntu server in AWS. We are both logged into the same server.
Client OS: Successful client = Win7. Unsuccessful client = Kali 2016.1 Rolling release.

**Comment by zeroSteiner** [comment]
Are you both using the same server and can you double check that you've both selected the same campaign? The campaign can be selected from the File menu under "Open Campaign".

**Comment by Catzpanz** [comment]
Yes we are both using the same server and have the same campaign open.
He is just installing a Windows version on his Win7 box now.

**Comment by zeroSteiner** [comment]
Has the Kali client refreshed the view? This sounds like a bug that would have come up quickly. Can you also attach the log output from Kali with logging set to DEBUG?

**Comment by zeroSteiner** [comment]
Also version 1.1 is quite old, please update to a newer version and see if the issue persists.

**Comment by zeroSteiner** [comment]
This hasn't been updated in about a week so I'm going to close it out. If you continue to experience trouble and are using the latest version feel free to comment on this thread or open a new ticket.
