### ISSUE TITLE
Import error: No module named ipaddress

### ISSUE THREAD

**Issue by domahoney** [securestate/king-phisher#14]
Hi, I have followed the install instructions but am hitting an issue when starting the KingPhisherServer. I get the error;
 Traceback (most recent call last):
  File "/opt/king-phisher/KingPhisherServer", line 44, in <module>
    from king_phisher import utilities
  File "/opt/king-phisher/king_phisher/utilities.py", line 37, in <module>
    import ipaddress
ImportError: No module named ipaddress

Any ideas what I'm doing wrong? Running Kali Linux

**Comment by zeroSteiner** [comment]
Yes, the ```py2-ipaddress``` module is required for Python 2.7. It should have been installed when you ran ```sudo pip install -r requirements.txt```. Try running pip install again to make sure all the packages are installed and up to date.

**Comment by zeroSteiner** [comment]
This issue has been open for a week with no response, so I'm going to close it now. If you still need help feel free to reopen it.

**Comment by Anton064** [comment]
error----sudo: pip: command not found

**Comment by gtrani** [comment]
install pip with command `sudo apt install pip`
