### ISSUE TITLE
Postfix Settings From Campaign "How-To" Video

### ISSUE THREAD

**Issue by parappsys** [securestate/king-phisher#145]
## Issue Description
In the How To video from creating a campaign, it's mentioned that the user is utilizing Postfix as the SMTP backend. I am trying to do the same, but can't successfully authenticate from KP (though I can when testing from the mail command). I realize that it's outside the scope of support for KP, but if you could post the Postfix settings that you used with that install, it would be helpful.

For example, what domain did you use for postfix? How do you send as a .corn address to be extra sneaky? In a split install, should postfix be installed on the client or the server piece?

Thanks!

## Environment Details
Client OS: Ubuntu 16.04 Desktop LTS
Server OS: Ubuntu 16.04 Server

## Error Details / Stack Trace

Not really an error

If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
We don't share our internal configuration files and these are questions which are outside of the scope of King Phisher. I'm sorry but we can't support postfix in addition to our own projects with the limited resources we have available. I suggest you find a postfix mailing list, forum or something similar.

Regarding where you install postfix, it really doesn't matter. You can install it on the same system as the client, the server or an entirely different system altogether. It just needs to be configured correctly in the client.

**Comment by parappsys** [comment]
Fair enough. I decided to try with Gmail using the provided settings (including matching the email and sending account), but that won't authenticate either. Maybe I'll re-install the client again.

**Comment by parappsys** [comment]
Just an update, but Gmail seems to be blocking SMTP access from KP now. When I try to send, I receive an email from Google stating that:

"Someone just tried to sign in to your Google Account XXXXXXX@gmail.com from an app that doesn't meet modern security standards."

Guess it's back to Postfix.
