### ISSUE TITLE
error 404 while accessing landing page

### ISSUE THREAD

**Issue by vaneet123** [securestate/king-phisher#148]
whenever i try to open the landing page of kingphisher it says error 404 page not found .
king-phisher is running on port 80 and when checking log file it says  AdvancedHTTPServer                                 WARNING  denying request due to lack of a valid id
i have disbled reqire_id option  in server config file but it still displays this error . Besides i cant start king-phisher server on any other port exept port 80

**Comment by wolfthefallen** [comment]
@vaneet123 ,

The [404 Page Not Found](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#im-getting-a-404--error-page-on-the-server) occurs when require_id for the King Phisher is set (by default it is) and you attempt to navigate to a webpage hosted by King Phisher with out valid ID. We recommend keeping this setting set, and send yourself a test email with the jinja syntax from the FAQ, to verify everything is working correctly. Once the testing is complete you can delete the instance of sending yourself an email to keep your data for the campaign clean.

If you decide to change the King Phisher require_id setting to false, you must restart the King Phisher Server for it to take effect. This can be done via upstart or systemd which ever is installed on your server. 
upstart:
`service king-phisher stop`
systemd:
`systemctl stop king-phisher`

**Comment by vaneet123** [comment]
I have started the kingfisher server several times but this aint working .

**Comment by wolfthefallen** [comment]
can you please increase your log level of your King Phisher server to DEBUG, restart the server, and attempt to connect, and provide me log out put from the server. Also what operating system is your King Phisher server running on?

**Comment by vaneet123** [comment]
@ @
![screenshot from 2016-08-25 06-09-24](https://cloud.githubusercontent.com/assets/21233039/17972300/41842188-6aac-11e6-957e-6a6004e83b6f.png)

**Comment by vaneet123** [comment]
thanks a lot it is working now and my apologies for disturbing u for such a silly mistake   .
everything worked after i stoped the server and restarted it with systemctl .
but i ahve another problem the test emails dont reach my gmail account although it says  sending message succesful i guess gmail drops them as spam is there any way around this.

**Comment by zeroSteiner** [comment]
GMail's spam filter is particularly effective. If you're just testing you can make a rule to never classify your source address as spam. Otherwise you'll need to fiddle with the settings, and likely send from an address your SMTP server is authorized to send from. You can send from a GMail account if you use the GMail SMTP server. Steps to do this are outlined in the [FAQ](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-send-messages-through-gmail).

**Comment by vaneet123** [comment]
ok thanks a lot for your help will see what i can do .
