### ISSUE TITLE
Kali Linux build failed on pip install -r requirements.txt

### ISSUE THREAD

**Issue by mozg31337** [securestate/king-phisher#15]
Hello,

I am trying install the King Phisher on the latest Kali linux and have an issue with satisfying the requirements. When I manually run the pip install -r requirements.txt I have the following issue with the py2-ipaddress dependency:

Downloading/unpacking py2-ipaddress>=2.0.0 (from -r requirements.txt (line 12))
  Downloading py2-ipaddress-2.0.1.linux-x86_64.tar.gz
  Running setup.py egg_info for package py2-ipaddress
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/root/kingphisher/17032015/king-phisher-master/build/py2-ipaddress/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/root/kingphisher/17032015/king-phisher-master/build/py2-ipaddress/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /root/kingphisher/17032015/king-phisher-master/build/py2-ipaddress

I have tried to manually download the py2-ipaddress file and extracting it. Indeed, it doesn't have the setup.py file.

Is there a way to fix this issue?

Thanks

Andrei

**Comment by zeroSteiner** [comment]
Do you get the same error if you try running ```pip install py2-ipaddress``` by itself?

**Comment by mozg31337** [comment]
Yes, the exact error message.

**Comment by zeroSteiner** [comment]
It looks like version 2.0.1 is the version being downloaded. Can you try specifically installing 2.0.0 with ```sudo pip install "py2-ipaddress==2.0.0"```

**Comment by mozg31337** [comment]
Thanks, this has actually worked. Thanks for your help ))
