### ISSUE TITLE
parser error

### ISSUE THREAD

**Issue by sealnil** [securestate/king-phisher#154]
![screenshot from 2016-09-24 20-14-16](https://cloud.githubusercontent.com/assets/20501121/18809200/99581672-8293-11e6-8ba1-ea1edf9d2733.png)
hello i am getting this error, and whenever i restart my machine i have to reinstall my king phisher,
please tell how to install plugins, and how to make first campaign.

it is not necessary to run the king phisher client as root
ERROR    css parser error (not a number) in /root/Desktop/king-phisher/data/client/king_phisher/style/theme.v2.css:98
ERROR    css parser error (Expected a string.) in /root/Desktop/king-phisher/data/client/king_phisher/style/theme.v2.css:98
ERROR    there was an error parsing the css file, it will not be applied as a style provider

**Comment by zeroSteiner** [comment]
The theme CSS file appears to be corrupted, you should restore it from the repository. In the future please fill out all of the fields in the issue template, specifically you haven't provided details regarding what system you are running this on. 

For help with logging in please see the tutorial videos available in the wiki. Additionally steps for installing plugins is available in the wiki.

**Comment by sealnil** [comment]
ok buddy, now its showing connection refused,
i am running kali aka, with updated version of king phisher

**Comment by zeroSteiner** [comment]
Are both the King Phisher service and the SSH services running?

**Comment by guitarmanj** [comment]
Is ssh setup on your kali machine? Are you using your kali machine for both the server and client?



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by sealnil** [comment]
yes i have ssh set up on machine along with king phisher client, not config server, 
the commands i used
apt-get install openssh-server
after downloading king phiser , extract it on desktop, open in terminal
cd king-phisher
cd tools
sudo bash ./install.sh
and enter uname as root and machine password to loging, earlier i was logged in and showing new campaign, and other options, after after today i started up the machine it is connection refused error.
 this much i have done till now, 
please tell where i am doing wrong or have i missed any step in between.
thanks in advacne

**Comment by zeroSteiner** [comment]
It sounds like you need to configure and start the server. Also please copy and paste the exact connection error message into the issue. If the server is started, please share the logs with us as well. We'll need all that information to help.

**Comment by sealnil** [comment]
# King-Phisher Server Configuration
#

logging:
  file: /var/log/king-phisher.log
  # Available levels: FATAL, ERROR, WARNING, INFO, DEBUG
  level: warning
  console: false

server:
  # Bind address information, multiple ports can be
  addresses:
    - host: 0.0.0.0
      port: 80
      ssl: false

  # Server RPC authentication related settings
  #authentication:
    # How long to cache authentication information in the server process
    #cache_timeout: 10m
    # Require authenticating users to be a member of the specified group
    #group: king-phisher
    # The service to use for PAM authentication
    #pam_service: sshd
    # How long an authenticated RPC session should be valid for after no
    # requests have been received.
    #session_timeout: 30m

  # A cookie to retrieve the client's IP from, useful when a proxy is in place
  #client_ip_cookie: X-Real-IP

  # The name of the cookie used to track users
  cookie_name: KPID

  # Specify an additional search path for server data files
  data_path: /opt/king-phisher

  # The SQLite3 database file to use, the folder needs write permissions
  # WARNING: SQLite3 is not fully supported as of version 0.1.6, see
  # https://github.com/securestate/king-phisher/wiki/Database#sqlite for more
  # details
  #database: sqlite:////var/king-phisher/king-phisher.db

  # The PostgreSQL database to use
  database: postgresql://king_phisher:6MWSbKiYa6FjBAuxuZ3Q96eXS6S1aAJ0pxEOrUH6@localhost/king_phisher

  # Fork the server process into the background
  fork: true

  geoip:
    # The location of the GeoLite2 City database
    database: /var/king-phisher/geoip.mmdb

  # Set a file to write the PID to
  pid_file: /var/run/king-phisher.pid

  # Add additional search paths for plugin directories
  #plugin_directories:
  #  - /some/plugin/path
  # List the plugins that need to be enabled
  #plugins:
  #  # The plugin to enable's name
  #  some_plugin:
  #    # An option specific to this particular plugin
  #    value_for_some_plugin: true

  # Require an ID associated with a campaign to load pages
  require_id: true

  rest_api:
    enabled: false
    # Networks which are authorized to use the REST API
    networks:
      - 10.0.0.0/8
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
    # When null the token will be randomized at run time
    token: null

  # Configure the server header value
  #server_header: Apache/2.4.9 (Unix)

  # Set the opened timestamp on the first visit if it's null
  set_message_opened_on_visit: true

  # Drop privileges to the specified user
  setuid_username: nobody

  # Default SSL certificate settings
  #ssl_cert: /path/to/ssl.crt
  #ssl_key: /path/to/ssl.key
  # Hostname specific SSL certificates can be added below
  #ssl_hosts:
  #  - host: www.king-phisher.com
  #    ssl_cert: /path/to/www.king-phisher.com/ssl.crt
  #    ssl_key: /path/to/www.king-phisher.com/ssl.key

  # Configure the image file name used to track opened emails
  tracking_image: email_logo_banner.gif

  # Use subfolders in the web_root which correspond to vhost names
  vhost_directories: false


this is the config file of server
 and now i am able to loging as connection refused error is poping

**Comment by sealnil** [comment]
root@kali:~# service ssh status
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; disabled; vendor preset: dis
   Active: active (running) since Sat 2016-09-24 19:47:47 IST; 3h 50min ago
 Main PID: 1719 (sshd)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/ssh.service
           └─1719 /usr/sbin/sshd -D

Sep 24 19:47:47 kali systemd[1]: Starting OpenBSD Secure Shell server...
Sep 24 19:47:47 kali sshd[1719]: Server listening on 0.0.0.0 port 22.
Sep 24 19:47:47 kali sshd[1719]: Server listening on :: port 22.
Sep 24 19:47:47 kali systemd[1]: Started OpenBSD Secure Shell server.
lines 1-12/12 (END)


ssh server is active and running

**Comment by zeroSteiner** [comment]
What is the status of your King Phisher service? Please don't post your confirmation file again as it contains your Postgresql connection information including the password.

**Comment by sealnil** [comment]
ok thanks i will take care next time

still connection refused, should i remove and reinstall it?

**Comment by zeroSteiner** [comment]
No you need to make sure that the king-phisher systemd service is running with systemctl.

**Comment by sealnil** [comment]
plz send the command format for checking king-phisher systemctl

**Comment by sealnil** [comment]
King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: disabled)
   Active: failed (Result: resources) since Sat 2016-09-24 23:30:38 IST; 24min ago
  Process: 19984 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.

Sep 24 23:30:37 kali python3[19984]:   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py
Sep 24 23:30:37 kali python3[19984]:     return self.dbapi.connect(*cargs, **cparams)
Sep 24 23:30:37 kali python3[19984]:   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 
Sep 24 23:30:37 kali python3[19984]:     conn = _connect(dsn, connection_factory=connection_factory, async=async
Sep 24 23:30:37 kali python3[19984]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  passwo
Sep 24 23:30:37 kali python3[19984]: FATAL:  password authentication failed for user "king_phisher"
Sep 24 23:30:38 kali systemd[1]: king-phisher.service: Daemon never wrote its PID file. Failing.
Sep 24 23:30:38 kali systemd[1]: Failed to start King Phisher Server.
Sep 24 23:30:38 kali systemd[1]: king-phisher.service: Unit entered failed state.
Sep 24 23:30:38 kali systemd[1]: king-phisher.service: Failed with result 'resources'.
~

**Comment by zeroSteiner** [comment]
It's sudo systemctl status king-phisher

In the future please try to find the answer to these basic questions yourself using a search engine like Google.

**Comment by sealnil** [comment]
sure

**Comment by sealnil** [comment]
sudo systemctl status king-phisher
● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: disabled)
   Active: failed (Result: resources) since Sat 2016-09-24 23:30:38 IST; 28min ago
  Process: 19984 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.

Sep 24 23:30:37 kali python3[19984]:   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py
Sep 24 23:30:37 kali python3[19984]:     return self.dbapi.connect(*cargs, **cparams)
Sep 24 23:30:37 kali python3[19984]:   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 
Sep 24 23:30:37 kali python3[19984]:     conn = _connect(dsn, connection_factory=connection_factory, async=async
Sep 24 23:30:37 kali python3[19984]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  passwo
Sep 24 23:30:37 kali python3[19984]: FATAL:  password authentication failed for user "king_phisher"
Sep 24 23:30:38 kali systemd[1]: king-phisher.service: Daemon never wrote its PID file. Failing.
Sep 24 23:30:38 kali systemd[1]: Failed to start King Phisher Server.
Sep 24 23:30:38 kali systemd[1]: king-phisher.service: Unit entered failed state.
Sep 24 23:30:38 kali systemd[1]: king-phisher.service: Failed with result 'resources'.

**Comment by zeroSteiner** [comment]
The service is not running because the password for the database is incorrect. There is a section in the FAQ page of the wiki on how to address this.

**Comment by zeroSteiner** [comment]
I'm going to close this issue since the solution is in the FAQ and there hasn't been any response.
