### ISSUE TITLE
Ubuntu 16.04.1 LTS not recognized by install script

### ISSUE THREAD

**Issue by xillwillx** [securestate/king-phisher#157]
## Issue Description
If the current version of Linux is one of these flavors but it is
not recognized, please open a support ticket and include the version.

## Reproduction Steps
1. Start King Phisher install script
sudo tools/install.sh
Failed to detect the version of Linux

## Environment Details
 
cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"

**Comment by zeroSteiner** [comment]
It's actually determined based on the contents of `/etc/issue`. Could you please post the contents of that file as well?

**Comment by xillwillx** [comment]
well damn vmware's fault, will try a normal install and report back 

cat /etc/issue
************************************************
************************************************
 VMware Easy Install

 PLEASE WAIT! VMware Tools is currently being
 installed on your system. Depending on the
 version of Ubuntu you are installing, you may
 log in below and use the system during the
 installation. Otherwise, please wait for the
 graphical environment to launch. Thank you.

************************************************
************************************************

**Comment by wolfthefallen** [comment]
@xillwillx have you successfully gotten King Phisher to install?

**Comment by xillwillx** [comment]
sorry for the delay , was able to successfully install on ubuntu and ubuntu server vm's. after configuring ubuntu vm in vmware, would need to remove the easy install iso before powering up the vm for the first time. not sure why it overwrites etc/issue

**Comment by wolfthefallen** [comment]
Good to know that vmware quick install overwrites etc/issues, and can be correct by removing the easy install iso before powering up the vm for the first time.
