### ISSUE TITLE
Does not install into default directory

### ISSUE THREAD

**Issue by DigiAngel** [securestate/king-phisher#158]
## Issue Description
The install script doesn't install to /opt/king-phisher as document

## Reproduction Steps
1. sudo tools/install.sh

## Environment Details

Host OS: Ubuntu 16.04.1

## Error Details / Stack Trace
~~~
Successfully installed basemap with pip
Creating King Phisher admin group: 'king-phisher'
Configuring the PostgreSQL server
PostgreSQL configuration file found at /etc/postgresql/9.5/main/pg_hba.conf
Created the PostgreSQL user 'king_phisher' with a random password
Installing the King Phisher systemd service file in /lib/systemd/system/
Starting the King Phisher service
Created symlink from /etc/systemd/system/multi-user.target.wants/king-phisher.service to /lib/systemd/system/king-phisher.service.
-----------------------------------------------------------------------------------------------
You can start the King Phisher client with the following command:
python3 /home//build/kingphisher/king-phisher/KingPhisher

[11:20:58 analysis:~$ cd /opt
[11:21:01 analysis:/opt$ ls
[11:21:01 analysis:/opt$
~~~

**Comment by zeroSteiner** [comment]
If you have it cloned already it installs King Phisher in place. This is the intended behavior. If you want it installed into /opt/king-phisher then you can clone it to there and run the installation script from there. Alternatively you can just download the raw install script and run it, and it should detect that King Phisher hasn't been cloned and clone it for you in to the default location in /opt.

**Comment by DigiAngel** [comment]
Awesome thanks...might wanna put that in the install doc at some point in time.  Thanks again.
