### ISSUE TITLE
advancedhttpserver.RPCError when sending email

### ISSUE THREAD

**Issue by xillwillx** [securestate/king-phisher#159]
## Issue Description
sending email from client

## Reproduction Steps
1. Start King Phisher
2. configure and send email

## Environment Details

Host OS: Ubuntu 16.04.1 LTS
Client OS: Ubuntu 16.04.1 LTS

## Error Details / Stack Trace
Error Type: advancedhttpserver.RPCError
Error Details: RPCError(message='Unauthorized', status=401, remote_exception=False)
Error UID: 37460cb8-7641-44f9-8a22-fe275251f58d
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.5.2-beta (rev: d09ca949)
Platform Version: Linux: Ubuntu 16.04 xenial
Python Version: 3.5.2
Gtk Version: 3.18.9
Timezone: America/New_York

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-2 (alive=True daemon=True)
    Thread-1 (alive=True daemon=False)
    Thread-78 (alive=True daemon=True)

Stack Trace:
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/tabs/mail.py", line 274, in signal_button_clicked_sender_start
    if not self._sender_precheck_campaign():
  File "/opt/king-phisher/king_phisher/client/tabs/mail.py", line 157, in _sender_precheck_campaign
    campaign = self.application.rpc.remote_table_row('campaigns', self.config['campaign_id'])
  File "/opt/king-phisher/king_phisher/client/client_rpc.py", line 246, in remote_table_row
    row = self.call('db/table/get', table, row_id)
  File "/usr/local/lib/python3.5/dist-packages/advancedhttpserver.py", line 565, in call
    raise RPCError(resp.reason, resp.status)
advancedhttpserver.RPCError: the server responded with 401 'Unauthorized'

**Comment by wolfthefallen** [comment]
@xillwillx 
From Looking at the stack trace it appears that your login token with the King Phisher Server has expired and thus you are getting the unauthorized error. Is this error occurring every time you attempt to send emails? or during any other time utilizing the King Phisher Client?

**Comment by zeroSteiner** [comment]
Any chance we could get the additional details to try and reproduce this? Without them there's nothing we can do and we'll be forced to close the issue.

**Comment by xillwillx** [comment]
sorry for delay, couldnt reproduce a second time and havent had the time to revisit more to verify. If anything, ill open another issue if it happens in the future.

**Comment by zeroSteiner** [comment]
Alright sounds good, then I'll close this one.
