### ISSUE TITLE
HTTP 404 Error on Campaign

### ISSUE THREAD

**Issue by s4b3rt0oth** [securestate/king-phisher#160]
## Issue Description
When I setup a test campaign and send the email to myself (which is successful) I click the link. I then receive a 404 error, in the king-phisher style. (I've look at the other 404 issues and noted the differences in other 404 pages). I have loaded the template files into the /var/www/ directory and noted that in server_config.yaml the directory is set for /var/www/ and require_id is set to true. I have tried with verify URL in the client as well as disabling require_id. No matter what I do I receive a 404 page. I am not sure at this point if it is an issue with the webserver, the requirement links, or something I did while setting up. (I followed the wiki and read all documentation before beginning)

## Reproduction Steps
1. Start King Phisher
2. Send a test campaign email to some email address(es).
3. Follow the link.
4. Receive 404 error.

## Environment Details

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
Kernel: 4.4.0-31-generic

NOTE: I've tried on various distributions. Kali (an older version, not sure of the release), Kali 2016.2, Ubuntu 16. Neither of the Kali's worked and I saw similar results that I am seeing now with the Ubuntu 16. All Ubuntu installations are server/headless installs.

## Error Details / Stack Trace

```
404 Error when clicking the link. I would like to note that the link is being clicked in a physically different location than king-phisher. Nothing is wrong with the firewall, it is forwarding traffic properly.
```
Example of the 404:
![screen shot 2016-10-19 at 2 26 20 pm](https://cloud.githubusercontent.com/assets/3665270/19532047/0c67f9a2-9608-11e6-9efc-93240e9dc3ad.png)

Server_config.yaml

    #
    # King-Phisher Server Configuration
    #
    
    logging:
      file: /var/log/king-phisher.log
      # Available levels: FATAL, ERROR, WARNING, INFO, DEBUG
      level: warning
      console: false
    
    server:
      # Bind address information, multiple ports can be
      addresses:
        - host: 0.0.0.0
          port: 80
          ssl: false
    
      # Server RPC authentication related settings
      #authentication:
        # How long to cache authentication information in the server process
        #cache_timeout: 10m
        # Require authenticating users to be a member of the specified group
        #group: king-phisher
        # The service to use for PAM authentication
        #pam_service: sshd
        # How long an authenticated RPC session should be valid for after no
        # requests have been received.
        #session_timeout: 30m
    
      # A cookie to retrieve the client's IP from, useful when a proxy is in place
      #client_ip_cookie: X-Real-IP
    
      # The name of the cookie used to track users
      cookie_name: KPID
    
      # Specify an additional search path for server data files
      data_path: /opt/king-phisher
    
      # The SQLite3 database file to use, the folder needs write permissions
      # WARNING: SQLite3 is not fully supported as of version 0.1.6, see
      # https://github.com/securestate/king-phisher/wiki/Database#sqlite for more
      # details
      #database: sqlite:////var/king-phisher/king-phisher.db
    
      # The PostgreSQL database to use
      database:     <edited out>
    
      # Fork the server process into the background
      fork: true
    
      geoip:
        # The location of the GeoLite2 City database
        database: /var/king-phisher/geoip.mmdb
    
      # Set a file to write the PID to
      pid_file: /var/run/king-phisher.pid
    
      # Add additional search paths for plugin directories
      #plugin_directories:
      #  - /some/plugin/path
      # List the plugins that need to be enabled
      #plugins:
      #  # The plugin to enable's name
      #  some_plugin:
      #    # An option specific to this particular plugin
      #    value_for_some_plugin: true
    
      # Require an ID associated with a campaign to load pages
      require_id: true
    
      rest_api:
        enabled: false
        # Networks which are authorized to use the REST API
        networks:
          - 10.0.0.0/8
          - 127.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
        # When null the token will be randomized at run time
        token: null
    
      # Configure the server header value
      #server_header: Apache/2.4.9 (Unix)
    
      # Set the opened timestamp on the first visit if it's null
      set_message_opened_on_visit: true
    
      # Drop privileges to the specified user
      setuid_username: nobody
    
      # Default SSL certificate settings
      #ssl_cert: /path/to/ssl.crt
      #ssl_key: /path/to/ssl.key
      # Hostname specific SSL certificates can be added below
      #ssl_hosts:
      #  - host: www.king-phisher.com
      #    ssl_cert: /path/to/www.king-phisher.com/ssl.crt
      #    ssl_key: /path/to/www.king-phisher.com/ssl.key
    
      # Configure the image file name used to track opened emails
      tracking_image: email_logo_banner.gif
    
      # Use subfolders in the web_root which correspond to vhost names
      vhost_directories: false
      web_root: /var/www

Log Output from /var/log/king-phisher.log
```
<REDACTED>@<REDACTED>:/opt/king-phisher$ tail -f /var/log/king-phisher.log
2016-10-19 14:32:15,936 KingPhisher.Server.Database                        DEBUG    current database schema version: 6 (latest)
2016-10-19 14:32:15,939 KingPhisher.Server.Database                        DEBUG    connected to postgresql database: king_phisher
2016-10-19 14:32:15,942 KingPhisher.Server.SessionManager                  INFO     restored 0 valid sessions and skipped 0 expired sessions from the database
2016-10-19 14:32:15,942 KingPhisher.Server.Authenticator                   DEBUG    use pam service 'sshd' for authentication
2016-10-19 14:32:15,943 KingPhisher.Server.Authenticator                   DEBUG    forked an authenticating process with pid: 1973
2016-10-19 14:32:15,945 JobManager                                         INFO     the job manager has been started
2016-10-19 14:32:15,948 KingPhisher.Server.CLI                             INFO     server running in process: 1945 main tid: 0x7<REDACTED>
2016-10-19 14:32:15,948 KingPhisher.Server.CLI                             INFO     dropped privileges to the nobody account
2016-10-19 14:32:20,001 AdvancedHTTPServer                                 INFO     x.x.x.x "GET /?id=lvF6zQnY8h2F3Jqo HTTP/1.1" 404 -
2016-10-19 14:32:20,058 AdvancedHTTPServer                                 INFO     x.x.x.x "GET /kp.js HTTP/1.1" 200 -
```

Any help would be immensely appreciated! If there is anything else I can provide to aid with your assistance please let me know.

Thank you!

**Comment by shad0wman** [comment]
when you click the 'verify url' button on the config page, what does it say?


________________________________

**Comment by s4b3rt0oth** [comment]
Here is the response from "Verify URL"
![screen shot 2016-10-19 at 2 48 29 pm](https://cloud.githubusercontent.com/assets/3665270/19532766/27143d58-960b-11e6-84c7-77b0e78e4669.png)

**Comment by wolfthefallen** [comment]
is the landing page for your campagin located in the `web_root:` directory that is in your King Phisher server configuration file? 

Also please don't post your server configuration files on github or the internet has it has sensitive information in it.

**Comment by shad0wman** [comment]
okay, so King Phisher can't find the web page.


In your /var/www folder you should have a folder with your url in it, let's say 'mail.king-phisher.com'. Your landing page should be located within that folder and you need to point to that landing page in your config. i.e. "http://mail.king-phisher.com/index.html'


Then verify your url


________________________________

**Comment by s4b3rt0oth** [comment]
Should there be a folder in /var/www/ even if I have virtual_directory option set to false?

**Comment by wolfthefallen** [comment]
if `virtual_directory` is disabled you do need to put your landing page in a subfolder of `/var/www`. So if your landing page is index.html then place it directly into `/var/www` and then your url will be `http://<ip>/index.html` or `http://<your dns record point to your IP address of your King Phisher server>/index.html`

**Comment by s4b3rt0oth** [comment]
I have verified that the web server works by placing a copy of the default Apache page onto the server and sending out emails/verifying URL through the client. So now I suppose my next question is about templates. I am using one of the Anti-Virus templates. I have the following files in the directory. 
![screen shot 2016-10-19 at 3 42 03 pm](https://cloud.githubusercontent.com/assets/3665270/19534642/9edadda4-9612-11e6-86cf-a76cf11f41aa.png)

By pointing the URL to either login or scan, I get a 404. Am i missing something or is there a missing page?

Thanks everyone for your responses so far!

**Comment by s4b3rt0oth** [comment]
So I am not sure what happened but I sent another test email and everything is working as it should now. Thanks for all of the responses!
