### ISSUE TITLE
Mails not delivered to target inbox

### ISSUE THREAD

**Issue by shrirambharathkumar** [securestate/king-phisher#161]
## Issue Description
My mails are not getting delivered to target inbox. 
I tried to send a mail, everything looks fine, Mail is sent from Kingphisher. But mail is not getting delivered to the target inbox , what i am i missing here. 

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by shad0wman** [comment]
Can you please include logs from postfix?



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by shrirambharathkumar** [comment]
Hi, i got the issue. My IP got blocked in Microsoft, due to spoofed mails from my ip.. once I whitelist it my mails are getting delivered, but mails are failing spf checks and going to target junk folder., what is way to pass spf checks,.? Thanks in advance

**Comment by shad0wman** [comment]
There are many ways to pass spf checks but not really a king phisher issue. Try a different domain. If your target has a hard fail on their spf record, your email will not go through and it's a crap shoot if there's a soft fail. There is a check built into king phisher that will warn you before sending.



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by shrirambharathkumar** [comment]
Yes.. Thanks a lot Jeremy.. i will check those out..
