### ISSUE TITLE
how to connect to king-phisher server in amazon aws

### ISSUE THREAD

**Issue by shrirambharathkumar** [securestate/king-phisher#162]
## Issue Description
How to connect to King-Phisher server installed on amazon aws
I have installed king-phisher server in ubuntu machine hosted in amazon-aws , how should i connect to this using king-phisher client. what should be the username and password i should be using (since aws uses key pair for normal ssh connection and there is no password associated with the usename)

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by wolfthefallen** [comment]
ssh into your AWS server and set the password for the account via the `passwd` command. Once you have set the password. From there you will need to adjust your client configuration file to utilize the ssh key for authentication along with your password that you have set. [Server Authentication](https://github.com/securestate/king-phisher/wiki/Server-Authentication) section of the wiki will walk you through this process.
