### ISSUE TITLE
Failed to connect to King phisher RPC server

### ISSUE THREAD

**Issue by shrirambharathkumar** [securestate/king-phisher#164]
## Issue Description
Getting the attached errors when trying to connect to king-phisher server. The issue is similar to issue#52 expect that the server and client are in different machines. I tried to install in VM and connect using a client and tried to install in server in cloud and connect to client. similar issue raises with minor difference in the description . Attaching the errors and serverconfig.yml file
<img width="377" alt="error2" src="https://cloud.githubusercontent.com/assets/17475407/19722908/6d624314-9b96-11e6-969e-ff2219169756.PNG">
<img width="340" alt="error" src="https://cloud.githubusercontent.com/assets/17475407/19722912/7338c088-9b96-11e6-95b7-2c146400a048.PNG">

Server_config.yml file:

#
# King-Phisher Server Configuration
#

logging:
  file: /var/log/king-phisher.log
  # Available levels: FATAL, ERROR, WARNING, INFO, DEBUG
  level: DEBUG
  console: false

server:
  # Bind address information, multiple ports can be
  addresses:
    - host: 192.168.1.16
      port: 80
      ssl: false

I also tried with server : 0.0.0.0 , getting the same error

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
Sounds like the server is not running. 501 is the HTTP error for not implemented which is commonly returned by HTTP servers when the verb is not supported. In this case the verb that isn't supported is King Phishers RPC verb and the server isn't the King Phisher server. Make sure that your server is running and bound to the port you think it's bound to with a combination of `netstat` and `ps` or what ever utilities you'd prefer.

Also please do not share you're entire configuration file, it has your randomly generated database password in it.

**Comment by shrirambharathkumar** [comment]
Thanks Zerosteiner,
I have removed the server config file. Can you please help to rectify the error that states the "ensure HTTP server is currently running on port 80" it is installed in local VM , i am unable to connect to it. What things i need to check on it.

**Comment by zeroSteiner** [comment]
No, I can't help you to fix the error beyond making the recommendations that I already have. You need to verify that the server is correctly running on the port that you are trying to connect to. My guess is something else is already running there like apache or nginx.

**Comment by shrirambharathkumar** [comment]
Thanks ZeroStenier,
As stated the server had apache running on it. But i am stuck with issue number #94 . I will try to get that fixed with the solution provided in that issue. Thanks for the support.

**Comment by zeroSteiner** [comment]
Well since you were able to fix the issue that this ticket was originally opened for, I'm going to close it. You can browse the other closed issues for the solutions we've offered to people in the past. I also highly recommend reading the wiki very carefully, there's 24 pages of documentation just for how to use King Phisher.
