### ISSUE TITLE
Style fails to load in Kali

### ISSUE THREAD

**Issue by WJDigby** [securestate/king-phisher#165]
## Issue Description
King-Phisher client GUI style fails to load in Kali Linux Rolling Edition.

## Reproduction Steps
1. Start King Phisher in Kali Linux

## Environment Details
Host OS: Kali 2 Rolling Edition
Linux kali 4.7.0-kali1-amd64 #1 SMP Debian 4.7.5-1kali3 (2016-09-29) x86_64 GNU/Linux

## Error Details / Stack Trace
root@kali:~# python3 /opt/king-phisher/KingPhisher -L DEBUG
WARNING  it is not necessary to run the king phisher client as root
DEBUG    king phisher version: 1.5.2-beta (rev: 6ff175b1) python version: 3.5.2
DEBUG    client running in process: 6824 main tid: 0x7f428eb1b700
DEBUG    using ui data from glade file: /opt/king-phisher/data/client/king_phisher/king-phisher-client.ui
DEBUG    gi.repository GLib version: 2.50.0
DEBUG    gi.repository GObject version: 3.22.0
DEBUG    gi.repository Gtk version: 3.22.1
DEBUG    gi.repository VTE version: 2.91
DEBUG    matplotlib version: 1.5.3
INFO     loading the config from disk
INFO     loading 2 plugins
DEBUG    plugin 'check_for_updates' has been loaded
DEBUG    plugin 'data_collection' has been loaded
DEBUG    client loaded in 0.01 seconds
DEBUG    resetting the gtk-theme-name property to it's default value
DEBUG    resetting the gtk-icon-theme-name property to it's default value
DEBUG    loading style from css file: /opt/king-phisher/data/client/king_phisher/style/theme.v2.css
ERROR    css parser error (not a number) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:98
ERROR    css parser error (Expected a string.) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:98
ERROR    there was an error parsing the css file, it will not be applied as a style provider

**Comment by zeroSteiner** [comment]
@wolfthefallen my wild guess is that [this line](https://github.com/securestate/king-phisher/blob/6ff175b1fd3b412673f5dbbb1741189e3947b725/data/client/king_phisher/style/theme.v2.scss#L74) might need to be updated to `font-weight` instead of `font`. Don't forget that the CSS is generated from the SCSS file.

**Comment by zeroSteiner** [comment]
This has been fixed and is now sitting pretty in the dev branch.
