### ISSUE TITLE
Office 365 SMTP Connection Issue

### ISSUE THREAD

**Issue by rlfree** [securestate/king-phisher#167]
## Issue Description
After logging into the server via the client, I set the SMTP server settings in accordance to what Microsoft has listed on the email settings for using Office 365 email as an SMTP relay (smtp.office365.com:587 since I am using SSL). After correctly configuring the message settings I attempted to send the message but received an authentication error. I confirmed that both that my username and password were correct by copying and pasting the input I originally used into the Office 365 login page and successfully logged in. I also attempted to connect to the Office 365 SMTP server on ports 465, 2525, and 25 (both with SSL on and off for each). This also resulted in failure

I also tried to send a message via Gmail's SMTP relay service on port 465 since I have successfully sent messages through Gmail in the past. After configuring the SMTP server using the Gmail settings I was able to successfully send messages on the first attempt.

Next I checked the MX records to ensure that my email was being detected correctly as Office 365. MX records confirmed that Office 365 is the mail provider for the domain. 

## Reproduction Steps
1. Start King Phisher
2. Set SMTP settings as follows per Microsoft:
                  SMTP Server: smtp.office365.com:587
                  SMTP Username: Microsoft Office 365 email address
                  Connect With SSL: On
3. I receive a Connection Failed: Failed to connect to the SMTP Server. I attempted to reset the SMTP server settings to use Gmail's SMTP relay service and successfully sent email messages on the first attempt. 

## Environment Details
Host OS: Kali 2016.2

## Error Details / Stack Trace
I am just receiving a failed to connect to the SMTP server error as follows:
Checking the target URL... success, done.
Skipped checking the SPF policy because the SMTP server address could not be detected.
Message mode is: Email
Connecting to SMTP server... failed.

**Comment by zeroSteiner** [comment]
This seems easy enough for us to look into. Can you please also post the version of King Phisher you're using.

**Comment by rlfree** [comment]
The client side version I'm using is Version: 1.5.2-beta (rev: d09ca949) and the server side version I'm using is Version: 1.5.1. Let me know if you need any additional information. Thanks for the help.

**Comment by zeroSteiner** [comment]
These [docs](https://support.office.com/en-us/article/POP-and-IMAP-settings-for-Outlook-Office-365-for-business-7fc677eb-2491-4cbc-8153-8e7113525f6c) are a bit misleading. The connection to `smtp.office365.com:587` actually requires STARTTLS which King Phisher does not support right now. It only supports plaintext and full TLS / SSL connections.

As it is right now you won't be able to use Office 365's SMTP server.

**Comment by rlfree** [comment]
Thanks for the quick response! I appreciate the help!

**Comment by zeroSteiner** [comment]
This issue has now been fixed in the dev branch. To obtain the changes, you can either wait for them to be merged into the master branch (which will likely take a few weeks) or you can obtain them immediately by opting into [beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

Added this feature into the dev branch (see commit 0d31a49cbad675ac9e413deb476e6150130f09bc). When it's available **do not enable SSL** when connecting to the server. You need to use a plaintext connection and King Phisher will automatically identify that the remote server support `STARTTLS` and negotiate it for you.
