### ISSUE TITLE
Help: how to connect from python app to get a few campaign stats

### ISSUE THREAD

**Issue by twkrol** [securestate/king-phisher#170]
## Issue Description
I would like to write a simple python app to retrieve campaign stats and store them in reporting db

## Reproduction Steps
1. Could you provide a simple example how to connect to king-phisher server from vanilla python app?

## Environment Details

Host OS: Ubuntu 16.04 LTS

## Error Details / Stack Trace
none

**Comment by wolfthefallen** [comment]
King-phisher has extensive developer documentation at http://king-phisher.readthedocs.io/en/latest/
For an example of connecting to King Phishers database directly to pull information, please review the example ipython notebook that is located in the data directory.

**Comment by zeroSteiner** [comment]
I definitely agree, the iPython notebook is the best way to go. You can find it [here](https://github.com/securestate/king-phisher/blob/master/data/king-phisher.ipynb) and will need a working understanding of SQLAlchemy. There's a few examples in there to help you get started.

Alternatively if you wanted to create a new graph you could do that and or write a client plugin to provide the graph of some other feature which would take alot more effort. Finally, the last option would be to write some Python code and import or exec it in the RPC Terminal of the client (which is only available on Linux). The RPC documentation is available with the rest of the technical documentation [here](http://king-phisher.readthedocs.io/en/latest/server_api/rpc_api.html).

**Comment by twkrol** [comment]
Thank you for suggestions.
I would like to use RPC API as I prefer to integrate using api's.
But I'm not sure if the xmlrpclib will work (tried but unsuccessfull) or need to use AdvancedHTTPServer for RPC? Therefore any working example will help.

**Comment by zeroSteiner** [comment]
Yes, you'll need to use the AdvancedHTTPServer RPC interface. It's not actually xmlrpc at all. The client RPC class is documented [here](http://king-phisher.readthedocs.io/en/latest/king_phisher/client/client_rpc.html#king_phisher.client.client_rpc.KingPhisherRPCClient).

A quick primer on how to use it:
```
# the instance is directly callable through python's __call__ interface
rpc('ping')
# the first argument is a string of the remote method that is to be called, args and kwargs can be added after that
rpc('geoip/lookup', '8.8.8.8', lang='en')
```

Hope that helps get you started. You can grep for `rpc(` in the king_phisher/client code base and you'll find many other examples.

**Comment by twkrol** [comment]
Ok, got it working, and simple demo below for memory and helping others:
`from king_phisher.client import client_rpc

#connect
server = ('localhost',80)
rpc = client_rpc.KingPhisherRPCClient(server, use_ssl=0)
login_result, login_reason = rpc.login("username", "password", None)
if not login_result:
	print('failed to authenticate to the remote king phisher service, reason: ' + login_reason)
else:
	rpc.username = rpcusername
	print('successfully authenticated to the remote king phisher service')

#list campaigns & stats
for campaign in rpc.remote_table('campaigns'):
	print(str(campaign.id)+":"+campaign.name)
`
