### ISSUE TITLE
SPF-Record Check

### ISSUE THREAD

**Issue by wolfthefallen** [securestate/king-phisher#171]
## Issue Description
A stack trace occurs when checking to see if a domain has a SPF Record. It appears to be occurring when parsing out the exchange part of the mx_record. Not sure if it just hard failures, soft, or both.

## Reproduction Steps
1. Start King Phisher Windows Client version 1.5.1
2.a Put in an email address for a domain that has a soft SPF record failure.
2.b Put in an email address for a domain that has a hard SPF record failure.

## Environment Details

Host OS: Windows 7, Windows 2008 R2

## Error Details / Stack Trace

```
Error Type: exceptions.AttributeError
Error Details: AttributeError("'GenericRdata' object has no attribute 'exchange'",)
Error UID: 34d55106-1f9a-4bec-9fb6-fbf1a4b52b1c
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.5.1
Platform Version: Windows: 7 6.1.7601 SP1 Multiprocessor Free (Frozen=True)
Python Version: 2.7.12
Gtk Version: 3.14.15
Timezone: America/New_York

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-2 (alive=True daemon=True)
    Thread-1 (alive=True daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\client\tabs\mail.py", line 866, in signal_button_clicked_verify_spf
    spf_result = spf_test.check_host()
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\spf.py", line 170, in check_host
    self.policy = self._check_host(self.ip_address, self.domain, self.sender)
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\spf.py", line 232, in _check_host
    if self._evaluate_mechanism(ip, domain, sender, mechanism, rvalue):
  File "Y:\FastStorage\king-phisher-release\king-phisher\king_phisher\spf.py", line 288, in _evaluate_mechanism
    mx_record = str(mx_record.exchange).rstrip('.')
AttributeError: 'GenericRdata' object has no attribute 'exchange'
```

**Comment by zeroSteiner** [comment]
Can't reproduce this exact error on Linux, or Windows without it being frozen. I did however identify 2 issues that I am in the process of fixing.

1. The DNS limit was effectively set to 9 instead of 10 due to improper checking of the remaining queries
1. A check using a `str` type was failing in Python 2 due to `rvalue` being `unicode`

**Comment by zeroSteiner** [comment]
Fixed a third issue that was actually a variation in functionality from the RFC where DNS queries which resulted with an RCODE of 3 or `dns.rcode.NXDOMAIN` would immediately raise a temperror instead of proceeding as if no records were retrieved.

**Comment by wolfthefallen** [comment]
confirmed the DNS fixes are working correctly and updated windows cx_freeze, to support windows build in commit 138e49f.
