### ISSUE TITLE
smtplib.SMTPDataError

### ISSUE THREAD

**Issue by rlfree** [securestate/king-phisher#175]
## Issue Description
When sending emails I receive "WARNING  failed to send message (exception: smtplib.SMTPDataError)"
This issue just started a couple days ago. I was able to successfully use King Phisher to send emails via Office 365 SMTP just a few days ago using the same reproduction steps. 

## Reproduction Steps
1. Start King Phisher server and client both with python3 command.
2. Use Office 365 SMTP server, Port 587, Connect With SSL turned off.
3. Attempt to send email with no attachment.

## Environment Details
Client Side OS: Kali 2016.2
KingPhisher Version: 1.6.0-beta1 (rev: 15907b0acbf1)
Python Version: 3.5.2+

Server Side OS: Ubuntu 16.04.1 LTS
KingPhisherServer Version: 1.6.0-beta1 (rev: 15907b0acbf1)
Python Version: 3.5.2

## Error Details / Stack Trace
When sending emails I received the following error and delivery failure from the log:
            "WARNING  failed to send message (exception: smtplib.SMTPDataError)"
I verified that I was able to successfully connect to the SMTP server from the the client GUI as well:
            "Connecting to SMTP server... done."
After three attempts to send the message, the client GUI displays:
             "Paused sending emails, waiting to resume"
Attempting to send the message again results with the same error as above.

**Comment by zeroSteiner** [comment]
Can you provide the output from the logs on the console with the level set to DEBUG? Also to clarify are you able to send emails and you get this error after a few or you can't send any at all? If you are able to send emails, is it having an error on a particular target or after a particular number of targets?

**Comment by rlfree** [comment]
I can't send emails at all. I was able to send emails to both single email addresses and to multiple email addresses via CSV and both result in failure.

I also confirmed that emails sent through Gmail's SMTP server with SSL enabled works with both single and multiple addresses.

Here is the results with the client set to debug, I attempted to send three times. I did sanitize my email and the UID from this output.

WARNING  skipping spf policy check because the smtp server address could not be reliably detected
INFO     writing the client configuration to disk
DEBUG    loading GTK builder object with id: LoginDialogBase.button_connect
DEBUG    loading GTK builder object with id: LoginDialogBase.entry_server
DEBUG    loading GTK builder object with id: LoginDialogBase.entry_username
DEBUG    loading GTK builder object with id: LoginDialogBase.entry_password
DEBUG    loading GTK builder object with id: LoginDialogBase.label_main
DEBUG    target SMTP server supports the STARTTLS extension
DEBUG    calling RPC method: campaign/landing_page/new
DEBUG    loaded 0 MIME attachments
INFO     sending email 1 of 1 with uid: ####### to #######
INFO     failed to send message (exception: smtpdataerror)
WARNING  failed to send message (exception: smtplib.SMTPDataError)
INFO     failed to send message (exception: smtpdataerror)
WARNING  failed to send message (exception: smtplib.SMTPDataError)
INFO     failed to send message (exception: smtpdataerror)
WARNING  failed to send message (exception: smtplib.SMTPDataError)
INFO     disconnected from the smtp server
INFO     paused sending emails, waiting to resume
INFO     resuming sending emails
DEBUG    target SMTP server supports the STARTTLS extension
INFO     failed to send message (exception: smtpdataerror)
WARNING  failed to send message (exception: smtplib.SMTPDataError)
INFO     failed to send message (exception: smtpdataerror)
WARNING  failed to send message (exception: smtplib.SMTPDataError)
INFO     failed to send message (exception: smtpdataerror)
WARNING  failed to send message (exception: smtplib.SMTPDataError)
INFO     disconnected from the smtp server
INFO     paused sending emails, waiting to resume
INFO     resuming sending emails
DEBUG    target SMTP server supports the STARTTLS extension
INFO     failed to send message (exception: smtpdataerror)
WARNING  failed to send message (exception: smtplib.SMTPDataError)
INFO     failed to send message (exception: smtpdataerror)
WARNING  failed to send message (exception: smtplib.SMTPDataError)
INFO     failed to send message (exception: smtpdataerror)
WARNING  failed to send message (exception: smtplib.SMTPDataError)
INFO     disconnected from the smtp server
INFO     paused sending emails, waiting to resume

**Comment by zeroSteiner** [comment]
So I was able to reproduce this error by purposely typo-ing my email address in the "Source Email (SMTP)" and "Source Email (MIME)" fields. It looks like the same value needs to be in both of those places as well as the username with which you are authenticating to outlook 365.

Can you confirm that all three of these values are the same? If they are can you also please try with an overly-simplified email template to ensure it's not flagging on something malicious in the message HTML.

**Comment by rlfree** [comment]
That fixed it. When I changed over my MIME username to the same as the SMTP username it corrected this issue and I was able to successfully send emails.
