### ISSUE TITLE
KingPhisher-1.5.2-win32 msi Crashed at  Startup

### ISSUE THREAD

**Issue by Ben3Othman** [securestate/king-phisher#177]
## Issue Description
I install KingPhisher-1.5.2-win32 msi on windows 7 pro , installation completed succesfully , but whene running KP  client , and error aoccured : cx_freeze error in main script

## Reproduction Steps
1. Start King Phisher
2. error  dispalyed

## Environment Details

Host OS: Windows 7 Pro

## Error Details / Stack Trace
![startup](https://cloud.githubusercontent.com/assets/24269851/21748315/4087e4c2-d582-11e6-92bb-fbd49ef7da2b.PNG)

**Comment by wolfthefallen** [comment]
I cannot reproduce this error.

Please make sure you have completely uninstalled King Phisher (All versions) from add and remove programs, and then reinstall.

If the issue reproduces please provide more information and step by step instructions on how to recreate it.

**Comment by Ben3Othman** [comment]
I installed it on windows 8 pro and it works successfully , but let you know that the same problem persist for windows 7 pro 

Thank you

**Comment by wolfthefallen** [comment]
Glad to hear that you got it working on a windows box. Unfortunately I have not been able to recreate the issue you are having on your Windows 7 Pro instance.
