### ISSUE TITLE
King Phisher Error

### ISSUE THREAD

**Issue by jgoody** [securestate/king-phisher#178]
## Issue Description
I am trying to start King Phisher on Kali Linux and I am getting the following error:

ImportError: No Module named AdvancedHTTPServer

## Reproduction Steps

Just tried running /usr/share/king-phisher/kingphisher

## Environment Details
KALI 20167

## Error Details / Stack Trace
ImportError: No Module named AdvancedHTTPServer

```

**Comment by wolfthefallen** [comment]
Try running it with `python3 /usr/share/king-phisher/KingPhisher`
if that fails you will need to install AdvancedHTTPServer. This can be completed with pip, `pip install AdvancedHTTPServer` or if you want to run it with python3 `pip3 install AdvancedHTTPServer`

**Comment by jgoody** [comment]
next error:

ImportError:  No module names 'termcolor'

**Comment by zeroSteiner** [comment]
It sounds like you haven't properly installed the application. Can you please follow the instructions in the [INSTALL](https://github.com/securestate/king-phisher/blob/master/INSTALL.md) guide, mainly the part about running the script.

After that keep in mind that when running it from the command like, as @wolfthefallen stated, you'll need to run it with `python3`.

**Comment by jgoody** [comment]
It comes preinstalled on Kali.

**Comment by zeroSteiner** [comment]
Have you tried executing it through the GUI menu?

**Comment by jgoody** [comment]
ok, looks like I was mistaken.  It isn't pre-installed.  I ran the install as instructed in the INSTALL guide and it is unable tollocate girl.2-webjit-3.0.

forgive me I am a n00b

**Comment by wolfthefallen** [comment]
With Kali Linux it is recommend to use `apt-get install king-phisher` to make sure all the dependencies are correctly installed. If you are having issues after the install, Please send us a stack-trace so we can make sure we are providing the best feed back possible.

**Comment by jgoody** [comment]
which command to use for the stack trace?  strace doesn't work on Kali.

**Comment by wolfthefallen** [comment]
stack trace is the whole out put that is generated when you try to launch king phisher.

**Comment by jgoody** [comment]
root@LAB-KALI-2016:/usr/share/king-phisher# python3 KingPhisher
Traceback (most recent call last):
  File "KingPhisher", line 44, in <module>
    from king_phisher import color
  File "/usr/share/king-phisher/king_phisher/color.py", line 41, in <module>
    import termcolor
ImportError: No module named 'termcolor'

**Comment by jgoody** [comment]
sudo pip install termcolor
Requirement already satisfied: termcolor in /usr/lib/python2.7/dist-packages

**Comment by wolfthefallen** [comment]
I recommend install from GitHub so you are on the latest version. To do this you will need to uninstall King Phisher, then clone down the GitHub repository, and run the `tools/install.sh` script. Run the commands below as root, and it should do the trick for you.
```
apt-get remove king-phisher
cd /opt
git clone https://github.com/securestate/king-phisher.git
cd king-phisher
tools/install.sh
python3 KingPhisher
```

**Comment by jgoody** [comment]
I ran pip install -r requirements.txt and all requirements installed and now working.

**Comment by wolfthefallen** [comment]
Cool as you run through your campaign(s) if you have any issues please refer to the King Phisher [wiki](https://github.com/securestate/king-phisher/wiki) and the [video guides](https://securestate.wistia.com/projects/laevqz2p29).
