### ISSUE TITLE
Client RPC API Compatibility Question

### ISSUE THREAD

**Issue by fdeleon463** [securestate/king-phisher#18]
Hey guys, i recently installed KP and when i try to connect via desktop client on a 64bits Windows 7

i get this:

The RPC API Versions Are Incompatible
The local client is not up to date with the server version.
Please ensure that both the client and server are fully up to date

Any clues?
Thanks

**Comment by zeroSteiner** [comment]
That message is displayed when the version of the server is newer than the version of the client. If you recently installed the latest server version then you're running 0.2.0-beta. The Windows binaries are only built for the major releases meaning that it is still on 0.1.7.

You'll need to do a ```git checkout v0.1.7``` from the King Phisher directory on the server to downgrade and use the older version that the windows client is currently compatible with.

Alternatively, you can install the latest King Phisher client on Linux from source using the steps [here](https://github.com/securestate/king-phisher/blob/master/INSTALL.md), which will be compatible with the 0.2.0-beta server you are running.

**Comment by fdeleon463** [comment]
I installed this morning so, yeah, thats probably it. Il do the workaround and let you know the results.

Thanks for your time

**Comment by fdeleon463** [comment]
Hi, i did the "git chekout v0.1.7 with no problems.

Now im getting this:

Traceback (most recent call last):
  File "opt/king-phisher/KingPhisherServer", line 205, in <module>
    sys.exit(main())
  File "opt/king-phisher/KingPhisherServer", line 85, in main
    missing_requirements = utilities.check_requirements(__requirements__)
  File "/opt/king-phisher/king_phisher/utilities.py", line 212, in check_requirements
    installed_version = distutils.version.StrictVersion(installed_pkg.version)
  File "/usr/lib64/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib64/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '0.7.5.post2'

Seems like im still doing something wrong

**Comment by zeroSteiner** [comment]
Ah yes, that issue is described in #18 and has already been fixed.

As a work around until 0.2.0 is released (which will be in the next few weeks), you can do ```pip install alembic==0.6.7``` on the server.

**Comment by fdeleon463** [comment]
Yes!!! that worked great, thanks a lot.

ps: sorry for repeating an exsiting issue

**Comment by zeroSteiner** [comment]
It's no problem, glad that fixed your issue. I'm going to go ahead and close this now.

If you experience any more problems feel free to open another issue ticket.
