### ISSUE TITLE
Send Email with cci  address

### ISSUE THREAD

**Issue by Ben3Othman** [securestate/king-phisher#180]
Hello;

I've a  mail diffusing list and i don't want that the list email appear to the users when sending phishing email, is it possible to send email with cci to hide the destination email-address

**Comment by zeroSteiner** [comment]
I don't know what you're referring to as "CCI" and can't find any obvious references from a search engine. I'm going to guess that what you're referring to is not supported.

**Comment by Ben3Othman** [comment]
Cci : copy carbon invisible and in  english is :  BCC : Blind carbon copy

Means i want to send a phishing  email to a destribution list  using BCC, i dont want  to show  the destination  address to the users

Sorry for using the french  abbreviation

**Comment by zeroSteiner** [comment]
That makes a lot more sense, thanks for clarifying. Sending emails with CC and BCC is something on our to do list. It'll hopefully be added in one of the next releases.

**Comment by Ben3Othman** [comment]
Thank you , we are waiting for the next release; it's very interesting for organization that have very large number of users, to use distribution list to send emails, because  sending phishing emails, one by one for more than 10000 users will take much time (  one day (8hours)),  but distribution list will take 10 or 15 min

**Comment by zeroSteiner** [comment]
PR #188 adds the ability to send messages to targets using CC and BCC. If you can test it out, let us know what you think.
