### ISSUE TITLE
Dev Revision Compatibility Issue: ValueError("Expected string but got 1<class 'int'>",)

### ISSUE THREAD

**Issue by rlfree** [securestate/king-phisher#182]
## Issue Description
Just wanted to reach out and let you know of this error we just started receiving with the most current revision of the Dev branch. 

Not an issue since our team was able to find a workaround for it. If anyone on our team uses the newest revision for their client side, it throws a ValueError("Expected string but got 1<class 'int'>",)

## Reproduction Steps
1. Start King Phisher Server with version 1.6.0-beta3 (rev: 717952217ac8)
2. Pull the most current dev version of King Phisher for the client.
3. Log in to King Phisher via SSH and attempt to open a previously saved campaign, error should be thrown at this point.
4. Workaround to fix the issue was pretty simple:
    On the client run:
        git reset 717952217ac89ecc56ef85f09fcbc3dffea569f8
	git reset –hard

## Environment Details
Server OS: Ubuntu 16.04.1 LTS Xenial
KingPhisherServer Version: 1.6.0-beta3 (rev: 717952217ac8)

Host OS: Kali Rolling 
KingPhisherClient Version 1.6.0-beta3 (rev: a627577f8717)

## Error Details / Stack Trace
Error Type: builtins.ValueError
Error Details: ValueError("Expected string but got 1<class 'int'>",)
Error UID: 02294917-0639-4c5b-a543-a6eac68aa543
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.6.0-beta3 (rev: a627577f8717)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.5.3
Gtk Version: 3.22.5
Timezone: Etc/UTC

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-6 (alive=True daemon=True)
    Thread-24 (alive=True daemon=True)
    Thread-10 (alive=True daemon=True)
    Thread-5 (alive=True daemon=False)
    Thread-27 (alive=True daemon=True)
    Thread-11 (alive=True daemon=True)
    Thread-20 (alive=True daemon=True)
    Thread-19 (alive=True daemon=True)

Stack Trace:
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/gui_utilities.py", line 104, in wrapper
    results.append(function(*args))
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 956, in append
    return self._do_insert(-1, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 947, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 857, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 875, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 218, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 274, in set_value
    (py_value, type(py_value)))
ValueError: Expected string but got 1<class 'int'>

**Comment by zeroSteiner** [comment]
@wolfthefallen This looks related to the changes introduced in 69e5a4f9cdec689c5d4fa959ac1b506b1b8e591d to fix the unicode issues we were experiencing.

**Comment by rlfree** [comment]
Also, not sure if this is related (might be a connection reliability issue with our ISP) but I also randomly receive a Socket Error (#N/A) when attempting to SSH into the server from the client from time to time. Doesn't happen all the time, maybe every 1 out of 10 login attempts. I have HTTPS enabled login on the server config. This also started around the same time as the above error.

**Comment by zeroSteiner** [comment]
I am able to reproduce this `ValueError`, I'll have it fixed shortly. Thanks for bringing this to our attention.

**Comment by zeroSteiner** [comment]
Alright just pushed up commit 50ac24586567482eef44d537cf057d72bec1f60b which fixes this issue. If you wouldn't mind verifying it, we can get this issue closed out.

**Comment by rlfree** [comment]
That fixed the issue. Thanks for the help. I really appreciate everything that you and your team does on this project.
