### ISSUE TITLE
Cannot start KingPhisher

### ISSUE THREAD

**Issue by mother2110** [securestate/king-phisher#183]
## Issue Description
Error when starting KingPhisher

## Reproduction Steps
sudo service king-phisher start
Job for king-phisher.service failed because the control process exited with error code. See "systemctl status king-phisher.service" and "journalctl -xe" for details.

## Environment Details

Host OS: Ubuntu 16.04 LTS
King Phisher Version: 1.5.1

## Error Details / Stack Trace
`king@phisher:/opt$ systemctl status king-phisher.service
● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-01-19 17:25:13 PST; 1min 58s ago
  Process: 30132 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml (code=exited, status=1/FAILURE)
 Main PID: 22693 (code=killed, signal=TERM)

Jan 19 17:25:13 phisher python3[30132]:   File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
Jan 19 17:25:13 phisher python3[30132]:     return self.fetch_value()
Jan 19 17:25:13 phisher python3[30132]:   File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 576, in fetch_value
Jan 19 17:25:13 phisher python3[30132]:     self.get_mark())
Jan 19 17:25:13 phisher python3[30132]: yaml.scanner.ScannerError: mapping values are not allowed here
Jan 19 17:25:13 phisher python3[30132]:   in "/opt/king-phisher/server_config.yml", line 103, column 21
Jan 19 17:25:13 phisher systemd[1]: king-phisher.service: Control process exited, code=exited status=1
Jan 19 17:25:13 phisher systemd[1]: Failed to start King Phisher Server.
Jan 19 17:25:13 phisher systemd[1]: king-phisher.service: Unit entered failed state.
Jan 19 17:25:13 phisher systemd[1]: king-phisher.service: Failed with result 'exit-code'.
`

I am using port 443 and letsencrypt. I was following this post > https://www.sw1tch.net/2016/11/24/king-phisher-1-5-1-with-ssh-keys-tls/
```

**Comment by zeroSteiner** [comment]
You're configuration file is malformed. It says that line 103 is the problem.

**Comment by mother2110** [comment]
Thank you.. I found the issue
