### ISSUE TITLE
Almost there!!  Error:404: Page Not Found

### ISSUE THREAD

**Issue by mother2110** [securestate/king-phisher#184]
## Issue Description
I am using the generic Web credential template and can send emails to users. Users get the email and when they click on the link they get Error: 404: Page Not Found.
the link looks right - https://name.com/login?id=Qwhnfnlskd33

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 16.04 lts.
King Phisher Version: 1.5.1

## Error Details / Stack Trace

Not sure what to put here..
```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by wolfthefallen** [comment]
Please review the [FAQ 404 Error](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#im-getting-a-404--error-page-on-the-server). You will want to use the jinja text `<a href="{{ url.webserver }}">the text of the link</a>`  to dynamically create the link for each user. This will allow them to view the landing page, and for you to collect the data for each unique email you send out.

**Comment by zeroSteiner** [comment]
I'm closing this issue because there hasn't been any activity in over a week.

**Comment by mother2110** [comment]
Sorry - I have been swamped here at work. Everything is working fine
