### ISSUE TITLE
Can't Install on Backbox

### ISSUE THREAD

**Issue by anonxx1** [securestate/king-phisher#185]
sudo bash install.sh
[sudo] password for user1: 
Failed to detect the version of Linux
This installer only supports the following Linux distributions:
  - BackBox
  - CentOS
  - Debian
  - Fedora
  - Kali
  - Ubuntu

If the current version of Linux is one of these flavors but it is
not recognized, please open a support ticket and include the version.
---------
└─[~]>cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
--------
└─[~]>cat /etc/issue
BackBox Linux 4.7

**Comment by anonxx1** [comment]
waiting ....

**Comment by zeroSteiner** [comment]
The issue has been assigned. It'll be updated when the status has been changed or we have questions.

**Comment by wolfthefallen** [comment]
Currently the `tools/install.sh` script only supports Backbox versions 4-6. This issue will be addressed in the next release.

**Comment by anonxx1** [comment]
Thanks, i guess i have to wait more

**Comment by wolfthefallen** [comment]
The dev branch now has an updated `tools/install.sh` script to support the newest version of BackBox and future minor releases of BackBox 4.x.

**Comment by zeroSteiner** [comment]
The next release will be this Tuesday, and at that time the changes that are currently in the dev branch will be merged into the master branch.

**Comment by zeroSteiner** [comment]
The 1.6.0 release is now complete.
