### ISSUE TITLE
no module named smoke_zephyr

### ISSUE THREAD

**Issue by cappinmcnasty** [securestate/king-phisher#186]
## Issue Description
I get a error when I...

## Reproduction Steps
1. Install King Phisher as instructed at this site:
https://www.sw1tch.net/2015/06/24/gone-kingphishin-part-1-kingphisher-beef-digital-ocean-kali/
2. Run KinPhisherServer 
sudo python /opt/king-phisher/KingPhisherServer -L INFO -f server_config.yml

## Environment Details
Host OS: Ubuntu 16.04

## Error Details / Stack Trace
Using username "root".
Authenticating with public key "rsa-key-20170121"
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-59-generic x86_64)
root@KingPhish:~# sudo python /opt/king-phisher/KingPhisherServer -L INFO -f server_config.yml
Traceback (most recent call last):
  File "/opt/king-phisher/KingPhisherServer", line 42, in <module>
    from king_phisher import color
  File "/opt/king-phisher/king_phisher/__init__.py", line 33, in <module>
    from . import version
  File "/opt/king-phisher/king_phisher/version.py", line 37, in <module>
    import smoke_zephyr.utilities
ImportError: No module named smoke_zephyr.utilities
root@KingPhish:~#

**Comment by wolfthefallen** [comment]
That particular guide you are using is a old, sw1tch has done an [updated guide](https://www.sw1tch.net/2016/11/24/king-phisher-1-5-1-with-ssh-keys-tls/) that works like a charm.
As you are installing KingPhisher with the `tools/install.sh` tool you will need use python3 to start the server. `python3 /opt/king-phisher/KingPhisherServer -L INFO -f server_config.yml`

**Comment by cappinmcnasty** [comment]
I reinstalled using the updated guide and everything seemed to go well right up until the end.  When I get to the line that says "sudo service king-phisher start" I get the following error:
Job for king-phisher.service failed because the control process exited with error code. See "systemctl status king-phisher.service" and "journalctl -xe" for details.
I ran "journalctl -xe" and get the following errors:
an error occurred while parsing the server configuration file while parsing a block mapping
in “/opt/king-phisher/server_config.yml”, line 26, column 3
did not find expected key in “/opt/king-phisher/server_config.yml”, line 109, column 7
king-phisher.service: Control process exited, code=exited status=78
Failed to start King Phisher Server.
I wiped the server and reinstalled from scratch to eliminate any possibility of some error and I get the exact same message.  Earlier in the instructions the only changes that were to be made to server_config.yml the port change and ssl path settings.  I navigated to the directory and at first thought that the paths were not created properly since I could not see any directory within letsencrypt directory but then I realized that only root could see those folders so I thought that was my problem.  I used chown to grant my user access and then I could navigate down to the fullchain.pem and privkey.pem and everything seemed to be in order so I attempted to run "sudo service king-phisher start" again but I get the exact same message.  Any suggestions on what to try next?

**Comment by wolfthefallen** [comment]
There is an error in your configuration file. Line 26 and 109. Correct those issues and then it should start with out an issue.

**Comment by cappinmcnasty** [comment]
I rolled back my server then ran the install again this time eliminating the "letsencrypt" portion of the wallkthrough and now it starts up with no issues.  Does anyone have a more detailed walkthrough of enabling the letsencrypt ssl function?  I would love to use this for added security, and I believe it is likely my unfamiliarity with it that is causing the problem.

**Comment by zeroSteiner** [comment]
There is a whole Server SSL Support wiki page which will have all of the information you need except for the Let's Encrypt specifics. We also have a blog post that may help you here: https://warroom.securestate.com/lets-hack-part-2-using-certificates-from-lets-encrypt/
