### ISSUE TITLE
Cannot open SMTP options

### ISSUE THREAD

**Issue by cappinmcnasty** [securestate/king-phisher#190]
## Issue Description
Errors show up in the terminal whenever I do anything at all.  Program seems to function but cannot find preferences supposedly I click edit>preferences to set smtp but there is no preferences not sure if these errors have to do with it.

## Reproduction Steps
1. Start King Phisher
2. Do anything

## Environment Details
Host OS: Ubuntu 16.04 GNOME
King Phisher Version: 1.6.0

## Error Details / Stack Trace
(KingPhisher:4675): Gtk-WARNING **: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita

(KingPhisher:4675): Gtk-WARNING **: Error loading theme icon 'document-save' for stock: Icon 'document-save' not present in theme Adwaita

(KingPhisher:4675): Gtk-WARNING **: Error loading theme icon 'document-save-as' for stock: Icon 'document-save-as' not present in theme Adwaita

(KingPhisher:4675): Gtk-WARNING **: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita

```

**Comment by zeroSteiner** [comment]
What do you mean there is "no preferences"? When you click `Edit > Preferences` what happens, do you see the preferences dialog window popup?

**Comment by cappinmcnasty** [comment]
I click edit but there is no preferences option at all simply a blank window with 3 unlabeled buttons.   When I get access to my box I will send a screencap

⁣Sent from BlueMail ​

**Comment by wolfthefallen** [comment]
I've been unable to reproduce this issue in Ubuntu 16 GNOME with GTK version 3.18 or 3.20.
@cappinmcnasty Have you altered or uninstalled the default Adwaita Gnome Theme?

**Comment by cappinmcnasty** [comment]
I haven't altered the default adwaita gnome theme.  I tried installing as stated above and it said that it was already the newest version.  Here are screenshots of the login up to the point where I should see preferences when I click edit:
![login](https://cloud.githubusercontent.com/assets/24417131/22856909/185e5b28-f069-11e6-804e-c650638062bd.JPG)
![once logged in](https://cloud.githubusercontent.com/assets/24417131/22856910/1c171426-f069-11e6-8d19-87e12249d319.JPG)
![edit missing preferences](https://cloud.githubusercontent.com/assets/24417131/22856915/29cbc04e-f069-11e6-8bd0-c88b2b8ae311.JPG)

**Comment by wolfthefallen** [comment]
The tab `edit` is for the body of phishing email you are sending out. Please read the [wiki](https://github.com/securestate/king-phisher/wiki) for additional information. The [how to video](https://securestate.wistia.com/projects/laevqz2p29) is a great place to start.

**Comment by zeroSteiner** [comment]
That also does not look like Ubuntu GNOME based on the colors and the missing menu bar. Regardless, @wolfthefallen is correct and this is not a bug.

**Comment by wolfthefallen** [comment]
For the missing Icon buttons it appears that there is an issue with your gnome icon cache,  One option you can try is `sudo update-icon-caches /usr/share/icons/*` . If that does not work you will have to conduct further research, on your own, to resolve your gnome issues.

**Comment by cappinmcnasty** [comment]
I didn't know that the gnome desktop was required I was just using the default unity desktop that comes with 16.4 I will install the gnome desktop and see if that helps.

**Comment by zeroSteiner** [comment]
It's not the Desktop, Ubuntu GNOME is a spin off that uses GNOME instead of Unity. It shouldn't be necessary. King Phisher should run just fine, it just may not look quite as nice as it does on native GNOME environments. I wouldn't recommend making serious system changes unless something isn't functioning in King Phisher but that's up to you.

**Comment by cappinmcnasty** [comment]
It appears to have been the operating system.  Installed the client on 3 different Ubuntu clients and no menu bar, The first time I installed on a Gnome client all menu bars and icons were visible.  All clients were installations into VirtualBox and only had King Phisher installed once the install was complete.  Version was Ubuntu 16.04, the version of Ubuntu Gnome is 16.1.

**Comment by wolfthefallen** [comment]
Found issue to be Ubuntu Unity does not have the Adwaita full icon theme package installed. Manual fix `sudo apt install adwaita-icon-theme-full`. `tools/install.sh` script now installs adwaita-icon-theme-full if operating system is identified as Ubuntu.
