### ISSUE TITLE
Opener IP Address shows load balancer rather than client IP

### ISSUE THREAD

**Issue by AlexCline** [securestate/king-phisher#195]
In our environment, our KP server is running in a docker container behind an Elastic Load Balancer. When targets open links in messages, the campaign report shows the Opener IP Address as that of the ELB for all targets. The ELB will create the X-Forwarded-For header that contains the upstream client IP. This header will be prepended to if there are multiple load balancers. The last IP will always be the upstream client IP.

Please update the campaign reporting mechanism to use the last IP from the X-Forwarded-For header if it exists rather than the connecting client IP.

Additionally, because the Opener IP Address is a private IP address (10.x.x.x), Visitor Location information doesn't seem to be available.

More Info:
http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

This is related to #32 

Host OS: Ubuntu 16.04
KP Version: 1.6.0

**Comment by zeroSteiner** [comment]
You should be able to set the server configuration option `server.client_ip_cookie`. The name is a admittedly a bit misleading as it is treated as a the name of a header and not a cookie. Just set that option to the following and restart the server.

```yaml
    client_ip_cookie: X-Forwarded-For
```
That should do the trick.

**Comment by AlexCline** [comment]
Thanks @zeroSteiner. Setting `client_ip_cookie: X-Real-IP` gave the right display in the interface.
