### ISSUE TITLE
Failed to connect to the kingphisher service

### ISSUE THREAD

**Issue by Quinnshank** [securestate/king-phisher#199]
Okay I'm on Parrot OS and every time I try to start kingphisher and go to login it says "Failed to connect to the kingphisher service, the server responded with HTTP status: 501 I don't know what I'm doing wrong can you please help me?
```

**Comment by wolfthefallen** [comment]
Can you please check your King Phisher Server logs, it will provide more information to help troubleshooting.

**Comment by Quinnshank** [comment]
this is KingPhisherServer log:
#!/usr/bin/python -B
# -*- coding: utf-8 -*-
#
#  KingPhisherServer
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are
#  met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following disclaimer
#    in the documentation and/or other materials provided with the
#    distribution.
#  * Neither the name of the project nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#  pylint: disable=too-many-locals

import argparse
import logging
import os
import pwd
import signal
import sys
import threading

from king_phisher import color
from king_phisher import errors
from king_phisher import find
from king_phisher import geoip
from king_phisher import its
from king_phisher import utilities
from king_phisher import version
from king_phisher.server import build
from king_phisher.server import plugins

from boltons import strutils
from smoke_zephyr.configuration import Configuration
from smoke_zephyr.requirements import check_requirements

__requirements__ = [
	'advancedhttpserver==2.0.5',
	'alembic>=0.8.6',
	'blinker>=1.3',
	'boltons>=16.2.2',
	"dns{0}>=1.12.0".format('python' if its.py_v2 else 'python3'),
	'geoip2>=2.2.0',
	'Jinja2>=2.8',
	'markupsafe>=0.23',
	'msgpack-python>=0.4.7',
	'pluginbase>=0.4',
	'psycopg2>=2.6.1',
	'pyotp>=2.1.1',
	'python-dateutil>=2.4.2',
	'PyYAML>=3.11',
	'requests>=2.10.0',
	'SQLAlchemy>=1.0.13',
	'termcolor>=1.1.0'
]
if its.py_v2:
	__requirements__.append('ipaddress>=1.0.16')

logger = logging.getLogger('KingPhisher.Server.CLI')

def build_and_run(arguments, config, plugin_manager):
	# fork into the background
	should_fork = True
	if arguments.foreground:
		should_fork = False
	elif config.has_option('server.fork'):
		should_fork = bool(config.get('server.fork'))
	if should_fork and os.fork():
		return sys.exit(os.EX_OK)

	try:
		king_phisher_server = build.server_from_config(config, plugin_manager=plugin_manager)
	except errors.KingPhisherError as error:
		logger.critical(error.message)
		return os.EX_SOFTWARE

	server_pid = os.getpid()
	logger.info("server running in process: {0} main tid: 0x{1:x}".format(server_pid, threading.current_thread().ident))

	if should_fork and config.has_option('server.pid_file'):
		pid_file = open(config.get('server.pid_file'), 'w')
		pid_file.write(str(server_pid))
		pid_file.close()

	if config.has_option('server.setuid_username'):
		setuid_username = config.get('server.setuid_username')
		try:
			user_info = pwd.getpwnam(setuid_username)
		except KeyError:
			logger.critical('an invalid username was specified as \'server.setuid_username\'')
			king_phisher_server.shutdown()
			return os.EX_NOUSER
		if config.has_option('logging.file') and config.get('logging.file'):
			os.chown(config.get('logging.file'), user_info.pw_uid, user_info.pw_gid)
		os.setregid(user_info.pw_gid, user_info.pw_gid)
		os.setreuid(user_info.pw_uid, user_info.pw_uid)
		logger.info("dropped privileges to the {0} account".format(setuid_username))
	else:
		logger.warning('running with root privileges is dangerous, drop them by configuring \'server.setuid_username\'')

	db_engine_url = king_phisher_server.database_engine.url
	if db_engine_url.drivername == 'sqlite':
		logger.warning('sqlite is no longer fully supported, see https://github.com/securestate/king-phisher/wiki/Database#sqlite for more details')
		database_dir = os.path.dirname(db_engine_url.database)
		if not os.access(database_dir, os.W_OK):
			logger.critical('sqlite requires write permissions to the folder containing the database')
			king_phisher_server.shutdown()
			return os.EX_NOPERM
	sighup_handler = lambda: threading.Thread(target=king_phisher_server.shutdown).start()
	signal.signal(signal.SIGHUP, lambda signum, frame: sighup_handler())
	try:
		king_phisher_server.serve_forever(fork=False)
	except KeyboardInterrupt:
		pass
	king_phisher_server.shutdown()
	return os.EX_OK

def main():
	parser = argparse.ArgumentParser(description='King Phisher Server', conflict_handler='resolve')
	utilities.argp_add_args(parser)
	parser.add_argument('-f', '--foreground', dest='foreground', action='store_true', default=False, help='run in the foreground (do not fork)')
	parser.add_argument('--verify-config', dest='verify_config', action='store_true', default=False, help='verify the configuration and exit')
	parser.add_argument('--update-geoip-db', dest='update_geoip_db', action='store_true', default=False, help='update the geoip database and exit')

	parser.add_argument('config_file', action='store', type=argparse.FileType('r'), help='configuration file to use')
	arguments = parser.parse_args()

	console_log_handler = utilities.configure_stream_logger(arguments.loglvl, arguments.logger)
	config_file = arguments.config_file
	del parser

	missing_requirements = check_requirements(__requirements__)
	if missing_requirements:
		color.print_error('the following package requirements are missing or incompatible:')
		for missing_req in missing_requirements:
			color.print_error('  - ' + missing_req)
		color.print_error('please install the missing requirements with pip')
		return os.EX_SOFTWARE

	if os.getuid():
		color.print_error('the server must be started as root, configure the')
		color.print_error('\'server.setuid_username\' option in the config file to drop privileges')
		return os.EX_NOPERM

	try:
		config = Configuration(config_file.name)
	except Exception as error:
		color.print_error('an error occurred while parsing the server configuration file')
		error_name = "{0}.{1}".format(error.__module__, error.__class__.__name__)
		if error_name != 'yaml.parser.ParserError':
			raise
		for line in str(error).split('\n'):
			color.print_error(line.rstrip())
		return os.EX_CONFIG

	# configure environment variables
	find.data_path_init('server')
	if config.has_option('server.data_path'):
		find.data_path_append(config.get('server.data_path'))

	# check the configuration for missing and incompatible options
	verify_config = find.find_data_file('server_config_verification.yml')
	if not verify_config:
		color.print_error('could not load server config verification data')
		return os.EX_NOINPUT
	missing_options = config.get_missing(verify_config)
	if missing_options:
		if 'missing' in missing_options:
			color.print_error('the following required options are missing from the server configuration:')
			for option in missing_options['missing']:
				color.print_error('  - ' + option)
		if 'incompatible' in missing_options:
			color.print_error('the following options are of an incompatible data type in the server configuration:')
			for option in missing_options['incompatible']:
				color.print_error("  - {0} (type: {1})".format(option[0], option[1]))
		return os.EX_CONFIG
	if arguments.verify_config:
		color.print_good('configuration verification passed')
		color.print_good('all required settings are present')
		return os.EX_OK
	if arguments.update_geoip_db:
		color.print_status('downloading a new geoip database')
		size = geoip.download_geolite2_city_db(config.get('server.geoip.database'))
		color.print_good("download complete, file size: {0}".format(strutils.bytes2human(size)))
		return os.EX_OK

	# setup logging based on the configuration
	if config.has_section('logging'):
		log_level = min(getattr(logging, arguments.loglvl), getattr(logging, config.get('logging.level').upper()))
		if config.has_option('logging.file') and config.get('logging.file'):
			file_handler = logging.FileHandler(config.get('logging.file'))
			file_handler.setFormatter(logging.Formatter("%(asctime)s %(name)-50s %(levelname)-8s %(message)s"))
			logging.getLogger('').addHandler(file_handler)
			file_handler.setLevel(log_level)
		if config.has_option('logging.console') and config.get('logging.console'):
			console_log_handler.setLevel(log_level)
	logger.debug("king phisher version: {0} python version: {1}.{2}.{3}".format(version.version, sys.version_info[0], sys.version_info[1], sys.version_info[2]))
	if its.py_v2:
		logger.warning('python 2.7 support is deprecated, see https://github.com/securestate/king-phisher/wiki/Python-3 for details')

	# initialize the plugin manager
	try:
		plugin_manager = plugins.ServerPluginManager(config)
	except errors.KingPhisherError as error:
		if isinstance(error, errors.KingPhisherPluginError):
			color.print_error("plugin error: {0} ({1})".format(error.plugin_name, error.message))
		else:
			color.print_error(error.message)
		return os.EX_SOFTWARE

	status_code = build_and_run(arguments, config, plugin_manager)
	plugin_manager.shutdown()
	logging.shutdown()
	return status_code

if __name__ == '__main__':
	sys.exit(main())

**Comment by y4utj4** [comment]
that would be the king phisher server python script. your king phisher log will be under '/var/log/king-phisher.log'


________________________________

**Comment by Quinnshank** [comment]
there is no king-phisher.log in var/ but i clearly am running it.

**Comment by zeroSteiner** [comment]
The log file location can be specified in the server configuration. It's in the first few lines so you can check it there. It's generally `/var/log` which is different from `var/` so I suggest you check there.

**Comment by Quinnshank** [comment]
Sorry that's what I meant var/log im just learning how to use this program
and this OS so give me a break.

**Comment by zeroSteiner** [comment]
If you can't provide the logs, the last option is to start the server directly using the following command and then providing us the output:
`sudo python3 KingPhisherServer -f -L DEBUG server_config.yml`

That will need to be executed from within the folder where the project is installed. If I may ask how did you install King Phisher, given that ParrotOS is not a supported operating system? Did you run the install script because that probably would have failed?

**Comment by Quinnshank** [comment]
Okay it i entered it and this was the output # sudo python3 KingPhisherServer -f -L DEBUG server_config.yml
**python3: can't open file 'KingPhisherServer': [Errno 2] No such file or directory**

**Comment by Quinnshank** [comment]
No its standard in Parrot OS

**Comment by Quinnshank** [comment]
this was the output: Traceback (most recent call last):
  File "KingPhisherServer", line 45, in <module>
    from king_phisher import geoip
  File "/usr/share/king-phisher/king_phisher/geoip.py", line 45, in <module>
    import geoip2.database
ImportError: No module named 'geoip2'

**Comment by zeroSteiner** [comment]
You have missing dependencies. These should have been installed by the `install.sh` script for you. You'll want to try and install them yourself by running `python3 -m pip install -r requirements.txt`. It's very possible that one or more may fail due to missing operating system dependencies which also would have been installed by the `install.sh` script.

You'll need to install any of these missing dependencies manually, I'm not sure what flavor of Linux ParrotOS is based on but perhaps you could update the install script to handle it for you.

**Comment by zeroSteiner** [comment]
I was just talking to @wolfthefallen and it's possible that ParrotOS is using an older version of King Phisher that users Python 2.7. Try running that same command but with python instead of python3 like this:
`sudo python KingPhisherServer -f -L DEBUG server_config.yml`

**Comment by Quinnshank** [comment]
Now its it gave me this output: python: can't open file "KingPhisherServer': [Errno 2] No such file or directory"

**Comment by Quinnshank** [comment]
Its still in my file system but its not recognizing it.

**Comment by zeroSteiner** [comment]
You need to be in the same directory as when you ran the other command.

**Comment by Quinnshank** [comment]
Sorry its been a long night here is the output of that last string: 

#sudo python KingPhisherServer -f -L DEBUG server_config.yml
DEBUG    king phisher version: 1.4.0 python version: 2.7.13
WARNING  python 2.7 support is deprecated, see https://github.com/securestate/king-phisher/wiki/Python-3 for details
CRITICAL failed to bind server to address (socket error #98)
CRITICAL socket error #98 (Address already in use)
INFO     unloading 0 plugins

**Comment by zeroSteiner** [comment]
Ok, that's much more helpful. It indicates a few things.

1. The version you are using is about 6 months out of date.
1. The server can't start because the address is in use, you probably have something running on port 80 already. You need to stop that process and then re-try starting the King Phisher server. I highly recommend you verify that the port is free by ensuring nothing is listening on it by using `netstat` before starting the King Phisher server. You can find all of the ports it's trying to listen on under the `addresses` section in the server config file, by default it's just 80.

**Comment by wolfthefallen** [comment]
you will need to stop the service that is already utilizing port 80 prior to starting the King Phisher Server.

**Comment by Quinnshank** [comment]
so i shut down what was running on port 80 and tried to start the server and gave me this output: sudo python3 KingPhisherServer -f -L DEBUG server_config.yml
Traceback (most recent call last):
  File "KingPhisherServer", line 45, in <module>
    from king_phisher import geoip
  File "/usr/share/king-phisher/king_phisher/geoip.py", line 45, in <module>
    import geoip2.database
ImportError: No module named 'geoip2'

**Comment by zeroSteiner** [comment]
You ran it with Python 3, you need to run it with Python 2.7. Python 3 is for newer versions.

`sudo python KingPhisherServer -f -L DEBUG server_config.yml`

**Comment by Quinnshank** [comment]
Hey it seems to be working i got things worked out thanks so much for your guys help!
