### ISSUE TITLE
Man-In-The-Middle Session Cookies Feature Request

### ISSUE THREAD

**Issue by rlfree** [securestate/king-phisher#209]
## Issue Description
This is not an issue, but a feature request that could enhance the capability of King Phisher, by allowing attackers to bypass multi-factor authentication.

There is a new project that enables attackers to capture session cookies of users via Nginx HTTP server, which utilizes proxy_pass and sub_filter to proxy and modify HTTP content, while intercepting traffic between client and server. [Here ](https://github.com/kgretzky/evilginx)is the link to the other project so that you can review the technical information of the project.

Would there be a possibility of something like this to be implemented into King Phisher in a future release?

**Comment by zeroSteiner** [comment]
We've considered this in the past pretty extensively. The issue has always been how to store and maintain the session token. This would be a pretty complicated to natively integrate the functionality into King Phisher. It would probably be easier to see if the two projects could somehow integrate with each other. Unfortunately trying to work with other open source projects has proven to be an unreliable venture.

**Comment by rlfree** [comment]
I'll go ahead and close this issue out if that's the case. I'll explore trying to integrate use for this other project with KP when I have some free time and let you know if I make any progress. Thanks!
