### ISSUE TITLE
File attachment unable to be cleared after select

### ISSUE THREAD

**Issue by nullpainter** [securestate/king-phisher#210]
## Issue Description
After selecting a file attachment, I am unable to remove the attachment.

This is a particular issue because of #211 - there appears to be no way I can ever remove this sample file attachment from any campaign.

## Reproduction Steps
1. Start King Phisher
2. Open a campaign
3. Select a file attachment
4. No ability to clear the file attachment field

## Environment Details

Host OS: Windows 7
King Phisher Version: 1.7.1

## Error Details / Stack Trace
No error; issue is with UI only.

**Comment by zeroSteiner** [comment]
Select the field and press the backspace key on the keyboard.

**Comment by nullpainter** [comment]
Thanks. I would suggest that this is a non-obvious and non-standard UI control (on Windows, at least).

**Comment by zeroSteiner** [comment]
Thanks for the suggestion.
