### ISSUE TITLE
Configuration not unique to a campaign

### ISSUE THREAD

**Issue by nullpainter** [securestate/king-phisher#211]
## Issue Description
When I create a new campaign, the configuration fields (email subject, message HTML file etc.) are retrieved from the previous campaign.

It appears that the fields on the Configuration tab aren't campaign-specific - which is odd if King Phisher is able to run multiple campaigns simultaneously, thus potentially needing different email subjects and content.

## Reproduction Steps
1. Start King Phisher
2. Configuration details pre-populated
3. Select a campaign
4. Configuration details are unchanged
5. Select another campaign
6. Configuration details are unchanged

## Environment Details

Host OS: Windows 7
King Phisher Version: 1.7.1

**Comment by zeroSteiner** [comment]
This is the intended behavior and not a bug. The message information is independently configured from the campaign and this won't be changed. You can export the message configuration using the UI if you want to save the settings that you used with a particular campaign.

**Comment by nullpainter** [comment]
Can this be considered a feature request then? Otherwise, the usefulness of maintaining multiple campaigns is severely diminished if the vast majority of campaign setup state is shared.

**Comment by zeroSteiner** [comment]
No we won't be changing this. The idea is that you send messages once as part of a campaign and then move on. I fail to see the value in storing all of the information for the message configuration. It would only make sense if you had to prepare one campaign and before sending the messages switch to prepare and send messages for another before transitioning back to the first one. This would require massive and no trivial changes to store the information serve side as opposed to client side with the message exporting. If you're concerned about tracking the details of each campaign I suggest exporting the information before sending messages. There are plugins to facilitate automatic exporting as well.
