### ISSUE TITLE
ParrotOS Not supported

### ISSUE THREAD

**Issue by bflew** [securestate/king-phisher#217]
## Issue Description
Does not support ParrotOS install needs to be updated (debian build)

## Reproduction Steps
1. Try to install King Phisher on Parrot OS

## Environment Details

Host OS: Newest ParrotOS Build.
King Phisher Version: current

## Error Details / Stack Trace
Failed to detect the version of Linux
This installer only supports the following Linux distributions:
  - BackBox
  - CentOS
  - Debian
  - Fedora
  - Kali
  - Ubuntu

If the current version of Linux is one of these flavors but it is
not recognized, please open a support ticket and include the version.

**Comment by bflew** [comment]
thanks for escalating wolfthefallen, I looked at making the change myself but fell short, do you think this will get done or have a eta on a quick fix?

**Comment by wolfthefallen** [comment]
I'll be taking a look into on Monday, as ParrotOS is not an official OS that we support, I cannot give it a defendant time line.

**Comment by wolfthefallen** [comment]
Although ParrotOS is not officially supported by King Phisher the OS maintainers have it available through `apt`. 
You can install King Phisher on ParrotOS by doing the following commands
```
sudo apt update
sudo apt install king-phisher
```
Once installed you can start the King Phisher server with `sudo systemctl start king-phisher` and you can start the client type in `/usr/share/king-phisher/KingPhisher`

If you have any issues with installing KingPhisher on ParrotOS please reach out to the maintainers of the ParrotOS.
