### ISSUE TITLE
pdf_generator plugin load failed

### ISSUE THREAD

**Issue by SCGoPackGo** [securestate/king-phisher#218]
Desired outcome: confirm that an attachment to a phishing email was opened, validating awareness training to not open unsolicited attachments without confirmation.  Only plugin that appeared to offer that functionality was pdf_generator.  However:

## Issue Description
After extracting plugin pdf_generator into $HOME ./config/king-phisher/plugins directory and restarting king-phisher, the plugin manager displayed 
![image](https://cloud.githubusercontent.com/assets/29127866/26691528/72777d0c-46cb-11e7-8dcd-dd0074cc7052.png)
(Load Failed)

## Environment Details

Host OS: Kali Linux 2016.2-vm-amd64 VMPlayer 12.5.6
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
King Phisher Version: 1.7.0

## Error Details / Stack Trace

Plugin information
ImportError("No module named 'reportlab'",)

Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/plugins.py", line 369, in load_all
    self.load(name)
  File "/opt/king-phisher/king_phisher/plugins.py", line 336, in load
    raise error
  File "/opt/king-phisher/king_phisher/plugins.py", line 333, in load
    module = self.plugin_source.load_plugin(name)
  File "/usr/local/lib/python3.5/dist-packages/pluginbase.py", line 273, in load_plugin
    globals(), {}, ['__name__'])
  File "/usr/local/lib/python3.5/dist-packages/pluginbase.py", line 410, in plugin_import
    fromlist, level)
ImportError: No module named 'reportlab'

If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
You need to install the `reportlab` module. You can do that with PIP. The plugin however should not through an exception when it is absent so I'll get that addressed as well. Either way though, you'll need to install the missing dependency.

**Comment by SCGoPackGo** [comment]
thanks Spencer.  Can you comment on my desired outcome of using the
attachment as the bait and obtaining metrics on how many actually open the
attachment?

**Comment by zeroSteiner** [comment]
That's what I was saying about the phishery plugin. It can be used to tell if users open the word document, without needing to do something like enable macros. Unfortunately there is no fool proof method to see if users open an attachment. The phishery plugin for example requires that the document be opened in MS word and not another application like open office, or the online version.

**Comment by SCGoPackGo** [comment]
Ah sorry, did'nt see past the gmail preview window.  Looks like a bit of
extra config to run phishery wrt SSL cert.  Not sure we want to tackle that
unless SecureState provisions the server with the cert since you're hosting
it for us?

**Comment by zeroSteiner** [comment]
If you're hosting it with us just drop your PM an email with your request and they'll put you in touch directly with me and the rest of the team. We can then handle setting it up for you and discuss the details outside the prying eyes of GitHub.

**Comment by SCGoPackGo** [comment]
Ok, we'll look at that for a future enhancement.  Thanks.
John

**Comment by zeroSteiner** [comment]
I'm going to close this issue out as it doesn't look like there is anything outstanding that needs to be addressed.
