### ISSUE TITLE
Windows client 0.2.0 on Windows 7 64bit won't connect

### ISSUE THREAD

**Issue by pahtzo** [securestate/king-phisher#22]
Running Windows 7 64 bit, installed 0.2.0 client.  When connecting I get Failed to connect to SSH service an unknown error occurred.  I can SSH to the machine using putty with no issues.  Wireshark capture shows no network traffic during king_phisher client login to the machine.

**Comment by zeroSteiner** [comment]
Does the SSH server support TCP port forwarding? Also if it is running SSH on a non-default port is that being specified in the Server input field in the login dialog?

**Comment by pahtzo** [comment]
thanks for the quick reply Spencer, I've got a kali linux install
running, ssh enabled on 22, X11Forwarding yes.  client server input
field: 172.16.0.118:22

I think it may be a dependency or something as I can connect using my
work laptop running Win7 64 bit.

Any debug logging I can enable to help me trace it out?

Great application btw!

**Comment by zeroSteiner** [comment]
Thanks!

Unfortunately the Windows builds do not have any easily accessible logs. I'll have to take a look at the error conditions tomorrow. Usually it should be more descriptive on a connection error.

**Comment by zeroSteiner** [comment]
I just double checked the 0.2.0 Windows MSI build on my 7 SP1 x64 system and it was connecting just fine for me so there shouldn't be any dependency issues. Are you able to connect to the server with the King Phisher client from the Kali Linux install? The Linux client can be started from the command line with the ```-L DEBUG``` flag to produce verbose logging information.

**Comment by pahtzo** [comment]
Yes, the linux client on the Kali install connects.  I also connected via a different windows box and that worked.  If I figure out what's up with my laptop I'll post back details.  Thanks for looking into it.

**Comment by zeroSteiner** [comment]
I'm going to close this now. If you have anything to add to it I can reopen it later. Thanks for your patience!
