### ISSUE TITLE
WARNING  skipping spf policy check because the smtp server address could not be reliably detected

### ISSUE THREAD

**Issue by rishabhupreti** [securestate/king-phisher#220]
## Issue Description
I am not able to send mails using King Phisher as I am getting the error cannot connect to smtp server

## Reproduction Steps
1. Start King Phisher
2.I put the web server url which it connects to but when i click on check spf is says skipping spf policy beacause smtp server address could not be reliably detected

## Environment Details

Host OS: Kali Rolling 
King Phisher Version: latest

## Error Details / Stack Trace
WARNING  it is not necessary to run the king phisher client as root
WARNING  skipping spf policy check because the smtp server address could not be reliably detected
WARNING  received a socket.error while connecting to the SMTP server

```

**Comment by rishabhupreti** [comment]
WARNING  skipping spf policy check because the smtp server address could not be reliably detected
WARNING  received an SMTPException while connecting to the SMTP server
Traceback (most recent call last):
  File "/usr/share/king-phisher/king_phisher/client/mailer.py", line 390, in server_smtp_connect
    self.smtp_connection = SmtpClass(*self.smtp_server, timeout=15)
  File "/usr/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.5/smtplib.py", line 337, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.5/smtplib.py", line 393, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
WARNING  skipping spf policy check because the smtp server address could not be reliably detected
WARNING  received an SMTPException while connecting to the SMTP server
Traceback (most recent call last):
  File "/usr/share/king-phisher/king_phisher/client/mailer.py", line 390, in server_smtp_connect
    self.smtp_connection = SmtpClass(*self.smtp_server, timeout=15)
  File "/usr/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.5/smtplib.py", line 337, in connect
    (code, msg) = self.getreply()
  File "/usr/lib/python3.5/smtplib.py", line 393, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

This is after i went into preferences and changed my smtp server to smtp.gmail.com:465 , also in web server url I wrote mail.google.com

**Comment by zeroSteiner** [comment]
When connecting to `smtp.gmail.com;465` do you have SSL enabled? Also your server URL of `mail.google.com` is wrong. This needs to be the publicly accessible URL to your King Phisher server, otherwise you won't be collecting any stats.

**Comment by rishabhupreti** [comment]
I will let you know the settings of SSL tomorrow when I go back to office.Can you tell me how to use(the settings) a public server like Gmail?

I have few more doubts. Does KingPhisher help us spoof email address also?
As I was able to send e-mail through King-phisher using the mail server of my organization but if I change the Sender Address(other than the mail id whose credentials I am providing)  then I am not able to send the mail,it shows some error.
To make it more clear, I am providing  the credentials for rishabhupreti@example.com but to do phishing I want to spoof my address as ceoID@example.com to make phishing really effective otherwise employees would know that I have mailed them.

Secondly, how to set up a Mail Server in Kali Linux as default preference for SMTP Server is localhost:25.How to set up that  smtp server on our machine?

I want to send phishing e-mail with spoofed e-mail address for penetration testing purpose .Can you tell me how can use King-Phisher to achieve this goal.I don't a e-mail server.

**Comment by zeroSteiner** [comment]
Settings for public servers are in the wiki here: https://github.com/securestate/king-phisher/wiki/Public-SMTP-Servers.

King Phisher allows you to set the source email address to what ever you want. The configuration and SMTP server are going to control whether or not you are successful in spoofing. With things like the SPF check, it tries to warn when it can foresee a problem but there's a wide variety in factors that will prevent a message from being delivered whether or not it was "spoofed".

We don't help setup SMTP servers, we recommend postfix but you'll need to check their documentation for steps on how to install and configure it. Once that's done you can configure the King Phisher client to use it as your SMTP server.

**Comment by rishabhupreti** [comment]
You say that I can write any source email address but if I was changing the source email address other than the email address whose credential I provided , I was getting an error and email was not sent.

For example,  I used the SMTP server of my organization - rishabhu@myorg.com When I am writing rishabhu@myorg.com in both the source email addresses (MIME and other).I am able to send the e-mail but if I change the source email address to any other address , the email is not being sent and I am getting an error.

**Comment by zeroSteiner** [comment]
Yeah, that's because an SMTP server isn't accepting it. For example you'll run into that if you try and use Google's SMTP server, it'll only let you send as the user you're authenticated as.

That's not King Phisher that's preventing the message from being sent, it doesn't care what the fields are or impose any kind of restriction on them.

**Comment by rishabhupreti** [comment]
So my organization's mail server is preventing me to send the spoofed mail?
If so how can I solve this problem?

**Comment by zeroSteiner** [comment]
You can contact the server's owner and ask for an exception to be made for you or you can get creative and read up on how to phish. There's plenty of resources in the form of blogs that are available on the internet. These will talk about different settings and configuration options you can tweak. Ultimately King Phisher gives you alot of knobs and levers for you to adjust but it's up to you use them to effectively accomplish your task. We can't provide one configuration to rule them all because everything is highly dependent on factors that are outside of our (the King Phisher project's) control.

**Comment by rishabhupreti** [comment]
I got this issue resolved .but I have another problem.I want to run Apache server as well as King Phisher at the same time, how can I change the port of King Phisher from other than 80

**Comment by zeroSteiner** [comment]
You can change that in the server config file. After doing so restart the service.
