### ISSUE TITLE
Can l use any url for the web server url in king phisher? l am very new and confused.

### ISSUE THREAD

**Issue by Selormi** [securestate/king-phisher#222]
## Issue Description
I get a stack trace when I...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by wolfthefallen** [comment]
Read through the [wiki ](https://github.com/securestate/king-phisher/wiki) It will provide you the details you are looking for. I highly recommend watching the how-to videos.

The url should be to the landing page you are hosting with King Phisher so the clicks to the links and additional data can be tracked. but you can use any url, but if it is not a url to the a page that is not being hosted by your King Phisher server no data will be collected and tracked.

**Comment by Selormi** [comment]
l really much appreciate your quick response. I read about the landing page. And being very new to this, lm still confused. I have followed steps and installed the server and the client. l just can not figure out what the server url could be. l put my kali linux's ip there and when l searched for it, its not found. that's where lm lost. And also, l cannot connect to the smtp server. though l tried using gmail's.
Can you please help?

**Comment by zeroSteiner** [comment]
Unfortunately no, we simply can't provide help desk support with the resources we have. You need to ask specific questions after having read our documentation. In addition to the wiki, you can try watching the how to videos as well. There's a lot of information in there that will help you get started. Good luck!

**Comment by Selormi** [comment]
Thank you so much.

**Comment by Selormi** [comment]
Hi Engineers, l have gone through the documentation. I still fail to
connect using google's smtp server since im struggling to create mine. I do
understand that google might filter the packets and drop them should they
suspect anything. However, i am at the moment concerned of connectivity.
Can l please be assisted in reaching the smtp server? Because ssh is ok.
Thanks in advance.

**Comment by rami418** [comment]
Here is the documentation for the public smtp server 
https://github.com/securestate/king-phisher/wiki/Public-SMTP-Servers
It worked for me... until my gmail address got banned because not respecting google's reglementation 😈
