### ISSUE TITLE
No information back after sending mail

### ISSUE THREAD

**Issue by rami418** [securestate/king-phisher#223]
Hi again ;)

## Issue Description
When launching campaign, mail successfully sended and received, however only mail sending statistics appear into "View Campaign". Nothing into "opened", "visits" or "unique visits" even if I do click, visit and enter credential.

## Reproduction Steps
1. Start King Phisher

- Sending single target phishing, 
- using @outlook address to send
- using mail template : /root/king-phisher-templates/Email_Templates/Credentials/Ticket_Notice/email.html with href="{{ url.webserver }}" for the URL of landing page
- using the simple landing page "login"

2. Send mail
3. Have increased number of mail sent, but no information about opened, clicked, credential.

## Environment Details

Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-2kali1 (2017-06-22) x86_64 GNU/Linux
King Phisher Version: 1.8.0

## Error Details / Stack Trace
None

Any idea ? Thank you !

**Comment by wolfthefallen** [comment]
The email must contain a {{ tracking_dot_image_tag }} to see if the email was opened. But this also requires the recipient of the email to view images. 

Have you test the link sent out in the email.. I also recommend sending out a test phish to your self to verify everything is working correctly prior to sending out to your desired targets.

if you are using `<a href="{{ url.webserver }}">what ever you want your link to read as</a>` and that page is being hosted by your King Phisher server you should get results when ever some visits the landing page through your link.

**Comment by rami418** [comment]
This email is containing {{ tracking_dot_image_tag }}  (it was in the template, do i need to change something there ?) I did clicked on view image. 
Yeah, i'm sending it to my own email address (not the same i send from by the way) and clicked on the link i received. I am correctly redirected to the fake login page, when i submit credential, i'm redirected to /error then to google.com

I used the king-phisher-templates/Email_Templates/Credentials/Ticket_Notice/email.html mail template, do i need to change smthg on it where there is the <a href="{{ url.webserver }}"> ?

What do you mean about hosted by my King Phisher server ? My landing page is a simple apache2 server i launched on the same machine, where i copied the login and error files. So i did put on the Web Server URL field http://myIPaddress:443/login 
where my IPaddress is something like 172.16.*.*
after a "service apache2 start" my landing page is reachable even through the email link.

What am I doing wrong ?
Thanks a lot ;)

**Comment by wolfthefallen** [comment]
The King Phisher Server itself needs to host your landing page to collect the metrics.  There is no need for Apache or ngix to host a website so **turn them off**. 

Look at your King Phisher Server config file and verify where the webroot is configured for. With default installation of King Phisher you can find your King Phisher Server config file at `/opt/king-phisher/server_config.yml'. By default the web root is `/var/www` put your landing pages in to your web root. So if your King Phisher Server webroot is set to `/var/www` your login page should be located at `/var/www/login`. This will make your Web Server URL field `http://youripaddress/login`.

**Comment by rami418** [comment]
Ok, I'm understanding more how it works. I had some problems : 
- So i needed to change web root (instead of copying all the file) as on kali, web root is now /var/www/html. 
- I didn't start sshd service ( yeah I know ... but i though i would start automatically on startup and it was working with locahost )
- I put 127.0.0.1 into the server config file, instead of 0.0.0.0. This is much better with 0.0.0.0 now ^^

Thank you very much for your help !

I might open a new issue with an error message. I'm trying to find the cause before, and explain enough to let other be able to reproduce ;)

Thanks !
