### ISSUE TITLE
Error type: advancehttpserver.RPCError

### ISSUE THREAD

**Issue by rami418** [securestate/king-phisher#224]
## Issue Description
I have this error which randomly appears (client side)

## Reproduction Steps
1. Start King Phisher Client (OS doesn't matter,  error on both kali and windows 7)
2. Just use it. This error is incoming quickly after launching client, or sometimes after 10 mins, and sometimes it just doesn't appear.

## Environment Details

Host OS: 
- (Client) Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-2kali1 (2017-06-22) x86_64 GNU/Linux
- (Client) Windows 7 32bits
King Phisher Version: 1.8.0

## Error Details / Stack Trace

rror Type: advancedhttpserver.RPCError
Error Details: RPCError(message='Unauthorized', status=401, remote_exception=False)
Error UID: 50f822b9-f0c6-4bf7-aebd-37792d43acdf
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.8.0
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.5.3
Gtk Version: 3.22.12
Timezone: Europe/Paris

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-1 (alive=True daemon=True)

Stack Trace:
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/tabs/campaign.py", line 185, in signal_server_event_db
    row_data = self.format_node_data(get_node(row.id))
  File "/opt/king-phisher/king_phisher/client/tabs/campaign.py", line 178, in <lambda>
    get_node = lambda id: self.rpc.graphql(self.node_query, {'id': str(id)})['db']['node']
  File "/opt/king-phisher/king_phisher/client/client_rpc.py", line 186, in graphql
    response = self.call('graphql', query, query_vars=query_vars)
  File "/usr/local/lib/python3.5/dist-packages/advancedhttpserver.py", line 566, in call
    raise RPCError(resp.reason, resp.status)
advancedhttpserver.RPCError: the server responded with 401 'Unauthorized'

**Comment by wolfthefallen** [comment]
Thank you for the bug report.

I'll work on trying to get this bug to reproduce on my side.

**Comment by wolfthefallen** [comment]
I've been unable to recreate this issue. From the error above it appears that your session token is becoming invalid. Only way I know of that would create this issue is logging in from another client with the same username, or the King Phisher Client does not have a connection with the King Phisher server for a prolonged period of time and then attempts to do a request with an expired session token.

Can you provide any additional details of what actions are occurring and approximate time frames when it does happen 'randomly'?

**Comment by rami418** [comment]
hum, I might have two clients at the same time. I will try to reproduce it ensuring I only launch one client.
By randomly, I mean it can happen few seconds after login on client, or it can happen 5 min later, or 10 ... I will retry with only one client and let you know about it ;)

**Comment by rami418** [comment]
Ok so it seems I was a little bit stupid ^^ I didn't have it with only one client running, obviously ...
So I closed it and will reopen if I have it again !

Thank you
