### ISSUE TITLE
Crash on startup in 1.8.0

### ISSUE THREAD

**Issue by nullpainter** [securestate/king-phisher#226]
## Issue Description
After upgrading to 1.8.0 from 1.7.1, I get a crash on startup. Hopefully pertinent details have been transcribed from the error dialog.

Uninstalling King Phisher and reinstalling resolves the issue.

## Reproduction Steps
1. Start King Phisher

## Environment Details

Host OS: Windows 7
King Phisher Version: 1.8.0

## Error Details / Stack Trace
```
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
...
ImportError: Bad magic number in C:|Program Files (x86)\KingPhisher\collections\__init__.pyc
```

**Comment by zeroSteiner** [comment]
Can't say I've seen that before. Can you try to delete `C:\\Program Files (x86)\\KingPhisher\\collections\\__init__.pyc` then restart the application. If that doesn't work please try to uninstall and reinstall.

It sounds like that file got corrupted some how.

**Comment by nullpainter** [comment]
Since I had already reinstalled, I'm afraid I'm not able to test this. Feel free to close if you feel this may just be a random corruption.

**Comment by zeroSteiner** [comment]
Ok thanks for the quick reply. I'll close this out. After looking into it a bit more and finding this seemingly [related issue](https://bugs.python.org/issue20794) I'm thinking it may also have been because you updated from 1.7.1 to 1.8 where we changed the Python version as well.
