### ISSUE TITLE
backbox support 

### ISSUE THREAD

**Issue by Zaxscdvf** [securestate/king-phisher#23]
add support for backbox in the install script.

**Comment by zeroSteiner** [comment]
I like this idea.

**Comment by Zaxscdvf** [comment]
thanks when do you think you can add it in?

**Comment by zeroSteiner** [comment]
I can probably get support for the latest (BB 4.2) added within the next week.

**Comment by zeroSteiner** [comment]
Just added this in commit fb025ee. It's currently in the dev branch but will be merged over into the master branch later this week.

Until then, if you'd like you can use it by cloning the project, then following the [Beta Testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing) steps **before** running ```sudo tools/install.sh```. The repo will have to be cloned locally and switched to the beta testing branch before running the script until dev is merged into master.

**Comment by Zaxscdvf** [comment]
k thanks
