### ISSUE TITLE
Kali not recognized bi install.sh

### ISSUE THREAD

**Issue by rami418** [securestate/king-phisher#232]
## Issue Description
My up to date Kali is not recognized by install.sh
(I deleted the if in install.sh to force install on Kali :)
## Environment Details

Host OS: Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-2kali1 (2017-06-22) x86_64 GNU/Linux
King Phisher Version: 1.8.0

Thanks :)

**Comment by zeroSteiner** [comment]
Fixed in commit 61f516d7652fa0287063aaa9d73d0c850a991ecf. Issue was `/etc/debian_version` changing from `Kali Linux Rolling` to `kali-rolling`.
