### ISSUE TITLE
ssl error in kali linux rolling

### ISSUE THREAD

**Issue by kureeoffsec** [securestate/king-phisher#236]
## Issue Description
Error Type: ssl.SSLError
Error Details: SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:719)')
Error UID: 04931009-d5f8-4447-adb6-4a82bfd1f8ff
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.8.0
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.5.4
Gtk Version: 3.22.17

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-2 (alive=True daemon=True)
    Thread-7 (alive=True daemon=True)
    Thread-6 (alive=True daemon=True)
    Thread-1 (alive=True daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "/pentest/phishing/king-phisher/king_phisher/client/tabs/mail.py", line 353, in signal_button_clicked_sender_start
    connection_status = self.sender_thread.server_smtp_connect()
  File "/pentest/phishing/king-phisher/king_phisher/client/mailer.py", line 402, in server_smtp_connect
    self.smtp_connection.starttls()
  File "/usr/lib/python3.5/smtplib.py", line 767, in starttls
    server_hostname=self._host)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:719)

## Reproduction Steps
1)set up both server and client. 
2) start set up campaign
3) press the start button under the send tab

## Environment Details
client and server: Linux kali 4.11.0-kali1-amd64 #1 SMP Debian 4.11.6-1kali1 (2017-06-21) x86_64 GNU/Linux (completely updated kali rolling)

**Comment by kureeoffsec** [comment]
SSL scan of smtp server
Version: 1.11.10-static
OpenSSL 1.0.2-chacha (1.0.2g-dev)

Testing SSL server <SMTP SERVER> on port 2525 using SNI name <SMTP SERVER>

  TLS Fallback SCSV:
Server does not support TLS Fallback SCSV

  TLS renegotiation:
Session renegotiation not supported

  TLS Compression:
Compression disabled

  Heartbleed:
TLS 1.2 not vulnerable to heartbleed
TLS 1.1 not vulnerable to heartbleed
TLS 1.0 not vulnerable to heartbleed

  Supported Server Cipher(s):

**Comment by zeroSteiner** [comment]
I believe in discussing this on IRC that we determined that this was not a bug in King Phisher but rather an issue with the OpenSSL libraries that were being used. Is that correct? I'd like to get this closed out if there's no changes we need to make.

**Comment by kureeoffsec** [comment]
That is correct. It was an issue with the OpenSSL libraries installed on Kali. I was able to fix it by compiling them from scratch myself.

I also understand that this package can be problematic in that sometimes it works and sometimes not so much.
