### ISSUE TITLE
Kali not recognized install.sh

### ISSUE THREAD

**Issue by isabellah750** [securestate/king-phisher#237]
I am trying to install the kingphisher along with requirements but install.sh os not recognized. I am using kali rolling 2017.1. i have installed using repository...also tried on github version.  Plz help

**Comment by zeroSteiner** [comment]
Please actually fill out the issue template. It's there to help us gather the information necessary for us to address the issues.

**Comment by wolfthefallen** [comment]
pretty sure this issue was addressed in commit 61f516d which is currently in the dev branch. If the title of the issue is accurate

**Comment by isabellah750** [comment]
what should i do then??

**Comment by zeroSteiner** [comment]
Yeah, I guess this is a duplicate of #232.

**Comment by zeroSteiner** [comment]
Just merged dev into master so the changes are there now. @isabellah750, pull down the latest changes and re-try the install script.
