### ISSUE TITLE
Email send error

### ISSUE THREAD

**Issue by thedividedguy** [securestate/king-phisher#238]
## Issue Description
When I attempt to send an email I get an error

## Reproduction Steps
1. Start King Phisher
2. Put in variables for source, friendly name, template, etc

## Environment Details
KingPhisher Server running on Digital Ocean 16.04 LTS
Client Running on Kali 2 rolling

Error Type: ipaddress.AddressValueError
Error Details: AddressValueError(u"'127.0.0.1' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?",)
Error UID: 16761a1d-eda6-4df1-9756-69dd996b28a5
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.1.0
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 2.7.11
Gtk Version: 3.22.18
Timezone: US/Eastern

Thread Information:
 => MainThread (alive=True daemon=False)
    Thread-2 (alive=True daemon=True)
    Thread-1 (alive=True daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "/usr/share/king-phisher/king_phisher/client/tabs/mail.py", line 269, in signal_button_clicked_sender_start
    if not self._sender_precheck_spf():
  File "/usr/share/king-phisher/king_phisher/client/tabs/mail.py", line 206, in _sender_precheck_spf
    spf_test_ip = mailer.guess_smtp_server_address(self.config['smtp_server'], (self.config['ssh_server'] if self.config['smtp_ssh_enable'] else None))
  File "/usr/share/king-phisher/king_phisher/client/mailer.py", line 192, in guess_smtp_server_address
    ip = ipaddress.ip_address(info.pop())
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 163, in ip_address
    ' a unicode object?' % address)
AddressValueError: '127.0.0.1' does not appear to be an IPv4 or IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
I noticed you're using version 1.1.0. Can you please update to the latest version? You're exactly 10 versions and about a year and a half behind the latest. You can find steps on how to do this in the [Updating King Phisher](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher) wiki page.

After you've done that can you please try to reproduce the issue and update us on whether or not it is still present?

**Comment by zeroSteiner** [comment]
I'm going to close this issue out due to inactivity. If you're still experiencing it, please respond to the preceding message in this thread and we'll re-open it. Thanks.
