### ISSUE TITLE
Verify URL 404 even with RequireID set to false

### ISSUE THREAD

**Issue by rthalerLPS** [securestate/king-phisher#239]
## Issue Description
I had a template and campaign setup, but have noticed that I can no longer "Verify URL". I have tried to set the URL back to the local IP of the machine instead of the domain name and still am getting 404. Because of this I have tried to update King Phisher and make sure my server is update to date as possible. Tried to run in verbose logging and I am only getting the 404 requests. I have also verify no other process is using port 80.

## Reproduction Steps
1. Start King Phisher
2. Select Campaign
3. Insert Local IP of server running KingPhisher
4. Unable to Verify URL

## Environment Details
Host OS: Linux: debian 8.9
King Phisher Version: 1.9.0-beta3 Rev: 1649c342fb68

## Error Details / Stack Trace
Server Logs:

> DEBUG    king phisher version: 1.9.0-beta3 (rev: 1649c342fb68) python version: 3.4.2
> INFO     listening on 0.0.0.0:80
> INFO     serving files has been enabled
> INFO     initializing database connection with driver postgresql
> DEBUG    postgresql-setup was not found
> DEBUG    postgresql service is already running via systemctl
> DEBUG    current database schema version: 7 (latest)
> DEBUG    connected to postgresql database: king_phisher
> INFO     restored 0 valid sessions and skipped 0 expired sessions from the database
> DEBUG    use pam service 'sshd' for authentication
> DEBUG    forked an authenticating process with pid: 1661
> INFO     the job manager has been started
> INFO     adding new job with id: 2ae8a665-c6a8-48ef-ba74-a6b05ab86ada and callback function: ping_all
> DEBUG    web socket manager worker running in tid: 0x7f8ccde7f700
> WARNING  the geoip database is older than 90 days
> INFO     including 0 custom http headers
> INFO     server running in process: 1632 main tid: 0x7f8cd8ad1700
> INFO     dropped privileges to the nobody account
> DEBUG    executing job with id: 2ae8a665-c6a8-48ef-ba74-a6b05ab86ada and callback function: ping_all
> DEBUG    10.9.0.146 tid: 0x7f8ccd67e700 running http request handler
> INFO     10.9.0.146 "GET /?id=jtbySCb4voWfKNDO4dQ1SEcU HTTP/1.1" 404 -
> DEBUG    127.0.0.1 tid: 0x7f8ccd67e700 running http request handler
> INFO     127.0.0.1 "GET /_/ws/events/json HTTP/1.1" 401 -
> cDEBUG    executing job with id: 2ae8a665-c6a8-48ef-ba74-a6b05ab86ada and callback function: ping_all
> DEBUG    127.0.0.1 tid: 0x7f8ccd67e700 running http request handler
> INFO     127.0.0.1 "GET /_/ws/events/json HTTP/1.1" 401 -
> DEBUG    executing job with id: 2ae8a665-c6a8-48ef-ba74-a6b05ab86ada and callback function: ping_all
> DEBUG    127.0.0.1 tid: 0x7f8ccd67e700 running http request handler
> INFO     127.0.0.1 "GET /_/ws/events/json HTTP/1.1" 401 -
> DEBUG    executing job with id: 2ae8a665-c6a8-48ef-ba74-a6b05ab86ada and callback function: ping_all
> DEBUG    127.0.0.1 tid: 0x7f8ccd67e700 running http request handler
> INFO     127.0.0.1 "GET /_/ws/events/json HTTP/1.1" 401 -

Client Logs:

> DEBUG    king phisher version: 1.9.0-beta3 (rev: 1649c342fb68) python version: 3.4.2
> DEBUG    client running in process: 1502 main tid: 0x7f53fba99700
> DEBUG    using ui data from glade file: /opt/king-phisher/data/client/king_phisher/king-phisher-client.ui
> DEBUG    gi.repository GLib version: 2.42.0
> DEBUG    gi.repository GObject version: 3.14.0
> DEBUG    gi.repository Gtk version: 3.14.5
> DEBUG    gi.repository VTE version: 2.91
> DEBUG    matplotlib version: 2.0.2
> DEBUG    creating the user configuration directory
> INFO     loading the config from disk
> INFO     loading the config from: /root/.config/king-phisher/config.json
> INFO     loading 2 plugins
> DEBUG    plugin 'check_for_updates' has been loaded
> DEBUG    plugin 'data_collection' has been loaded
> DEBUG    client loaded in 0.02 seconds
> 
> (KingPhisher:1502): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
> DEBUG    loading style from css file: /opt/king-phisher/data/client/king_phisher/style/theme.v1.css
> DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_file_open
> DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_file_quit
> DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_tools_rpc_terminal
> DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_tools_sftp_client
> DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_tools_create_graph
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.button_target_file_select
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.calendar_calendar_invite_date
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_calendar_invite_all_day
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_calendar_request_rsvp
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.combobox_importance
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.combobox_sensitivity
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_webserver_url
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_calendar_invite_location
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_calendar_invite_summary
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_company_name
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_recipient_email_cc
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_recipient_email_to
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_source_email
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_source_email_smtp
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_source_email_alias
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_subject
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_reply_to_email
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_html_file
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_target_file
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_target_name
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_target_email_address
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_attachment_file
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.expander_calendar_invite_settings
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.expander_email_settings
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_message_type_calendar_invite
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_message_type_email
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_field_bcc
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_field_cc
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_field_to
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_type_file
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_type_single
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.spinbutton_calendar_invite_duration
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.spinbutton_calendar_invite_start_hour
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.spinbutton_calendar_invite_start_minute
> DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.viewport
> DEBUG    loading GTK builder object with id: MailSenderEditTab.toolbutton_save_as_html_file
> DEBUG    loading GTK builder object with id: MailSenderEditTab.toolbutton_save_html_file
> DEBUG    loading GTK builder object with id: MailSenderEditTab.view_html_file
> DEBUG    loading HTML completion data from: /opt/king-phisher/data/client/king_phisher/completion/html.json
> DEBUG    loading Jinja completion data from: /opt/king-phisher/data/client/king_phisher/completion/jinja.json
> DEBUG    loading GTK builder object with id: MailSenderSendTab.button_mail_sender_start
> DEBUG    loading GTK builder object with id: MailSenderSendTab.button_mail_sender_stop
> DEBUG    loading GTK builder object with id: MailSenderSendTab.textview_mail_sender_progress
> DEBUG    loading GTK builder object with id: MailSenderSendTab.togglebutton_mail_sender_pause
> DEBUG    loading GTK builder object with id: MailSenderSendTab.progressbar_mail_sender
> DEBUG    loading GTK builder object with id: MailSenderSendTab.scrolledwindow_mail_sender_progress
> INFO     matplotlib is installed, dashboard will be available
> DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.box_top_left
> DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.box_top_right
> DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.box_bottom
> DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.scrolledwindow_top_left
> DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.scrolledwindow_top_right
> DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.scrolledwindow_bottom
> DEBUG    dashboard refresh frequency set to 300 seconds
> DEBUG    loading GTK builder object with id: CampaignViewMessagesTab.button_refresh
> DEBUG    loading GTK builder object with id: CampaignViewMessagesTab.treeview_campaign
> DEBUG    loading GTK builder object with id: CampaignViewVisitsTab.button_refresh
> DEBUG    loading GTK builder object with id: CampaignViewVisitsTab.treeview_campaign
> DEBUG    loading GTK builder object with id: CampaignViewCredentialsTab.button_refresh
> DEBUG    loading GTK builder object with id: CampaignViewCredentialsTab.treeview_campaign
> DEBUG    loading GTK builder object with id: LoginDialog.button_connect
> DEBUG    loading GTK builder object with id: LoginDialog.entry_server
> DEBUG    loading GTK builder object with id: LoginDialog.entry_server_username
> DEBUG    loading GTK builder object with id: LoginDialog.entry_server_password
> DEBUG    loading GTK builder object with id: LoginDialog.entry_server_one_time_password
> DEBUG    loading GTK builder object with id: LoginDialog.label_main
> DEBUG    loading GTK builder object with id: LoginDialog.label_server_one_time_password
> DEBUG    loading GTK builder object with id: LoginDialog.revealer_server_one_time_password
> DEBUG    loading GTK builder object with id: LoginDialog.spinbutton_server_remote_port
> DEBUG    loading GTK builder object with id: LoginDialog.switch_server_use_ssl
> INFO     connecting to local king phisher instance
> DEBUG    using serializer: application/json
> DEBUG    using serializer: binary/message-pack
> DEBUG    calling RPC method: version
> INFO     successfully connected to the king phisher server (version: 1.9.0-beta3 (rev: 1649c342fb68) rpc api version: 5.5)
> DEBUG    calling RPC method: login
> DEBUG    successfully authenticated to the remote king phisher service
> INFO     connecting to the server event socket
> DEBUG    successfully connected to the server event socket
> DEBUG    calling RPC method: config/get
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.button_new_campaign
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.button_select
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.drawingarea_color_key
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.label_campaign_info
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.menubutton_filter
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.treeview_campaigns
> DEBUG    calling RPC method: graphql
> INFO     campaign set to Testing 3 (id: 23)
> INFO     the RPC cache has been purged
> DEBUG    the rpc cache has been cleared
> DEBUG    calling RPC method: db/table/get
> DEBUG    calling RPC method: db/table/get
> DEBUG    calling RPC method: db/table/get
> INFO     campaign set to Testing 3 (id: 23)
> INFO     the RPC cache has been purged
> DEBUG    the rpc cache has been cleared
> DEBUG    calling RPC method: db/table/get
> DEBUG    calling RPC method: db/table/get
> DEBUG    calling RPC method: graphql
> DEBUG    calling RPC method: graphql
> DEBUG    calling RPC method: graphql
> DEBUG    calling RPC method: db/table/get
> DEBUG    calling RPC method: db/table/view
> DEBUG    calling RPC method: db/table/view
> DEBUG    calling RPC method: db/table/count
> DEBUG    calling RPC method: db/table/count
> DEBUG    calling RPC method: events/subscribe
> DEBUG    calling RPC method: events/subscribe
> DEBUG    calling RPC method: events/subscribe
> DEBUG    calling RPC method: graphql
> DEBUG    calling RPC method: graphql
> DEBUG    calling RPC method: graphql
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.button_new_campaign
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.button_select
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.drawingarea_color_key
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.label_campaign_info
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.menubutton_filter
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.treeview_campaigns
> DEBUG    calling RPC method: graphql
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.button_new_campaign
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.button_select
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.drawingarea_color_key
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.label_campaign_info
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.menubutton_filter
> DEBUG    loading GTK builder object with id: CampaignSelectionDialog.treeview_campaigns
> DEBUG    calling RPC method: graphql
> INFO     campaign set to Technology (id: 17)
> INFO     the RPC cache has been purged
> DEBUG    the rpc cache has been cleared
> DEBUG    calling RPC method: db/table/get
> DEBUG    calling RPC method: db/table/get
> DEBUG    calling RPC method: db/table/get
> DEBUG    calling RPC method: graphql
> DEBUG    calling RPC method: graphql
> DEBUG    calling RPC method: graphql
> DEBUG    calling RPC method: db/table/view
> DEBUG    calling RPC method: db/table/view
> DEBUG    calling RPC method: db/table/count
> DEBUG    calling RPC method: db/table/count
> WARNING  verify url HTTP error: 404 Not Found

**Comment by rthalerLPS** [comment]
## Another Error Popup
Error type: advancedhttpserver.RPCError

Error Details:
Error Type: advancedhttpserver.RPCError
Error Details: RPCError(message='Unauthorized', status=401, remote_exception=False)
Error UID: 1760a05a-664c-4790-a054-580ddf2acd09
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.9.0-beta3 (rev: 1649c342fb68)
Platform Version: Linux: debian 8.9 
Python Version: 3.4.2
Gtk Version: 3.14.5
Timezone: America/Chicago

Thread Information:
 => MainThread (alive=True daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/client_rpc.py", line 363, in ping
    return self.call('ping')
  File "/usr/local/lib/python3.4/dist-packages/advancedhttpserver.py", line 601, in call
    raise RPCError(resp.reason, resp.status)
advancedhttpserver.RPCError: the server responded with 401 'Unauthorized'

**Comment by zeroSteiner** [comment]
What is the setting of your `vhost_directories` setting in the server config? Also note that when you restart the server, the client needs to refresh a token that's used for the "Verify URL" functionality. This means you need to either restart the client or open the Configuration windows under the Edit menu after you've restarted the server.

**Comment by rthalerLPS** [comment]
I have tried having my vhost_directories set to true and to false. Under both settings I was getting the same 404 Error for Verify URL

**Comment by zeroSteiner** [comment]
I only see one 404 response in the server logs to an empty resource. You can try to specify an existing page in the webroot and ensure that the permissions allow it to be read by the King Phisher server which by default is going to drop privileges to the nobody user.

**Comment by rthalerLPS** [comment]
Currently in my webroot I created a folder called secured and then have my files located within that file. They are not at the root of www, but in my Verify URL I have been referencing this directly with http://IPofServer/secure/login

Is it possible this is what is causing the verify issues?

**Comment by zeroSteiner** [comment]
Yes, that URL should be the URL in the `Target URL` field of the client when you select Verify URL. This does not look like it was the case for the one and only 404 response that was in the server logs.

When you click this button you should get logging message showing up in the server logs. Please post to this issue while the server is running in DEBUG mode. We'll need a few lines before and a few lines after, there should be ~20 lines total.

**Comment by rthalerLPS** [comment]
Hey! Great news. After bouncing back and forth here with you I was able to get it up and running again. I believe the issue may have been my vhost settings and then after correctly restarting the service I was able to Verify. Thank you for the fast reply and help.

**Comment by zeroSteiner** [comment]
Glad to hear it! I'm going to close this out now.
