### ISSUE TITLE
Users IPs are not registering

### ISSUE THREAD

**Issue by mozg31337** [securestate/king-phisher#24]
I am running a test campaing and have noticed that the user/client IPs are all shown as a single IP address of the proxy server. The proxy server passes on the following headers:

X-Real-IP
X-Forwarded-For
X-Forwarded-Proto

However, KingPhisher is not picking those headers and uses the proxy's ip address.

Is there a way to change the behaviour and let the KingPhisher work well behind proxies?

**Comment by zeroSteiner** [comment]
There is not a way to do that right now. It is however a feature I would be interested in adding. In your situation are the "real" IP addresses public addresses or private (RFC-1918 reserved) addresses? 

Recording private addresses would ideally be done in addition to the public address to allow the geo location feature to function but that would require a database schema update to log the additional info. If both addresses are public, then I suppose King Phisher should opt to use the one the client is claiming is it's real one. This would then make it trivial to forge any value though.

**Comment by mozg31337** [comment]
I have been testing with the public addresses. I've got a proxy server between the KingPhisher server and the internet, so then the user accesses a phishing site, the user's IP address is shown as the proxy's private IP address.

It would be a nice to see feature as a lot of organisations use proxy or would like to proxy the requests for one reason or another.

Cheers

**Comment by zeroSteiner** [comment]
I see, so you control the proxy server and all users have to connect to the King Phisher server through the proxy. It's not a proxy server that the users / clients are opting into using or are even aware of.

Is that correct?

**Comment by mozg31337** [comment]
That's correct. All users are connecting to the nginx proxy and the proxy forwards the request to the King Phisher server.

I have no control over how clients are connecting as each client's case is different. However, in many cases, the clients are also behind a proxy server of some sort. However, I do not see many issues with working with clients behind the proxy. The problem is when the King Phisher server is behind a proxy.

Thanks

**Comment by zeroSteiner** [comment]
Ok that makes sense and that's a good idea. I'll add that in as a server option. Thanks for the clarification and feedback!

**Comment by mozg31337** [comment]
Not a problem. Perhaps adding an option how to get the IP addresses of the clients, including support for the HTTP headers where used?

**Comment by zeroSteiner** [comment]
Yeah, I'm thinking a server option for a header that if defined in the configuration and present in the request will be used as the IP address instead of the address of the socket peer like it is now.

**Comment by mozg31337** [comment]
That sounds like a good way forward ). I would be happy to test and report any problems.

Thanks

**Comment by zeroSteiner** [comment]
Alright this feature is now in the development branch as of commit 93d4173. The change introduces the ```client_ip_cookie``` setting in the server's configuration file which can be set to ```X-Real-IP``` or any appropriate value that a single IPv4 or IPv6 address can be pulled from. If a port is at the end of the address that's fine, but names will not be resolved.

You can pull down the development branch by following the [beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing) instructions and restarting the server. Alternatively you can wait for dev to be merged into master.

I plan on merging dev into master at the end of this week once I'm done testing a few other features. I'm going to close this ticket since the feature has been implemented. If you have additional feed back on this feature feel free to update this ticket.

**Comment by mozg31337** [comment]
Hi Spencer, 

I guess the changes are now merged with Master and I can give it a go. I will let you know the progress. 

Thanks 

Andrei 

----- Original Message -----

**Comment by mozg31337** [comment]
Hi, 

I can confirm that this is working perfectly well and the user IPs are registered using the specified header settings. 

Thanks for implementing this feature so quickly!!! ) 

Andrei

**Comment by zeroSteiner** [comment]
Excellent, I'm glad I was able address the issue. Thanks for the feature suggestion.
