### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by wermaxta** [securestate/king-phisher#240]
hi i have problem with king-phisher. My OS is Kali Linux 
Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux
My PostgreSQL version is
``` 
psql --version
psql (PostgreSQL) 10.0
```
When i type
`systemctl start king-phisher`
```
Job for king-phisher.service failed because a timeout was exceeded.
See "systemctl  status king-phisher.service" and "journalctl  -xe" for details.
When i check status 
systemctl  status king-phisher.service
● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; disabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Tue 2017-10-17 15:20:31 EEST; 2min 43s ago
  Process: 6654 ExecStart=/usr/bin/python3 /usr/share/king-phisher/KingPhisherServer /etc/king-phisher/server

Oct 17 15:19:10 kali python3[6654]:     return dialect.connect(*cargs, **cparams)
Oct 17 15:19:10 kali python3[6654]:   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.
Oct 17 15:19:10 kali python3[6654]:     return self.dbapi.connect(*cargs, **cparams)
Oct 17 15:19:10 kali python3[6654]:   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", lin
Oct 17 15:19:10 kali python3[6654]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync
Oct 17 15:19:10 kali python3[6654]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  pass
Oct 17 15:19:10 kali python3[6654]: FATAL:  password authentication failed for user "king_phisher"
Oct 17 15:20:31 kali systemd[1]: king-phisher.service: Start operation timed out. Terminating.
Oct 17 15:20:31 kali systemd[1]: king-phisher.service: Failed with result 'timeout'.
Oct 17 15:20:31 kali systemd[1]: Failed to start King Phisher Server.
```
and

`journalctl  -xe`
```
Oct 17 15:19:10 kali python3[6654]:   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", lin
Oct 17 15:19:10 kali python3[6654]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync
Oct 17 15:19:10 kali python3[6654]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  pass
Oct 17 15:19:10 kali python3[6654]: FATAL:  password authentication failed for user "king_phisher"
Oct 17 15:20:31 kali systemd[1]: king-phisher.service: Start operation timed out. Terminating.
Oct 17 15:20:31 kali systemd[1]: king-phisher.service: Failed with result 'timeout'.
Oct 17 15:20:31 kali systemd[1]: Failed to start King Phisher Server.
-- Subject: Unit king-phisher.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit king-phisher.service has failed.
-- 
-- The result is RESULT.
Oct 17 15:24:08 kali systemd[1]: Starting Cleanup of Temporary Directories...
-- Subject: Unit systemd-tmpfiles-clean.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit systemd-tmpfiles-clean.service has begun starting up.
Oct 17 15:24:08 kali systemd[1]: Started Cleanup of Temporary Directories.
-- Subject: Unit systemd-tmpfiles-clean.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit systemd-tmpfiles-clean.service has finished starting up.
-- 
-- The start-up result is RESULT.
Oct 17 15:25:01 kali CRON[6761]: pam_unix(cron:session): session opened for user root by (uid=0)
Oct 17 15:25:01 kali CRON[6762]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Oct 17 15:25:01 kali CRON[6761]: pam_unix(cron:session): session closed for user root
```

Thank you 
## Issue Description
I get a stack trace when I...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by Gilks** [comment]
Thank you for opening an issue! To get a better understanding of what's going on, can you please complete the issue description, reproduction steps and environment details?

The formatting is making it difficult to determine where you're having a problem. I'd recommend using a gist for large stack traces for better readability.

**Comment by wermaxta** [comment]
when i want to start king-phisher i got this message 

Job for king-phisher.service failed because a timeout was exceeded.
See "systemctl  status king-phisher.service" and "journalctl  -xe" for details.

so i'm checking the details with this command 

systemctl  status king-phisher.service
and i get this

root@kali:~# systemctl  status king-phisher.service
● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; disabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Tue 2017-10-17 16:04:19 EEST; 4min 24s ago
  Process: 1538 ExecStart=/usr/bin/python3 /usr/share/king-phisher/KingPhisherServer /etc/king-phisher/server_

Oct 17 16:02:55 kali python3[1538]:     return dialect.connect(*cargs, **cparams)
Oct 17 16:02:55 kali python3[1538]:   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.p
Oct 17 16:02:55 kali python3[1538]:     return self.dbapi.connect(*cargs, **cparams)
Oct 17 16:02:55 kali python3[1538]:   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line
Oct 17 16:02:55 kali python3[1538]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Oct 17 16:02:55 kali python3[1538]: sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  passw
Oct 17 16:02:55 kali python3[1538]: FATAL:  password authentication failed for user "king_phisher"
Oct 17 16:04:19 kali systemd[1]: king-phisher.service: Start operation timed out. Terminating.
Oct 17 16:04:19 kali systemd[1]: king-phisher.service: Failed with result 'timeout'.
Oct 17 16:04:19 kali systemd[1]: Failed to start King Phisher Server.

**Comment by Gilks** [comment]
Ah, I see. The key part of that stack trace is here:

> Oct 17 16:02:55 kali python3[1538]: FATAL: password authentication failed for user "king_phisher"

This is referenced in the King-Phisher FAQ [here](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#database-authentication-failure). Basically, the king_phisher account needs to have the password reset in postgres and then the server_config.yml file needs to be updated with the new password.

**Comment by wermaxta** [comment]
Thank you :)

**Comment by Gilks** [comment]
You got it!
