### ISSUE TITLE
help fix this.

### ISSUE THREAD

**Issue by debengils** [securestate/king-phisher#241]
someone help me, i've tried various ways but the password that i input always wrong.
![screenshot from 2017-10-25 21-59-12](https://user-images.githubusercontent.com/32804350/32005993-d3ba4c80-b9cf-11e7-9ef0-4dd85efa47f4.png)

**Comment by wolfthefallen** [comment]
Please see [the faq about username and password](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#what-are-the-default-credentials), It is the username and password you use to login to your King Phisher Sever, either via ssh or via mouse and keyboard at the login screen... As it appears you are using Kali Linux, it is what ever you set your username and password during installation. Generally this is root, and what ever your password is.

**Comment by debengils** [comment]
king-phisher is installed by default in my system. I've tried to login with root: toor and still can not login. I try to change the username and password in postgres and the result is the same

**Comment by wolfthefallen** [comment]
For the login screen you showing that you are having in issue with, has nothing to do with a postgres username and password. 

It is the username and password you use at your systems login screen which looks like the below image.
![image](https://user-images.githubusercontent.com/9035933/32008203-a554eba8-b979-11e7-86f2-669173f17fd6.png)

**Comment by debengils** [comment]
is this fine?
![screenshot from 2017-10-25 22-52-34](https://user-images.githubusercontent.com/32804350/32008790-5e79216e-b9d7-11e7-94a5-a528cf1821a3.png)

**Comment by wolfthefallen** [comment]
Click the King Phisher Campaigns window, and create your first campaign! you are good to go

**Comment by debengils** [comment]
nice!! thx for help!!!
