### ISSUE TITLE
This is the issue am having 

### ISSUE THREAD

**Issue by seanjackson** [securestate/king-phisher#243]
school@kali:~$ systemctl start king-phisher.service
Failed to start king-phisher.service: Access denied
school@kali:~$ sudo service postgresql start 
school@kali:~$ systemctl start king-phisher.service
school@kali:~$ systemctl status king-phisher.service
● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-10-31 13:44:56 WAT; 9s ago
  Process: 2125 ExecStart=/usr/share/king-phisher/KingPhisherServer /etc/king-phisher/server_config.yml (code=exited, status=0/SUCCESS)
 Main PID: 2134 (KingPhisherServ)
   CGroup: /system.slice/king-phisher.service
           ├─2134 /usr/bin/python -B /usr/share/king-phisher/KingPhisherServe...
           └─2136 /usr/bin/python -B /usr/share/king-phisher/KingPhisherServe...
school@kali:~$ systemctl start ssh
school@kali:~$ systemctl status ssh
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-10-31 13:51:11 WAT; 8s ago
  Process: 2373 ExecStartPre=/usr/sbin/sshd -t (code=exited, status=0/SUCCESS)
 Main PID: 2376 (sshd)
   CGroup: /system.slice/ssh.service
           └─2376 /usr/sbin/sshd -D
school@kali:~$ uname -a 
Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux
school@kali:~$

**Comment by zeroSteiner** [comment]
Once again, when you open an issue please fill out the template in it's entirety. This still does not have the information we requested in #242. Furthermore, it is unnecessary to open a new GitHub issue to solve the same logical problem. Please continue the discussion there.

Once you have provided the information that we have requested we will be happy to assist you.
