### ISSUE TITLE
This is what the client is displaying to me 

### ISSUE THREAD

**Issue by seanjackson** [securestate/king-phisher#244]
version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
WARNING  failed to connect to the remote rpc service
Traceback (most recent call last):
  File "/usr/share/king-phisher/king_phisher/client/application.py", line 432, in server_connect
    server_version_info = rpc('version')
  File "/usr/share/king-phisher/king_phisher/third_party/AdvancedHTTPServer.py", line 475, in __call__
    return self.call(*args, **kwargs)
  File "/usr/share/king-phisher/king_phisher/third_party/AdvancedHTTPServer.py", line 526, in call
    resp = self.client.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
WARNING  failed to connect to the remote rpc service with http status: 501

**Comment by seanjackson** [comment]
![screenshot from 2017-10-31 14-17-42](https://user-images.githubusercontent.com/11593932/32227185-ec93fe20-be4a-11e7-9238-7cf872ba8a4e.png)

**Comment by seanjackson** [comment]
![screenshot from 2017-10-31 14-53-20](https://user-images.githubusercontent.com/11593932/32227300-4aee453e-be4b-11e7-8936-28019cd578d8.png)

**Comment by seanjackson** [comment]
Please what is likely the problem i have been troubleshooting this

**Comment by wolfthefallen** [comment]
Please do not open new issues, Please go back to your original issue and post any follow ups to your current issue in there util it has been resolved.

Furthermore:
For us to provide full support Please fill out the template below completely. This information will provide us all the information that is required for us to help you in your issue. Do not remove any section, and fill out each issue to the best of your ability. 

Primarily You are missing key information: 
* what version of King Phisher you are running
* What steps need to be taken to reproduce the issue

Fill this out:
## Issue Description
I get a stack trace when I...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
Once again, as stated in #242 and #243 please provide us with the version of King Phisher. All of the other information is pretty much there at this point and we can figure it out. Additionally, **please stop opening new issues and continue the discussion in #242.** I'm closing this as an invalid duplicate, please do not open another ticket for the same issue.

@wolfthefallen we really just need the version of King Phisher at this point.
