### ISSUE TITLE
Multiple user logon results in 401 Unauthorized and first user being booted 

### ISSUE THREAD

**Issue by routeback** [securestate/king-phisher#247]
## Issue Description
We are unable to have more than one user access King-Phisher at a time.
When someone is logged on, and another user attempts to authenticate, the first user gets booted off and is forced to close the client and wait until the other user has logged off.

## Reproduction Steps
1. Start King Phisher
2. Connect to the King-Phisher server remotely with the client `./King-Phisher`
3. Have another user attempt to logon to King-Phisher

## Environment Details
Host OS: Kali Rolling
King Phisher Version: Latest

## Error Details / Stack Trace
```
advancedhttpserver.RPCError:` the server responded with 401 'Unauthorized'
WARNING  failed to logout, rpc error: Unauthorized
```

**Comment by zeroSteiner** [comment]
That's the intended functionality. If the same user tries to log on multiple times, then the previous session will be invalidated resulting in the `401 Unauthorized` error you're seeing being displayed.

I recommend you create multiple accounts instead of sharing one.

**Comment by routeback** [comment]
Creating a separate user and authenticating with it solved my issue.

Thanks!
