### ISSUE TITLE
User still able access landing page after credential submission

### ISSUE THREAD

**Issue by cafeitduong** [securestate/king-phisher#252]
## Issue Description
In the Campaign config, I already selected "Deny Requests After Credential Submission" but user still able to revisit the landing page and going through the flow with new credential submitted.

## Reproduction Steps
1. Start King Phisher
2. Create new campaign
3. Name "Testing123"
4. Select Type: credential, Next
5. Select "Deny Requests After Credential Submission", Next
6. Leave all other as default
7. Select campaign and input required fields such as sender, receipt, email body
8. Send email
9. On receiver side, input username + password and submit to go through the flow (education confirmed). close window.
10. Re-visit the same URL from email, user still able o submit credential and going through flow.

## Environment Details

Host OS: Ubuntu 14.04 LTS
King Phisher Version: 1.8.0

## Error Details / Stack Trace

N/A

**Comment by zeroSteiner** [comment]
Can you verify for me that if you clear all of your cookies (or open an incognito / equivalent tab) that you're still able to go to the landing page? I'm pretty sure that existing sessions won't stop working but new visits to the landing page should when that setting is enabled.

**Comment by cafeitduong** [comment]
You're right, it's not loading on the new browser. So it cannot stop user keep opening on the same browser?

**Comment by zeroSteiner** [comment]
That's correct. The intention is to redirect users that may have received the email after it was forwarded, like the IT security department. That way when the second party gets it, they'll see something different (that 404 page) than what the original user reporting the issue saw.

Now if you want the original user to not be able to go back to that page you could do that with a bit of Jinja-foo. You should be able to wrap the pages you want to protect in something like:
```
{% if client.message_id is defined and client.credential_count %}
<!-- this HTML will get displayed after at least 1 credential has been collected -->
{% else %}
<!-- this HTML will get displayed when no credentials have been collected -->
{% endif %}
```

Also keep in mind the difference between `client.credential_count` is how many have been collected for that phishing message and `client.campaign.credential_count` which is how many have been collected for the campaign that phishing message is a part of.

**Comment by cafeitduong** [comment]
Great thanks for your detail explanation. I'm clear now.

**Comment by zeroSteiner** [comment]
No problem, I'm just going to close this issue out though since we got that cleared up. I'll see about reviewing the documentation as well to make what that option does a bit more clear.
