### ISSUE TITLE
New OS Support

### ISSUE THREAD

**Issue by usmarine2141** [securestate/king-phisher#253]
please support Parrot OS

**Comment by zeroSteiner** [comment]
I think it's already supported by their package manager. I'll double check though.

It should be easy enough for us to add it to the install script assuming that they're using modern versions of the libraries we need.

**Comment by usmarine2141** [comment]
funny. cause it is in the repository but nowhere on the system is it found to be able to be ran. But the files are in /usr/share/king-phisher

**Comment by usmarine2141** [comment]
found it

**Comment by wolfthefallen** [comment]
As stated in issue #217, Parrot OS is not offically supported by Parrot OS. The Parrot OS maintainers have it available through `apt`. 
You can install King Phisher on ParrotOS by doing the following commands
```
sudo apt update
sudo apt install king-phisher
Once installed you can start the King Phisher server with `sudo systemctl start king-phisher` and you can start the client by typing in `/usr/share/king-phisher/KingPhisher` into the terminal.
```
If you have any issues with installing King Phisher on Parrot OS please reach out to the maintainers of the Parrot OS.
