### ISSUE TITLE
"Failed to Connect to the KingPhisher RPC Service" But Nothing Else is Running on That Port

### ISSUE THREAD

**Issue by shristi1** [securestate/king-phisher#256]
## Issue Description
I get a "Failed to Connect to the KingPhisher RPC Service" error when I...

## Reproduction Steps
1. Start the King Phisher Client
2. Try to log in to my server

## Environment Details

Host OS: Ubuntu 16.04.3
King Phisher Version: 1.9.0

## Error Details / Stack Trace

Here's what it looks like:
![error](https://user-images.githubusercontent.com/7952820/35158884-169ff42a-fcfe-11e7-870a-a3067a2d8e1e.png)

However, when I check what is running on port 80, I get nothing:
![error](https://user-images.githubusercontent.com/7952820/35158994-7845ac1a-fcfe-11e7-955f-ffbfe1479d54.png)

Everything works fine when I run the server on debug mode:
![error](https://user-images.githubusercontent.com/7952820/35158962-58f399e4-fcfe-11e7-94e3-a39871032cc3.png)

Can anybody help me figure out what's going on?

**Comment by zeroSteiner** [comment]
You are leaving the server running while you're trying to connect and running `lsof` right? The server should have actually installed a service, but it doesn't really matter how it's started.

There is definitely an issue with your connection to the server.

**Comment by shristi1** [comment]
Thank you for your reply! Can you please elaborate on what type of issue I am having connecting to the server? 
And also, yes, I did try to leave the server running while trying to connect, but I also tried it without it running and got the same result.

**Comment by zeroSteiner** [comment]
Please refer to the [Client Fails To Connect](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#king-phisher-client-fails-to-connect) section in the FAQ.

**Comment by shristi1** [comment]
Alright, using this command I am finally getting an error:
`sudo /opt/king-phisher/KingPhisherServer -L INFO -f /opt/king-phisher/server_config.yml`
It now says that:
`FATAL:` Password Authentication failed for user "king_phisher"`
I will try to see if the password has somehow changed since my last login. But, I am not sure how that would be possible.

**Comment by zeroSteiner** [comment]
If you ran the installation script more than once it would have changed your postgresql password for the `king_phisher` account. There should be the original password in the `server_config.yml.bck` file.

**Comment by shristi1** [comment]
Fixed that problem, but the original error still persists. Thank you for your help so far!

**Comment by wolfthefallen** [comment]
Verify Your King Phisher Server is running, and set to port 80. Make sure you have all other web server services such as apache or ngix is turned off.

**Comment by shristi1** [comment]
Thank you, but I have already checked both things and that is not causing the error. Any other ideas?

**Comment by shristi1** [comment]
However, when I try to run the client as root (after I start the server) I get this error:
`(KingPhisher:3325): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
`
I'm not sure if this is useful, but I thought that I might as well let you know.

**Comment by shristi1** [comment]
Fixed my issue! I was connecting with my public ip address during "Server Login" instead of my loopback address "127.0.0.1" . Thanks for your help!
