### ISSUE TITLE
Error in installaing (Failed to detect the version of Linux)

### ISSUE THREAD

**Issue by macrosec** [securestate/king-phisher#258]
When I run the install.sh script i get the following error:

root@test:#tools/install.sh
Failed to detect the version of Linux
This installer only supports the following Linux distributions:
  - BackBox
  - CentOS
  - Debian
  - Fedora
  - Kali
  - Red Hat
  - Ubuntu
  - Arch

If the current version of Linux is one of these flavors but it is
not recognized, please open a support ticket and include the version.

Here is the output to show OS version:

root@test:# cat /etc/issue
Debian GNU/Linux buster/sid \n \l

root@test:# uname -a
Linux labman 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

**Comment by wolfthefallen** [comment]
From the out put of /etc/issue you are running a none standard version of Debian. King Phisher only supports the [operating systems here](https://github.com/securestate/king-phisher/wiki/Advanced-Installation#install-script-supported-flavors). 

Please note that it is only the current versions are supported, as buster is in testing and is not in stable release yet King Phisher does not currently support it.
