### ISSUE TITLE
Client Side: Connecting to SMTP server... failed.

### ISSUE THREAD

**Issue by macrosec** [securestate/king-phisher#259]
## Issue Description
When sending out mails from the KP Server after setting up campaign I keep getting connecting to SMTP server failed.

## Reproduction Steps
1. Start King Phisher
2. Sending mails from client

## Environment Details
Host OS: Kali 2017.3
King Phisher Version: 1.9.0

## Error Details / Stack Trace
Checking the target URL... failed, error ignored.
Checking the SPF policy of target domain 'xyz.com'... done, no policy was found.
SPF policy result: N/A (No policy found)
Sending messages started at: Friday February 09, 2018 15:49:27
Message mode is: Email
Connecting to SSH... done.
Connecting to SMTP server... failed.

**Comment by zeroSteiner** [comment]
Is your SMTP server configured correctly and can you connect to it from the host on which your King Phisher client is running?

From the logs, it looks like you have the SSH forwarding option enabled for your SMTP server. If that's not necessary and you're not trying to connect to your SMTP server over an SSH tunnel then go ahead and turn that option off.

**Comment by zeroSteiner** [comment]
I'm going to close this issue out due to inactivity. If you're still experiencing it, please respond to the preceding message in this thread and we'll re-open it. Thanks.
