### ISSUE TITLE
Verify Web URL 404 Not Found

### ISSUE THREAD

**Issue by macrosec** [securestate/king-phisher#260]
## Issue Description
When I am setting up a campaign and click on verify web url I get the error 404 not found

## Reproduction Steps
1. Start King Phisher
2. Click verify web url while setting up campaign

## Environment Details
Host OS: Kali 2017.3
King Phisher Version: 1.9.0

## Error Details / Stack Trace
When I click verify web url or if I open the path to KP web server I get the 404 error as shown in attachement. I have set **require_id** to **false** in server_config.yml yet this is happening. KP web server is running on default port 80
![screenshot from 2018-02-09 16-03-30](https://user-images.githubusercontent.com/30057970/36029371-fdcf75d0-0db3-11e8-86c5-90397ae42cfe.png)

**Comment by wolfthefallen** [comment]
Make sure you have the `index.html` webpage in King Phisher Server's webroot. By default this is `/var/www/` and make sure everyone has read access to the file.

**Comment by macrosec** [comment]
The files are in the correct folder as shown in attached screenshot and the relevant access rights given.

![screenshot from 2018-02-09 18-09-16](https://user-images.githubusercontent.com/30057970/36034326-cc184fec-0dc4-11e8-87ac-872ff6513ccc.png)

Still get the 404 error

**Comment by zeroSteiner** [comment]
Do you have the `vhost_directories` option set to True in your server configuration or `False`? Also can you please provide us with the server logs of what happens when you hit the Verify URL button? Please make sure that the log level is set to DEBUG for this. You can find steps on how to do that in the [FAQ section](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-generate-verbose-logging-output) of the wiki.

Additionally, if you have any invalid Jinja code in your index.html file, it'll fail to render and you'll get a 404 error.

**Comment by macrosec** [comment]
**vhost_directories** has been set to **true**

Also the index.html file should be fine unless there is something I am not seeing right in it. Here is the output of the index.html file:
_root@macrosec:/var/www# cat index.html
<!DOCTYPE html>
<html>
<head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <title>HansaWorld</title>
        <link href="./include/style.css" rel="stylesheet" type="text/css" />
        <script src="./include/forgotPasswd.js" type="text/javascript"></script>
        <link rel="SHORTCUT ICON" href="./images/favicon.ico" />
</head>
<body>
        <div id="container">
                <h1><img src="./images/logo.png" align="center" width="200"></h1>
                <form method="post" action="./error.html">
                        <label for="username">Username:</label>
                        <input name="username" type="name" autocomplete="off">
                        <label for="password">Password:</label>
                        <input name="password" type="password" autocomplete="off">
                        <p><a onClick="myPopup()">Forgot your password?</a></p>
                        <div id="lower">
                                <input type="checkbox"><label class="check" for="checkbox">Keep me logged in</label>
                                <input type="submit" value="Login">
                        </div>
                </form>
        </div>
</body>
</html>_

I am enabling debug and will provide the server output asap.

**Comment by zeroSteiner** [comment]
Ok so having `vhost_directories: true` is your issue. That means that the web root directory is actually a subdirectory of the `web_root` where the value of the `Host` header for the request is the name of the directory. So in your example above the actual web root for that request would be `/var/www/192.168.60.103/`. You can either create that directory and move your index file into there, or you can disable `vhost_directories` by setting it to `false`.

See the wiki section on [Configuring the Web Root](https://github.com/securestate/king-phisher/wiki/Creating-Server-Content#configuring-the-web-root) for more details.

**Comment by zeroSteiner** [comment]
If you set `vhost_directories` to `false` don't forget to restart the service.

**Comment by macrosec** [comment]
I left vhost_directories to true and created the folder as you instructed with the files in it and the appropriate access rights to it but still now working. Here is the output of the rights to the folder and the folder created:

_root@macrosec:/var/www/192.168.60.103# pwd
/var/www/192.168.60.103
root@macrosec:/var/www/192.168.60.103# ls -l
total 60
-rwxr-xr-x 1 root root  5232 Feb  9 18:48 error
-rwxr-xr-x 1 root root   319 Feb  9 18:48 error.html
drwxr-xr-x 2 root root  4096 Feb  9 18:48 images
drwxr-xr-x 2 root root  4096 Feb  9 18:48 include
-rwxr-xr-x 1 root root   965 Feb  9 18:48 index.html
-rw-r--r-- 1 root root 10701 Feb  9 18:48 index.html.bkp
-rw-r--r-- 1 root root   612 Feb  9 18:48 index.nginx-debian.html
-rwxr-xr-x 1 root root  5232 Feb  9 18:48 register.html
-rwxr-xr-x 1 root root  5232 Feb  9 18:48 sorry
drwxr-xr-x 5 root root  4096 Feb  9 18:48 templates_

What command can I run to stop the KP server so that I can start it with DEBUG enabled?

**Comment by zeroSteiner** [comment]
You'll need to stop the service then start it with DEBUG. Again, steps on starting it with DEBUG logging are in the [FAQ](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-generate-verbose-logging-output).

Also if you haven't restarted the service then your configuration hasn't taken affect and you'll still have the same issue. Finally, know that if you create the directory as the IP address, **it will only ever work when the server is visited by that IP address.** If you assign it a hostname through DNS you'll need to create a separate folder for each hostname each with their own content.

**Comment by zeroSteiner** [comment]
It's probably `sudo systemctl stop king-phisher` to stop it and `sudo systemctl restart king-phisher` to restart it. I say probably because it depends on if your system is using SystemD or the Upstart (which shouldn't be nearly as common any more, my guess is you're probably using SystemD).

**Comment by macrosec** [comment]
So I was doing exactly that to stop and start the service yet it didn't work. I followed the stop procedure and started it with the **./KingPhisherServer -f -L DEBUG server_config.yml** yet can't access it. 

When I ran the service king-phisher status I got the following output:

root@macrosec:/var/www/192.168.60.103# service king-phisher status
● king-phisher.service - King Phisher Server
   **Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2018-02-09 19:17:53 EAT; 10min ago
  Process: 3566 ExecStop=/bin/kill -INT $MAINPID (code=exited, status=0/SUCCESS)
  Process: 3477 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml (code=exited, status=0/S
 Main PID: 3484 (code=killed, signal=TERM)**

Feb 09 19:15:56 macrosec su[3507]: + ??? root:postgres
Feb 09 19:15:56 macrosec su[3507]: pam_unix(su:session): session opened for user postgres by (uid=0)
Feb 09 19:15:56 macrosec systemd[1]: king-phisher.service: PID file /var/run/king-phisher.pid not readable (yet?) after start: No such file
Feb 09 19:15:56 macrosec su[3507]: pam_unix(su:session): session closed for user postgres
Feb 09 19:15:56 macrosec systemd[1]: Started King Phisher Server.
Feb 09 19:16:37 macrosec python3[3477]: WARNING  denying request due to lack of a valid id
Feb 09 19:16:41 macrosec python3[3477]: WARNING  denying request due to lack of a valid id
Feb 09 19:17:53 macrosec systemd[1]: Stopping King Phisher Server...
Feb 09 19:17:53 macrosec python3[3477]: WARNING  processing shutdown request
Feb 09 19:17:53 macrosec systemd[1]: Stopped King Phisher Server.
lines 1-17/17 (END)

**Comment by wolfthefallen** [comment]
what is the error you are getting when trying to start King Phisher Server in debug mode? As the status out put of the service shows you have stopped it

**Comment by macrosec** [comment]
When I start it with the DEBUG option this is the output I got:

root@macrosec:/opt/king-phisher# sudo ./KingPhisherServer -f -L DEBUG server_config.yml
DEBUG    king phisher version: 1.10.0-beta (rev: 6f2ade795b6a) python version: 3.6.4
INFO     listening on 0.0.0.0:80
INFO     serving files has been enabled
INFO     initializing database connection with driver postgresql
DEBUG    postgresql-setup was not found
DEBUG    postgresql service is already running via systemctl
DEBUG    current database schema version: 7 (latest)
DEBUG    connected to postgresql database: king_phisher
INFO     restored 0 valid sessions and skipped 0 expired sessions from the database
DEBUG    use pam service 'sshd' for authentication
DEBUG    forked an authenticating process with pid: 3348
INFO     the job manager has been started
INFO     adding new job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    web socket manager worker running in tid: 0x-4b3404c0
INFO     including 4 custom http headers
INFO     server running in process: 3318 main tid: 0x-483e43c0
INFO     dropped privileges to the nobody account
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    192.168.60.103 tid: 0x-4f9164c0 running http request handler
WARNING  denying request due to lack of a valid id
INFO     192.168.60.103 http request aborted
INFO     192.168.60.103 "GET / HTTP/1.1" 404 -
INFO     192.168.60.103 "GET /kp.js HTTP/1.1" 200 -
INFO     192.168.60.103 "GET /favicon.ico HTTP/1.1" 404 -
INFO     192.168.60.103 "GET /favicon.ico HTTP/1.1" 404 -
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
WARNING  denying request due to lack of a valid id
INFO     192.168.60.103 http request aborted
INFO     192.168.60.103 "GET /index.html HTTP/1.1" 404 -
INFO     192.168.60.103 "GET /kp.js HTTP/1.1" 200 -
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    executing job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
^CWARNING  processing shutdown request
WARNING  request received without a specified action
INFO     deleting job with id: 3222aab9-fae1-4cf3-b23d-dc758b290715 and callback function: ping_all
DEBUG    stopping the job manager
DEBUG    waiting on 0 job threads
INFO     the job manager has been stopped
INFO     no sessions to store in the database
DEBUG    sent request with sequence number 0 and action 'stop'
DEBUG    received request with sequence number 0 and action 'stop'
DEBUG    stopped the forked authenticator process
INFO     unloading 0 plugins
root@macrosec:/opt/king-phisher# sudo ./KingPhisherServer -f -L DEBUG server_config.yml
DEBUG    king phisher version: 1.10.0-beta (rev: 6f2ade795b6a) python version: 3.6.4
ERROR    failed to bind server to address (socket error #98)
ERROR    socket error #98 (Address already in use)
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/server/build.py", line 145, in server_from_config
    server = KingPhisherServer(config, plugin_manager, handler_klass, addresses=addresses, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/opt/king-phisher/king_phisher/server/server.py", line 853, in __init__
    super(KingPhisherServer, self).__init__(handler_klass, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/advancedhttpserver.py", line 1780, in __init__
    server = server_klass((address[0], address[1]), handler_klass, config=self.__config)
  File "/usr/local/lib/python3.6/dist-packages/advancedhttpserver.py", line 703, in __init__
    super(ServerNonThreaded, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.6/dist-packages/advancedhttpserver.py", line 771, in server_bind
    super(ServerNonThreaded, self).server_bind(*args, **kwargs)
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
CRITICAL server failed to build with error: socket error #98 (Address already in use)
INFO     unloading 0 plugins
root@macrosec:/opt/king-phisher# sudo ./KingPhisherServer -f -L DEBUG server_config.yml
DEBUG    king phisher version: 1.10.0-beta (rev: 6f2ade795b6a) python version: 3.6.4
INFO     listening on 0.0.0.0:80
INFO     serving files has been enabled
INFO     initializing database connection with driver postgresql
DEBUG    postgresql-setup was not found
DEBUG    postgresql service is already running via systemctl
DEBUG    current database schema version: 7 (latest)
DEBUG    connected to postgresql database: king_phisher
INFO     restored 0 valid sessions and skipped 0 expired sessions from the database
DEBUG    use pam service 'sshd' for authentication
DEBUG    forked an authenticating process with pid: 3602
INFO     the job manager has been started
INFO     adding new job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    web socket manager worker running in tid: 0x-4b4004c0
INFO     including 4 custom http headers
INFO     server running in process: 3573 main tid: 0x-483fe3c0
INFO     dropped privileges to the nobody account
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    192.168.60.103 tid: 0x-4fa164c0 running http request handler
WARNING  denying request due to lack of a valid id
INFO     192.168.60.103 http request aborted
INFO     192.168.60.103 "GET /index.html HTTP/1.1" 404 -
INFO     192.168.60.103 "GET /kp.js HTTP/1.1" 200 -
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
DEBUG    executing job with id: a5ffc069-cf32-4861-932d-03c59614c2e3 and callback function: ping_all
