### ISSUE TITLE
Error while running ./install.sh

### ISSUE THREAD

**Issue by djtroby** [securestate/king-phisher#261]
Hi,

I am getting the following error while installing the king-phisher.

sudo ./install.sh 
Failed to detect the version of Linux
This installer only supports the following Linux distributions:
  - BackBox
  - CentOS
  - Debian
  - Fedora
  - Kali
  - Ubuntu

If the current version of Linux is one of these flavors but it is
not recognized, please open a support ticket and include the version.
Also ..please advise if king-phisher can work on ARM7 processor for Raspberry Pi 3

## Environment Details

Host OS: SMP Debian 4.14.13-1kali1 (2018-01-25)
King Phisher Version: king-phisher   1.7.1-0kali1

**Comment by zeroSteiner** [comment]
Well Kali already has King Phisher in their package repository. You can simply install it using `sudo apt-get install king-phisher` I think. It should work just fine with an ARM processor, although I haven't tried it myself.

It does look like your version of King Phisher is a bit out of date and I'm confused as to the `kali1` tag at the end. Are you trying to replace the one provided by Kali with an install from source?

**Comment by zeroSteiner** [comment]
I'm going to close this issue out due to inactivity. If you're still experiencing it, please respond to the preceding message in this thread and we'll re-open it. Thanks.
