### ISSUE TITLE
Tracking multiple URL's within a campaign

### ISSUE THREAD

**Issue by secureality** [securestate/king-phisher#262]
Just started working with KP, and appreciate the work and effort you folks have put into building and supporting this project.  I have two quick questions:

1) What would be your suggestion for the best way to track users accessing different URL's on the KP server?  For example, I have a standard landing page, but also an "unsubscribe" link in the message template.  I am experimenting with using POST requests to send data to the creds table, but ultimately I would rather see the specific URL's accessed by the users in the Visits table.  Any thoughts on a perhaps better way to accomplish this?

2) What is the TAG/Type functionality used for?  Is there any way to integrate this into a web or e-mail template?  I haven't see any reference in the templates documentation.

Thanks again!

**Comment by zeroSteiner** [comment]
**Question 1**
So you can track different URLs in a sort of indirect fashion. The easiest would probably be to set the Web Server URL as the first URL you want to track and send yourself a single test message. Then while in the same campaign, delete your previously sent test message, set the Web Server URL to the second URL you want to track and proceed as usual. What this does is causes both to be created as landing pages that are associated with one campaign.

Alternatively you could have a single landing page that redirects or changes the content based on a query variable like `?page=unsubscribe` vs `?page=login`. Of course unsubscribe and login could be numbers or what ever you'd like.

**Question 2**
The tag editor allows you to change tags, which are basically small pieces of metadata that are applied to different things. For example campaign types are a tag that are applied to campaigns. Basically, it's a short name with a description. In the case of the campaign type, it can be whatever you want to use it for, it's entirely optional. We use it internally to classify our campaigns based on what data we're trying to collect so we know what constitutes a success (visit, credential, nothing in the case of test / demo campaigns) and can more accurately analyze the data later.

**Comment by secureality** [comment]
Thanks for the info, Z.  I accomplished what I wanted (tracking access to specific landing pages) through a bit of a hack, using the Credential storing ability as a placeholder for the data I was looking for.  Here's what I did:
**In the e-mail template:**
For any landing page besides the default, for the href use: href="{{ url.webserver_raw }}/some_landing_page.html?id={{ uid }}"

**In the landing page:**
```
<iframe name="shim" style="align:left;border:2px;width:100%;height:1px" src="/images/trans.gif"></iframe>

<form name="unsub" id="unsub" method="post" action="./shim.html" target="shim">
	<input type="hidden"   id="username" name="username" value="{{ client.first_name }} {{ client.last_name }}" />
        <input type="hidden"   id="password" name="password" value="some note to track" />
	</form>

<script type="text/javascript">document.getElementById("unsub").submit();</script>
```

The shim.html page can be anything, include just a blank page, I put some debug information that I can use when troubleshooting data.

This gives me the data that I am looking for, and unique visits by user are still handled properly.  Not the most elegant solution, but it does the trick for now.  I am going to experiment with your query valuable above at some point, it is something I used to do in my prior PHP version of my landing website.  I will update if I come up with something more elegant!

Thanks!

**Comment by zeroSteiner** [comment]
Cool sounds good! Yeah there's a few ways to accomplish the same things sometimes. I'd like to take it as a sign that we've succeeded in making the tool quite flexible. If there's something you need added into to the variables let me know through another ticket. Adding Jinja variables, functions, filters etc are some of the easiest changes we can make. 

If you start to get hard core into template design, you might find the [page-variables.html](https://github.com/securestate/king-phisher/blob/dev/data/server/king_phisher/pages/page-variables.html) page useful. We keep it for debugging purposes and it shows the status of all of the variables. Just drop it in your webroot, send yourself a test message and then view the page.
