### ISSUE TITLE
GraphQLQueryError

### ISSUE THREAD

**Issue by pechom** [securestate/king-phisher#264]
## Issue Description
I get a stack trace when I create campaign with new company

## Reproduction Steps
1. Start King Phisher
2. Create campaign with new company or edit campaign to add new company.

## Environment Details

Host OS: LinuxMint 18.3 sylvia
King Phisher Version: 1.10.0-beta

## Error Details / Stack Trace

```
  File "/opt/king-phisher/king_phisher/client/assistants/campaign.py", line 290, in signal_assistant_apply
    company_id = self._get_company_new_id()
  File "/opt/king-phisher/king_phisher/client/assistants/campaign.py", line 237, in _get_company_new_id
    remote_company_id = self._get_graphql_company_id(name)
  File "/opt/king-phisher/king_phisher/client/assistants/campaign.py", line 265, in _get_graphql_company_id
    }""", {'name': company_name})
  File "/opt/king-phisher/king_phisher/client/client_rpc.py", line 205, in graphql
    query_vars=query_vars
king_phisher.errors.KingPhisherGraphQLQueryError
```

**Comment by zeroSteiner** [comment]
I've reproduced this and confirmed that it only effects the master branch. I'll get a fix pushed up here shortly.

**Comment by zeroSteiner** [comment]
Fixed in commit 6bab024ed81114295d3adbd210194e8e4508e69d. @pechom can you update your version using git and try again? Instructions on updating are available [in the wiki](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#how-to-update-from-git).

**Comment by pechom** [comment]
It works after update

**Comment by zeroSteiner** [comment]
Excellent, thanks for the update.
