### ISSUE TITLE
Failed to Start King Phisher Server

### ISSUE THREAD

**Issue by gomezda21** [securestate/king-phisher#272]
## Issue Description
I get a stack trace when I...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 15.10 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```
![failed to start server](https://user-images.githubusercontent.com/37555336/37618030-2a4f4884-2b8b-11e8-91a6-f2114e028df1.PNG)
 I am tryiing to start the King Phisher Server but it is displaying this message. I already change the Postgresql password and restarted the server but it did not fix the issue. 
![failure to start kingphisher](https://user-images.githubusercontent.com/37555336/37618136-9b96e74a-2b8b-11e8-8e8c-f29fd6f9d73d.PNG)
This is the image where it is telling me that King Phisher cannot start because it failed to connect to server socket. Thanks!

**Comment by zeroSteiner** [comment]
You need to fix your postgresql password and then update the server config with the correct value. Please see the [FAQ](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#database-authentication-failure) in regards to this.

For the second one it looks like it's having trouble starting the graphical environment. Are you trying to start it from an SSH session?

**Comment by gomezda21** [comment]
Already did that but it is not working for me. Any other thing I could do for this? 

Yes, I am trying to start it from ssh session

**Comment by zeroSteiner** [comment]
I would suggest you try resetting it again and making sure that the configuration under `pg_hba.conf` is correct. Don't rerun the install script by the way, that'll update your password again.

Well you can't start the client from an SSH session unless you want to see if you can get X11 forwarding working but that's definitely something we can't provide support for. It might work, it might not.

**Comment by gomezda21** [comment]
Where can I find the pg_hba.conf ? 

What is X11 forwarding? 

Thanks, 

Denis

**Comment by zeroSteiner** [comment]
You'll need to find your own pg_hba.conf file, the location varies from distribution to distribution. The installation script should have configured it correctly for you. You should just need to reset the password for the king_phisher postgres user. Set it to whatever you want then put the new value in the server configuration where the database connection string is.

Don't worry about X11 forwarding, just know that you **can't start the client over SSH**. You need to either have a Linux installation with a GUI that you can use to run the client, or download one of the Windows builds form our [Releases Page](https://github.com/securestate/king-phisher/releases).

**Comment by zeroSteiner** [comment]
I'm going to close this issue out due to inactivity. If you're still experiencing it, please respond to the preceding message in this thread and we'll re-open it. Thanks.
