### ISSUE TITLE
WARNING  verify url HTTP error: 503 Service Unavailable

### ISSUE THREAD

**Issue by chrisandjer949** [securestate/king-phisher#284]
## Issue Description
When I tried to verify URL, I get a 503 Service Unavailable error.  I can see via "netstat -tulpn" that python3 is using :80.

root@kali2:/opt/king-phisher# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1865/python3        
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      735/postgres        
tcp6       0      0 ::1:5432                :::*                    LISTEN      735/postgres      

## Reproduction Steps
1. Start King Phisher
2. Click on "verify URL" button.  My configured URL page is http://kali/index.html

## Environment Details

Host OS: Kali 2018.1 
King Phisher Version: latest KP clone from GitHub.  

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```
Based on the DEBUG server_config.yml logs, there are no errors.

root@kali2:/opt/king-phisher# ./KingPhisherServer -f -L DEBUG server_config.yml
DEBUG    king phisher version: 1.10.0 (rev: 63aaf4772ed9) python version: 3.6.5
INFO     listening on 0.0.0.0:80
INFO     serving files has been enabled
INFO     initializing database connection with driver postgresql
DEBUG    postgresql-setup was not found
DEBUG    postgresql service is already running via systemctl
DEBUG    current database schema version: 8 (latest)
DEBUG    connected to postgresql database: king_phisher
INFO     restored 0 valid sessions and skipped 0 expired sessions from the database
DEBUG    use pam service 'sshd' for authentication
DEBUG    forked an authenticating process with pid: 1742
INFO     the job manager has been started
INFO     adding new job with id: 852c6615-e494-4642-aa5e-7b118321f02c and callback function: ping_all
DEBUG    web socket manager worker running in tid: 0x7f1baefec700
INFO     including 4 custom http headers
INFO     server running in process: 1712 main tid: 0x7f1bbc2e5740
INFO     dropped privileges to the nobody account
DEBUG    executing job with id: 852c6615-e494-4642-aa5e-7b118321f02c and callback function: ping_all
DEBUG    executing job with id: 852c6615-e494-4642-aa5e-7b118321f02c and callback function: ping_all
DEBUG    127.0.0.1 tid: 0x7f1bae7eb700 running http request handler
DEBUG    calling RPC method rpc_version()
INFO     127.0.0.1 "RPC /version HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1bae7eb700 running http request handler
DEBUG    sent request with sequence number 0 and action 'authenticate'
DEBUG    received request with sequence number 0 and action 'authenticate'
DEBUG    pam returned code: 0 reason: 'Success' for user root after 0.02 seconds
DEBUG    sent response with sequence number 0
DEBUG    received response with sequence number 0
INFO     user root has successfully authenticated
INFO     successful login request from 127.0.0.1 for user root
INFO     127.0.0.1 "RPC /login HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1bae7eb700 running http request handler
INFO     127.0.0.1 "GET /_/ws/events/json HTTP/1.1" 101 -
INFO     web socket has been connected
DEBUG    127.0.0.1 tid: 0x7f1badfaa700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1badfaa700 running http request handler
INFO     127.0.0.1 "RPC /config/get HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1badfaa700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1badfaa700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1badfaa700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1bad729700 running http request handler
DEBUG    calling RPC method rpc_events_subscribe('db-messages', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1badfaa700 running http request handler
DEBUG    calling RPC method rpc_events_subscribe('db-visits', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1bad729700 running http request handler
DEBUG    calling RPC method rpc_events_subscribe('db-credentials', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1bad729700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1bad729700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1bad729700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f1bad729700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    executing job with id: 852c6615-e494-4642-aa5e-7b118321f02c and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 852c6615-e494-4642-aa5e-7b118321f02c and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 852c6615-e494-4642-aa5e-7b118321f02c and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
Killed
root@kali2:/opt/king-phisher# systemctl status KingPhisher
Unit KingPhisher.service could not be found.
root@kali2:/opt/king-phisher# ./KingPhisherServer -f -L DEBUG server_config.yml
DEBUG    king phisher version: 1.10.0 (rev: 63aaf4772ed9) python version: 3.6.5
INFO     listening on 0.0.0.0:80
INFO     serving files has been enabled
INFO     initializing database connection with driver postgresql
DEBUG    postgresql-setup was not found
DEBUG    postgresql service is already running via systemctl
DEBUG    current database schema version: 8 (latest)
DEBUG    connected to postgresql database: king_phisher
INFO     restored 0 valid sessions and skipped 0 expired sessions from the database
DEBUG    use pam service 'sshd' for authentication
DEBUG    forked an authenticating process with pid: 1895
INFO     the job manager has been started
INFO     adding new job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    web socket manager worker running in tid: 0x7f60765ce700
INFO     including 4 custom http headers
INFO     server running in process: 1865 main tid: 0x7f60838c7740
INFO     dropped privileges to the nobody account
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    127.0.0.1 tid: 0x7f6075dcd700 running http request handler
DEBUG    calling RPC method rpc_version()
INFO     127.0.0.1 "RPC /version HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f6075dcd700 running http request handler
DEBUG    sent request with sequence number 0 and action 'authenticate'
DEBUG    received request with sequence number 0 and action 'authenticate'
DEBUG    pam returned code: 0 reason: 'Success' for user root after 0.01 seconds
DEBUG    sent response with sequence number 0
DEBUG    received response with sequence number 0
INFO     user root has successfully authenticated
INFO     successful login request from 127.0.0.1 for user root
INFO     127.0.0.1 "RPC /login HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f6075dcd700 running http request handler
INFO     127.0.0.1 "GET /_/ws/events/json HTTP/1.1" 101 -
INFO     web socket has been connected
DEBUG    127.0.0.1 tid: 0x7f607558c700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f607558c700 running http request handler
INFO     127.0.0.1 "RPC /config/get HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f6074d4b700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f6074d4b700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f6074d4b700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f6074d4b700 running http request handler
DEBUG    calling RPC method rpc_events_subscribe('db-messages', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f6074d4b700 running http request handler
DEBUG    calling RPC method rpc_events_subscribe('db-visits', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f6074d4b700 running http request handler
DEBUG    calling RPC method rpc_events_subscribe('db-credentials', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f6074d4b700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f607558c700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f607558c700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f607558c700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    127.0.0.1 tid: 0x7f607558c700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f607558c700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1 tid: 0x7f607558c700 running http request handler
DEBUG    calling RPC method rpc_ping()
INFO     127.0.0.1 "RPC /ping HTTP/1.1" 200 -
DEBUG    executing job with id: 86393401-3230-4d96-a460-c239b46d4c8a and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DE

**Comment by zeroSteiner** [comment]
I don't understand why this is deemed a King Phisher issue. Your URL isn't using a fully qualified domain name, so I can't even test it. I just did a quick search and neither King Phisher nor the underlying HTTP server have any reference to where they would return a 503 status, it should always be a 404 if there's any kind of error.

You are setting the URL to your King Phisher server right? You can't just set it to a public site, it must be the King Phisher server if you're going to collect any results.

**Comment by chrisandjer949** [comment]
Sorry, my KP server is sitting inside my lab so it's not publicly reachable.  When I enter "kali2/index.html" in Firefox in my kali2 machine, I can reach the index.html page fine.  Within the KP client, the URL points to "http://kali2/index.html" and that's when I get the URL Web Server Timeout via browser.   Just not sure what else to look it

**Comment by zeroSteiner** [comment]
I would start the server in [debug mode](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-generate-verbose-logging-output) and watch it as you hit the "Verify URL" button to see if a request hits it.

Regardless, it's pretty arbitrary since you won't be able to send messages out with that URL anyways unless your organization has a DNS record pointing kali2 to your system. If not and you're just testing, you could try it by IP address, either an interface or the loopback.

If the server does log something indicating it gets a request, post the relevant lines back here because there's probably an error. If it doesn't log anything then the request isn't getting to the server, and the 503 is coming from somewhere else.

**Comment by chrisandjer949** [comment]
Well, I am seeing this.  Socket Error #98, which I read about in the wiki.  But when I issue a netstat -tulpn, I see python3 occupying port 80.  Apache2 definitely is not enabled.   Should I disable python3 on port 80?  

root@kali2:/opt/king-phisher# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      711/python3         
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      738/postgres        
tcp6       0      0 ::1:5432                :::*                    LISTEN      738/postgres        
root@kali2:/opt/king-phisher# systemctl status apache2
● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; disabled; vendor preset:
   Active: inactive (dead)




root@kali2:/opt/king-phisher# sudo ./KingPhisherServer -f -L DEBUG server_config.html
[-] an error occurred while parsing the server configuration file
[-] fix the errors in the configuration file and restart the server
root@kali2:/opt/king-phisher# sudo ./KingPhisherServer -f -L DEBUG server_config.html
[-] an error occurred while parsing the server configuration file
[-] fix the errors in the configuration file and restart the server
root@kali2:/opt/king-phisher# sudo ./KingPhisherServer -f -L DEBUG server_config.yml
DEBUG    king phisher version: 1.10.0 (rev: 63aaf4772ed9) python version: 3.6.5
ERROR    failed to bind server to address (socket error #98)
ERROR    socket error #98 (Address already in use)
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/server/build.py", line 145, in server_from_config
    server = KingPhisherServer(config, plugin_manager, handler_klass, addresses=addresses, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/opt/king-phisher/king_phisher/server/server.py", line 864, in __init__
    super(KingPhisherServer, self).__init__(handler_klass, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/advancedhttpserver.py", line 1780, in __init__
    server = server_klass((address[0], address[1]), handler_klass, config=self.__config)
  File "/usr/local/lib/python3.6/dist-packages/advancedhttpserver.py", line 703, in __init__
    super(ServerNonThreaded, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.6/dist-packages/advancedhttpserver.py", line 771, in server_bind
    super(ServerNonThreaded, self).server_bind(*args, **kwargs)
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
CRITICAL server failed to build with error: socket error #98 (Address already in use)
INFO     unloading 0 plugins
root@kali2:/opt/king-phisher# systemctl status KingPhisher
Unit KingPhisher.service could not be found.

**Comment by zeroSteiner** [comment]
Ok well that would make sense. It doesn't look like you're running the King Phisher server (or another instance is running). You're probably getting the 503 error from the existing apache or whatever that is running on Kali. You need to kill what ever is already bound on 80 so you can start the King Phisher server.

**Comment by wolfthefallen** [comment]
The service name is king-phisher.. so try `systemctl status king-phisher` to see its current status. If it running you need to stop it before running it from the command line in debug mode.

**Comment by chrisandjer949** [comment]
OK, I killed the previous python3 process and started ./KingPhisherServer debug command.  Seems to load without errors per the logs.  Then I checked netstat and it showed python3 occupying port 80, which I assume it's ok?   But, systemctl status king-phisher yielded the error below.  What is going on here?  

root@kali2:/opt/king-phisher# systemctl status king-phisher
● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Thu 2018-03-29 17:18:47 PDT; 3min 29s ago
  Process: 526 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_
 Main PID: 711 (code=killed, signal=KILL)

Mar 29 16:38:04 kali2 su[863]: + ??? root:postgres
Mar 29 16:38:04 kali2 su[863]: pam_unix(su:session): session opened for user postgres by (uid=0)
Mar 29 16:38:04 kali2 su[863]: pam_unix(su:session): session closed for user postgres
Mar 29 16:38:04 kali2 su[884]: Successful su for postgres by root
Mar 29 16:38:04 kali2 su[884]: + ??? root:postgres
Mar 29 16:38:04 kali2 su[884]: pam_unix(su:session): session opened for user postgres by (uid=0)
Mar 29 16:38:04 kali2 su[884]: pam_unix(su:session): session closed for user postgres
Mar 29 16:38:04 kali2 systemd[1]: Started King Phisher Server.
Mar 29 17:18:47 kali2 systemd[1]: king-phisher.service: Main process exited, code=killed, status=9/KILL
Mar 29 17:18:47 kali2 systemd[1]: king-phisher.service: Failed with result 'signal'.

**Comment by zeroSteiner** [comment]
If you started it successfully from the command line in the foreground (without systemctl) then don't worry about what systemctl says about it not running.

**Comment by zeroSteiner** [comment]
I'm going to close this issue out due to inactivity. If you're still experiencing it, please respond to the preceding message in this thread and we'll re-open it. Thanks.

**Comment by chrisandjer949** [comment]
Sorry for the silence, guys.  You guys have been great!   I was out traveling all last week.  I was able to get it working.  Didn't have to start the KingPhisherServer DEBUG command all the time.   Things just sorted started working...     Thanks again!
