### ISSUE TITLE
Please add Parrot Security OS

### ISSUE THREAD

**Issue by PaganGuy** [securestate/king-phisher#288]
## Issue Description
I use Parrot Security (Debian) which is basically just a souped up version of Kali. Please make Kind Phisher recognize it, as I am sure it will run on ParSec just fine as it is now. Just needs to get past the install script.

## Reproduction Steps
1) git clone and try to install
2) My OS is not on the list so it refuses to install

## Environment Details

Host OS: Parrot Security 3.11 GNOME/Mate, Debian System
King Phisher Version: Latest Stable as of 4/5/2018

## Error Details / Stack Trace

THERE IS NO ERROR - REQUESTING YOU ADD PARROT SECURITY TO YOUR LIST OF ACCEPTED LINUX OS
```

```

**Comment by wolfthefallen** [comment]
You can utilize the improved install script from the dev branch to install King Phisher on an unsupported OS. 

Or you can do `apt install king-phisher` as parrot utilize Kali repository.
