### ISSUE TITLE
added sms unsupported local provider, still not available in drop down selection

### ISSUE THREAD

**Issue by marxenegls** [securestate/king-phisher#290]
## Issue Description
I tried editing the sms.py to add the local sms service provider i use i got all the details gprs mms gateway ip .etc but it still doesn't show up in the preferences  server / alert settings drop selection. I'm sure i'm missing something but i don't know what or where .
Also on clinet's terminal i can see a gtk complaint which reads;

(KingPhisher:24639): Gtk-WARNING **: 05:53:06.486: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node arrow owner GtkNotebook)
It seems to be a bug but i'm wondering if It's only happening here with my setup.

**Comment by zeroSteiner** [comment]
In `data/client/king_phisher/king-phisher-client.ui` there's a `GtkListStore` called SMSCarriers that the new SMS provider's name needs to be added to. We generally edit this file with Glade.

**Comment by zeroSteiner** [comment]
I'm going to close this issue out due to inactivity. If you're still experiencing it, please respond to the preceding message in this thread and we'll re-open it. Thanks.
