### ISSUE TITLE
Include text/txt version of the email

### ISSUE THREAD

**Issue by mozg31337** [securestate/king-phisher#292]
Hi
I can't seem to find how to include a plain text alternative copy of the phishing email. We seem to be getting a SPAM flags from a number of domains and spam protection systems. Further investigation show that they were all complaining about our email not having the plain text version. Is there a way to embed it at the moment or implement this feature in the future releases?
Thanks
Andrei

**Comment by mozg31337** [comment]
Ah, thanks. That makes sense. I haven't updated for good 3 months or so. Cheers

**Comment by mozg31337** [comment]
I have updated to 1.11.1, the current latest version and done the Sent test. I do see the extra text/txt content type with the following contents: VGhpcyBtZXNzYWdlIHJlcXVpcmVzIGFuIEhUTUwgYXdhcmUgZW1haWwgYWdlbnQgdG8gYmUgcHJv
cGVybHkgdmlld2VkLg0KDQo=

or "This message requires an HTML aware email agent to be properly viewed."

However, what I was after is to have the ability to include the same text in plain text as the html version. I am seeing some spam protection engines are actually comparing the text and html versions of the email and mark down if they differ. Is this something that has been implemented yet? Thanks

**Comment by zeroSteiner** [comment]
No, in order to have the text be the same as the HTML we'd have to have some rendering or parsing involved to take the body portions of the HTML and include them as plain text. That's something we haven't gotten around to yet. From our testing, simply having the text part of the message (along with some other tweaks to the MIME message in v1.10) was enough to lower the spam assassin score for our messages to reach their inbox.

**Comment by mozg31337** [comment]
You are right, having the mime content type txt does lower the score and in our last engagement this has helped getting the message through the spam list. However, we were very close and the main factor in being very close to being detected was the point about the mismatch of the txt vs html content. My guess is that this will start making a deal in a due course.

**Comment by zeroSteiner** [comment]
Well I'd suggest using one of the online spam assassin scoring sites and tweaking the other parts of the message to lower the score to compensate for that one specific check.

I like these two:
  * https://spamcheck.postmarkapp.com/
  * https://www.mail-tester.com/

**Comment by True-Demon** [comment]
@mozg31337 I will be developing a plugin for this exact feature (converting html to plaintext version) that should land within the next month. It's just a matter of getting the time to put it together. :sweat_smile: 
Keep an eye on the PRs for https://github.com/securestate/king-phisher-plugins

**Comment by zeroSteiner** [comment]
Going to mark this as closed since the `message_plaintext` plugin has been landed (huge thanks to @True-Demon for that!).

Go ahead and pull it down from the plugin manager, it's in the latest version and is compatible with KP v1.10+.
