### ISSUE TITLE
Importing existing email

### ISSUE THREAD

**Issue by justaskingquestions** [securestate/king-phisher#295]
Some phishing frameworks such as GoPhish allow you to [import email](https://gophish.gitbooks.io/user-guide/content/documentation/templates.html) by copying the raw text of an exisiting email (e.g. from an .eml file) to create a phishing email from that. Is this possible in KingPhisher? To wat extent?

**Comment by zeroSteiner** [comment]
You could copy the HTML from the email into the message editor.

**Comment by justaskingquestions** [comment]
Thank you @zeroSteiner , that I understand. It was things like tweaking the actual MIME headers etc. that I was after. That's why I was referring to eml and raw.

**Comment by zeroSteiner** [comment]
No, you can't import MIME headers, but you can set them through the [Custom MIME Headers](https://github.com/securestate/king-phisher-plugins/blob/master/client/mime_headers.py) plugin.

**Comment by justaskingquestions** [comment]
Okay thank you. I'll give that a try.
