### ISSUE TITLE
Checking the target URL... success, done. Skipped checking the SPF policy because the SMTP server address could not be detected. Sending messages started at: Saturday June 02, 2018 08:27:39 Message mode is: Email Connecting to SMTP server... failed.

### ISSUE THREAD

**Issue by aasatti** [securestate/king-phisher#299]
## Issue Description
Checking the target URL... success, done.
Skipped checking the SPF policy because the SMTP server address could not be detected.
Sending messages started at: Sunday June 03, 2018 05:11:26
Message mode is: Email
Connecting to SMTP server... failed.

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
Please completely fill out the issue template. We need all of the details that it requests to better identify the issue and provide the help that you are requesting. Please do not open a new issue but instead just edit this one and fill out all of the details.

It looks like you need to fix your SMTP server settings though.

**Comment by wolfthefallen** [comment]
@aasatti have you resolved this issue? You should be able to by setting your SMTP settings.
You can change this setting by click on the `Edit` menu and selecting `preferences`. In the window window select SMTP Server.

**Comment by aasatti** [comment]
The issue is solved.
