### ISSUE TITLE
Blinker not installing

### ISSUE THREAD

**Issue by Joshua-Bornman** [securestate/king-phisher#300]
## Issue Description
When installing King-Phisher I get the following message:
"Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

## Reproduction Steps
1. Run the install command: "/opt/king-phisher/tools$ sudo ./install.sh"

## Environment Details

Host OS: Ubuntu 16.04.
King Phisher Version: 1.11.0 Final

## Error Details / Stack Trace

When installing King-Phisher I get the following message:
"Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

**Comment by zeroSteiner** [comment]
So after you get that message does the installation fail? Also what are the messages above and below it, we need some more context here.

@wolfthefallen Are we uninstalling the native blinker package on Ubuntu to replace it with the one from PyPi?

**Comment by wolfthefallen** [comment]
No, currently the install script does not uninstall any python packages that could be potentially installed through native package managers. That would have the potential of breaking some operating systems applications such as those on Kali. 

You will have to manually uninstall the blinker package, `sudo apt remove python3-blinker` and then run the install script again.

**Comment by Joshua-Bornman** [comment]
Everything before this point works. More info is below, after this message the installation stops:

"Installing collected packages: blinker, boltons, idna, asn1crypto, pycparser, cffi, cryptography, dnspython, ecdsa, email-validator, urllib3, certifi, chardet, requests, maxminddb, geoip2, geojson, typing, promise, rx, graphql-core, graphql-relay, graphene, iso8601, singledispatch, graphene-sqlalchemy, pytz, icalendar, jsonschema, markupsafe, jinja2, cycler, kiwisolver, numpy, matplotlib, msgpack-python, pynacl, bcrypt, paramiko, pluginbase, psycopg2, pyotp, python-pam, PyYAML, requests-file, smoke-zephyr, termcolor, tzlocal, websocket-client, XlsxWriter
  Found existing installation: blinker 1.3
Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
ERROR: Failed to install python requirements with pip
root@user:/opt/king-phisher/tools$ "

**Comment by zeroSteiner** [comment]
We did not suggest that you reinstall blinker, only that you use `apt remove` to uninstall it. Leave it uninstalled and then run the King Phisher install script which will then handle the necessary dependencies for you.

**Comment by killercoderz4** [comment]
i have the same issue. i both uinstalled and purged it and it failed to install. i use ubuntu 16.04

**Comment by killercoderz4** [comment]
i have fixed it . it installed smoohtly.t hanks. only issue is it removes all css when i run it. it says error in css parser. when i run the client , i get such error mesages

**Comment by GrineUlf** [comment]
I have had this problem often enough, just use sudo apt-get remove python3.6 and then run the install.sh script again. This will re-install python3.6 and blinker along with it.

**Comment by zeroSteiner** [comment]
@killercoderz4 if you're having a theme related issue can you please open a separate issue to track it? We try to keep the issues on topic in regards to the original post so this information is organized for other users who may be experiencing the same issue. When you do open the issue, please be sure to fill out **all** of the information in the issue template. Thanks!
