### ISSUE TITLE
Password complexity chart

### ISSUE THREAD

**Issue by rami418** [securestate/king-phisher#304]
Hi,

I didn't found the answer to my question on the wiki:
How do you define the complexity of password ? I mean, I now have a graph which shows percentage of complex password, but I don't know what are the requirements to fall in the complex category ?

In addition, is it possible to configure those parameters ?

Thanks a lot !

**Comment by zeroSteiner** [comment]
I realized that this wasn't documented but probably should be so I added it to the wiki's [graph](https://github.com/securestate/king-phisher/wiki/Graphs#the-password-complexity-graph) page.

At this time there is no way to change the complexity requirements.

**Comment by rami418** [comment]
Thanks for this answer. Very appreciated :)
