### ISSUE TITLE
ReadTheDocs 4.2.2

### ISSUE THREAD

**Issue by ninedeaths** [securestate/king-phisher#307]
ClientOptionPort is not a valid option for client "plugins" on ReadTheDocs 4.2.2 for KingPhisher.

**Comment by zeroSteiner** [comment]
I don't understand the issue.

* It's defined here in [king_phisher/client/plugins.py](https://github.com/securestate/king-phisher/blob/8dceb379f8ab4325e20a584770a7ec25f405082b/king_phisher/client/plugins.py#L294-L303) (Latest commit in master as of the time of this writing)
* It's documented [here](https://king-phisher.readthedocs.io/en/latest/king_phisher/client/plugins.html#king_phisher.client.plugins.ClientOptionPort).

**Comment by zeroSteiner** [comment]
It's even used in the [hello_world.py plugin](https://github.com/securestate/king-phisher-plugins/blob/5ec9b7a209a85fc0499d5478e30c92d865c60870/client/hello_world.py#L43-L48).
