### ISSUE TITLE
Question with Inline Images

### ISSUE THREAD

**Issue by smscjim** [securestate/king-phisher#309]
I am creating some html emails using the Inline Image feature.  This works flawlessly every time but I'm wondering if its possible to to include the client.last_name and client.first_name as variables in the inline image.  

For example:
{{ inline_image('var/www/images/Smith, John.jpg' }}
works every time...

but if I change it to this:
{{ inline_image('var/www/images/{{client.last_name}}, {{client.first_name}}.jpg') }}

I get an error when sending saying
Missing required file: 'var/www/images/{{client.last_name}}, {{client.first_name}}.jpg'

I can make this work if I dont use the Inline Image and just use:
img src="http://www.landingpage.com/images/{{client.last_name}}, {{client.first_name}}.jpg?id={{client.message_id}}"

but img src doesn't always show the image and requires action by the recipient to display the image.  It would be great if I could get the inline image to work instead of using img src.

What am I doing wrong or is what I'm asking not possible?

**Comment by zeroSteiner** [comment]
This is a super interesting question and I originally thought it wasn't going to be possible but it turns out it is.

Give this a shot:
```
{{ inline_image("/var/www/images/" ~ client.last_name ~ ", " ~ client.first_name ~ ".jpg") }}
```

That should load a picture at: `/var/www/images/Liddle, Alice.jpg` for user Alice Liddle.

The general idea is once you're in a Jinja expression (as started by `{{`) you don't want to start another one. You instead should be concatenating the strings with your variables using Jinja's `~` operator, for which documentation can be found [here](http://jinja.pocoo.org/docs/2.10/templates/#other-operators).

**Comment by smscjim** [comment]
Ok!

I added the line you suggested exactly... but now when sending the email I get a error messages saying 
Missing required file: '/var/www/images/Liddle, Alice.jpg'
?
maybe I have an older version of jinja???

**Comment by zeroSteiner** [comment]
So it renders the template in an effort to check the state of things. If you create that file, it'll be enough to bypass that check. You'll be on your own from there though and it'll have an issue if one of the images for a target is not at the specified path.

**Comment by zeroSteiner** [comment]
Yeah... so after I looked at this more it's looking like it's not going to work. While it's possible to set variables in the template and pass them to functions like `inline_image`, the way we're processing messages right now handles all of the attachments once at the start of the sending phase. So even though the Jinja templating component is working, this means that when the message goes out, it's going to have the contents from the Alice Liddle target (the one used during the analysis rendering phase). We'd have to re-analyze the message in it's entirety for each target to support this.

**Comment by smscjim** [comment]
Well I think that answers my question!   Thanks for the prompt responses!  I can just use the img src with the variables.  Thanks again!!!!
