### ISSUE TITLE
King Phisher Error JPG is Missing

### ISSUE THREAD

**Issue by JannisFreimann** [securestate/king-phisher#311]
## Environment Details

Host OS: root
King Phisher Version: 

## Error Details / Stack Trace

Missing required file: '/root/phish_one.jpg'
Missing required file: '/root/phish_two.jpg'

JPG is Missing? o.O

**Comment by wolfthefallen** [comment]
@JannisFreimann can you please completely fill out the issue template.

To better support you, I need to know what you are doing to cause the issue to occur and if it is in the King Phisher Client or the Server.

**Comment by JannisFreimann** [comment]
https://i.gyazo.com/6f9e49fe5ce23d9d9b5f42ab3feca413.png
https://i.gyazo.com/8158a9aea30bb3c30b01fcdaf40a21d3.png
https://i.gyazo.com/9dcdb80a236132bf4db1c92a109e0506.png

**Comment by wolfthefallen** [comment]
can you please describe what you are doing when you are getting the `missing required file` issue and if it is the client or server logs.

**Comment by JannisFreimann** [comment]
Ah, sorry^^

https://i.gyazo.com/dec0ffb970a08d3a5c8858029ab7d86d.png

**Comment by wolfthefallen** [comment]
Your phishing message contains embedded images, when you try to send the message King Phisher is trying to the email together it is unable to locate the images that where originally located at the pathing you being presented to you. You can either move/copy the images back to their location when you first put the email together, remove and put the images back in with their new pathing, or remove the embedded images from the message.

**Comment by JannisFreimann** [comment]
I dont need the Images.

You can either move/copy the images back to their location when you first put the email together, remove and put the images back in with their new pathing, or remove the embedded images from the message.

How? I not can good speak english. Can you german?^^

**Comment by wolfthefallen** [comment]
Unfortunately I cannot speak German. 

Open your edit tab
Look through the email for any `{{ inline_image(' ') }}` tags and remove them since you do not need the images.

**Comment by JannisFreimann** [comment]
What edit tab of email?^^

email.html ?

**Comment by wolfthefallen** [comment]
![image](https://user-images.githubusercontent.com/9035933/43097644-b23d123c-8e8a-11e8-9251-3c42dce00b9e.png)

**Comment by JannisFreimann** [comment]
Next Error
https://i.gyazo.com/27699180a94f39bfe2af7ebf83449793.png

**Comment by wolfthefallen** [comment]
You need to configure your King Phisher Client to use an SMTP server to send the email. https://github.com/securestate/king-phisher/wiki/Getting-Started#smtp-server

You can access your King Phisher Configuartion window by clicking the file menu edit > preferences
once the window is open select the SMTP Server tab then update your settings
![image](https://user-images.githubusercontent.com/9035933/43103560-85a57874-8e9c-11e8-84d2-7de737ecdb1b.png)

**Comment by wolfthefallen** [comment]
You need to put in your SMTP server information.

**Comment by JannisFreimann** [comment]
What? All is full

SMTP = localhost:22
SMTP Username = root

**Comment by wolfthefallen** [comment]
King Phisher does not come with its own SMTP Server, so you need to provide it the information of the SMTP Server that you are going to use to send the email.

**Comment by JannisFreimann** [comment]
How i can create a SMTP Server? :)

**Comment by wolfthefallen** [comment]
setting up an SMTP server is out of the scope we support for King Phisher. There are plenty guides that you can find online on how to setup a SMTP Server.

**Comment by zeroSteiner** [comment]
I'm going to close this issue out since it has moved to requesting support well beyond the scope of the original question. Moving forward I highly recommend that you read the [King Phisher Wiki](https://github.com/securestate/king-phisher/wiki) particuarly the [FAQ page](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions). There are even [videos available](https://github.com/securestate/king-phisher/wiki/Videos#how-to-videos) to help you get started and perform the basic tasks.

Finally if you open an issue again in the future, please remember to fill out the entire form so we can assist you more quickly. Thanks.
