### ISSUE TITLE
install error kali linux

### ISSUE THREAD

**Issue by slumpdgod** [securestate/king-phisher#312]
## Issue Description
I am very new to this and when I try to install king-phisher server I get an error that I can't find a solution to.

## Reproduction Steps
root@theslumpgod:~# wget -q https://github.com/securestate/king-phisher/raw/master/tools/install.sh && \
> sudo bash ./install.sh
INFO: Linux version detected as Kali
Install and use PostgreSQL? (Highly recommended and required for upgrading) [Y/n] y
INFO: Will install and configure PostgreSQL for the server
INFO: Attempting to update apt-get cache package information
Reading package lists... Done
INFO: Downloading and installing the King Phisher server to /opt/king-phisher
Installing Kali dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package pkg-config is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python3-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libfreetype6-dev
E: Package 'python3-dev' has no installation candidate
E: Unable to locate package python3-pip
E: Package 'pkg-config' has no installation candidate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libpq-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package gir1.2-webkit-3.0
E: Couldn't find any package by glob 'gir1.2-webkit-3.0'
E: Couldn't find any package by regex 'gir1.2-webkit-3.0'
E: Unable to locate package libgeos++-dev
E: Couldn't find any package by regex 'libgeos++-dev'
E: Unable to locate package libgtk-3-dev
E: Package 'libpq-dev' has no installation candidate
E: Package 'libpq-dev' has no installation candidate
ERROR: Failed to install dependencies with apt-get

## Environment Details

Host OS: Kali GNU
King Phisher Version: 1.7.1

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by wolfthefallen** [comment]
I've been unable to reproduce this issue. 

Make sure you are connected to the internet, and you have the the correct [apt repositories for kali setup](https://docs.kali.org/general-use/kali-linux-sources-list-repositories), then make sure you have the system completely updated `apt update && apt upgrade && apt dist-upgrade`

**Comment by slumpdgod** [comment]
zerosteiner aha that is the case. cheers
