### ISSUE TITLE
KP link going to Apache default page

### ISSUE THREAD

**Issue by mother2110** [securestate/king-phisher#313]
## Issue Description
When I send a test email to myself and click on the link (Using KP Email Training Phishing template) it goes to the Apache default page 

## Reproduction Steps
Send email
Click on Link
Apache default page shows

## Environment Details

Server on Debian 9.
Client - Kali 2018.1 64bit
King Phisher Version: 1.12.0-beta (rev: 643ff93fd8ee)

## Error Details / Stack Trace
No errors
```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
That sounds very **very** wrong. It sounds like you're using Apache instead of King Phisher. You should see a white page with black and grey text that looks generic. Nothing that says Apache unless you changed it yourself.

I would double check that you're actually running the King Phisher server and that your Target URL is set correctly.

**Comment by mother2110** [comment]
![2018-08-16_8-26-09](https://user-images.githubusercontent.com/17184373/44218314-4dc31c00-a12e-11e8-8af4-dd0d92d072cd.png)

![image](https://user-images.githubusercontent.com/17184373/44218389-7519e900-a12e-11e8-8d16-876ee2b2eb18.png)


![image](https://user-images.githubusercontent.com/17184373/44218449-91b62100-a12e-11e8-8d52-3c26b620a5e3.png)

**Comment by zeroSteiner** [comment]
Uh well this has been closed so I'm not sure if you got if figured out or not but it looks like you need to install the King Phisher server on your Debian system and disable Apache. You logged in with the KP client so the server must be installed somewhere. It looks like the Target URL you're using isn't on the server you're connected to.

**Comment by mother2110** [comment]
Sorry. I closed this by mistake. So Apache doesn't need be running?

**Comment by zeroSteiner** [comment]
Not only does it not need to be running but it can't be running. King Phisher includes it's own HTTP server that must be used to host the landing pages. The Target URL that you use needs to resolve to the King Phisher server and a landing page it is hosting.

**Comment by mother2110** [comment]
OK, thats were I messed up. If I stop apache I cannot connect to the url. 
![image](https://user-images.githubusercontent.com/17184373/44219370-b01d1c00-a130-11e8-80a3-434d602bce33.png)

**Comment by zeroSteiner** [comment]
That's because you need to install and run the King Phisher server in place of Apache. You then need to log into that instance of the King Phisher server instead of whichever one you're currently logged into (I'm guessing it's localhost?).

When you run the installer you can use the `--skip-client` option to only install server components.

**Comment by mother2110** [comment]
Thanks, I will start over. LOL
It has been a while since I used KP.

**Comment by mother2110** [comment]
Last question then I will close this. Does Apache2 need to be installed?

![image](https://user-images.githubusercontent.com/17184373/44220540-bbbe1200-a133-11e8-975d-33417ea0ea9c.png)

**Comment by zeroSteiner** [comment]
No, you can remove it entirely if you'd like. There is no dependency on Apache. If you leave it installed both Apache and King Phisher just can not be running at the same time, one must be disabled unless you are binding to odd ports.

**Comment by zeroSteiner** [comment]
Oh I see you're trying to use LetsEncrypt. King Phisher is compatible with that and we provide a wrapping script to help you use it. You can find it at `tools/certbot_wrapper.py`. The script helps setup the options and get the configuration information for the King Phisher server.

**Comment by mother2110** [comment]
Thanks, I was using this guide to install it.

https://www.sw1tch.net/2018/07/09/king-phisher-setup/

**Comment by mother2110** [comment]
Can you give an example of how to use certbot_wrapper.py?

**Comment by mother2110** [comment]
So I reinstalled the server without Apache2 and get the same default Apache2 webpage.

**Comment by zeroSteiner** [comment]
Does the apache2 page exist in your webroot? Is it possible that it stayed and King Phisher is now serving it?

**Comment by mother2110** [comment]
I reinstall on Ubuntu server instead of Debian. Hopefully, it will work.
