### ISSUE TITLE
KP still hitting Apache default page.

### ISSUE THREAD

**Issue by mother2110** [securestate/king-phisher#315]
## Issue Description
I know I am probably getting annoying at this point but I am at a loss. 
I installed Ubuntu 16.04 with no Apache at all. Set up everything and was able to connect and send a test phish email.
![image](https://user-images.githubusercontent.com/17184373/44239938-b0d5a280-a170-11e8-813e-d21be732b025.png)

![image](https://user-images.githubusercontent.com/17184373/44239906-8edc2000-a170-11e8-9abd-60121123da88.png)

When I click on the link I get this...

![image](https://user-images.githubusercontent.com/17184373/44239972-d5ca1580-a170-11e8-8f47-50865629633a.png)

## Reproduction Steps
1. Start King Phisher
2. Send test email

## Environment Details

Host OS: Ubuntu 16.04 
Client OS: Kali 2018.1
King Phisher Version: 1.12.0-beta

## Error Details / Stack Trace
No errors
```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by mother2110** [comment]
Something I am doing is installing Apache in the background.

**Comment by zeroSteiner** [comment]
So is the Target URL your King Phisher server? Also what does the 404 page look like? It's still possible that King Phisher is serving the Apache page I guess.
