### ISSUE TITLE
Still get Apache default page

### ISSUE THREAD

**Issue by mother2110** [securestate/king-phisher#316]
## Issue Description
Installed KP according to KP guide. Everything seems to install fine but when I click on the email link I get sent to Apache default page. I did install python-certbot-apache which I think is installing Apache. 

![image](https://user-images.githubusercontent.com/17184373/44420639-543d0380-a533-11e8-8cab-cd3a436ef950.png)

![image](https://user-images.githubusercontent.com/17184373/44420585-32438100-a533-11e8-9769-43de2ba8dff6.png)

## Reproduction Steps
1. Start King Phisher
2. Send a test email
3. Click on link and get a default Apache page.

## Environment Details

Host OS: Ubuntu 16.04
King Phisher Version: 1.12.0-beta

## Error Details / Stack Trace
No errors
```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
So if you use netstat, can you confirm what process is running on port 80 / 443 so we can identify if it is in fact Apache or King Phisher?

**Comment by mother2110** [comment]
netstat -antl
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN     
tcp        0    208 172.40.1.196:22         172.40.1.20:57200       ESTABLISHED
tcp        0      0 127.0.0.1:58060         127.0.0.1:443           ESTABLISHED
tcp        0      0 172.40.1.196:22         172.40.1.20:57252       ESTABLISHED
tcp        0      0 127.0.0.1:443           127.0.0.1:58060         ESTABLISHED
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 ::1:5432                :::*                    LISTEN     
tcp6       0      0 :::80                   :::*                    LISTEN     
tcp6       0      0 ::1:5432                ::1:37616               ESTABLISHED
tcp6       0      0 ::1:37616               ::1:5432                ESTABLISHED

**Comment by mother2110** [comment]
Port 443 is already taken by a vpn server. I just want to use port 80

**Comment by zeroSteiner** [comment]
Please use `sudo netstat -lntp` so we can see the programs.

And I'm confused if 443 is already taken, then what port are you trying to use the cert from certbot with?

**Comment by mother2110** [comment]
4443

**Comment by mother2110** [comment]
Do I need to specify 4443 when running certbot-wrapper.py?

**Comment by zeroSteiner** [comment]
No, as long as 80 is open I'm pretty sure it'll work. Also how about that `sudo netstat -lntp` output?

**Comment by mother2110** [comment]
sudo netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      991/sshd        
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1187/postgres   
tcp        0      0 0.0.0.0:4443            0.0.0.0:*               LISTEN      2116/python3    
tcp6       0      0 :::22                   :::*                    LISTEN      991/sshd        
tcp6       0      0 ::1:5432                :::*                    LISTEN      1187/postgres   
tcp6       0      0 :::80                   :::*                    LISTEN      1880/apache2

**Comment by mother2110** [comment]
As you can see port 80 is not running. How do I start it?

**Comment by zeroSteiner** [comment]
Okay, that's definitely showing that you have apache running. You need to kill that service and start King Phisher in it's place. I also recommend that you disable the apache service so it doesn't start again on reboot.

**Comment by mother2110** [comment]
If I kill Apache then the web page does not load.
![image](https://user-images.githubusercontent.com/17184373/44422128-32458000-a537-11e8-84be-f77a2d24b41c.png)

**Comment by zeroSteiner** [comment]
Yeah that's because you need to start King Phisher in it's place. Start the King Phisher service which includes it's own HTTP server.

**Comment by mother2110** [comment]
sudo service king-phisher status
● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-08-21 11:30:42 PDT; 14min ago
  Process: 2075 ExecStop=/bin/kill -INT $MAINPID (code=exited, status=0/SUCCESS)
  Process: 2109 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml (code=exited, status=0/SUCCESS)
 Main PID: 2116 (python3)
    Tasks: 4
   Memory: 89.8M
      CPU: 2.918s
   CGroup: /system.slice/king-phisher.service
           ├─2116 /usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml
           └─2167 /usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml

Aug 21 11:30:40 phishy systemd[1]: Starting King Phisher Server...
Aug 21 11:30:42 phishy su[2118]: Successful su for postgres by root
Aug 21 11:30:42 phishy su[2118]: + ??? root:postgres
Aug 21 11:30:42 phishy su[2118]: pam_unix(su:session): session opened for user postgres by (uid=0)
Aug 21 11:30:42 phishy su[2135]: Successful su for postgres by root
Aug 21 11:30:42 phishy su[2135]: + ??? root:postgres
Aug 21 11:30:42 phishy su[2135]: pam_unix(su:session): session opened for user postgres by (uid=0)
Aug 21 11:30:42 phishy systemd[1]: king-phisher.service: PID file /var/run/king-phisher.pid not readable (yet?) after start: No such file or directory
Aug 21 11:30:42 phishy systemd[1]: Started King Phisher Server.

It is running

**Comment by zeroSteiner** [comment]
Is it bound to port 80 now (as verified with netstat again)? If not restart it, and if it's still not then show us your configuration file. Just make sure to take out the database connection string which contains a password.

**Comment by mother2110** [comment]
sudo netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      991/sshd        
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1187/postgres   
tcp        0      0 0.0.0.0:4443            0.0.0.0:*               LISTEN      2551/python3    
tcp6       0      0 :::22                   :::*                    LISTEN      991/sshd        
tcp6       0      0 ::1:5432                :::*                    LISTEN      1187/postgres

**Comment by zeroSteiner** [comment]
Ok so there you go, it's listening on port 4443 not 80.

**Comment by mother2110** [comment]
cat server_config.yml 
#
# King-Phisher Server Configuration
#
# Configuration options can also be loaded from other files using:
#   !include path/to/file.yml
# This allows the main file to be broken up into smaller parts if necessary

logging:
  console:
    # Whether or not to enable console-based logging and use the configuration options within this section
    enabled: true
    # See https://docs.python.org/3/library/logging.html#logrecord-attributes for available attributes
    format: '%(levelname)s %(message)s'
    # Available levels: FATAL, ERROR, WARNING, INFO, DEBUG
    level: warning

  file:
    # Whether or not to enable file-based logging and use the configuration options within this section
    enabled: true
    # See https://docs.python.org/3/library/logging.html#logrecord-attributes for available attributes
    format: '%(asctime)s %(name)-50s %(levelname)-8s %(message)s'
    # Available levels: FATAL, ERROR, WARNING, INFO, DEBUG
    level: warning
    # Location to store the log file
    path: /var/log/king-phisher.log

server:
  # Bind address information, multiple ports can be
  addresses:
    - host: 0.0.0.0
      port: 4443
      ssl: true

  # Server RPC authentication related settings
  #authentication:
    # How long to cache authentication information in the server process
    #cache_timeout: 10m
    # Require authenticating users to be a member of the specified group
    #group: king-phisher
    # The service to use for PAM authentication
    #pam_service: sshd
    # How long an authenticated RPC session should be valid for after no requests have been received.
    #session_timeout: 30m

  # A header to retrieve the client's IP from, useful when a proxy is in place
  #client_ip_header: X-Real-IP

  # The name of the cookie used to track users
  cookie_name: KPID

  # Specify an additional search path for server data files
  data_path: /opt/king-phisher

  # The SQLite3 database file to use, the folder needs write permissions
  # WARNING: SQLite3 is not fully supported as of version 0.1.6, see
  # https://github.com/securestate/king-phisher/wiki/Database#sqlite for more
  # details
  #database: sqlite:////var/king-phisher/king-phisher.db

  # The PostgreSQL database to use
  database: postgresql://king_phisher:

  # Fork the server process into the background
  fork: true

  geoip:
    # The location of the GeoLite2 City database
    database: /var/king-phisher/geoip.mmdb

  # Additional headers to include in HTTP responses
  headers:
    - "Referrer-Policy: no-referrer"
    - "X-Content-Type-Options: nosniff"
    - "X-Frame-Options: DENY"
    - "X-XSS-Protection: 1; mode=block"

  # Set a file to write the PID to
  pid_file: /var/run/king-phisher.pid

  # Add additional search paths for plugin directories
  #plugin_directories:
  #  - /some/plugin/path
  # List the plugins that need to be enabled
  #plugins:
  #  # The plugin to enable's name
  #  some_plugin:
  #    # An option specific to this particular plugin
  #    value_for_some_plugin: true

  # Require an ID associated with a campaign to load pages
  require_id: true

  rest_api:
    enabled: false
    # Networks which are authorized to use the REST API
    networks:
      - 10.0.0.0/8
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
    # When null the token will be randomized at run time
    token: null

  # Configure the server header value
  #server_header: Apache/2.4.9 (Unix)

  # Set the opened timestamp on the first visit if it's null
  set_message_opened_on_visit: true

  # Drop privileges to the specified user
  setuid_username: nobody

  # Default SSL certificate settings
  ssl_cert: /etc/letsencrypt/live/name.com/fullchain.pem
  ssl_key: /etc/letsencrypt/live/name.com/privkey.pem

  # Hostname specific SSL certificates can be added below
  #ssl_hosts:
  #  - host: www.king-phisher.com
  #    ssl_cert: /path/to/www.king-phisher.com/ssl.crt
  #    ssl_key: /path/to/www.king-phisher.com/ssl.key

  # Configure the image file name used to track opened emails
  tracking_image: email_logo_banner.gif

  # Use subfolders in the web_root which correspond to server hostnames, for
  # example if the server's hostname is king-phisher.lan, then the web root for
  # http://king-phisher.lan would be /var/www/king-phisher.lan
  vhost_directories: false

  # The root directory from which page content and templates are served from
  web_root: /var/www/

**Comment by zeroSteiner** [comment]
So what are you trying to accomplish? It looks like you have it successfully running on 4443 with SSL. Is that what you want, or do you want it on 80 without SSL, both?

**Comment by mother2110** [comment]
Still, when I set to port 80, then the client will not connect to the web server...

![image](https://user-images.githubusercontent.com/17184373/44422829-1b079200-a539-11e8-82bd-91120661620b.png)

**Comment by mother2110** [comment]
sudo netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      991/sshd        
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1187/postgres   
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2716/python3    
tcp6       0      0 :::22                   :::*                    LISTEN      991/sshd        
tcp6       0      0 ::1:5432                :::*                    LISTEN      1187/postgres

**Comment by mother2110** [comment]
Do I have the certs wrong on the server_config?

**Comment by zeroSteiner** [comment]
You need to setup your configuration to run on both port 80 without a cert and on 4443 with a cert if that's what you want. It should look like the following, notice the two entries one for 80 and another for 4443.
```
server:
  addresses:
    - host: 0.0.0.0
      port: 80
      ssl: false
    - host: 0.0.0.0
      port: 4443
      ssl: true
```
Then after you have that, read [this section](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#im-getting-a-404--error-page-on-the-server) of the FAQ on why you're getting a 404.

**Comment by mother2110** [comment]
I tried that and still the same. 

![image](https://user-images.githubusercontent.com/17184373/44425248-2611f080-a540-11e8-8326-7fb0ae8af821.png)

sudo netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      982/sshd        
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1185/postgres   
tcp        0      0 0.0.0.0:4443            0.0.0.0:*               LISTEN      1437/python3    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1437/python3    
tcp6       0      0 :::22                   :::*                    LISTEN      982/sshd        
tcp6       0      0 ::1:5432                :::*                    LISTEN      1185/postgres   

ls /var/www
html  images  include  sorry.html  trained.html  verify.html

**Comment by zeroSteiner** [comment]
Set `require_id` to false in your server config. Restart the server and then restart the client too (just the King Phisher software for both, not the whole OS unless you want to).

**Comment by mother2110** [comment]
WARNING  verify url HTTP error: 404 Not Found

This is killing me. I may try to start over. I remember KP being easy to install.

When I ran certbot-wrapper.py the first time, it said it could not find the binary. Can you tell me where to get the proper binary to run this? I don't want to use python-certbot-apache.

**Comment by wolfthefallen** [comment]
Your `Web Page Url` needs to be set to your landing page for the campaign. So if your King Phisher Server is running on port 80, and you have your landing page, lets say index.html in your webroot ( Generally `/var/www` and you have your A record pointed to your server. It should look like 'http://thedomain.com/index.html`

**Comment by mother2110** [comment]
![picards-facepalm-facebalm](https://user-images.githubusercontent.com/17184373/44426551-c1f12b80-a543-11e8-8952-8bb6dac00cf2.gif)

I am a freaking moron! That was it. I did not add the verify.html in the campaign, I do not belong in IT.

Thanks for putting up with this.
