### ISSUE TITLE
Help with Error

### ISSUE THREAD

**Issue by bobscaggs** [securestate/king-phisher#318]
## Issue Description
I experience an issue when I start the client.

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Linux kali 4.9.0-kali2-amd64 #1 SMP Debian 4.9.10-1kali1 (2017-02-20) x86_64 GNU/Linux
King Phisher Version: 1.11.1

## Error Details / Stack Trace

```
Error Type: builtins.AttributeError
Error Details: AttributeError("'NoneType' object has no attribute 'get'",)
Error UID: 8bb4fddd-39dc-4cfa-ab39-4dc043a60d57
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.11.1 (rev: 0d6c0c19f0c2)
Platform Version: Linux: Kali kali-rolling kali-rolling
Python Version: 3.6.6
Gtk Version: 3.22.30
Timezone: Etc/UTC

Thread Information:
 => MainThread (alive=True daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/client/application.py", line 401, in do_activate
    self.main_window = main.MainAppWindow(self.config, self)
  File "/opt/king-phisher/king_phisher/client/windows/main.py", line 251, in __init__
    mailer_tab = MailSenderTab(self, self.application)
  File "/opt/king-phisher/king_phisher/client/tabs/mail.py", line 1132, in __init__
    config_tab = MailSenderConfigurationTab(self.application)
  File "/opt/king-phisher/king_phisher/client/tabs/mail.py", line 869, in __init__
    super(MailSenderConfigurationTab, self).__init__(*args, **kwargs)
  File "/opt/king-phisher/king_phisher/client/gui_utilities.py", line 684, in __init__
    self.objects_load_from_config()
  File "/opt/king-phisher/king_phisher/client/tabs/mail.py", line 917, in objects_load_from_config
    super(MailSenderConfigurationTab, self).objects_load_from_config()
  File "/opt/king-phisher/king_phisher/client/gui_utilities.py", line 763, in objects_load_from_config
    value = self.config.get(config_name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by zeroSteiner** [comment]
Please completely fill out the issue template. We need all of the details that it requests to better identify the issue and provide the help that you are requesting. Please do not open a new issue but instead just edit this one and fill out all of the details.

**Comment by bobscaggs** [comment]
Sorry.... edited issue.

**Comment by zeroSteiner** [comment]
If it's occurring on startup, it sounds like your config file might have been corrupted. Try running `mv ~/.config/king-phisher/config.json ~/.config/king-phisher/config.bk.json` and then restarting the client with [verbose logging](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-generate-verbose-logging-output).

If that doesn't fix the issue, post the results of the verbose logging.

**Comment by bobscaggs** [comment]
Yes, that was it.  I had edited the config.json manually to add ssh_preferred_key value.  Is there a way to do that without corrupting the file?  I am using the client to connect to an AWS EC2 instance and have to use the provided SSH key.

**Comment by zeroSteiner** [comment]
No, if you need to specify the `ssh_preferred_key` value, you need to do it manually and ensure that the result is still proper JSON. That particular option isn't exposed through the GUI since it's required before authentication. Make sure you have a trailing comma. There should be tools online that can validate your JSON data.

**Comment by bobscaggs** [comment]
Fixed!!!  I left out the quotes around the value.  Thanks for your help.
