### ISSUE TITLE
Gather IP info from Message Views

### ISSUE THREAD

**Issue by mozg31337** [securestate/king-phisher#32]
Hi

It would be useful to integrate the details of the IP addresses of users who open phishing emails, just like what is currently done from site views.

Cheers

Andrei

**Comment by zeroSteiner** [comment]
Sounds good to me. It will require a change to the DB schema to store this information, but you have good timing because I have changes planned for the next version so I'll just add this in as well.

**Comment by mozg31337** [comment]
Hi, 

It might be also a good idea to collect the stats on the email clients that open the emails, just like you do with user browsers that visit the site. Just a thought ). Not sure if this is feasible or not. 

Andrei 

----- Original Message -----

**Comment by zeroSteiner** [comment]
That's also a good idea. For a while I had been considering that as well and when you brought up the IP I remembered it so I added the changes necessary for the user agent to the database too.

**Comment by zeroSteiner** [comment]
So, status update: The changes for this are officially in the `dev` branch. It will be awhile before they are in master but the code is all written and the database changes have been made. Thanks for the feature request.

**Comment by zeroSteiner** [comment]
And now the changes are in the master branch as part of v0.3.0-beta. The information is available under the View Campaign > Messages tab, there are now "Opener IP Address" and "Opener User Agent" columns. The new server logs this information so it wont be available retro-actively, but moving forward new campaigns will log that information.

Thanks for the feature request!
