### ISSUE TITLE
Client Campaign configuration values should load/save with campaign

### ISSUE THREAD

**Issue by bobscaggs** [securestate/king-phisher#320]
# Feature Description
When a campaign is opened in the client the only configuration value that is populated from a saved value seems to be the "Company Name".  It would be nice to have all of the configuration values load and save with campaigns.  Ex: Web Server URL,Source Email, Friendly Alias, Subject, Message HTML File.

## Example Use Case
Each time you switch campaigns and especially so when running multiple campaigns fo varying types and configuration for multiple clients.

**Comment by wolfthefallen** [comment]
@bobscaggs 

There is a plugin for King Phisher that does just this! 
The plugin you are looking for is Campaign Message Configuration.
You can install and enable the plugin through the plugin manager.
