### ISSUE TITLE
Can the mailer send Multipart Mime type messages?

### ISSUE THREAD

**Issue by bobscaggs** [securestate/king-phisher#321]
# Feature Description
I want to send Multipart messages for text and HTML mail readers.  Is there a way to do this that I am missing?

## Alternatives Solutions
I created two separate email templates one for HTML and one for text.  This is not really the best and only works when you know the client's email viewer type

## Example Use Case
Sending an email that is formatted for the client's email viewer.

**Comment by wolfthefallen** [comment]
@bobscaggs 

By default the client does multipart messages. Currently it sets a generic message in the text part of the email stating you need an HTML enabled email client to view the message. 

There are currently two plugins that change the plain text part of the message. They are message padding, and message plaintext.

Message Padding plugin will add random sentences to the text part of the email to decrease its spam score. Very helpful when trying to get your phish through a paranoid email filter.

Message Plaintext plugin will convert your html message to plain text for you.

Hope that helps. Unfortunately at this time there is not a plugin that allows to select another template just for the text part of the email. But if you want to create a plugin (I would probably base it off of the message padding one) we accept PRs into the [King-Phisher-Plugins](https://github.com/securestate/king-phisher-plugins) repository.

**Comment by zeroSteiner** [comment]
I would add it as a feature to the existing `message_plaintext.py` plugin. That way the functionality is together.
