### ISSUE TITLE
Crashes when using X Forwarding

### ISSUE THREAD

**Issue by fmagin** [securestate/king-phisher#322]
## Issue Description
First off I am aware that X Forwarding is not officially supported, but given issues I am encountering when trying to connect with a client to a server on a different machine I am using this as a workaround. Will try to debug the other issues more and potentially open an issue for them too.
This issue can be worked around too if being careful so it is mostly just annoying.

## Reproduction Steps
1. Start King Phisher on Server
2. Login to machine with SSH X Forwarding (`ssh kp-host -X` or in my case `vagrant ssh -- -X`)
3. Start the King Phisher Client on that host, the window should appear on the X Server of the machine that connected to the KP Host 
4. In any field, for example the host/sshuser/sshpass in the connection dialog, press backspace when there are no letters left to remove, or move the cursor to the left/right when already at the left/right end of the field

## Environment Details

Host OS: Ubuntu 18.04 LTS (ubuntu/bionic64 from vagrant)
KingPhisherServer Version: 1.12.0-beta (rev: cd3f42f3a545)

The machine that is originating the SSH connection and rendering the actual window is a current Arch Linux
## Error Details / Stack Trace

The client runs with `-L DEBUG` but because it crashes instantly it cant log anything and the only thing that is shown on stdout after trigger the crash is:
```
(KingPhisher:3259): Gdk-ERROR **: 13:28:36.975: The program 'KingPhisher' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 1736 error_code 10 request_code 104 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)
```

**Comment by zeroSteiner** [comment]
Sorry but we don't support X11 forwarding. You need to install the King Phisher client on your system. We offer a [Windows Build](https://github.com/securestate/king-phisher/releases) and there's a version for [OS X via docker](https://github.com/securestate/king-phisher/tree/master/tools/mac_client).

**Comment by fmagin** [comment]
Fair enough, ran into some connection issues with that setup so I will write up an issue for those soon. The thing that confused me is that X forwarding should just work and that this is a pretty hard crash so maybe this issue lies outside of king phisher.
