### ISSUE TITLE
GraphQL error on startup

### ISSUE THREAD

**Issue by nullpainter** [securestate/king-phisher#326]
## Issue Description
When starting KingPhisher client, an error dialog appears. Cancelling allows messages to be sent, however the View Campaign tab, and campaign selection freezes.

I haven't tried a fresh installation, but a fresh installation on a different OS (Windows Server 2012) seems fine.

## Reproduction Steps
1. Start King Phisher (error appears)

## Environment Details

Host OS: Windows 10
King Phisher Version: 1.11.0

## Error Details / Stack Trace

Stack trace in client:

```
Error Type: king_phisher.errors.KingPhisherGraphQLQueryError
Error Details: KingPhisherGraphQLQueryError()
Error UID: 9da2cdc6-239c-44ce-91d6-083a91218548
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.11.0
Platform Version: Windows: 10 10.0.16299  Multiprocessor Free (Frozen=True)
Python Version: 3.4.4
Gtk Version: 3.18.9
Timezone: Pacific/Auckland

Thread Information:
    Thread-12 (alive=True daemon=True)
 => MainThread (alive=True daemon=False)
    Thread-7 (alive=True daemon=True)
    Thread-6 (alive=True daemon=True)
    Thread-2 (alive=True daemon=True)
    Thread-13 (alive=True daemon=True)
    Thread-1 (alive=True daemon=False)

Stack Trace:
Traceback (most recent call last):
  File "C:\king-phisher\king_phisher\client\gui_utilities.py", line 123, in wrapper
  File "C:\king-phisher\king_phisher\client\tabs\campaign.py", line 597, in <lambda>
  File "C:\king-phisher\king_phisher\client\graphs.py", line 332, in refresh
  File "C:\king-phisher\king_phisher\client\graphs.py", line 417, in _get_graphql_campaign_cache
  File "C:\king-phisher\king_phisher\client\client_rpc.py", line 205, in graphql
king_phisher.errors.KingPhisherGraphQLQueryError

```

Possibly related (?) logs on the server:

```
2018-10-10 02:35:07,674 graphql.execution.utils                            ERROR    graphql.error.located_error.GraphQLLocatedError: The address 103.101.42.253 is not in the database.
```

**Comment by zeroSteiner** [comment]
So that line down there from the server logs... can you please include some lines around it for more context? It does look related but it'd help more if I knew what was going on when that happened. It would also be super helpful if the log level was [set to debugging](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-generate-verbose-logging-output).

**Comment by nullpainter** [comment]
> can you please include some lines around it for more context? 

The only lines around it are the exact same error - no other errors or information. Will change log level presently.

**Comment by nullpainter** [comment]
I can replicate on the fresh install.

For the fresh install, the same / similar error appears as soon as an email is sent and the site visited. Once that occurs, the same error occurs on startup and the campaign can't be viewed.

Unfortunately, this is a significant blocker for us. Do you know of a workaround for now?

**Comment by zeroSteiner** [comment]
That makes sense, I'm pretty sure this is a server side error. I don't know of a workaround off hand but may be able to get a patch together in the next day or two.

**Comment by nullpainter** [comment]
Thanks for that; appreciated. To keep options open, do you have a feel roughly which version this may have been introduced? I can always install an earlier version and create a new database if needs be.

**Comment by nullpainter** [comment]
> Well what server version are you running?

That would have been useful for me to include. I seem to inadvertently be running `1.12.0-beta`.

I haven't updated my geoip database. I didn't even think it was a standalone database - `geoip.py` seems to download it itself?

The most sensible approach for me is to download `1.11.0`.

**Comment by nullpainter** [comment]
> Also have you updated your geoip database? I'm wondering if that's the database it's complaining about.

Bingo. I bodged in a temporary call to ` download_geolite2_city_db(database_file)` inside `init_database` and that seems to have done the trick. So, the issue definitely is as I was starting to suspect - missing IP address in geoip database isn't being handled gracefully.

**Comment by zeroSteiner** [comment]
That's a good point, I'll add a note into the [Updating King Phisher](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher) wiki page.

**Comment by zeroSteiner** [comment]
Quick update on this, I was able to reproduce the error. I then got side tracked on adding relevant details regarding the GraphQL exception to the error dialog so in the future it won't be so cryptic. I'd say I'll have a patch for this tonight but my schedule is a bit crazy right now but expect a formal fix in the next couple days at least.

**Comment by nullpainter** [comment]
Nice work. The pressure is off for me, so no panic from my perspective, at least 😄
