### ISSUE TITLE
Arbitrary Extra Data per Target

### ISSUE THREAD

**Issue by fmagin** [securestate/king-phisher#327]
# Feature Description

Arbitrary data for targets would allow adapting to arbitrary needs to also track the rank, location etc for a given target if this data is provided and should be analyzed.

If the templating engine can access this, this would also allow arbitrary flexibility in mail customization.
Naming could be solved by requiring a csv with the first lines indicating the names of each field when using a csv with more than 4 fields.

## Alternatives Solutions

My current workaround will probably be to merge the extra data I need with the company department and then split it when analyzing  the results.

## Example Use Case

Any time you need to flexibly track more fields than just name, first name, email and department for analyzing or want more specific mail customization options.

**Comment by zeroSteiner** [comment]
I talked this over with the other dev @wolfthefallen and we agree this is a good idea. Unfortunately however, we simply don't have the resources to accommodate a request of this magnitude right now. This would require non-trivial changes to both the database backend as well as the GUI and substantial documentation to be useful.

If you're interested in implementing this yourself, we do accept Pull Requests and provide pretty extensive [technical documentation](https://king-phisher.readthedocs.io/en/latest/).

**Comment by fmagin** [comment]
I would suggest  this issue to be kept open to keep track of it. If the feature is deemed useful and a PR is welcome closing it just hides it among all the other issues that are actually fixed (or deemed irrelevant). Maybe add a "help wanted" tag instead?

Closing as "wontfix" feels like the wrong message to me ( and means no one who wants to contribute will find it easily)

**Comment by zeroSteiner** [comment]
In my experience no one is scouring the issue tracker looking for opportunities to contribute. Leaving it open only clutters it for those of us that are actively engaged with the project.

Furthermore, GitHub has search support for labels, so simply using the query `label:"feature request" label:wontfix is:closed` will show [similar issues](https://github.com/securestate/king-phisher/issues?q=label%3A%22feature+request%22+label%3Awontfix+is%3Aclosed).

**Comment by zeroSteiner** [comment]
We'll leave this open until the stale bot harvests it. It's also been labeled as Help Wanted. After it's been closed by the stale bot, it can still be searched for by its label.

**Comment by True-Demon** [comment]
Just a heads-up, this issue has me interested. I can't promise I can make it a priority, but this isn't the first time this feature & similar changes have been discussed. Let me know if at some point you guys get some free time where you decide to start working on this. I may have something to provide at that time, if not completely finished. 

Besides, I can't let you guys forget about me. :smiling_imp:
