### ISSUE TITLE
issue on kali linux 2018.4

### ISSUE THREAD

**Issue by BlAd373** [securestate/king-phisher#337]
## Issue Description
I experience an issue when I... and the results I expected are...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 18.04 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```
journalctl -xe
Nov 23 15:43:59 Legion python3[22879]:     return list(lex)
Nov 23 15:43:59 Legion python3[22879]:   File "/usr/lib/python3.6/shlex.py", line 295, in __next__
Nov 23 15:43:59 Legion python3[22879]:     token = self.get_token()
Nov 23 15:43:59 Legion python3[22879]:   File "/usr/lib/python3.6/shlex.py", line 105, in get_token
Nov 23 15:43:59 Legion python3[22879]:     raw = self.read_token()
Nov 23 15:43:59 Legion python3[22879]:   File "/usr/lib/python3.6/shlex.py", line 136, in read_token
Nov 23 15:43:59 Legion python3[22879]:     nextchar = self.instream.read(1)
Nov 23 15:43:59 Legion python3[22879]: AttributeError: 'ArrayElement' object has no attribute 'read'
Nov 23 15:43:59 Legion systemd[1]: king-phisher.service: Control process exited, code=exited status=1
Nov 23 15:43:59 Legion systemd[1]: king-phisher.service: Failed with result 'exit-code'.
Nov 23 15:43:59 Legion systemd[1]: Failed to start King Phisher Server.
 
-- Unit king-phisher.service has failed.
-- 
-- The result is RESULT.
Nov 23 15:43:59 Legion sudo[21335]: pam_unix(sudo:session): session closed for user root
Nov 23 15:45:01 Legion CRON[22894]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 23 15:45:01 Legion CRON[22895]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Nov 23 15:45:01 Legion CRON[22894]: pam_unix(cron:session): session closed for user root
Nov 23 15:47:10 Legion org.gnome.Shell.desktop[1615]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x34000f8 (server_con

sudo ./KingPhisherServer -f -L DEBUG server_config.yml DEBUG    target diretory: /opt/king-phisher INFO     checking for the pipenv environment DEBUG    pipenv path: '/usr/bin/pipenv' DEBUG    pipenv Pipfile: /opt/king-phisher/Pipfile Loading .env environment variables… Traceback (most recent call last):   File "/usr/bin/pipenv", line 11, in <module>     load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()   File "/usr/lib/python3/dist-packages/pipenv/v
[15:55] <blad33> journalctl -xe Nov 23 15:43:59 Legion python3[22879]:     return list(lex) Nov 23 15:43:59 Legion python3[22879]:   File "/usr/lib/python3.6/shlex.py", line 295, in __next__ Nov 23 15:43:59 Legion python3[22879]:     token = self.get_token() Nov 23 15:43:59 Legion python3[22879]:   File "/usr/lib/python3.6/shlex.py", line 105, in get_token Nov 23 15:43:59 Legion python3[22879]:     raw = self.read_token() Nov 23 15:43:59 Legion python3[22879]:   File "/usr/lib/pytho

Linux Legion 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux
i use pipenv v11.9.0-1

**Comment by wolfthefallen** [comment]
Please try starting the King Phisher Server from the command line and provide me the full stack trace.
`sudo ./KingPhisherServer -L DEBUG -f -c server_config.yml`

**Comment by BlAd373** [comment]
sudo ./KingPhisherServer -L DEBUG -f -c server_config.yml
DEBUG    target diretory: /opt/king-phisher
INFO     checking for the pipenv environment
DEBUG    pipenv path: '/usr/local/bin/pipenv'
DEBUG    pipenv Pipfile: /opt/king-phisher/Pipfile
Loading .env environment variables…
usage: __main__.py [-h] [-v] [-L {DEBUG,INFO,WARNING,ERROR,FATAL}]
                   [--logger LOGGER] [--gc-debug-leak] [--gc-debug-stats] [-f]
                   [--update-geoip-db] [--verify-config]
                   config_file
__main__.py: error: unrecognized arguments: -c

**Comment by wolfthefallen** [comment]
sorry about that drop the `-c` and make sure `server_config.yml` is your server configuration file, and run the command from you king-phisher folder.

**Comment by BlAd373** [comment]
resolved I deleted pipenv and proceeded to / tools / install
and the problem has been solved

**Comment by wolfthefallen** [comment]
Awesome! happy phishing.

**Comment by BlAd373** [comment]
thank you
