### ISSUE TITLE
King-Phisher Client doesn't start (*nix gnome launcher fails)

### ISSUE THREAD

**Issue by GrizliK91** [securestate/king-phisher#339]
## Issue Description
King-Phisher Client doesn't start

## Reproduction Steps
1. Install  Ubuntu GNOME 16.04.4 LTS (without update)
2. Install vim, ssh, mc, open-vm-toolbox-desktop
3. Install King-Phisher with quick install (Full installation with server and client)

## Environment Details

Host OS: Ubuntu GNOME 16.04.4 LTS
King Phisher Version: 1.12.0

## Error Details / Stack Trace
King-Phisher Client doesn't start. 
Here error when i trying to start Client with command: /opt/king-phisher/KingPhisher

> /opt/king-phisher/.venv/bin/python: Error while finding spec for 'king_phisher.client' (ImportError: No module named 'king_phisher')

**Comment by zeroSteiner** [comment]
We'll need more information:

* Did the install script complete successfully?
* What's the full output with [verbose logging](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-generate-verbose-logging-output)?
* Did you clone the directory to `/opt/king-phisher` and regardless can you post a listing of the directory contents?

**Comment by GrizliK91** [comment]
Yes, install script complete successfully

`alex@kpclient:~$ /opt/king-phisher/KingPhisher -L DEBUG /opt/king-phisher/server_config.yml
DEBUG    target diretory: /opt/king-phisher
INFO     checking for the pipenv environment
DEBUG    pipenv path: '/usr/local/bin/pipenv'
DEBUG    pipenv Pipfile: /opt/king-phisher/Pipfile
Loading .env environment variables…
/opt/king-phisher/.venv/bin/python: Error while finding spec for 'king_phisher.client' (ImportError: No module named 'king_phisher')`

For installing King-Phisher i use this command: `wget -q https://github.com/securestate/king-phisher/raw/master/tools/install.sh && \
sudo -H bash ./install.sh
`
Here is listing
`alex@kpclient:/opt/king-phisher$ ls -la
total 132
drwxr-xr-x 10 root king-phisher  4096 дек  4 22:45 .
drwxr-xr-x  3 root root          4096 дек  4 22:39 ..
-rw-r--r--  1 root king-phisher  3225 дек  4 22:39 CODE_OF_CONDUCT.md
drwxr-xr-x  7 root king-phisher  4096 дек  4 22:39 data
drwxr-xr-x  3 root king-phisher  4096 дек  4 22:39 docs
-rw-r--r--  1 root king-phisher    29 дек  4 22:39 .env
drwxr-xr-x  8 root king-phisher  4096 дек  4 22:39 .git
drwxr-xr-x  3 root king-phisher  4096 дек  4 22:39 .github
-rw-r--r--  1 root king-phisher   788 дек  4 22:39 .gitignore
-rw-r--r--  1 root king-phisher  1329 дек  4 22:39 INSTALL.md
drwxr-xr-x  6 root king-phisher  4096 дек  4 22:45 king_phisher
-rwxr-xr-x  1 root king-phisher  1889 дек  4 22:39 KingPhisher
-rwxr-xr-x  1 root king-phisher  1895 дек  4 22:39 KingPhisherServer
-rw-r--r--  1 root king-phisher  1497 дек  4 22:39 LICENSE
-rw-r--r--  1 root king-phisher  1364 дек  4 22:39 Pipfile
-rw-r--r--  1 root king-phisher 39887 дек  4 22:39 Pipfile.lock
-rw-r--r--  1 root king-phisher  5789 дек  4 22:39 README.md
-rw-r--r--  1 root king-phisher   157 дек  4 22:39 readthedocs.yml
-rw-r--r--  1 root root          4650 дек  4 22:45 server_config.yml
drwxr-xr-x  4 root king-phisher  4096 дек  4 22:39 tests
drwxr-xr-x  4 root king-phisher  4096 дек  4 22:39 tools
drwxr-xr-x  6 root king-phisher  4096 дек  4 22:43 .venv`

**Comment by wolfthefallen** [comment]
try running `KingPhisher` from its working directory.
`cd /opt/king-phisher`
`./KingPhisher -L DEBUG`

**Comment by GrizliK91** [comment]
> DEBUG    target diretory: /opt/king-phisher
INFO     checking for the pipenv environment
DEBUG    pipenv path: '/usr/local/bin/pipenv'
DEBUG    pipenv Pipfile: /opt/king-phisher/Pipfile
Loading .env environment variables…
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/king-phisher/king_phisher/client/__init__.py", line 35, in <module>
    import gi

**Comment by wolfthefallen** [comment]
cool, first problem is solved.. As King Phisher is now using `pipenv` to create its own python3 environment, it needs to be ran from its working directory.  

from its working directory please run `pipenv run pip freeze` I need to verify if a package is installed, it should be, but just in case.

**Comment by GrizliK91** [comment]
> alex@kpclient:/opt/king-phisher$ pipenv run pip freeze
Loading .env environment variables…
AdvancedHTTPServer==2.0.11
asn1crypto==0.24.0
basemap==1.2.0
bcrypt==3.1.4
blinker==1.4
boltons==18.0.0
certifi==2018.10.15
chardet==3.0.4
cryptography==2.1.4
cycler==0.10.0
Cython==0.29
dnspython==1.15.0
ecdsa==0.13
email-validator==1.0.3
geojson==2.3.0
graphene-sqlalchemy==2.0.0
graphql-relay==0.4.5
icalendar==4.0.1
idna==2.6
ipaddress==1.0.19
iso8601==0.1.12
Jinja2==2.10
jsonschema==2.6.0
kiwisolver==1.0.1
Mako==1.0.7
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.2.2
maxminddb==1.4.1
msgpack-python==0.5.6
numpy==1.14.5
pluginbase==0.5
promise==2.2.1
psycopg2==2.7.3.2
py-gfm==0.1.3
pyasn1==0.4.4
pycairo==1.18.0
pycparser==2.19
pyotp==2.2.6
pyparsing==2.3.0
pyproj==1.9.5.1
pyshp==2.0.1
python-dateutil==2.7.2
python-editor==1.0.3
python-pam==1.8.3
pytz==2018.4
PyYAML==3.12
requests==2.18.4
requests-file==1.4.3
Rx==1.6.1
singledispatch==3.4.0.3
six==1.11.0
smoke-zephyr==1.2.0
SQLAlchemy==1.2.6
termcolor==1.1.0
tzlocal==1.5.1
urllib3==1.22
websocket-client==0.49.0
XlsxWriter==0.9.6

**Comment by wolfthefallen** [comment]
so there must have been an error when install `pipenv` virtual environment as I do not see `pygobject` 
To fix this issue please delete the `.venv` folder in the `king-phisher` directory then try launching KingPhisher again, this will force it to recreate the `pipenv` environment. 
`sudo rm -rf .venv`
`sudo ./KingPhisher -L DEBUG`

**Comment by GrizliK91** [comment]
Client started, but have some problem with interface

> alex@kpclient:/opt/king-phisher$ sudo ./KingPhisher -L DEBUG
DEBUG    target diretory: /opt/king-phisher
INFO     checking for the pipenv environment
DEBUG    pipenv path: '/usr/local/bin/pipenv'
WARNING  no pre-existing pipenv environment was found, installing it now
DEBUG    pipenv Pipfile: /opt/king-phisher/Pipfile
Loading .env environment variables…
WARNING  it is not necessary to run the king phisher client as root
DEBUG    king phisher version: 1.12.0 (rev: a311f02f3e39) python version: 3.5.2
DEBUG    client running in process: 28702 main tid: 0x7fc26b7d1700
DEBUG    using ui data from glade file: /opt/king-phisher/data/client/king_phisher/king-phisher-client.ui
DEBUG    gi.repository GLib version: 2.47.3
DEBUG    gi.repository GObject version: 3.28.3
DEBUG    gi.repository Gtk version: 3.18.9
DEBUG    gi.repository VTE version: 2.91
DEBUG    matplotlib version: 2.2.2
DEBUG    creating the user configuration directory
INFO     loading the config from: /home/alex/.config/king-phisher/config.json
INFO     loading 1 plugins
DEBUG    plugin 'check_for_updates' has been loaded
DEBUG    client loaded in 0.02 seconds

(__main__.py:28702): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
DEBUG    loading style from css file: /opt/king-phisher/data/client/king_phisher/style/theme.v2.css
ERROR    css parser error ('-gtk-icon-shadow' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:75
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:105
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:107
ERROR    css parser error ('min-height' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:120
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:121
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:144
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:153
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:165
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:168
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:191
ERROR    css parser error ('min-height' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:205
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:206
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:208
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:264
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:277
ERROR    css parser error ('min-height' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:338
ERROR    css parser error ('min-width' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:341
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:360
ERROR    css parser error ('min-width' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:371
ERROR    css parser error ('min-height' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:372
ERROR    css parser error ('min-height' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:380
ERROR    css parser error ('min-width' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:381
ERROR    css parser error ('min-height' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:392
ERROR    css parser error ('min-width' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:411
ERROR    css parser error ('min-height' is not a valid property name) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:412
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:413
ERROR    css parser error (Missing name of pseudo-class) in /opt/king-phisher/data/client/king_phisher/style/theme.v2.css:418
ERROR    there was an error parsing the css file, it will not be applied as a style provider
DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_file_open
DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_file_quit
DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_tools_rpc_terminal
DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_tools_sftp_client
DEBUG    loading GTK builder object with id: MainMenuBar.menuitem_tools_create_graph
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.button_target_file_select
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.calendar_calendar_invite_date
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_calendar_invite_all_day
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_calendar_request_rsvp
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_message_uid_charset_digits
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_message_uid_charset_lower
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.checkbutton_message_uid_charset_upper
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.combobox_importance
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.combobox_sensitivity
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_webserver_url
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_calendar_invite_location
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_calendar_invite_summary
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_company_name
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_recipient_email_cc
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_recipient_email_to
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_source_email
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_source_email_smtp
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_source_email_alias
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_subject
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_reply_to_email
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_html_file
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_target_file
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_target_name
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_target_email_address
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.entry_attachment_file
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.expander_calendar_invite_settings
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.expander_email_settings
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.label_target_count
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_message_type_calendar_invite
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_message_type_email
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_field_bcc
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_field_cc
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_field_to
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_type_file
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.radiobutton_target_type_single
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.spinbutton_calendar_invite_duration
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.spinbutton_calendar_invite_start_hour
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.spinbutton_calendar_invite_start_minute
DEBUG    loading GTK builder object with id: MailSenderConfigurationTab.viewport
DEBUG    loading GTK builder object with id: MailSenderEditTab.toolbutton_save_as_html_file
DEBUG    loading GTK builder object with id: MailSenderEditTab.toolbutton_save_html_file
DEBUG    loading GTK builder object with id: MailSenderEditTab.view_html_file
DEBUG    loading HTML completion data from: /opt/king-phisher/data/client/king_phisher/completion/html.json
DEBUG    loading Jinja completion data from: /opt/king-phisher/data/client/king_phisher/completion/jinja.json
DEBUG    loading GTK builder object with id: MailSenderSendTab.button_mail_sender_start
DEBUG    loading GTK builder object with id: MailSenderSendTab.button_mail_sender_stop
DEBUG    loading GTK builder object with id: MailSenderSendTab.textview_mail_sender_progress
DEBUG    loading GTK builder object with id: MailSenderSendTab.togglebutton_mail_sender_pause
DEBUG    loading GTK builder object with id: MailSenderSendTab.progressbar_mail_sender
DEBUG    loading GTK builder object with id: MailSenderSendTab.scrolledwindow_mail_sender_progress
INFO     matplotlib is installed, dashboard will be available
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.box_top_left
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.box_top_right
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.box_bottom
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.scrolledwindow_top_left
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.scrolledwindow_top_right
DEBUG    loading GTK builder object with id: CampaignViewDashboardTab.scrolledwindow_bottom
WARNING  /opt/king-phisher/.venv/lib/python3.5/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

DEBUG    dashboard refresh frequency set to 300 seconds
DEBUG    loading GTK builder object with id: CampaignViewMessagesTab.button_refresh
DEBUG    loading GTK builder object with id: CampaignViewMessagesTab.treeview_campaign
DEBUG    loading GTK builder object with id: CampaignViewVisitsTab.button_refresh
DEBUG    loading GTK builder object with id: CampaignViewVisitsTab.treeview_campaign
DEBUG    loading GTK builder object with id: CampaignViewCredentialsTab.button_refresh
DEBUG    loading GTK builder object with id: CampaignViewCredentialsTab.treeview_campaign
DEBUG    loading GTK builder object with id: LoginDialog.button_connect
DEBUG    loading GTK builder object with id: LoginDialog.entry_server
DEBUG    loading GTK builder object with id: LoginDialog.entry_server_username
DEBUG    loading GTK builder object with id: LoginDialog.entry_server_password
DEBUG    loading GTK builder object with id: LoginDialog.entry_server_one_time_password
DEBUG    loading GTK builder object with id: LoginDialog.label_main
DEBUG    loading GTK builder object with id: LoginDialog.label_server_one_time_password
DEBUG    loading GTK builder object with id: LoginDialog.revealer_server_one_time_password
DEBUG    loading GTK builder object with id: LoginDialog.spinbutton_server_remote_port
DEBUG    loading GTK builder object with id: LoginDialog.switch_server_use_ssl
^CTerminated

**Comment by zeroSteiner** [comment]
You're not trying to run the client over SSH are you? As in trying to SSH into a server and then starting the client from your SSH session?

**Comment by GrizliK91** [comment]
No, i'm trying to run client directly on virtual machine

**Comment by wolfthefallen** [comment]
hmm I am wondering if `Gtk version: 3.18.9` can't handle our v2 style.. Thats what it appears to be..
A temporary fix/test would be to copy the theme.v1.css over the theme.v2.css.. I recommend making a backup first.

`cp data/client/king_phisher/style/theme.v2.css   data/client/king_phisher/style/theme.v2.css.bck && cp data/client/king_phisher/style/theme.v1.css   data/client/king_phisher/style/theme.v2.css `

**Comment by zeroSteiner** [comment]
Yeah, we've fixed this issue in `dev` already. 3.18 *should* be loading the `v1.css` but it's not. You can either do what @wolfthefallen is recommending, or you can [opt into beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

We're probably just a week or two away from a routine merge of dev into master anyways. Technically everything should function correctly even without the theme loaded, you just don't get that pretty blue.

**Comment by GrizliK91** [comment]
Ok, Client started))

Here some warning messages

alex@kpclient:/opt/king-phisher$ sudo ./KingPhisher
Loading .env environment variables…
WARNING  it is not necessary to run the king phisher client as root

(__main__.py:31779): Gtk-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
WARNING  /opt/king-phisher/.venv/lib/python3.5/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

Should i worried about it?

**Comment by zeroSteiner** [comment]
That's just a deprecation warning in matplotlib. I'm assuming you just copied the file, instead of opting into beta testing since I'm pretty sure I fixed that too.

**Comment by GrizliK91** [comment]
Ok, thx you!))
Last question. When I trying to start Client from dashboard nothing happen 
Client started only if i go to the /opt/king-phisher/ and then start Client from terminal

**Comment by wolfthefallen** [comment]
That's a good catch, that would be an actual bug. We will get that taken care of and put into the dev branch.
The `data/client/king-phisher.desktop` file needs to be updated to execute `KingPhisher` in its working directory. According to `https://developer.gnome.org/desktop-entry-spec/` this is the `Path` option.

**Comment by zeroSteiner** [comment]
@wolfthefallen can you get that taken care of and then I'll merge dev into master to get these fixes in.

**Comment by wolfthefallen** [comment]
Yup I'll work on getting that fixed and into dev tomorrow..

**Comment by GrizliK91** [comment]
@wolfthefallen @zeroSteiner Thx for help
I will figure out how to change dashboard link

**Comment by wolfthefallen** [comment]
The icon launcher for *nix operating systems has been fixed in commit 4fdaa185fcbc24027e356108efc05f09c67f2e36 in to the dev branch.
