### ISSUE TITLE
An Error Occurred

### ISSUE THREAD

**Issue by us-SHE** [securestate/king-phisher#34]
If I go on "Preview" comes an error. Error Type: exceptions.TypeError
what can I do to solve this problem?
Also I get this error on "Edit" but only if I define a HTML file

Error details;
Error Type: exceptions.TypeError
Error Details: TypeError('Argument 2 does not allow None as a value',)
Error UID: 645dc104-569c-4f41-89c2-68b973a60fcd
RPC Error: N/A (Not an RPC error)
King Phisher Version: 0.2.1
Platform Version: Windows: 7 6.1.7601 SP1 Multiprocessor Free (Frozen=True)
Python Version: 2.7.9
Gtk Version: 3.8.9

Traceback (most recent call last):
  File "Y:\KingPhisher\king_phisher\client\tabs\mail.py", line 808, in signal_notebook_switch_page
  File "Y:\KingPhisher\king_phisher\client\tabs\mail.py", line 438, in show_tab
  File "Y:\KingPhisher\king_phisher\client\tabs\mail.py", line 430, in load_html_data
TypeError: Argument 2 does not allow None as a value

**Comment by zeroSteiner** [comment]
It looks like it's an error with how the webkit webview is being called to render the HTML message. It also looks like it's being caused by a file not being set in the "Message HTML File" box under the Configuration tab. Setting that should fix the issue.

**Comment by zeroSteiner** [comment]
This issue is now fixed on the `dev` branch as of commit 67a5d9e017a938d6b92e761adacebd7ffa4d891b. If you have no other questions on it, I'd like to close this issue out. Thanks for reporting it.

**Comment by us-SHE** [comment]
yes, thank you.
