### ISSUE TITLE
Department name

### ISSUE THREAD

**Issue by drc0nc** [securestate/king-phisher#344]
# Feature Description

Can we have department names variable show up in message content? With the department tag in the csv i'd like to have that in the message content. I've been searching through the wiki and documents and can't seem to find out if that's a possibility in Jinja.

**Comment by zeroSteiner** [comment]
I guess not, stand by and I'll add it in to the dev branch.

**Comment by zeroSteiner** [comment]
Added in commit [c99a543a](https://github.com/securestate/king-phisher/commit/c99a543a9df3ff617dca6dbe432e2947d6a9b2b9).

This feature has now been added in the dev branch. To obtain the changes, you can either wait for them to be merged into the master branch (which will likely take a few weeks) or you can obtain them immediately by opting into [beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).
