### ISSUE TITLE
King-phisher service fails

### ISSUE THREAD

**Issue by mother2110** [securestate/king-phisher#349]
## Issue Description
I experience an issue when I... and the results I expected are...
When I try to start king-phisher server

## Reproduction Steps
1. sudo service king-phisher start

## Environment Details

Host OS: Debian 9
King Phisher Version: New pull (not sure version number)

## Error Details / Stack Trace
sysadmin@KingServer:/opt$ sudo service king-phisher start
Job for king-phisher.service failed because of unavailable resources or another system error.
See "systemctl status king-phisher.service" and "journalctl -xe" for details.

sysadmin@KingServer:/opt$ sudo systemctl status king-phisher.service
● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: enabled)
   Active: failed (Result: resources) since Tue 2019-02-05 14:16:13 PST; 2min 14s ago
  Process: 1102 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml (code=exited, status=0/SUCCESS)

Feb 05 14:16:11 KingServer systemd[1]: Starting King Phisher Server...
Feb 05 14:16:11 KingServer python3[1102]: Loading .env environment variables…
Feb 05 14:16:13 KingServer python3[1102]: CRITICAL server failed to build with error: an ssl certificate must be specified when ssl is enabled
Feb 05 14:16:13 KingServer systemd[1]: king-phisher.service: PID file /var/run/king-phisher.pid not readable (yet?) after start: No such file or directory
Feb 05 14:16:13 KingServer systemd[1]: Failed to start King Phisher Server.
Feb 05 14:16:13 KingServer systemd[1]: king-phisher.service: Unit entered failed state.
Feb 05 14:16:13 KingServer systemd[1]: king-phisher.service: Failed with result 'resources'.

SERVER_CONFIG.YML

server:
  # Bind address information, multiple ports can be specified through additional entries under "addresses"
  addresses:
    # bind to port 80 on all IPv4 interfaces without SSL (http)
    - host: 0.0.0.0
      port: 80
      ssl: false
    # bind to port 443 on all IPv4 interfaces with SSL (https)
    - host: 0.0.0.0
      port: 443
      ssl: true
      ssl_cert: /etc/letsencrypt/live/company.tech/fullchain.pem
      ssl_key: /etc/letsencrypt/live/company.tech/privkey.pem

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by mother2110** [comment]
Thanks for the fast response.
So I am a little confused. Do you have a write up on how to use letsencrypt to add ssl cert? I followed this tutorial when setting this up. - https://www.sw1tch.net/2018/07/09/king-phisher-setup/

**Comment by zeroSteiner** [comment]
We have a wiki page at https://github.com/securestate/king-phisher/wiki/Server-SSL-Support. The article you mention is correct, it just means to update those values in the configuration, not necessarily to put them all together in the same location. You should just need to move those two definitions up to the level where the default ones that are commented out are.

**Comment by mother2110** [comment]
So move the 2 .pem files? Where are the "default ones" located at?

**Comment by mother2110** [comment]
So I did not move the .pem files yet but rebooted and not get this...

See "systemctl status king-phisher.service" and "journalctl -xe" for details.
sysadmin@KingServer:~$ sudo systemctl status king-phisher.service
● king-phisher.service - King Phisher Server
   Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: enabled)
   Active: failed (Result: resources) since Tue 2019-02-05 14:53:27 PST; 13s ago
  Process: 977 ExecStart=/usr/bin/python3 /opt/king-phisher/KingPhisherServer /opt/king-phisher/server_config.yml (code=exited, status=0/SUCCESS)

Feb 05 14:53:27 KingServer python3[977]:   File "/usr/lib/python3.5/socketserver.py", line 441, in __init__
Feb 05 14:53:27 KingServer python3[977]:     self.server_activate()
Feb 05 14:53:27 KingServer python3[977]:   File "/usr/lib/python3.5/socketserver.py", line 463, in server_activate
Feb 05 14:53:27 KingServer python3[977]:     self.socket.listen(self.request_queue_size)
Feb 05 14:53:27 KingServer python3[977]: OSError: [Errno 98] Address already in use
Feb 05 14:53:27 KingServer python3[977]: CRITICAL server failed to build with error: socket error #98 (Address already in use)
Feb 05 14:53:27 KingServer systemd[1]: king-phisher.service: PID file /var/run/king-phisher.pid not readable (yet?) after start: No such file or directory
Feb 05 14:53:27 KingServer systemd[1]: Failed to start King Phisher Server.
Feb 05 14:53:27 KingServer systemd[1]: king-phisher.service: Unit entered failed state.
Feb 05 14:53:27 KingServer systemd[1]: king-phisher.service: Failed with result 'resources'.
sysadmin@KingServer:~$

**Comment by mother2110** [comment]
I stopped apache2 and king-phisher started.

**Comment by zeroSteiner** [comment]
Excellent, I'll get this closed out then.

**Comment by mother2110** [comment]
Thanks again for the fast support.
