### ISSUE TITLE
Tool or tutorial to edit cloned websites for credentials

### ISSUE THREAD

**Issue by mother2110** [securestate/king-phisher#351]
# Feature Description
Playing with other tools. (Don't want to name them, unless asked for) I noticed they have the ability to clone a website and edit the needed fields to capture creds. Not being a web coder, I find it time-consuming to do this.  

## Alternatives Solutions
Are there any good documentation out there that describes the process of editing cloned web pages to use for credential capturing?

**Comment by zeroSteiner** [comment]
You want https://github.com/securestate/king-phisher/wiki/Web-Cloning and https://github.com/securestate/king-phisher/wiki/Creating-Server-Content.

**Comment by mother2110** [comment]
Thanks Steiner.

**Comment by mother2110** [comment]
Thanks Steiner.
