### ISSUE TITLE
Latest King Phisher unable to connect to Gmail SMTP:587

### ISSUE THREAD

**Issue by chrisandjer949** [securestate/king-phisher#355]
## Issue Description
I am able to launch KP fine.  Tried to connect to smtp.gmail.com:587 with my gmail username and App password.    

All i see on the KP terminal window is:  Warning:  received a socket error while connecting to the smtp server...   The strange thing is that I have another Kali VM in the same subnet running another GoPhish and that can connect to smtp.gmail.com:587 with no issues.  

## Reproduction Steps
1. Start King Phisher
2. Tried to send test email to smtp.gmail.com:587 with my gmail account name and App password.  

## Environment Details

Host OS: Kali 18.04
King Phisher Version: 1.13.0

## Error Details / Stack Trace
Where do I get the stack traces?
```

**Comment by zeroSteiner** [comment]
Well you're using port 587 and according to my notes [in the docs](https://github.com/securestate/king-phisher/wiki/Public-SMTP-Servers#using-public-smtp-servers) you need to use 465 with SSL turned on. Can you give that a shot and see if it fixes it?

If it does not, please include all of the relevant settings in the SMTP configuration tab. Can you also include the [verbose output](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-generate-verbose-logging-output) from when you try to connect too?

**Comment by chrisandjer949** [comment]
Ok, looks like problem is solved using port 465.  My bad and Thank you.  The verbose logs looks normal.  However, please see one error towards the bottom.   Something wrong with my install?  I am missing a module?

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'


====================================

root@kali2:/opt/king-phisher# ./KingPhisherServer -f -L DEBUG server_config.yml
DEBUG    target diretory: /opt/king-phisher
INFO     checking for the pipenv environment
DEBUG    pipenv path: '/usr/local/bin/pipenv'
DEBUG    pipenv Pipfile: /opt/king-phisher/Pipfile
Loading .env environment variables…
DEBUG    king phisher version: 1.13.0-beta3 (rev: f5a9c80c6157) python version: 3.7.2
DEBUG    plugin dependency path: /root/.local/lib/king-phisher/python3.7/site-packages
INFO     listening on 0.0.0.0:80
INFO     serving files has been enabled
INFO     initializing database connection with driver postgresql
DEBUG    postgresql-setup was not found
DEBUG    postgresql service is already running via systemctl
DEBUG    current database schema version: 9 (latest)
DEBUG    connected to postgresql database: king_phisher
INFO     restored 0 valid sessions and skipped 0 expired sessions from the database
DEBUG    use pam service 'sshd' for authentication
DEBUG    forked an authenticating process with pid: 6335
INFO     the job manager has been started
INFO     adding new job with id: dfcf2d77-59b0-4140-b534-53796e50368a and callback function: _maintenance
INFO     adding new job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    web socket manager worker running in tid: 0x7ff6ed136700
DEBUG    initialized the table api dataset (schema version: 8)
WARNING  the geoip database is older than 90 days
INFO     including 4 custom http headers
INFO     server running in process: 6296 main tid: 0x7ff6f1405740
INFO     dropped privileges to the nobody account
DEBUG    executing job with id: dfcf2d77-59b0-4140-b534-53796e50368a and callback function: _maintenance
DEBUG    running periodic maintenance tasks
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    127.0.0.1:35708 tid: 0x7ff6ec935700 running http request handler
DEBUG    calling RPC method rpc_version()
INFO     127.0.0.1 "RPC /version HTTP/1.1" 200 -
DEBUG    127.0.0.1:35712 tid: 0x7ff6ec935700 running http request handler
DEBUG    sent request with sequence number 0 and action 'authenticate'
DEBUG    received request with sequence number 0 and action 'authenticate'
DEBUG    pam returned code: 7 reason: 'Authentication failure' for user root after 2.31 seconds
WARNING  authentication failed for user: root reason: bad username or password
DEBUG    sent response with sequence number 0
DEBUG    received response with sequence number 0
WARNING  failed login request from 127.0.0.1 for user root, (authentication failed)
INFO     127.0.0.1 "RPC /login HTTP/1.1" 200 -
DEBUG    127.0.0.1:35716 tid: 0x7ff6ec935700 running http request handler
DEBUG    calling RPC method rpc_version()
INFO     127.0.0.1 "RPC /version HTTP/1.1" 200 -
DEBUG    127.0.0.1:35720 tid: 0x7ff6ec935700 running http request handler
DEBUG    sent request with sequence number 1 and action 'authenticate'
DEBUG    received request with sequence number 1 and action 'authenticate'
DEBUG    pam returned code: 0 reason: 'Success' for user root after 0.01 seconds
DEBUG    sent response with sequence number 1
DEBUG    received response with sequence number 1
INFO     user root has successfully authenticated
INFO     successful login request from 127.0.0.1 for user root
INFO     127.0.0.1 "RPC /login HTTP/1.1" 200 -
DEBUG    127.0.0.1:35724 tid: 0x7ff6ec935700 running http request handler
INFO     127.0.0.1 "GET /_/ws/events/json HTTP/1.1" 101 -
INFO     web socket has been connected
DEBUG    127.0.0.1:35728 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35732 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /config/get HTTP/1.1" 200 -
DEBUG    127.0.0.1:35736 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35740 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35744 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35748 tid: 0x7ff6dbfff700 running http request handler
DEBUG    calling RPC method rpc_events_subscribe('db-messages', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
DEBUG    127.0.0.1:35752 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35756 tid: 0x7ff6dbfff700 running http request handler
DEBUG    calling RPC method rpc_events_subscribe('db-visits', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
DEBUG    127.0.0.1:35760 tid: 0x7ff6dbfff700 running http request handler
DEBUG    calling RPC method rpc_events_subscribe('db-credentials', attributes=['id', 'campaign_id'], event_types=['deleted', 'inserted', 'updated'])
INFO     127.0.0.1 "RPC /events/subscribe HTTP/1.1" 200 -
DEBUG    127.0.0.1:35764 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35768 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35772 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35776 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    127.0.0.1:35780 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    10.2.2.17:43220 tid: 0x7ff6dbfff700 running http request handler
DEBUG    request received with the correct secret id
INFO     10.2.2.17 "GET /register.html?id=ytWUD56y7TD6jMoP6l3woJHd HTTP/1.1" 200 -
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    127.0.0.1:35788 tid: 0x7ff6dbfff700 running http request handler
DEBUG    calling RPC method rpc_campaign_landing_page_new('1', 'kali2', 'register.html')
INFO     127.0.0.1 "RPC /campaign/landing_page/new HTTP/1.1" 200 -
DEBUG    127.0.0.1:35792 tid: 0x7ff6dbfff700 running http request handler
DEBUG    calling RPC method rpc_campaign_message_new('1', 'VcxDDkga50NqlgIV', 'jelin@cisco.com', 'Jerry', '', None)
DEBUG    publishing event db-messages (type: inserted) with 1 objects
INFO     127.0.0.1 "RPC /campaign/message/new/deferred HTTP/1.1" 200 -
DEBUG    127.0.0.1:35796 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35800 tid: 0x7ff6dbfff700 running http request handler
DEBUG    publishing event db-messages (type: updated) with 1 objects
INFO     127.0.0.1 "RPC /db/table/set HTTP/1.1" 200 -
DEBUG    127.0.0.1:35804 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    127.0.0.1:35808 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    10.2.2.17:43248 tid: 0x7ff6dbfff700 running http request handler
DEBUG    request received with the correct secret id
INFO     10.2.2.17 "GET /register.html?id=ytWUD56y7TD6jMoP6l3woJHd HTTP/1.1" 200 -
DEBUG    127.0.0.1:35816 tid: 0x7ff6dbfff700 running http request handler
DEBUG    calling RPC method rpc_campaign_landing_page_new('1', 'kali2', 'register.html')
INFO     127.0.0.1 "RPC /campaign/landing_page/new HTTP/1.1" 200 -
DEBUG    127.0.0.1:35820 tid: 0x7ff6dbfff700 running http request handler
DEBUG    calling RPC method rpc_campaign_message_new('1', 'NE25LDkDgM2d91qT', 'jelin@cisco.com', 'Jerry', '', None)
DEBUG    publishing event db-messages (type: inserted) with 1 objects
INFO     127.0.0.1 "RPC /campaign/message/new/deferred HTTP/1.1" 200 -
DEBUG    127.0.0.1:35824 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35828 tid: 0x7ff6dbfff700 running http request handler
DEBUG    publishing event db-messages (type: updated) with 1 objects
INFO     127.0.0.1 "RPC /db/table/set HTTP/1.1" 200 -
DEBUG    127.0.0.1:35832 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    127.0.0.1:35840 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    10.2.2.17:43280 tid: 0x7ff6dbfff700 running http request handler
DEBUG    request received with the correct secret id
INFO     10.2.2.17 "GET /register.html?id=ytWUD56y7TD6jMoP6l3woJHd HTTP/1.1" 200 -
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    127.0.0.1:35848 tid: 0x7ff6dbfff700 running http request handler
DEBUG    calling RPC method rpc_campaign_landing_page_new('1', 'kali2', 'register.html')
INFO     127.0.0.1 "RPC /campaign/landing_page/new HTTP/1.1" 200 -
DEBUG    127.0.0.1:35852 tid: 0x7ff6dbfff700 running http request handler
DEBUG    calling RPC method rpc_campaign_message_new('1', 'n8A3J2lwYI0iqMiF', 'jelin@cisco.com', 'Jerry', '', None)
DEBUG    publishing event db-messages (type: inserted) with 1 objects
INFO     127.0.0.1 "RPC /campaign/message/new/deferred HTTP/1.1" 200 -
DEBUG    127.0.0.1:35856 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    127.0.0.1:35860 tid: 0x7ff6dbfff700 running http request handler
DEBUG    publishing event db-messages (type: updated) with 1 objects
INFO     127.0.0.1 "RPC /db/table/set HTTP/1.1" 200 -
DEBUG    127.0.0.1:35864 tid: 0x7ff6dbfff700 running http request handler
INFO     127.0.0.1 "RPC /graphql HTTP/1.1" 200 -
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message
DEBUG    executing job with id: 7e3e1e37-802c-439e-8f84-53e9ab3e33a3 and callback function: ping_all
DEBUG    received message (len: 16 opcode: 0x0a fin: True)
DEBUG    processing pong (opcode: 0x0a) message

==============================================

root@kali2:/opt/king-phisher# ./KingPhisher
Loading .env environment variables…
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
WARNING  it is not necessary to run the king phisher client as root
WARNING  /opt/king-phisher/king_phisher/client/__main__.py:101: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()

WARNING  failed to authenticate to the remote king phisher service, reason: invalid credentials
Memory pressure relief: Total: res = 13680640/13729792/49152, res+swap = 9539584/9539584/0


========================================

**Comment by zeroSteiner** [comment]
Well it's not clear what's throwing the exception. It doesn't appear to be uncaught because there's no stack trace. Matplotlib is the only component that uses numpy to my knowledge, we don't use it directly. If you can load the client and view graphs, you're probably just fine.

**Comment by chrisandjer949** [comment]
All the graphs appear to be loading fine.  Thanks again for the quick help!  Case closed.
