### ISSUE TITLE
Make every non existent page to point at main page

### ISSUE THREAD

**Issue by xdu8026** [securestate/king-phisher#360]
Lets say we have www.example.com/index.html, if someone visits a page www.example.com/something/index.html it returns an error 404, or for example www.example.com/something/somethingelse.asp again error 404, which is normal because those pages dont exist.
How to make the server to load the index.html and continue from there to the next pages, no matter that the page visited doesnt exist.
For example upon visiting example.com/some/something/en/example instead of showing error 404, load the index.html but without changing the URL in the address bar, meaning that the page index.html will be loaded but the URL will be the same custom nonexistent URL
The server.py file has a string for nonexistent pages I see, but how can it be edited correctly to achieve the upper goal

**Comment by zeroSteiner** [comment]
You could replace the default 404 html data file with your content, but the server would still respond with a 404 status code. You could have your new page redirect the users though.

**Comment by xdu8026** [comment]
https://king-phisher.readthedocs.io/en/latest/king_phisher/server/server.html#king_phisher.server.server.KingPhisherRequestHandler.respond_not_found

Instead of doing that can this handler be somehow edited in the server.py to achieve it directly, so it will be more cleaner without 404 status or a redirect to the page. This is in the source server.py I think handler:
`def respond_not_found(self):
		self.send_response(404, 'Not Found')
		self.send_header('Content-Type', 'text/html; charset=utf-8')
		file_path = find.data_file(os.path.join('pages', 'error_404.html'))
		if file_path:
			with open(file_path, 'rb') as file_h:
				message = file_h.read()
		else:
			message = b'Resource Not Found\n'
		self.send_header('Content-Length', len(message))
		self.end_headers()
		self.wfile.write(message)
return`

**Comment by zeroSteiner** [comment]
Sure, yeah you could edit that method to do whatever you'd like. Updating would become a bit of a pain though as you'd need to re-apply your changes periodically.

You could also write a custom server plugin to register a response path. The response handler map is checked before files on disk though, so you'd need to ensure that you're regex does not match any files that actually exist. There's an API method for this that's similar, but wouldn't work because it registers the path with a fixed prefix. You could just implement the code to do it yourself though easily enough. https://github.com/securestate/king-phisher/blob/dev/king_phisher/server/plugins.py#L80-L101

**Comment by xdu8026** [comment]
I think changing the server.py would be the easier option than writing a plugin, re-applying the changed with the original file for updates would be no problem.
I am trying to figure out how to edit https://github.com/securestate/king-phisher/blob/master/king_phisher/server/server.py#L621-L633 to achieve the goal but without success, probably I lack the knowledge. If its not a problem can you tell me which lines have to be edited and with what code so it can be achieved.

**Comment by zeroSteiner** [comment]
Yeah, do this:

1. Change https://github.com/securestate/king-phisher/blob/master/king_phisher/server/server.py#L622 to `self.send_response(200)`
1. Change https://github.com/securestate/king-phisher/blob/master/king_phisher/server/server.py#L624 to `file_path = find.data_file(os.path.join('pages', 'default.html'))`

The second step technically isn't necessary, you could just overwrite the contents of `error_404.html`, but when the time comes it'd be more difficult to merge your changes back in. This way you can put whatever you want in `default.html` and just worry about those two lines when the day comes to reapply your changes.

**Comment by xdu8026** [comment]
After tests if the link visited is example.com/Nonexistent the default.html loads perfectly, but if the link is example.com/nonexistent/nonexistent etc it doesnt load it just displays white page. The default.html has some .js files that it loads, could it be that it cant find they're location if the the link is example.com/something/something and etc etc ?

**Comment by zeroSteiner** [comment]
It's possible if you're doing a relative load for your .js files. Try doing an absolute one by prefixing it with `/`.
