### ISSUE TITLE
Not able to save message template

### ISSUE THREAD

**Issue by gosusnkr** [securestate/king-phisher#361]
I saved the users list in csv file as 
شيئا ما,something,something@something.com.

When I create the message template with Hi {{client.firstname}}, it is not getting saved.
If I change csv file to unicode format, message preview showing as Hi , blah blah.

Was it the problem with arabic format words.
Is the tool supports only english words in csv file.
If it is problem with arabic format what is the solution.

**Comment by zeroSteiner** [comment]
All files need to be UTF-8 encoded. We don't support any other encodings at this time. If your CSV file and your template file are UTF-8, then everything should just work.

**Comment by gosusnkr** [comment]
Thanks @zeroSteiner, it helped me
