### ISSUE TITLE
Cannot start king-phisher.service

### ISSUE THREAD

**Issue by greed5566** [securestate/king-phisher#362]
Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Tue 2019-04-09 18:12:00 PST; 1min 13s ago
  Process: 8640 ExecStart=/usr/bin/python3 /home/phhuang2/king-phisher/KingPhisherServer /home/phhuang2/king-phisher/server_config.yml (code=exited, status=0/SUCCESS)

Apr 09 18:10:33 DEVPHISH02 su[8654]: pam_unix(su:session): session opened for user postgres by (uid=0)
Apr 09 18:10:33 DEVPHISH02 su[8671]: Successful su for postgres by root
Apr 09 18:10:33 DEVPHISH02 su[8671]: + ??? root:postgres
Apr 09 18:10:33 DEVPHISH02 su[8671]: pam_unix(su:session): session opened for user postgres by (uid=0)
Apr 09 18:10:33 DEVPHISH02 systemd[1]: king-phisher.service: PID file /var/run/king-phisher.pid not readable (yet?) after start: No such file or directory
Apr 09 18:10:33 DEVPHISH02 python3[8640]: WARNING  the specified geoip database does not exist, downloading a new copy
Apr 09 18:12:00 DEVPHISH02 systemd[1]: king-phisher.service: Start operation timed out. Terminating.
Apr 09 18:12:00 DEVPHISH02 systemd[1]: Failed to start King Phisher Server.
Apr 09 18:12:00 DEVPHISH02 systemd[1]: king-phisher.service: Unit entered failed state.
Apr 09 18:12:00 DEVPHISH02 systemd[1]: king-phisher.service: Failed with result 'timeout'.

**Comment by zeroSteiner** [comment]
I'm guessing it timed out while it was downloading the GeoIP database.You can run `sudo ./KingPhisherServer --update-geoip-db /path/to/server_config.yml` to download it manually. After that try restarting the service and it shouldn't timeout.

**Comment by silkrod** [comment]
Ok. No longer having that issue but now I am seeing this:

`root@host:/opt/king-phisher# ls -la
total 156
drwxr-xr-x 11 root king-phisher  4096 Apr 10 09:42 .
drwxr-xr-x  3 root root          4096 Apr  9 23:16 ..
-rw-r--r--  1 root king-phisher  3225 Apr  9 23:16 CODE_OF_CONDUCT.md
drwxr-xr-x  7 root king-phisher  4096 Apr  9 23:16 data
drwxr-xr-x  3 root king-phisher  4096 Apr  9 23:16 docs
-rw-r--r--  1 root king-phisher    29 Apr  9 23:16 .env
drwxr-xr-x  8 root king-phisher  4096 Apr  9 23:16 .git
drwxr-xr-x  3 root king-phisher  4096 Apr  9 23:16 .github
-rw-r--r--  1 root king-phisher   788 Apr  9 23:16 .gitignore
drwxr-xr-x  3 root root          4096 Apr 10 09:42 $HOME
-rw-r--r--  1 root king-phisher  1329 Apr  9 23:16 INSTALL.md
drwxr-xr-x  6 root king-phisher  4096 Apr  9 23:21 king_phisher
-rwxr-xr-x  1 root king-phisher  1889 Apr  9 23:16 KingPhisher
-rwxr-xr-x  1 root king-phisher  1895 Apr  9 23:16 KingPhisherServer
-rw-r--r--  1 root king-phisher  1497 Apr  9 23:16 LICENSE
-rw-r--r--  1 root king-phisher  1554 Apr  9 23:16 Pipfile
-rw-r--r--  1 root root         57987 Apr 10 09:38 Pipfile.lock
-rw-r--r--  1 root king-phisher  5789 Apr  9 23:16 README.md
-rw-r--r--  1 root king-phisher   157 Apr  9 23:16 readthedocs.yml
-rw-r--r--  1 root root          4756 Apr  9 23:40 server_config.yml
drwxr-xr-x  4 root king-phisher  4096 Apr  9 23:16 tests
drwxr-xr-x  4 root king-phisher  4096 Apr  9 23:16 tools
drwxr-xr-x  6 root king-phisher  4096 Apr  9 23:18 .venv
root@host:/opt/king-phisher# ./KingPhisherServer server_config.yml
Loading .env environment variables…
ERROR    failed to bind server to address (socket error #98)
ERROR    socket error #98 (Address already in use)
Traceback (most recent call last):
  File "/opt/king-phisher/king_phisher/server/build.py", line 145, in server_from_config
    server = KingPhisherServer(config, plugin_manager, handler_klass, addresses=addresses, ssl_certfile=ssl_certfile, ssl_keyfile=ssl_keyfile)
  File "/opt/king-phisher/king_phisher/server/server.py", line 870, in __init__
    super(KingPhisherServer, self).__init__(handler_klass, *args, **kwargs)
  File "/opt/king-phisher/.venv/lib/python3.5/site-packages/advancedhttpserver.py", line 1791, in __init__
    server = server_klass((address[0], address[1]), handler_klass, config=self.__config)
  File "/opt/king-phisher/.venv/lib/python3.5/site-packages/advancedhttpserver.py", line 713, in __init__
    super(ServerNonThreaded, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 441, in __init__
    self.server_activate()
  File "/usr/lib/python3.5/socketserver.py", line 463, in server_activate
    self.socket.listen(self.request_queue_size)
OSError: [Errno 98] Address already in use
CRITICAL server failed to build with error: socket error #98 (Address already in use)
root@host:/opt/king-phisher# 
`
