### ISSUE TITLE
Connecting to external SMTP

### ISSUE THREAD

**Issue by silkrod** [securestate/king-phisher#364]
I can connect to SMTP server if I set one up on the same server that the KingPhisherServer daemon is running on. However, I cannot connect to any other SMTP no matter what options I choose. Tested on multiple external SMTP servers.

Is this a known issue?

**Comment by zeroSteiner** [comment]
Are you using the proper settings for TLS / disabling SSH tunneling etc.? Check the [debug logs](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-generate-verbose-logging-output) and share the error here along with your settings.

Settings for common [Public SMTP Servers](https://github.com/securestate/king-phisher/wiki/Public-SMTP-Servers) are available on the wiki.

**Comment by silkrod** [comment]
king-phisher # ./KingPhisher --no-plugins --no-style
Loading .env environment variables…
WARNING  it is not necessary to run the king phisher client as root
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/king-phisher/king_phisher/utilities.py", line 502, in run
    super(Thread, self).run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/king-phisher/king_phisher/client/tabs/mail.py", line 941, in _set_entry_completion_list_tsafe
    url_information = self.application.rpc.graphql_find_file('get_site_templates.graphql')
  File "/opt/king-phisher/king_phisher/client/client_rpc.py", line 241, in graphql_find_file
    return self.graphql_file(path, query_vars=query_vars)
  File "/opt/king-phisher/king_phisher/client/client_rpc.py", line 224, in graphql_file
    return self.graphql(query, query_vars=query_vars)
  File "/opt/king-phisher/king_phisher/client/client_rpc.py", line 205, in graphql
    query_vars=query_vars
king_phisher.errors.KingPhisherGraphQLQueryError


(__main__.py:27173): Gtk-WARNING **: /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkliststore.c:836: Unable to convert from (null) to gchararray

WARNING  received a socket.error while connecting to the SMTP server
WARNING  received a socket.error while connecting to the SMTP server

**Comment by zeroSteiner** [comment]
It can't connect. What are the settings your using?

**Comment by silkrod** [comment]
Just your basic SMTP settings. Whenever I create it myself and host it on the KingPhisherServer it works. I can connect and it mails fine. When I use any external one, it doesn't allow me to connect. I configured the SMTP servers the same way.

**Comment by silkrod** [comment]
I can get it to work ONLY when the SMTP is on the server. I just tried another configuration.

Client & Server on the same machine. I attempted to send from the SMTP that I was able to send from before and received the same error.

Does this confirm my suspicions that the SMTP server has to be setup on the KingPhisherServer?

**Comment by zeroSteiner** [comment]
If you're using an SMTP server that is not on the King Phisher server then you probably want to disable SSH tunneling. I can't help you though if you won't share the actual settings (minus the IP is you're worried about that) and the verbose logging output.

**Comment by silkrod** [comment]
I don't mind sharing anything what do you want me to do in order to diagnose this? Tell me exactly what to do in order to get you the information you need.

**Comment by zeroSteiner** [comment]
Post all of the SMTP settings from the configuration dialog and post all the debug output using the steps from the wiki I linked to two days ago.
