### ISSUE TITLE
Postgrel graph issue

### ISSUE THREAD

**Issue by Salfos** [securestate/king-phisher#366]
## Issue Description
I experience an issue when I first made a graph of phish results and now logging and dashboard graphs are messed and the results I expected are normal function.

## Reproduction Steps
1. run a graph
2. start King Phisher

## Environment Details

Host OS: Ubuntu 18.04.2 LTS
King Phisher Version: 1.14.0-beta(rev: e07132639c7e

## Error Details / Stack Trace
Error Type: king_phisher.errors.KingPhisherGraphQLQueryError
Error Details: KingPhisherGraphQLQueryError()
Error UID: e34fd0d0-d083-4d06-b356-df70941799cc
RPC Error: N/A (Not an RPC error)
King Phisher Version: 1.14.0-beta (rev: e07132639c7e)
Platform Version: Linux: Ubuntu 18.04 bionic
Python Version: 3.6.7
Gtk Version: 3.22.30
Timezone: America/New_York

Thread Information:
===================
 => MainThread (alive=True daemon=False)
    Thread-7 (alive=True daemon=True)
    Thread-6 (alive=True daemon=False)
    Thread-11 (alive=True daemon=True)
    Thread-12 (alive=True daemon=True)

Stack Trace:
============
Traceback (most recent call last):
  File "/home/saurus/king-phisher/king_phisher/client/application.py", line 488, in do_server_connected
    campaign = self.get_graphql_campaign() if campaign_id else None
  File "/home/saurus/king-phisher/king_phisher/client/application.py", line 371, in get_graphql_campaign
    campaign = self.rpc.graphql_find_file('get_campaign.graphql', id=campaign_id)
  File "/home/saurus/king-phisher/king_phisher/client/client_rpc.py", line 241, in graphql_find_file
    return self.graphql_file(path, query_vars=query_vars)
  File "/home/saurus/king-phisher/king_phisher/client/client_rpc.py", line 224, in graphql_file
    return self.graphql(query, query_vars=query_vars)
  File "/home/saurus/king-phisher/king_phisher/client/client_rpc.py", line 205, in graphql
    query_vars=query_vars
king_phisher.errors.KingPhisherGraphQLQueryError

GraphQL Exception Information:
=============================

GraphQL Errors:
---------------
table
table
table

GraphQL Query:
--------------
# retrieve a campaign by it's ID
query getCampaign($id: String!) {
  db {
    campaign(id: $id) {
      id
      created
      name
      description
      expiration
      maxCredentials

      credentialRegexUsername
      credentialRegexPassword
      credentialRegexMfaToken

      campaignType {
        id
        name
      }
      company {
        id
        name
      }
      user {
        id
        name
      }
    }
  }
}

**Comment by zeroSteiner** [comment]
Reproduced, bug is related to the recent upgrade of `SQLAlchemy` from v1.2.6 to 1.3.3.

**Comment by zeroSteiner** [comment]
Apparently the `sqlalchemy.relationships.orm.RelationshipProperty.table` attribute has been deprecated in favor of the `sqlalchemy.relationships.orm.RelationshipProperty.target` attribute. When `table` was removed, this broke `king_phisher.server.graphql.types.database.sa_get_relationship` which caused a cascading failure through the AuthorizationMiddleware up to GraphQL.

I'll have this fixed today so we can continue the upgrade to SQLAlchemy v1.3.3.

**Comment by zeroSteiner** [comment]
Fixed in commit 437dbae2ea04d864580f02acd818012661c20dcd.
