### ISSUE TITLE
Add alt parameters to images created with inline_images() in the email template

### ISSUE THREAD

**Issue by weedpatch2** [securestate/king-phisher#367]
# Feature Description
Adding an empty alt="" parameter to <img> tags makes emails look more legitimate to SPAM engines. Currently, there is no way to modify the <img> tag created by the inline_image() jinja method.

## Alternatives Solutions
It is possible to include image tags as such '<img alt="" src="data:img/png;base64,iVB...' however that is less reliable for getting the images to open in the mail client.

## Example Use Case
This should be used on all image tags to decrease SPAM scores.

**Comment by zeroSteiner** [comment]
This seems pretty reasonable, I can get this added. :+1:

**Comment by zeroSteiner** [comment]
This feature has now been added in the dev branch. To obtain the changes, you can either wait for them to be merged into the master branch (which will likely take a few weeks) or you can obtain them immediately by opting into [beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

Added in commit 4c701658181d1b13bd6d3d694dc6879f7b50b89c.

**Comment by zeroSteiner** [comment]
Forgot to mention, this is now implemented as an optional keyword argument to `inline_image` use it by specifying `alt` as an empty string like this: `inline_image(..., alt='')`.

**Comment by weedpatch2** [comment]
The turnaround on this was awesome! Thanks!
