### ISSUE TITLE
Installer only supports following linux distrobutions

### ISSUE THREAD

**Issue by jmartiuk5** [securestate/king-phisher#37]
Hello i am currently running kali 2.0 and when i run the install script i get the above message. I am guessing it is not yet compatible with kali 2.0. I just wanted to bring this to your attention thank you.

**Comment by jmartiuk5** [comment]
Sorry i downloaded the tar which would not work once i cloned the repo it worked like a charm

**Comment by zeroSteiner** [comment]
Yes the tarball is for the latest release (v0.2.1 as of now) which came out before Kali 2 was released. Cloning the repo however will provide you with the latest version in between releases.
