### ISSUE TITLE
Installation with install.sh freezes

### ISSUE THREAD

**Issue by Moooser** [securestate/king-phisher#370]
## Issue Description
I experience an issue when I start the install.sh script. At first it seems to work fine but then always freezes when synchronizing pipenv, I reproduced the error multiple times on different virtual machines

## Reproduction Steps
1. Start install.sh
2. just wait

## Environment Details

Ubuntu 19.04 VM (Virtual Box), Kali 2018 VM (Virtual Box)
King Phisher Version: 13

## Error Details / Stack Trace

obviously no error Detail, but this is the last information in the terminal window before the installation freezes:
"INFO: Synchronizing King Phisher's pipenv environment"

**Comment by zeroSteiner** [comment]
How long are you waiting? There's a lot of data for it to pull down so depending on your network connection, it could take up to 20 minutes.

**Comment by Moooser** [comment]
I am aware of that, but I waited for more than 3 hours one time and it
always freezes exactly at this point.

Spencer McIntyre <notifications@github.com> schrieb am Di., 7. Mai 2019,
18:40:

**Comment by zeroSteiner** [comment]
@wolfthefallen what's the recommendation here? Run `pipenv` manually to get more details? Are we aware of any issues in regards to Ubuntu 19.04 and the install script?

**Comment by zeroSteiner** [comment]
This looks related to #357 only with Ubuntu 19.04 instead of 18.04.

**Comment by wolfthefallen** [comment]
are you running behind a proxy?

**Comment by Moooser** [comment]
@wolfthefallen no, but the install script eventually worked after a lot of trials. It only took around 10 minutes and didnt freeze at all. Thanks for the help and the good work.

**Comment by zeroSteiner** [comment]
Weird, thanks for letting us know though and closing out the issue.
