### ISSUE TITLE
Cannot Start KingPhisherServer 

### ISSUE THREAD

**Issue by cpt-kernel** [securestate/king-phisher#376]
After ./KingPhisherServer
> No module named 'rx.concurrency'
`pip install rx` : Requirement already satisfied: rx in /usr/local/lib/python3.6/dist-packages (1.6.1)

I've reinstalled, rebooted, sudo, and more
no change 

## Environment Details
Ubuntu 18.04.2 LTS
Latest Version of KingPhisher

**Comment by zeroSteiner** [comment]
We need more details. What is everything that's printed after you start the server? We don't directly use a module called `rx` so I'm not sure where that's coming from.

**Comment by Nib0x62s** [comment]
Hello cpt-kernel, 

To further diagnose your issue we're going to need a bit more information.

If you could please refer to the _How do I generate verbose logging output_ in the following [article](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-generate-verbose-logging-output) and post the output contents here that'd be prefect :). 

Thanks!
