### ISSUE TITLE
 Edit cloned websites for credentials

### ISSUE THREAD

**Issue by will287** [securestate/king-phisher#383]
## Issue Description
[cloned_Office_site_2019.txt](https://github.com/securestate/king-phisher/files/3363964/cloned_Office_site_2019.txt)
King-phisher appears to be running as expected. I have cloned a webpage and change the username and password fields as the documentation suggest. I am still unable to capture credentials. 

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash
3. send email to user 
4. user click the link in the email 
5. user inputs user name and password 
6. user is routed to next page of phishing exercise. 
7. when i view the client/campaign it shows messages being sent to user. 
8. It does not capture any credentials. 
 

## Environment Details

Host OS: Kali Linux GNU\Linux Rolling 
King Phisher Version: 1.11.0

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
Did you send yourself a phishing message and verify that you got a visit before entering credentials into the landing page?

Assuming you did that, are you seeing the request show up in the server logs?

**Comment by will287** [comment]
I am seeing the initial email on the server. I will forward a copy of the email

**Comment by zeroSteiner** [comment]
No not the email, do you see a visit? Without a visit no information will be collected. If you're testing it yourself you need to click the link in the email before entering the credentials.

**Comment by will287** [comment]
It appears it is receiving the initial email communication. The server even receives the response when you click the link in the phishing email. I do not see any get response. In the screen shot I see the ./verify.html web page response. This page also renders with no issue. 
[KP_cred_capture.docx](https://github.com/securestate/king-phisher/files/3369432/KP_cred_capture.docx)

**Comment by zeroSteiner** [comment]
My guess is that it's not posting the `username` and `password` to the `verify.html` resource. I would suggest that you double check the HTML form to ensure both of those fields are present and they're named `username` and `password` not something else.

**Comment by will287** [comment]
Can you point me to the documentation that describes how to edit a cloned webpage. I have attached the text version of the page. the password and user fields have been edited as recommended.
[cloned_Office_site_2019.txt](https://github.com/securestate/king-phisher/files/3378733/cloned_Office_site_2019.txt)

**Comment by will287** [comment]
Is it possible to make changes to the cloned webpage without starting and stopping the applications?

**Comment by zeroSteiner** [comment]
Yeah that would be [here](https://github.com/securestate/king-phisher/wiki/Creating-Server-Content#pages-for-harvesting-credentials) in the wiki. Your page looks correct. And yes you can change the template content without restarting the server, it's not cached or anything.

Are you clicking a phishing link including a `?id=SOMETHING` parameter before landing on the page to submit your credentials?

**Comment by will287** [comment]
Not sure I understand second part of question. We have the below email sample email we send to the user. The sample IP is what the user clicks on that bring them to the landing page (index.html). 

In an effort to continue bringing you the best available technology, our team has implemented the newest version of Microsoft's Office 365 Webmail. 
Your existing emails, contacts and calendar events will be seamlessly transfered to your new account. 

Visit http://10.1.3.190 and login with your current username and password to confirm your new account

**Comment by zeroSteiner** [comment]
You shouldn't include a hardcoded link into your email, that would be your issue. You need to use a [tracking link](https://github.com/securestate/king-phisher/wiki/Creating-Message-Content#tracking-links) to enable tracking. That's why I was asking if you were seeing any entries in the Visits tab.

Change your URL in your email to `{{ url.webserver }}` then set the "Target URL" in the Message Configuraiton tab to your landing page (`http://10.1.3.190` in this case). After that, when you send the email the link should be `http://10.1.3.190?id=SOMETHING` where `SOMETHING` is a string of random numbers and characters.
