### ISSUE TITLE
Need Parrot Security added to accepted distros PLEASE...

### ISSUE THREAD

**Issue by hwac121** [securestate/king-phisher#385]
# Feature Description
You need to please add support for Parrot Security OS, this distro is quickly becoming as popular as Kali. Many of us prefer it over Kali, me included! This would only make your app even more popular.

## Alternatives Solutions
n/a

## Example Use Case
n/a

**Comment by zeroSteiner** [comment]
Thanks for the suggestion but no, we won't be officially supporting any additional Linux distributions any time soon.

There's a few reasons for this. First there's nothing stopping you from running King Phisher on Parrot, you may run into a few minor install issues but that's it. That does however bring me to my second point, the distros we've listed as supported are periodically tested, monitored for releases and documented. Adding an additional distribution is a lot of in going work for us and is not currently aligned with an initiative that we are pursuing.

Again thanks for the feature suggestion hopefully some time in the future we'll be in a better position to support additional distributions.
