### ISSUE TITLE
Problem sending email on version 0.3.0

### ISSUE THREAD

**Issue by snider14** [securestate/king-phisher#39]
I am unable to send email using new version, it states that one or more source email addresses specified are invalid even though it is the same formated CSV as used with older versions for recipient list. Below is the error. Thanks

Error Type: exceptions.AttributeError
Error Details: AttributeError("'GenericRdata' object has no attribute 'strings'",)
Error UID: 4e5eab73-9556-47fc-9ad6-4ec58791ca33
RPC Error: N/A (Not an RPC error)
King Phisher Version: 0.3.0
Platform Version: Windows: 7 6.1.7601 SP1 Multiprocessor Free (Frozen=True)
Python Version: 2.7.9
Gtk Version: 3.8.9

Traceback (most recent call last):
  File "Y:\KingPhisher\king_phisher\client\tabs\mail.py", line 231, in signal_button_clicked_sender_start
  File "Y:\KingPhisher\king_phisher\client\tabs\mail.py", line 179, in _sender_precheck_spf
  File "Y:\KingPhisher\king_phisher\spf.py", line 170, in check_host
  File "Y:\KingPhisher\king_phisher\spf.py", line 186, in _check_host
AttributeError: 'GenericRdata' object has no attribute 'strings'

**Comment by snider14** [comment]
When sending an email it says "checking the target URL... success, done." but never sends the email.

**Comment by zeroSteiner** [comment]
This is not an issue with the CSV file, this is an issue with the SPF checking module. As a work around while I fix this you can disable SPF checks by going to "Edit > Preferences > Client" and set "SPF Record Check Type" to "Do Not Check" then hit Apply. This will skip over the SPF checks for now.
Unfortunately a fix won't be available for Windows until the next release cycle when an updated MSI Build is made and posted.

**Comment by snider14** [comment]
![image](https://cloud.githubusercontent.com/assets/14295632/9908328/25af65e4-5c61-11e5-8ea2-8f8b5ebced2c.png)

Still doesn't work for me

**Comment by zeroSteiner** [comment]
Are you getting the same error message?

**Comment by snider14** [comment]
not sure, it is not popping up with an error dialog box anymore

**Comment by snider14** [comment]
When I click on the "preview" or "edit" tab I do get an error dialog box. below is what I get when I click on the preview tab

Error Type: exceptions.UnicodeDecodeError
Error Details: UnicodeDecodeError('utf8', '<html>\r\t<head>\r\n\t<style type="text/css">\r\r\t\tp {\r\t\t\tborder-style:solid;\r\r\n\t\t\tborder-width: 20px;\r\r\n\t\t\tborder-color: #0267AF;\r\r\n\t\t\tborder-right-style: none;\r\r\n\t\t\tborder-left-style: none;\r\r\t\t\ttext-align: center;\r\r\t\t\tpadding-top: 10px;\r\r\t\t\tpadding-right: 10px;\r\r\t\t\tpadding-bottom: 10px;\r\r\t\t\tpadding-left: 10px;\r\t\t\t\r\t\t\t}\r\t\t\t\t\t\t\r\n\t</style>\r\t</head>\r\n\t\t\r\r\n\t<body oncontextmenu="return false" onselectstart="return false" ondragstart="return false">\r\t\t\r\t\t<img src="\\\\aoins.com\\rootitsec\\itsec\\\\King Phisher\\Campaigns\\Test2\\MainLogo.png">\r\t\t\r\n\t\t<p>\r\t\t<p style="text-align: center"><font face="Arial" size="6"><b>Congratulations {{client.first_name}}!</b></font></p>\r\t\t<p><img align="right" src="\\\\aoins.com\\rootitsec\\itsec\\\\King Phisher\\Campaigns\\Test2\\ipad-keyboard.jpg"></p>\r\t\t<p style="text-align: left"><font face="Arial" size="4"><br>A colleague has recommended you to take part in our annual professional development survey.</font></p>\r\t\t<p style="text-align: left"><font face="Arial" size="4">In this survey you will be asked to answer brief questions related to your career and future goals.</font></p>\r\t\t<p style="text-align: left"><font face="Arial" size="4">As our \x93thank you\x94 for completing this survey, you will be sent a complimentary $10 gift card, and you will be entered to <b>win a new iPad3!</b></font></p>\r\t\t<p style="text-align: center"><a href="{{ url.webserver }}"><br><br><img src="\\\\aoins.com\\rootitsec\\itsec\\\\King Phisher\\Campaigns\\Test2\\StartNowButton.png"></a></p>\r\t\t</p>\r\n\t</body>\r\n</html>', 1167, 1168, 'invalid start byte')
Error UID: 37fe999d-5e7d-44f8-a4e4-d96da11f024d
RPC Error: N/A (Not an RPC error)
King Phisher Version: 0.3.0
Platform Version: Windows: 7 6.1.7601 SP1 Multiprocessor Free (Frozen=True)
Python Version: 2.7.9
Gtk Version: 3.8.9

Traceback (most recent call last):
  File "Y:\KingPhisher\king_phisher\client\tabs\mail.py", line 844, in signal_notebook_switch_page
  File "Y:\KingPhisher\king_phisher\client\tabs\mail.py", line 476, in show_tab
  File "Y:\KingPhisher\king_phisher\client\tabs\mail.py", line 440, in load_html_file
  File "c:\python\32-bit\2.7\lib\codecs.py", line 668, in read
  File "c:\python\32-bit\2.7\lib\codecs.py", line 474, in read
UnicodeDecodeError: 'utf8' codec can't decode byte 0x93 in position 1167: invalid start byte

**Comment by zeroSteiner** [comment]
That's a different error message. It's complaining that you have an invalid (non-ascii) character in your message HTML. I would load the HTML into a text editor and remove the invalid character.

**Comment by snider14** [comment]
okay I used a previous phishing html document and it allows me to click on both tabs, so we are just looking at the sending issue. same thing happens with a working html

**Comment by zeroSteiner** [comment]
After looking at the stack trace more it looks like your HTML is encoded using `windows-1252` and not UTF-8. You should be able to fix the issue by converting the HTML to UTF-8. Most text editors allow you to select the encoding, and I'm pretty sure Notepad++ can do this. King Phisher only supports UTF-8 encoding for both the client and server so all input files (message templates, server pages, etc.) need to be encoded that way.

**Comment by snider14** [comment]
this change had no impact on the sending issue

**Comment by snider14** [comment]
still says "checking the target url... success, done." and nothing else and no email is delivered.

**Comment by zeroSteiner** [comment]
It's possible that the previous messages left it in an unclean state. You should try restarting the client application and see if you get a different error message. Other wise if you do not, I don't have enough details to be able to troubleshoot this. There should be another error dialog that should appear. Otherwise it's likely an issue with one of the input files encoding / format or one of the other settings.

**Comment by snider14** [comment]
restarted and it worked!!! Thanks so much for the help.

**Comment by zeroSteiner** [comment]
Fantastic! I'm going to go ahead and close this issue since I've pushed up fixes for the reported SPF bug to the dev branch. I'll also try to add some more documentation to make it clear that files must be UTF-8 encoded to avoid confusion in the future.
