### ISSUE TITLE
Deaddrop connections

### ISSUE THREAD

**Issue by TheThingGoesSkra** [securestate/king-phisher#390]
## Issue Description
Hello, I'm sorry but I don't understand what deaddrop connections are. Even after modifying the client configuration to display the corresponding tab, no information appears despite all the scenario tests I could perform (Wrong ID, No ID, etc...)

## Reproduction Steps
1. Start King Phisher
2. Modify the client configuration => gui.display_deaddrop = true

## Environment Details

Host OS: Ubuntu 16.04 GNOME
King Phisher last version

## Error Details / Stack Trace

There isn't any error, just nothing displayed.

**Comment by wolfthefallen** [comment]
Dead Drop Campaigns and Dead Drop connections is used for campaigns utilizing dropped devices, such as USBs and CDs. This is why Phishing Campaigns display no data in the Dead Drop Connection tab when displayed.

**Comment by zeroSteiner** [comment]
It's not really documented because we haven't made a compatible agent executable publicly available. You're the first external user to ask about it so kudos for reading through the docs and or the source code. This is why the tab isn't displayed by default however.

**Comment by TheThingGoesSkra** [comment]
Thank you. That's good news!  I'm working on adding some features like plugin tracking and I need to modify the graphical interface. I will do a fork this will maybe be interest you. You're doing a great job!

**Comment by zeroSteiner** [comment]
Cool! Yeah feel free to send us a PR if you'd like us to look at adding your work.
