### ISSUE TITLE
Problem installing on Kali Linux

### ISSUE THREAD

**Issue by JoneSodaaa** [securestate/king-phisher#391]
## Issue Description
I experience an issue when I try to do a fresh install of king-phisher on Kali

## Reproduction Steps
Uninstall previous version preloaded
Pull a new install from Git

## Environment Details

Kali GNU/Linux Rolling
king-phisher install from Git

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```
INFO: Linux version detected as Kali
INFO: Git repo found at /opt/king-phisher
INFO: Synchronizing Kali OS dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package pkg-config is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libfreetype6-dev
E: Package 'python3-dev' has no installation candidate
E: Package 'pkg-config' has no installation candidate
pip 19.1.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libpq-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libgeos++-dev
E: Couldn't find any package by regex 'libgeos++-dev'
E: Unable to locate package libgirepository1.0-dev
E: Couldn't find any package by glob 'libgirepository1.0-dev'
E: Couldn't find any package by regex 'libgirepository1.0-dev'
E: Unable to locate package libgtk-3-dev
E: Package 'libpq-dev' has no installation candidate
E: Package 'libpq-dev' has no installation candidate
ERROR: Failed to install dependencies with apt-get

**Comment by wolfthefallen** [comment]
the install script is failing because it is not finding the required system packages from `apt`. You need to check and verify:

1) That your [repository list](https://docs.kali.org/general-use/kali-linux-sources-list-repositories) is correct
2) Your system has internet access can reach the repository sites. Some time proxies will block the repositories.

I also recommend your system is completely up-to-date `apt update && apt upgrade` prior to installing King Phisher on Kali Rolling.

**Comment by JoneSodaaa** [comment]
This is what is in my repository list: 

# deb cdrom:[Debian GNU/Linux 2018.3 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20180731-08:39]/ kali-last-snapshot contrib main non-free

#deb cdrom:[Debian GNU/Linux 2018.3 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20180731-08:39]/ kali-last-snapshot contrib main non-free

# This system was installed using small removable media
# (e.g. netinst, live or single CD). The matching "deb cdrom"
# entries were disabled at the end of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual.

**Comment by wolfthefallen** [comment]
Please reference the link in my previous post about repository list for Kali Rolling
