### ISSUE TITLE
Legend boxes are not displayed

### ISSUE THREAD

**Issue by TheThingGoesSkra** [securestate/king-phisher#393]
## Issue Description
The different legend boxes aren't displayed when I check the graph. On the client side, I found that if matplotlib.__version__ == '3.0.2' it skip legend patch for compatibility. But I don't find more leads about how resolve it.  What can I do in order to display the legend boxes plz ?

I already tried to uprade matplotlib thank to :

sudo python3 -m pip install matplotlib --upgrade
sudo apt-get install python-matplotlib --upgrade

But nothing change. I use the new version in the python IDE but not in king-phisher.

## Reproduction Steps
1. Start King Phisher
2. Open dashboard

## Environment Details

Host OS: Ubuntu 16.04 GNOME
King Phisher last version

**Comment by zeroSteiner** [comment]
You don't. That's the work around so you can get graphs at all with that particular version of matplotlib. We are downgrading to version 2.2.4 for compatibility reasons in the next release though.

We opened an upstream issue with matplotlib/matplotlib#12892 to track this which was then marked as a duplicate. You might be able to manually upgrade to matplotlib 3.0.3 but it might break other things. Again, we're downgrading to version 2.2.4 and that change is already in the `dev` branch which you can access by [opting into beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

**Comment by TheThingGoesSkra** [comment]
I am sorry, but how can I downgrade matplotlib in my project plz ? "sudo python3 -m pip" and
"sudo apt-get install" don't change the versions use in the project (.venv/lib/python3.7/sites-packages/matplotlib...)

**Comment by zeroSteiner** [comment]
You can opt into beta testing like I mentioned above, or wait until the next release which will be within the next week.
