### ISSUE TITLE
numpy.core._multiarray_umath not found

### ISSUE THREAD

**Issue by Quixus** [securestate/king-phisher#394]
When I start the KingPhisher client I get the following error message:
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
I have installed numpy, but the message persists.
KingPhisher otherwise seems to work correctly.

What can I do to get rid of the error?

**Comment by wolfthefallen** [comment]
`sudo ./KingPhisher --env-update`

**Comment by zeroSteiner** [comment]
Looks related to https://github.com/numpy/numpy/issues/11871

**Comment by wolfthefallen** [comment]
@zeroSteiner Could be the `--env-update` should resolve the issue as it forces a reinstall of the required packages in the pipenv environment.

**Comment by Quixus** [comment]
Thanks the env update helped
