### ISSUE TITLE
KingPhisher is a scam

### ISSUE THREAD

**Issue by CarnageKeith3301** [securestate/king-phisher#395]
KingPhisher doesn't work guys, and it's out dated. if you wanna do SE attacks do it without programs. none of the free programs actually work

**Comment by zeroSteiner** [comment]
Thanks for your feedback, we always appreciate hearing from the community. I can assure you that King Phisher is functioning but if you're running into a specific issue, we'd be happy to take a look. Feel free to open another issue and provide us with the relevant details as to what's not working.

In regards to it being out dated, I'm not sure which version you're referring to but we just released version [1.14](https://github.com/securestate/king-phisher/releases/tag/v1.14.0) 8 days ago. If that's not up to date enough for you, I might suggest opting into [beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing) as that gets updates more frequently.

I'm going to close this issue out as it's more of a statement than a question or bug report.
