### ISSUE TITLE
Installation Hangs on INFO: Synchronizing King Phisher's pipenv environment

### ISSUE THREAD

**Issue by No0neIsSafe** [securestate/king-phisher#396]
## Issue Description
The installation hangs on the pipenv synchronization step. I have waited for several minutes around 30 then retried and waited for 25-30 minutes. As, referred to by other threads (issues) I tried several time with no luck. Also, I would like to add that am using No proxy

## Reproduction Steps
Run the installation command.
## Environment Details
Host OS: Linux kali 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux
King Phisher Version: 1.14.0

## Error Details / Stack Trace
`root@kali:/opt# wget -q https://github.com/securestate/king-phisher/raw/master/tools/install.sh && \
> sudo bash ./install.sh
INFO: Linux version detected as Kali
Install and use PostgreSQL? (Highly recommended and required for upgrading) [Y/n] 
INFO: Will install and configure PostgreSQL for the server
INFO: Attempting to update apt-get cache package information
Hit:1 http://kali.download/kali kali-rolling InRelease
Reading package lists... Done   
INFO: Downloading and installing the King Phisher server to /opt/king-phisher
INFO: Successfully cloned the git repo
INFO: Synchronizing Kali OS dependencies
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libfreetype6-dev is already the newest version (2.9.1-4).
pkg-config is already the newest version (0.29-6).
python3-dev is already the newest version (3.7.3-1).
The following packages were automatically installed and are no longer required:
  libavahi-gobject0 libfolks-telepathy25 libgail-3-0 libgcab-1.0-0 libgeos-3.6.2 libgfortran4 libgtk2-perl libmission-control-plugins0
  libopencv-core3.2 libopencv-imgproc3.2 libpango-perl libsane-extras libsane-extras-common libtbb2 libtelepathy-glib0 libunbound2 magictree
  python-backports.ssl-match-hostname python-pam telepathy-mission-control-5 x11proto-dri2-dev x11proto-gl-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1748 not upgraded.
pip 19.2.2 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-gtk-3.0 is already the newest version (3.24.10-1).
gir1.2-gtksource-3.0 is already the newest version (3.24.9-2).
libgeos++-dev is already the newest version (3.7.2-1).
libgirepository1.0-dev is already the newest version (1.58.3-2).
libgtk-3-dev is already the newest version (3.24.10-1).
libpq-dev is already the newest version (11.4-1).
python3-cairo is already the newest version (1.16.2-1+b1).
python3-gi is already the newest version (3.32.2-1).
python3-gi-cairo is already the newest version (3.32.2-1).
The following packages were automatically installed and are no longer required:
  libavahi-gobject0 libfolks-telepathy25 libgail-3-0 libgcab-1.0-0 libgeos-3.6.2 libgfortran4 libgtk2-perl libmission-control-plugins0
  libopencv-core3.2 libopencv-imgproc3.2 libpango-perl libsane-extras libsane-extras-common libtbb2 libtelepathy-glib0 libunbound2 magictree
  python-backports.ssl-match-hostname python-pam telepathy-mission-control-5 x11proto-dri2-dev x11proto-gl-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1748 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-vte-2.91 is already the newest version (0.54.2-2).
The following packages were automatically installed and are no longer required:
  libavahi-gobject0 libfolks-telepathy25 libgail-3-0 libgcab-1.0-0 libgeos-3.6.2 libgfortran4 libgtk2-perl libmission-control-plugins0
  libopencv-core3.2 libopencv-imgproc3.2 libpango-perl libsane-extras libsane-extras-common libtbb2 libtelepathy-glib0 libunbound2 magictree
  python-backports.ssl-match-hostname python-pam telepathy-mission-control-5 x11proto-dri2-dev x11proto-gl-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1748 not upgraded.
INFO: Successfully installed gir1.2-webkit2-4.0 with apt-get
INFO: Synchronizing Python package dependencies from PyPi
pip 19.2.2 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
Requirement already up-to-date: pip in /usr/local/lib/python3.7/dist-packages (19.2.2)
pip 19.2.2 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
Requirement already up-to-date: setuptools in /usr/local/lib/python3.7/dist-packages (41.1.0)
Requirement already up-to-date: six in /usr/lib/python3/dist-packages (1.12.0)
Requirement already satisfied: pipenv in /usr/local/lib/python3.7/dist-packages (2018.11.26)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /usr/local/lib/python3.7/dist-packages (from pipenv) (0.5.3)
Requirement already satisfied: virtualenv in /usr/local/lib/python3.7/dist-packages (from pipenv) (16.7.2)
Requirement already satisfied: pip>=9.0.1 in /usr/local/lib/python3.7/dist-packages (from pipenv) (19.2.2)
Requirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.7/dist-packages (from pipenv) (41.1.0)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from pipenv) (2018.8.24)
INFO: Synchronizing King Phisher's pipenv environment
`

**Comment by wolfthefallen** [comment]
Synchronizing King Phisher's pipenv environment can take an extended length of time depending on the speed of your internet connection and processing power. I have seen it take 15 minutes before..

Navigate to your King Phisher folder, by default this would be `/opt/king-phisher/` and run `export PIPENV_VENV_IN_PROJECT=True && pipenv --site-packages install` 

This will provide you a more verbose output of what it is doing to set up King Phisher's pipenv environment, and will let you know if any issues occur.
