### ISSUE TITLE
ModuleNotFoundError: No module named 'paramiko'

### ISSUE THREAD

**Issue by Allen-Paul** [securestate/king-phisher#397]
Hi,
I've been running phishing awareness campaigns in my company through GoPhish with a VPS in digitalocean and I thought I would try out KingPhisher as part of the expansion that my company is going through; but no matter how much ever time I try to install KingPhisher, I'm not able to get it running.
I get the following error
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/Projects/Threat_Simulation/Tools/kingPhisher/king-phisher-1.14.0/king_phisher/client/__main__.py", line 48, in <module>
    from king_phisher.client import application
  File "/root/Projects/Threat_Simulation/Tools/kingPhisher/king-phisher-1.14.0/king_phisher/client/application.py", line 53, in <module>
    from king_phisher import ssh_forward
  File "/root/Projects/Threat_Simulation/Tools/kingPhisher/king-phisher-1.14.0/king_phisher/ssh_forward.py", line 46, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'

# I tried force reinstalling paramiko module but again it results in the same error.
the module does exist as during the process of re installation it says the following

 #pip3 install paramiko
Requirement already satisfied: paramiko in /usr/local/lib/python3.6/dist-packages (2.6.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from paramiko) (1.3.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib/python3.6/dist-packages (from paramiko) (2.7)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.6/dist-packages (from paramiko) (3.1.7)
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from pynacl>=1.0.1->paramiko) (1.12.3)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from pynacl>=1.0.1->paramiko) (1.12.0)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.6/dist-packages (from cryptography>=2.5->paramiko) (0.24.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko) (2.19) 

I'm not sure on how to resolve this issue and any help would be much appreciated.

regards,
Allen Paul

**Comment by wolfthefallen** [comment]
Allen,

King Phisher uses `pipenv` to create a python environment just for itself. There are three options you can do to resolve this issue, which can be found on our [FAQ](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#importerror-no-module-named-error-when-starting-king-phisher).

**Comment by Allen-Paul** [comment]
now a different module is showing the error, 
root@SRVR:~//Threat_Simulation/Tools/king-phisher# ./KingPhisherServer server_config.yml 
Loading .env environment variables…
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/Projects/Threat_Simulation/Tools/king-phisher/king_phisher/server/__main__.py", line 46, in <module>
    from king_phisher import geoip
  File "/root/Projects/Threat_Simulation/Tools/king-phisher/king_phisher/geoip.py", line 46, in <module>
    import geoip2.database
ModuleNotFoundError: No module named 'geoip2'

root@SRVR:~//Threat_Simulation/Tools/king-phisher# pip3 install geoip2==2.9.0
Requirement already satisfied: geoip2==2.9.0 in /usr/local/lib/python3.6/dist-packages (2.9.0)
Requirement already satisfied: maxminddb>=1.4.0 in /usr/local/lib/python3.6/dist-packages (from geoip2==2.9.0) (1.4.1)
Requirement already satisfied: requests>=2.9 in /usr/local/lib/python3.6/dist-packages (from geoip2==2.9.0) (2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.9->geoip2==2.9.0) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.9->geoip2==2.9.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.9->geoip2==2.9.0) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.9->geoip2==2.9.0) (2.6)


I tried reinstalling the whole python manually and even reinstalled king phisher, but no progress.

**Comment by zeroSteiner** [comment]
You're not supposed to install packages through pip, they need to be done through pipenv to be placed in King Phisher's environment. This should have been setup and taken care of for you when you installed, but you can explicitly install the necessary packages like `geoip2` by running `PIPENV_VENV_IN_PROJECT=True pipenv --site-packages install` from the King Phisher directory.

If you continue to have issues please post the output from that command, it can be a little large so feel free to put it in a gist / on pastebin or whatever.

**Comment by Allen-Paul** [comment]
okay thank you we have got that to working. We had installed as you said only, so I guess it was a glitch.

Can you please explain these two as well
1)why at time we need to run pipenv shell (virtual environment) to run the client and sometimes it doesnt.
2) why does this error pop up

Gtk-Message: 13:46:13.403: Failed to load module "canberra-gtk-module"

(__main__.py:15725): GLib-GIO-CRITICAL **: 13:46:13.404: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Gtk-Message: 13:46:16.651: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:46:16.676: Failed to load module "canberra-gtk-module"


regards.

**Comment by Allen-Paul** [comment]
Thank you for the support.
