### ISSUE TITLE
Creating a Data Entry Campaign

### ISSUE THREAD

**Issue by snider14** [securestate/king-phisher#40]
We are wondering what is the best method to creating a data entry campaign and is it possible for King Phisher to keep track of people who click on email link and separately who enters data in the form and submits? Basically what we have right now is an email sent by King Phisher with a link to a page hosted on our internal King Phisher server where they are asked to enter information. Once done and they attempt to continue with survey, we send them to the informational page letting them know they were "phished". We want to keep track of both counts (who clicked on phishing email link and who clicked the link and submitted information on the survey form). Is this possible within King Phisher alone? Thanks!

**Comment by zeroSteiner** [comment]
That's not directly supported right now. You might be able to simulate the data entry by setting the HTML form field to be named username and password and the data would then be stored in the credentials tab. This would be limited to storing two fields of information though. Doing it that way you would be able to track the people that submitted data back to the email that was sent just as if it was a credential.

**Comment by snider14** [comment]
Thanks for the information!

**Comment by zeroSteiner** [comment]
No problem, I'm going to close this out for now. If you have another question feel free to follow up or open a new ticket.
