### ISSUE TITLE
SSH Keys

### ISSUE THREAD

**Issue by TheThingGoesSkra** [securestate/king-phisher#402]
# Feature Description
Hello, I don't understand the documentation with regard to how can we connect ourself using an SSH  key pair (.pem) directly from the client ? Can you give me more details plz.

I'm on Kali linux, my ssh-agent and the ssh-add command doesn't work. I don't understand how to use Seahorse too... A new key is generated everytime but I'm working on amazon aws and I need to use their keys.

**Comment by zeroSteiner** [comment]
Well if your SSH agent isn't working you're going to have to manually add the key you want to use in to your configuration file. The documentation for how to do that is in the [User Authentication](https://github.com/securestate/king-phisher/wiki/Server-Authentication#user-authentication) section of the wiki. **Make sure the King Phisher client is not running when you edit the config or your changes will be overwritten.**

There's a few formats that the key can be specified in. Make sure it doesn't use a password, you can't use a key with a password unless you use your SSH agent.

**Comment by TheThingGoesSkra** [comment]
Ok, I was thinking that the "ssh_preferred_key" field took only the fingerprint generated by my ssh-agent as parameter in order to choose the good key if the user has multiple SSH keys.

Sorry, It's works now ! thanks you very much.

**Comment by zeroSteiner** [comment]
Good to hear, thanks for letting us know the issue is resolved.

**Comment by Ghostfacexx** [comment]
its redicilously retarded how bad that thing king phisher is made .....absolutelly impossible to run,
