### ISSUE TITLE
variable -friendly alias support chinese?

### ISSUE THREAD

**Issue by greed5566** [securestate/king-phisher#404]
# Feature Description

Does **variable** friendly alias support chinese ? 
## Example Use Case

I have tried using chinese as friendly alias ,and this variable couldn't work correctly.
How can I modify config to make it right or this may be support in the future ?

**Comment by zeroSteiner** [comment]
Can you please provide me a test name to use as the friendly alias and the error message you're receiving when you try to use it?

**Comment by greed5566** [comment]
![Chinese_friendly_result_2](https://user-images.githubusercontent.com/48907794/65737700-f1447580-e111-11e9-85ca-b13b54bdb9d9.png)
![Chinese_friendly_result](https://user-images.githubusercontent.com/48907794/65737701-f1dd0c00-e111-11e9-837a-5800bb7fa0f1.png)

It doesn't have error message but it shows different result as type friendly alias in english.

**Comment by zeroSteiner** [comment]
I don't understand what the different results are of one versus the other. Is the image you're showing of what you'd expect to see or of what you're actually seeing?

**Comment by greed5566** [comment]
When I use chinese as alias , you can see double quotes in the  sender as  last posted.
But in the english alias, you don't see the problem. 
![English_alian](https://user-images.githubusercontent.com/48907794/66465990-80f40780-eab4-11e9-9942-77bfb4332025.png)

Maybe encoding problem?
