### ISSUE TITLE
what localhost:22 username and password

### ISSUE THREAD

**Issue by nomankhan05001** [securestate/king-phisher#406]
## Issue Description
I experience an issue when I... and the results I expected are...

## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Environment Details

Host OS: Ubuntu 18.04 GNOME, Kali 2, etc.
King Phisher Version: x.y.z

## Error Details / Stack Trace

```
If you are opening an issue regarding the client, copy text from the "Error
Details" of the error dialog in the client here. If you are opening an issue
regarding the server copy the relevant lines from the logs here.
```

**Comment by zeroSteiner** [comment]
There isn't a default value for the credentials. This is covered in the FAQ here https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#what-are-the-default-credentials.
