### ISSUE TITLE
server starts at kali boot

### ISSUE THREAD

**Issue by sh1va73** [securestate/king-phisher#408]
When I boot Kali then I get a message that KingPhisher server is started. Can I prevent that? I only want to start that server manually.

**Comment by wolfthefallen** [comment]
`systemctl disable king-phisher` then you can start and stop it manually with `systemctl start king-phisher` and `systemctl stop king-phisher`

**Comment by zeroSteiner** [comment]
@wolfthefallen is correct. Disable the service with `systemctl` to prevent it from starting automatically on boot. If the command fails, double check that you're running as root (since you're using Kali this should be the case).

**Comment by sh1va73** [comment]
Thanks, I tried and it works perfectly.
