### ISSUE TITLE
Issue accessing image files from King Phisher server

### ISSUE THREAD

**Issue by snider14** [securestate/king-phisher#41]
We are having trouble accessing image files off the King Phisher server for the phishing email sent to associates. This is to ensure that all users can see the images in the email, but it seems like it needs to know the campaign when accessing these images. Do you have any info on this?

We obviously already have the images for the landing page on the King Phisher server, but we would also like to have the email images stored there as well. Thanks!

**Comment by zeroSteiner** [comment]
Yes, I know exactly whats wrong and you have two options to fix it. It sounds like you have the `require_id` set to true which is a good idea.

You can either send the images inline, go to the editor in the King Phisher client and right click, select Insert > Inline Image. This has the benefit if showing up in most email clients without requiring the user to "load external resources".

The other option is you can append the message id to the end of the URL. So if the image url is `http://king-phisher.com/images/cat.jpg`, you'd change it to `http://king-phisher.com/images/cat.jpg?uid={{ client.message_id }}`. This will allow the image to be hosted on the server, resulting in a smaller email but will also cause visits to appear if the image is just loaded. So if the user loads the external resources and shows the image, it will count as a visit without them actually clicking the link and visiting the landing page. If they do visit the landing page that will still be tracked separately as the browser will start a new session.

Finally you could technically disable the `require_id` setting but I personally recommend the inline image method.

**Comment by snider14** [comment]
by inline you are referring to the edit tab within the tool?

**Comment by snider14** [comment]
Oh I see exactly what you are talking about. would this inline syntax go directly in place of the image path? so for me I am using <img src= then the path.

**Comment by zeroSteiner** [comment]
The img tag will be included automatically so just use the jinja2 function
that's inserted when you right click.

**Comment by snider14** [comment]
Everything works now except for an image that needs to be aligned to the right. I just need to be able to format this inline image.

**Comment by zeroSteiner** [comment]
Try putting the `{{ inline_image('') }}` within span tags to float right like: `<span style="float: right">{{ inline_image('') }}</span>`.

**Comment by snider14** [comment]
the float tag does not work with in span tags or paragraph tags. the image is displaying just not aligning to the correct spot. Thanks for the ongoing help!

**Comment by snider14** [comment]
Here is the line of code that worked before with the different parts of the path whited out.
![image](https://cloud.githubusercontent.com/assets/14295632/10228813/cd6f1f8a-6842-11e5-8aa7-802ed01b40ef.png)

**Comment by snider14** [comment]
Then for the body content or verbiage I have the different lines in their own <p tags where text-align is to the left. this allows the image to always show up directly to the right on the content.

**Comment by zeroSteiner** [comment]
If you need to be able to style it and modify the tag it might be better to not use the inline method. The reason is, for the image to be attached the `inline_image` Jinja function must be called. Using an `<img src="\\some\local\path...` won't cause the image to be attached correctly. This is a bit beyond my basic HTML styling skills.

**Comment by zeroSteiner** [comment]
I added an optional `style` argument to the `inline_image` Jinja function which when specified will populate the style attribute of the img tag. This will be included in the 1.0.0 release scheduled for later this week. With that change I'm going to close this issue as everything should be resolvable through HTML changes.
