### ISSUE TITLE
How to assign a hostname through DNS

### ISSUE THREAD

**Issue by Azuredragon-eazy** [securestate/king-phisher#411]
How do i include my domain in kingphisher, i dont know what nameserver to point to and how to host it in kingphisher, any help is appreciated.

**Comment by zeroSteiner** [comment]
Assuming you own the domain, you'd just go into the configuration and point one or more A records to the IP address of the King Phisher server.

For example if you bought the domain through GoDaddy you'd do this through your GoDaddy account.
