### ISSUE TITLE
how do i start the kingphisher server

### ISSUE THREAD

**Issue by Azuredragon-eazy** [securestate/king-phisher#412]
am having the following errors whenever i start the king phisher server

sudo ./KingPhisherServer
usage: KingPhisherServer [-h] [-f] [--update-geoip-db] [--verify-config]
                         [--env-install | --env-update] [--env-verbose] [-v]
                         [-L {DEBUG,INFO,WARNING,ERROR,FATAL}]
                         [--logger LOGGER] [--gc-debug-leak]
                         [--gc-debug-stats]
                         config_file
KingPhisherServer: error: the following arguments are required: config_file

i try the command for the config_file and i also have the following errors again.

./KingPhisherServer server_config.yml
Loading .env environment variables…
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/king-phisher/king_phisher/server/__main__.py", line 42, in <module>
    from king_phisher import color
  File "/opt/king-phisher/king_phisher/color.py", line 41, in <module>
    import termcolor
ModuleNotFoundError: No module named 'termcolor'

**Comment by zeroSteiner** [comment]
If you've installed it correctly you start it through systemd using `sudo systemctl start king-phisher`.

This error however makes it look like the dependencies haven't been installed. Have you run the installer script in `tools/install.sh`?

**Comment by Azuredragon-eazy** [comment]
Yea i run the installer script but i skip the client because i already have clients installed.

**Comment by zeroSteiner** [comment]
Okay so then something is wrong because those dependencies should have been installed for you. 

From the King Phisher directory, run `PIPENV_VENV_IN_PROJECT=True sudo -E pipenv --site-packages install`, and see if you can then start the server.

**Comment by Azuredragon-eazy** [comment]
am still having the following error whener i start the kingphisher


*"Job for king-phisher.service failed because the control process exited
with error code.See "systemctl status king-phisher.service" and "journalctl
-xe" for details."*

and when check status i receive the following errors















*● king-phisher.service - King Phisher Server   Loaded: loaded
(/lib/systemd/system/king-phisher.service; enabled; vendor pre   Active:
failed (Result: exit-code) since Wed 2019-11-20 10:44:40 WAT; 2min 43
Process: 3131 ExecStart=/usr/bin/python3
/opt/king-phisher/KingPhisherServer /Nov 20 10:44:40 kali python3[3131]:
File "/usr/lib/python3.7/runpy.py", line 8Nov 20 10:44:40 kali
python3[3131]:     exec(code, run_globals)Nov 20 10:44:40 kali
python3[3131]:   File "/opt/king-phisher/king_phisher/serveNov 20 10:44:40
kali python3[3131]:     from king_phisher import colorNov 20 10:44:40 kali
python3[3131]:   File "/opt/king-phisher/king_phisher/colorNov 20 10:44:40
kali python3[3131]:     import termcolorNov 20 10:44:40 kali python3[3131]:
ModuleNotFoundError: No module named 'termcoNov 20 10:44:40 kali
systemd[1]: king-phisher.service: Control process exited, cNov 20 10:44:40
kali systemd[1]: king-phisher.service: Failed with result 'exit-Nov 20
10:44:40 kali systemd[1]: Failed to start King Phisher Server.*

**Comment by zeroSteiner** [comment]
Well did you run the command I told you to run?

**Comment by ik-dELTA** [comment]
> Well did you run the command I told you to run?

currently facing a similar challenge. after running the cmd it says ''virtual env already exists'' . can't seem to understand how to start and configure the server
