### ISSUE TITLE
CONNECTION ERROR

### ISSUE THREAD

**Issue by tuts19** [securestate/king-phisher#419]
## Issue Description
Hi ZeroSteiner 

when i start king-phisher with /opt/king-phisher/KingPhisher i get the following error 

WARNING  it is not necessary to run the king phisher client as root

(King Phisher:16976): Gtk-WARNING **: 06:56:50.163: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "RegisterClient" with signature "ss" on interface "org.xfce.Session.Manager" doesn't exist

## Reproduction Steps
1. Start King Phisher
2. login

## Environment Details

Host OS: Ubuntu 18.04 

## Error Details / Stack Trace
CONNECTION ERROR
Socket error #N/A  (Error)
Secsh channel 0 open FAILED: Connection refused: Connect failed
.
```

**Comment by zeroSteiner** [comment]
It looks like you're trying to run it in XFCE instead of Gnome. I'm not sure you can do that since it's all written in GTK.

**Comment by tuts19** [comment]
after installing king phisher on new Host OS: Ubuntu 18.04 gnome, i can't seem to get server running or connect to server

root@server:~# systemctl status king-phisher.service
● king-phisher.service - King Phisher Server
Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor pre
Active: failed (Result: timeout) since Tue 2020-01-14 07:13:58 PST; 1h 17min


Jan 14 07:12:31 server.brodwayed.net su[10062]: pam_unix(su:session): session opened for user postgres by (uid=0)
Jan 14 07:12:32 server.brodwayed.net su[10062]: pam_unix(su:session): session closed for user postgres
Jan 14 07:12:32 server.brodwayed.net su[10084]: Successful su for postgres by root
Jan 14 07:12:32 server.brodwayed.net su[10084]: + ??? root:postgres
Jan 14 07:12:32 server.brodwayed.net su[10084]: pam_unix(su:session): session opened for user postgres by (uid=0)
Jan 14 07:12:32 server.brodwayed.net su[10084]: pam_unix(su:session): session closed for user postgres
Jan 14 07:12:32 server.brodwayed.net python3[10045]: CRITICAL server failed to build with error: database initialization
Jan 14 07:13:58 server.brodwayed.net systemd[1]: king-phisher.service: Start operation timed out. Terminating.
Jan 14 07:13:58 server.brodwayed.net systemd[1]: king-phisher.service: Failed with result 'timeout'.
Jan 14 07:13:58 server.brodwayed.net systemd[1]: Failed to start King Phisher Server
lines 1-14/14 (END)
