### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by tuts19** [securestate/king-phisher#421]
## Issue Description
I experience an issue when I try to start king phisher server with errors
after installing king phisher on new Host OS: Ubuntu 18.04 gnome, i can't seem to get server running or connect to server

## Reproduction Steps
1. Start King Phisher
2. systemctl status king-phisher.service

## Environment Details

Host OS: Ubuntu 18.04 GNOME

## Error Details / Stack Trace

root@server:~# systemctl status king-phisher.service
● king-phisher.service - King Phisher Server
Loaded: loaded (/lib/systemd/system/king-phisher.service; enabled; vendor pre
Active: failed (Result: timeout) since Tue 2020-01-14 07:13:58 PST; 1h 17min

Jan 14 07:12:31 server.brodwayed.net su[10062]: pam_unix(su:session): session opened for user postgres by (uid=0)
Jan 14 07:12:32 server.brodwayed.net su[10062]: pam_unix(su:session): session closed for user postgres
Jan 14 07:12:32 server.brodwayed.net su[10084]: Successful su for postgres by root
Jan 14 07:12:32 server.brodwayed.net su[10084]: + ??? root:postgres
Jan 14 07:12:32 server.brodwayed.net su[10084]: pam_unix(su:session): session opened for user postgres by (uid=0)
Jan 14 07:12:32 server.brodwayed.net su[10084]: pam_unix(su:session): session closed for user postgres
Jan 14 07:12:32 server.brodwayed.net python3[10045]: CRITICAL server failed to build with error: database initialization
Jan 14 07:13:58 server.brodwayed.net systemd[1]: king-phisher.service: Start operation timed out. Terminating.
Jan 14 07:13:58 server.brodwayed.net systemd[1]: king-phisher.service: Failed with result 'timeout'.
Jan 14 07:13:58 server.brodwayed.net systemd[1]: Failed to start King Phisher Server
lines 1-14/14 (END)

**Comment by zeroSteiner** [comment]
Can you start the server in the foreground with debugging output and post it here.
