### ISSUE TITLE
ZeroDivisionError When Loading 0 Campaigns

### ISSUE THREAD

**Issue by zeroSteiner** [securestate/king-phisher#425]
I have reset password and it has been updated on my server_config.yml file, still trying to connect localhost:22 port 80 and using ssh credential takes me to campaign tab with error message below. and link to screenshot   https://imgur.com/a/zRRyqeE

Error Type: builtins.ZeroDivisionError
Error Details: ZeroDivisionError('division by zero',)
Error UID: 8b8093a6-f05e-41f7-bddf-5402879df86b
RPC Error: N/A (Not an RPC error)
King Phisher Version: 1.16.0-beta (rev: 51185b4a2afd)
Platform Version: Linux: Ubuntu 18.04 bionic
Python Version: 3.6.9
Gtk Version: 3.22.30
Timezone: America/Los_Angeles

Thread Information:
===================
=> MainThread (alive=True daemon=False)
RPCAsyncWorker (alive=True daemon=False)
ServerEventsDispatcher (alive=True daemon=True)

Stack Trace:
============
Traceback (most recent call last):
File "/opt/king-phisher/king_phisher/client/gui_utilities.py", line 176, in wrapper
function(*args, **kwargs)
File "/opt/king-phisher/king_phisher/client/dialogs/campaign_selection.py", line 249, in __async_rpc_cb_load_campaigns
progress = len(self._tv_model) / campaigns['total']
ZeroDivisionError: division by zero

_Originally posted by @gviva17 in https://github.com/securestate/king-phisher/issues/423#issuecomment-579608032_

**Comment by zeroSteiner** [comment]
Originally reported at the end of #423, the issue looks to be pretty straight forward. There's a `ZeroDivisionError` when the progress is rendered for loading campaigns.

**Comment by gviva17** [comment]
Thanks for the reply, How do i know when bug is be fixed?

**Comment by zeroSteiner** [comment]
You follow this ticket. Now that you've commented on it you're "participating" and should get notices unless you unsubscribe. I'll comment on it when it's resolved and I close it.

**Comment by gviva17** [comment]
ok thanks.

**Comment by zeroSteiner** [comment]
Fixed in commit d8b1105f2416b2ffb660b26b50e5eb7685e15e50. The bug was pretty easy to track down and fix by checking if there are any campaigns before calculating progress.

**Comment by gviva17** [comment]
thanks, so is there something are suppose to do on my end like up king-phisher?

**Comment by zeroSteiner** [comment]
Yeah, update King Phisher. There's a page in the wiki that explains how to do it.

**Comment by gviva17** [comment]
thanks alot
