### ISSUE TITLE
inline image problem

### ISSUE THREAD

**Issue by greed5566** [securestate/king-phisher#427]
## Issue Description
I  found  the quote from  King Phisher Documentation  on Version 1.0.0"Support for specifying an img style attribute for inline images in messages" 

Can you give me a example How to use above description 
I have tried many times and I couldn't find the right way to use it

Thanks

**Comment by zeroSteiner** [comment]
I don't recommend you do it manually. Instead, right click in the HTML and select Insert Inline Image from the context menu. It'll open a file chooser dialog where you can then select your image.

That's the easiest way to do it.
