### ISSUE TITLE
export to csv not available in 1.0.0?

### ISSUE THREAD

**Issue by pahtzo** [securestate/king-phisher#46]
It appears csv flat file export of campaign results has been replaced with XML export.  How can I import that XML file into a spreadsheet for parsing the results so it joins the proper target with their respective actions?

**Comment by zeroSteiner** [comment]
CSV wasn't removed, however it was never available from the File Export menu. CSV exporting support is still in the "View Campaign" tab, just select Messages, Visits, or Credentials and in the bottom left is an "Export" button for that specific set of data.

**Comment by pahtzo** [comment]
OK, I was looking at the credentials tab which only has show password.  As you suggested in one of our email threads, I am collecting alternate landing page clicks in the credentials table.  Now need to export those.  I'm looking at creating a view with pgadmin3 to dump it all out but that's going to add a step to the process.

**Comment by zeroSteiner** [comment]
Ah, yes credentials doesn't have CSV export, my mistake. You could select all rows in the table with Control A, then right click Copy > All and that will copy them all using spaces as delimiters. That will work in the other tables as well.

**Comment by pahtzo** [comment]
No trouble, I wasn't very clear on that to begin with.  I'll take a look at the tables and see what sql query I can come up with to dump it all with proper joins for the fields I'm looking for.  The detailed reporting side is where I end up spending too much time slicing and dicing the export files.

**Comment by zeroSteiner** [comment]
OK then since it sounds like you know the direction you're going to go in, I'm going to close out this issue. We're looking into better options for reporting but that's still quite a ways away from being completed.
