### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by DrDinosaur** [securestate/king-phisher#47]
Error Type: exceptions.TypeError
Error Details: TypeError("Couldn't find foreign struct converter for 'cairo.Context'",)
Error UID: f7af1181-ebbe-4ede-ae48-c81985e1e30e
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.0.0
Platform Version: Linux: Kali 2.0 sana
Python Version: 2.7.9
Gtk Version: 3.14.5

TypeError: Couldn't find foreign struct converter for 'cairo.Context'

**Comment by zeroSteiner** [comment]
Thank you for the bug report. There isn't much of a stack trace here, can you describe what you were doing when it happened?

**Comment by DrDinosaur** [comment]
I was clicking on the various tabs.

**Comment by zeroSteiner** [comment]
Thanks for reporting this issue, I'll keep an eye out for it. Given that there is not much of a stack trace and not a specific action that caused the issue I can't reproduce this. In the future, the error text will include some basic information about threads which may help to identify other scenarios where the stack trace is a frame deep.
