### ISSUE TITLE
Reuse Email 

### ISSUE THREAD

**Issue by DrDinosaur** [securestate/king-phisher#48]
Hi,

I'm trying to reuse an email I got from some organization as a template. I go under "show original" and copy the contents (excluding the headers), but when I preview the email under the preview tab, it looks nothing like the original email. How can I reuse this newsletter type email template? Cobalt Strike has this implemented well I think. 

Thanks

**Comment by zeroSteiner** [comment]
Can you describe what exactly is not looking correct in the preview tab? I've done this myself with a few emails without experiencing any issues. The only thing I can think of is if images are included inline then you'll need to download those individually and place them inline using the editor.

**Comment by DrDinosaur** [comment]
The rendering was quite off, so it looked like there was an obvious error. I'm not sure how to describe it right now other than to say the parsing was probably not working properly. Sorry, I haven't used it in a while.

**Comment by zeroSteiner** [comment]
Would you be able to provide screenshots for a comparison?

**Comment by zeroSteiner** [comment]
I'm going to close this out because I don't have enough information to act on. If you get a chance to provide additional details and ideally a screen shot feel free to re open it.
