### ISSUE TITLE
Using message template variables in email subject

### ISSUE THREAD

**Issue by mozg31337** [securestate/king-phisher#57]
Hi

I was wondering if message template variables could be used in the email Subject field and perhaps other fields like Friendly Alias, Company Name, etc?

I tried using {{client.first_name}} in the Subject and it didn't work.
Thanks

**Comment by wolfthefallen** [comment]
mozg31337 at this time king-phisher only supports the use of tags in the body of the email. Although this is a great idea for a feature request. I'll take take a look at it and see what we can do.

**Comment by zeroSteiner** [comment]
So this is a pretty delayed response, but this feature has finally been implemented. It's currently resting in the dev branch but will be merged over to master in time.
