### ISSUE TITLE
Support CentOS 6.7

### ISSUE THREAD

**Issue by zeroSteiner** [securestate/king-phisher#64]
Please add support to the install script for installing the server components on CentOS 6.7 (and 6.6 as well if possible). As of today CentOS is only supported for the server not the client and this shouldn't change that.

CentOS 6.x will be supported by their project until Q2 2017 from what I've read. If you have any questions let me know.

**Comment by wolfthefallen** [comment]
CentOS 6.x has python version 2.6 as the base version of python Installed. King-Phisher only supports Python Versions 2.7 and above. Users that want to utilize the King-Phisher server on CentOS 6.x is encouraged to upgrade to the latest version of CentOS to receive support.
