### ISSUE TITLE
tools/install.sh does not install on BackBox v4.5 (checks for 4.[2-4])

### ISSUE THREAD

**Issue by piratica** [securestate/king-phisher#70]
Using BackBox v4.5 and installing King Phisher with the PenTesterFramework.  The installer looks at /etc/issue and sees BackBox Linux 4.5 but it is looking for 4.[2-4] (this is line 123 of tools/install.sh).  Updating the tools/install.sh from 4.[2-4] to 4.[2-5] seems to resolve the issue but I'm not sure if there are dependencies that were overlooked (testing now).

**Comment by zeroSteiner** [comment]
Okay thanks for testing that. Let us know if you run into any trouble with missing dependencies. I'm going to leave this open until we patch it into the install script.

**Comment by piratica** [comment]
I *think* that I did this right (I'm dawning my flame retardant suit though, just in case :) ).  I created a fork, updated the install.sh file to include 4.5.

**Comment by wolfthefallen** [comment]
Piratica, you did that correctly, i'll review it shortly.

**Comment by wolfthefallen** [comment]
@piratica thank you for the pull request. I did notice a theme issue after checking to make sure king-phisher was working as intended. If you are having this issue, you can run king-phisher client with no-style by doing 

```BASH
KingPhisher --no-style
```
We are looking into this issue to update the theme for better support for backbox.

**Comment by piratica** [comment]
Apologies for the delay but I can now confirm that, on Backbox v4.5 (relatively clean install, it's our base image which has PTF installed), we cloned the current repo and installed King-Phisher (it worked out of the box, no need to tweak the install.sh, very cool) and then started the server and the client.  The server started without issue but the client without the --no-style argument had some issues.  With the --no-style argument, it seemed to work but I did not go through a test campaign with it (since the issue appears to be aesthetic only, I expect that a campaign would be unaffected by the bug other than the tester would have to guestimate the location of some fields).

**Comment by zeroSteiner** [comment]
Yeah because the issue was aesthetic only the patch is currently in the dev branch. Planning on merging it over into master on Friday at which point an update will fix the problem. If you're feeling particularly adventurous you too could checkout and test the dev branch. We have steps for it on the wiki under the [Beta Testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing) section.
