### ISSUE TITLE
KingPhisher Client theme issue on backbox

### ISSUE THREAD

**Issue by wolfthefallen** [securestate/king-phisher#73]
BackBox default theme is causing KingPhisher client cause the MailSenderConfigurationTab to appear almost completely white.

Current work around is to run KingPhisher client in no-style

```BASH
KingPhisher --no-style
```

**Comment by piratica** [comment]
I was using an Ubuntu box for the KingPhisher client and don't currently have access to the BackBox server that we we setup.  I can check it tomorrow though and confirm that there are / are not styling issues and will be happy to report back.

**Comment by zeroSteiner** [comment]
Just opened PR #74 to fix this issue. This should be closed out once it has been tested and landed.

**Comment by zeroSteiner** [comment]
PR #74 has been landed to the dev branch so this issue has been fixed. The changes will eventually make their way into master within the next couple weeks.
