### ISSUE TITLE
King fisher config guide for windows

### ISSUE THREAD

**Issue by Hemza** [securestate/king-phisher#75]
## Issue Description
is there a configuration guide for windows version of king fisher , 
## Reproduction Steps
1. Start King Phisher
2. ask me for SSH credentials ??? what are those credentials or default ones if exists

## Error Details / Stack Trace
```
Copy details from the logs or client dialog here.
```

**Comment by zeroSteiner** [comment]
There is a plethora of documentation provided in the [Wiki](https://github.com/securestate/king-phisher/wiki), I highly recommend at least reviewing the [Getting Started](https://github.com/securestate/king-phisher/wiki/Getting-Started) page. The credentials are to connect to the King Phisher server which you must also set up.

**Comment by phathutshedzo1993** [comment]
i am un able to connect to king phisher can you please help how to connect
