### ISSUE TITLE
King fisher ssh credentials for windows

### ISSUE THREAD

**Issue by Hemza** [securestate/king-phisher#76]
## Issue Description
i've install king fisher , but i didnt find config guide for windows version, and when i run kingfisher the first page ask me for credentials, where can i find default credentials  see attached screen captur
## Reproduction Steps
1. Start King Phisher
2. Do something to trigger the crash

## Error Details / Stack Trace
```
Copy details from the logs or client dialog here.
[```](url)

**Comment by Hemza** [comment]
![credentials](https://cloud.githubusercontent.com/assets/3252236/13287707/b762cde8-db08-11e5-9f7f-fe8d4db92744.PNG)

**Comment by Hemza** [comment]
please i'm new and i want to have a detailed documentation for implementing king fisher

**Comment by zeroSteiner** [comment]
It's spelled "King PHisher" with a "P-H" please. Also you need to read the wiki.

A server needs to be setup with the account you want to log in with. The username and password fields you are seeing correspond to this account that needs to be created on the server.

**Comment by Hemza** [comment]
thanks freind , i undrstand u but the screen captur that i've sent you is launched when i star king phisher server , do you undrstand , when i run  the page is launched and ask me for  the credentials,

**Comment by wolfthefallen** [comment]
Hemza,

You will need to start by setting up a king phisher server ( [Getting started ](https://github.com/securestate/king-phisher/wiki/Getting-Started) ) 

There are two parts to the King Phisher program, One is the King Phisher Server, which manages the database, and website templates.

The second part is the King Phisher Client which is used to interface with the King Phisher Server.

We highly recommend using a linux distro just as [Kali Linux](https://www.kali.org/downloads/), [Ubuntu](ubuntu.com), or [Ubuntu Gnome](https://ubuntugnome.org/).

After setting up your Linux server for King Phisher, you will use the user account on that system to login in from the King Phisher client.

**Comment by Zaryn** [comment]
Salut Hemza!

Dans le futur, poste en l’anglais et le français s’il te plâit. Mon français n’est pas très bien mais j’espère que ça t’aide.

King Phisher a deux parts: le client et le serveur.  Tu utilises le client dans Windows.  Tu manques le serveur, qui a besoin de Linux.  Linux peut fonctionner sur une machine virtuelle ou un autre ordinateur.

Après tu as installé Linux, installe et configure le serveur de King Phisher.  Le nom d’utilisateur et le mot de passe que tu utilise pour le machine Linux (se connecter) est le nom d’utilisateur et le mot de passe que tu utilises pour le client de King Phisher.

############

Hi Hemza!

In the future, please post in both English and French. My French is not very good, but I hope it helps you.

There are two parts to King Phisher: client and server.  The part that you are interacting with is the client portion, which is available in Windows.  The part that you are missing is the server portion, which requires Linux.  A Linux installation can be ran on a virtual machine or another physical computer.

After you have set up Linux, install and set up King Phisher server.  The username and password that you use to access the Linux machine is the username and password that you will use on King Phisher client.

**Comment by Hemza** [comment]
Thank you freinds , sorry for this late reply , i'll start installing King Phisher on linux and try to test a phishing compagne

**Comment by Hemza** [comment]
Hello can any one send me the installation instruction in kali linux, Thank U

**Comment by wolfthefallen** [comment]
For supported linux distros, please see [INSTALL.md](https://github.com/securestate/king-phisher/blob/master/INSTALL.md). The short answer is the following bash commands.

```BASH
cd /opt
git clone https://github.com/securestate/king-phisher.git
cd king-phisher/tools
./install.sh
```

This will install both the client and server for you on your kali linux machine.
to start the King Phisher Server do the following.

```BASH
cd /opt/king-phisher
./KingPhisherServer server_config.yml &
```

then start the client

```BASH
cd /opt/king-phisher
./KingPhisher
```

Your username and password is the username and password you use to **login into kali linux**

**Comment by Hemza** [comment]
Dear Freinds ,

i've try to install King-phisher on kali linux , during execution of installing script , it return this errors :
![error installing kphisher](https://cloud.githubusercontent.com/assets/3252236/13379330/269c3f88-de23-11e5-88cf-87fc1a8606e5.PNG)
![starkingphisher](https://cloud.githubusercontent.com/assets/3252236/13379329/26999f9e-de23-11e5-807b-5f49b47faddf.PNG)

**Comment by Hemza** [comment]
please i'm waiting for ur answers , provide me with more details to of data base configuration

**Comment by Hemza** [comment]
hello, i've run the installation script,  and after execution, i run king-phisher, it return these error , see attached file
![run error](https://cloud.githubusercontent.com/assets/3252236/13392054/467eca90-ded8-11e5-88fe-32a8bb02a6a2.PNG)

**Comment by wolfthefallen** [comment]
Please install smoke zephyr
```BASH
pip install smoke-zephyr
```
You can also do

Pip install -r requirements.txt

From the King Phisher directory

**Comment by Hemza** [comment]
hello erik, i've run the give comds , the same error is returned see attached file

**Comment by Zaryn** [comment]
As-tu installé le <<smoke zephyr>>?

#####

You installed smoke zephyr, right?

**Comment by Hemza** [comment]
![pip cmd error](https://cloud.githubusercontent.com/assets/3252236/13395550/c9d3bc7c-deef-11e5-9031-1fefd8bef708.PNG)

**Comment by Hemza** [comment]
not yet  smoke zephyr   can't be installed

**Comment by Hemza** [comment]
![pip logs](https://cloud.githubusercontent.com/assets/3252236/13396699/5c56b526-def6-11e5-995b-f648d568425c.PNG)

**Comment by zeroSteiner** [comment]
You're having a connection error to pypi.python.org that is preventing pip from retrieving the packages. It might be a rate limit you've exceeded or a faulty internet connection but regardless you need to have all of the requirements from `requirements.txt` installed before the application will run.

Troubleshoot your connection timeout error to pypi.python.org.

**Comment by Hemza** [comment]
is it possible to download it manually and install it manually from a file not by connecting to server
 from cli

**Comment by wolfthefallen** [comment]
Hemza,

You need to address your connectivity issues to pypi.python.org to get the required dependencies installed to run King Phisher.

If you cannot resolve those issues you can look through the ```requirements.txt``` file and see if you can manually download and install the each of the dependencies, but we cannot guarantee that all requirements are available for manual download and install, that would have to be further research on your end.

**Comment by Hemza** [comment]
thank u freind , i've a proposition and i think it's a good idea , if you can prepar a VM machine (linux kali + king phisher installed on) and put a link for download , it a very intresting for every one who want to know  and work on the product ( king-phisher) after testing it, without westing time and blocking on installation,  Thank U

**Comment by zeroSteiner** [comment]
Packaging and distributing a virtual machine with King Phisher is well outside the scope of the project and not currently a venture we are interested in pursuing. Thank you for your suggestion but we will not be doing that.

**Comment by wolfthefallen** [comment]
Hemza,

If you are the latest version of Kali linux you can get King Phisher through apt-get. 

```BASH
apt-get --reinstall install king-phisher
service ssh start
systemctl start king-phisher.service
cd /usr/share/king-phisher/
./KingPhisher
```

Remember your username and password to login into kali is your username and password for King Phisher.

**Comment by Hemza** [comment]
i've try to install it i dont know whats the probleme  i'm try to
troubleshoot to see if its a network connection probleme

Thank u

2016-03-01 20:34 GMT+01:00 Erik Daguerre <notifications@github.com>:

**Comment by wolfthefallen** [comment]
Hemza,

Please make sure you are using the latest version of Kali Linux, which is [Kali Rolling](https://www.kali.org/news/kali-linux-rolling-edition-2016-1/). You can also upgrade to the latest version by adding the rolling repo into your source file and doing a dist-upgrade.

```BASH
cat << EOF > /etc/apt/sources.list
deb http://http.kali.org/kali kali-rolling main non-free contrib
EOF

apt-get update
apt-get dist-upgrade # get a coffee, or 10.
reboot
```

**Comment by Hemza** [comment]
Hello freinds, i've install king-phisher and run the execution script ( i've instaled it on the latest version of Kali)
when i insert the credentials : user name and pwd, it send me an error connection refused 
![connexion refused error 06032016](https://cloud.githubusercontent.com/assets/3252236/13553126/59657dde-e37e-11e5-979a-d6c6504ec8fc.PNG)

**Comment by wolfthefallen** [comment]
Hemza,

I'm glad to see that you have King Phisher installed and running now. You need to start SSH and the King Phisher Server prior to launching the King Phisher Client.

To start the SSH server
```BASH
system ssh start
```
To start the King Phisher Server
```BASH
systemctl start king-phisher.service
```

Then start the King Phisher Client and Log in.

For guide on how to use the King Phisher Client, please see the [How to videos](https://securestate.wistia.com/projects/laevqz2p29)

**Comment by Hemza** [comment]
I've start the ssh server , successfully, but the "systemctl start king-phisher.service" return an error see the attached image, please return me as soon as possible i want to deploy it ive passed long time on the installation step , Thank you for your support
and please provide me with more details and guided
![king-phisher server error](https://cloud.githubusercontent.com/assets/3252236/13554374/6e6a1a8c-e3a6-11e5-84fa-43f74f8130c3.PNG)

**Comment by wolfthefallen** [comment]
Please do the following and then post the error

```BASH
cd /usr/share/king-phisher
./KingPhisherServer -L DEBUG server_config.yml
```

**Comment by Hemza** [comment]
please find attached de debug results
![debug06032016](https://cloud.githubusercontent.com/assets/3252236/13554539/b4d36218-e3aa-11e5-91d7-a4d5fac6e4cd.PNG)

**Comment by Hemza** [comment]
the execution is blocked on the shown step ( database) i think the exec not finish yet

**Comment by wolfthefallen** [comment]
Hemza,

The King Phisher Server is running as intended, Its just a warning that King Phisher does not fully support sqlite. As the King Phisher Server is a process it will continue to run and not return your prompt. 

Please do the following.

```BASH
cd /usr/share/king-phisher
./KingPhisherServer -L DEBUG server_config.yml &
```
This will start your King Phisher server and give you back your command prompt. Then start your King Phisher Client and login.

**Comment by Hemza** [comment]
i've run the given cmds, see attached somme desplayed errors
![debug0603201622](https://cloud.githubusercontent.com/assets/3252236/13554624/2efe91b4-e3ad-11e5-9af4-f15c39f783e9.PNG)


Thank You Freind

**Comment by wolfthefallen** [comment]
Hemza,

You need to stop or kill the process that is already bind to port 80. Once you have stopped or killed that process please try again.

**Comment by Hemza** [comment]
i've killed all processus that use port 80,  and run the cmd , the king phisher didn't start , see attached image :
![kingphisher after killing the processus](https://cloud.githubusercontent.com/assets/3252236/13554890/c990df06-e3b3-11e5-85b3-fb0e7612dd5e.PNG)

**Comment by wolfthefallen** [comment]
Hemza,

From your screenshot you are providing, the King Phisher Server did **start **and is running **correctly**. Please start the King Phisher client and log in. To start the King Phisher Client:

```BASH
cd /usr/share/king-phisher
./KingPhisher
```

**Comment by Hemza** [comment]
Thank you Erik, but after running, i can't connect via ssh 
must i autorize root to connect via ssh  ( /etc/ssh/sshd_config ) file

**Comment by wolfthefallen** [comment]
Hemza,

You can either authorize root via SSH or change server on the login screen just to localhost.

Erik

**Comment by Hemza** [comment]
see attached the error  connexion ssh refused
![connexion refused error 06032016](https://cloud.githubusercontent.com/assets/3252236/13555421/599f6f84-e3c0-11e5-8669-82c4230e9354.PNG)

**Comment by Hemza** [comment]
![kingphisher client connexionerror06032016](https://cloud.githubusercontent.com/assets/3252236/13555428/796a2bba-e3c0-11e5-8141-09d1f571da21.PNG)


This one is the last captured

**Comment by Hemza** [comment]
i can't connect to kali linux via ssh from another machine althought i add root user to the /etc/ssh/sshd_config file

**Comment by wolfthefallen** [comment]
make sure you allow root login in the SSH config, or create another user user account. I recommend using a different user account for increased security.

**Comment by Hemza** [comment]
erik i create a new user but i don't know whats the probleme, i cqn't connect to kingphisher, the same msg is displayed "connexion refused"

**Comment by wolfthefallen** [comment]
Please change Server to from localhost:22 to localhost

**Comment by Hemza** [comment]
Hello sorry for this late reply , i've change "localhost:22 to localhost" but the same error was returned see attached files
![connexion to kingphisher_07032016](https://cloud.githubusercontent.com/assets/3252236/13563613/7070cbd0-e443-11e5-9bd9-e6fddc875296.PNG)
![connexion to kingphisher_kp07032016](https://cloud.githubusercontent.com/assets/3252236/13563612/706fd9a0-e443-11e5-82ec-d3c7312f7f0f.PNG)

**Comment by Hemza** [comment]
can any one help me to trouble shoot this probleme

**Comment by wolfthefallen** [comment]
Hemza,

Your King Phisher client (./KingPhisher) cannot connect to the King Phisher Server (./KingPhisherServer). Please verify that you have the King Phisher Server running and listening on port 80 prior to starting the King Phisher Server.

**Comment by Hemza** [comment]
I've verify step by step yesterday, but here is the result of the test  king phisher server is running but i dont know why i cant connect via SSH
![kingphisher server 07032016 running test](https://cloud.githubusercontent.com/assets/3252236/13571228/d21cc836-e473-11e5-8b91-b12c739d2595.PNG)

**Comment by Hemza** [comment]
i want someoen who help me to troubleshoot step by step i must run it

**Comment by Hemza** [comment]
erik do u have gmail plz to interact directly talk to u directly to trouble shoot the probleme

**Comment by Hemza** [comment]
can some one give me an email to talk with him directly

**Comment by zeroSteiner** [comment]
@Hemza, unfortunately we can no longer continue to invest time and resources into providing the necessary level of support that you require. This issue has been opened for 12 days and I feel that we have been exceedingly responsive throughout the process without any clear progress occurring. As this is a free and open source project, we like many others, are operating and providing the support that you have received thus far with limited resources.

We will not be providing you with any contact information as this is the proper forum for support regarding the project. You need to continue researching the apparent problems with your system and installation. Please continue to refer to the documentation we have provided in the wiki. Beyond that, until there is progress made on your behalf and a **new, clear and concise issue** can be communicated to us, we will no longer be offering you our support.

If you would like to reconsider using King Phisher has your FOSS phishing solution, there exist numerous other solutions, none of which require a client to be installed and configured. You may find them easier to get started with.

 * [Phishing Frenzy](https://github.com/pentestgeek/phishing-frenzy)
 * [gophish](https://github.com/gophish/gophish)

I wish you the best of luck in whatever you try next!
