### ISSUE TITLE
The "open campaign" dialog does not open

### ISSUE THREAD

**Issue by alogon** [securestate/king-phisher#77]
This is the most basic of issues, but I cannot figure out what I have broken...

When I launch the client, I no longer get the "open campaign" dialog. I am stuck in the current campaign and hope to avoid a reinstall. I do not see anything in the server_config.yml file that would disable the dialog, but perhaps I am missing something.

Thank you!

EDIT: Additional information.

There were application menus available in the client that are missing, as well. I did not specify that. File, Edit, etc. are gone. I wonder if I have hit a keyboard combination that hides menus or something along those lines.

**Comment by zeroSteiner** [comment]
The "Open Campaign" dialog is only displayed if a campaign hasn't been selected yet as is the case for the first time you run the client. To start a new campaign or open a previously created one, from within the client just go to the "File" menu and select "Open Campaign".

**Comment by zeroSteiner** [comment]
This hasn't been updated in a week so I'm going to close it out. If you're still experiencing trouble finding it just comment on this thread and I'll reopen it.
