### ISSUE TITLE
Install King phisher templates

### ISSUE THREAD

**Issue by Hemza** [securestate/king-phisher#78]
## Issue Description
Hello i finally install king phisher and it works good i want to know
How can i install King phisher templates 
https://github.com/securestate/king-phisher-templates

and how to configure gmail smtp server to send messages, i've use those parameters but it didn't worked :  smtp.gmail.com:25

myemail@gmail.com
password  but it doesnt work

Thanks for alla who participate in helping me during the installation

**Comment by zeroSteiner** [comment]
The templates repository does not actually need to be installed. You can clone it down and then just place the files where you need them to go. In the case of the email templates you can simply open them with the client.

To send email through gmail you need to use TLS and a different port.

**Comment by Hemza** [comment]
can you ptovide me with detailed config to send email via gmail
and what do you recommand for me

**Comment by zeroSteiner** [comment]
No, we don't provide configuration details for specific SMTP servers. You'll need to look that up for which ever system you intend to use.
