### ISSUE TITLE
Stopping at SPF check

### ISSUE THREAD

**Issue by roobixx** [securestate/king-phisher#82]
## Issue Description
When I go to send emails, it is getting stuck on the checking of the target domains SPF policy. I changed to debugging in the logs but I am getting nothing as to what the issue is. 

if it helps I am running postifx as my smtp sever and the SPF records are in place in my DNS zone file for my target domain.

**Comment by zeroSteiner** [comment]
Can you please post the logs from the mail tab and the debug logs? It sounds like it's having trouble resolving the records.

**Comment by roobixx** [comment]
I determined that the issue is somewhere in the windows client. When I used my linux King Phisher client, I had no issues sending the emails.

When I have time I will try to figure out exactly where the widows client was hanging but I am going to close this issue.

**Comment by zeroSteiner** [comment]
That's great to know, thanks for the update. I'll see if I can reproduce it on my end as well this week.

**Comment by knc331** [comment]
I am also facing the same problem for some of the domains. It would be great if you can look in to the same. Thank you.
