### ISSUE TITLE
Unable to start KingPhisherServer service using config_file.csv file

### ISSUE THREAD

**Issue by itmaniac** [securestate/king-phisher#84]
## Issue Description
Hi ZeroSteiner,
I have installed King Phisher on Ubuntu 15.10 and was trying to start the King phisher server but it was asking for config_file, after reading the documentation, i prepared one file name as config_file.csv and put the basic information but when ever i tried to run it i got error msg mentioned below. need your help to understand the proper way to run the server or do i need to change some parameters/variables in the beginning before running the king phisher server for the first time. 

## Reproduction Steps
1. Start King Phisher
root@ubuntu:/opt/king-phisher/king-phisher-1.2.0# ./KingPhisherServer config_file.csv

2. Do something to trigger the crash

## Error Details / Stack Trace
[-] an error occurred while parsing the server configuration file
Traceback (most recent call last):
  File "./KingPhisherServer", line 215, in <module>
    sys.exit(main())
  File "./KingPhisherServer", line 106, in main
    error_name = "{0}.{1}".format(error.__module__, error.__class__.__name__)
AttributeError: 'exceptions.ValueError' object has no attribute '__module__'

Copy details from the logs or client dialog here.
Config_file.yaml & Config_file.csv file content
IT,Maniac,ITManiac@maniac.com,Student

**Comment by zeroSteiner** [comment]
What you are specifying as the server configuration file is the client's target list. The server's configuration file is a YAML file not CSV. There is a template one under the data directory that should have been copied to the project root directory when you ran the installation script. The server's configuration file's name is server_config.yml and you need to pass it to the server. Keep the target CSV list to load into the client later.

**Comment by itmaniac** [comment]
Thank you. you are the great guy. it worked perfectly and i successfully loaded my server.

**Comment by zeroSteiner** [comment]
Great to hear. I'm going to close this out this issue then. If you have another problem just open a new one.
