### ISSUE TITLE
Open new pop up after inserting 4 caracter of user credentials

### ISSUE THREAD

**Issue by Hemza** [securestate/king-phisher#86]
Hello freind Spencer,
I've a proposition and i want to  see if it's configurable, i want to inform user that he was phished via "pop up message " and this after inserting 3 or 4 characters of the password ( without capturing all user credentials , in some companies it's not legal to capture credentials)

Thank You

**Comment by zeroSteiner** [comment]
Yes, use javascript and HTML. You'll have to write it yourself though as there's nothing builtin to facilitate this.
