### ISSUE TITLE
Deploy landing page

### ISSUE THREAD

**Issue by Hemza** [securestate/king-phisher#87]
## Issue Description
Hello can you explane me please how to deploy exactly the phishing processus, i've install king-phisher and it works good send emails , now i want to set up  a cloned owa exchange login page to send it to users and capture the users who've cliked and insert credentials ; 
King phisher work good, i want to know how to deploy the landing page (web server Url) to get statistics on Kingphisher

Thank you

**Comment by zeroSteiner** [comment]
You place the landing pages into the directory configured as the web root. Please see the wiki page on [Creating Server Content](https://github.com/securestate/king-phisher/wiki/Creating-Server-Content) for more details, specifically read the Configuring the Web Root section at the bottom.
