### ISSUE TITLE
install king-phisher template

### ISSUE THREAD

**Issue by Hemza** [securestate/king-phisher#88]
Hello , 
can you tell me how to install King-phisher template from these repository 

https://github.com/securestate/king-phisher-templates
sorry i mean where to place the landing pages on king phisher car on the wiki there isn't more details
give juste simple diescription of differente steps

Thank you

**Comment by zeroSteiner** [comment]
A template is essentially a landing page, what I told you in issue #87 applies here as well. Doesn't matter if it's a template from the templates repo or a cloned landing page, it goes into the web root. Look at your server's configuration for the `web_root` option, it's probably `/var/www` (the default).
