### ISSUE TITLE
Urgent Please - Error in  installaing King phisher server (Failed to detect the version of Linux)

### ISSUE THREAD

**Issue by raky01** [securestate/king-phisher#93]
Error on the Following command while installaing King phisher server
root@kali:~# sudo /opt/king-phisher-master/tools/install.sh
Failed to detect the version of Linux
This installer only supports the following Linux distributions:
  - BackBox
  - CentOS
  - Debian
  - Fedora
  - Kali
  - Ubuntu

If the current version of Linux is one of these flavors but it is
not recognized, please open a support ticket and include the version.

Thanks in Advance

**Comment by zeroSteiner** [comment]
King Phisher is already provided in the latest version of Kali. Can you please tell me which version of Kali Linux you are using? If you're not using the latest, there is a chance that it's not supported and you'll need to update.

**Comment by raky01** [comment]
Distributor ID:	Kali
Description:	Kali GNU/Linux 1.1.0
Release:	1.1.0
Codename:	moto

**Comment by zeroSteiner** [comment]
Yeah you need to update to Kali 2 or some other newer version of Linux. I highly recommend Ubuntu 15.10 GNOME or in a couple of weeks Ubuntu 16.04.

Kali 1 is no longer supported and hasn't been supported for quite a while.

**Comment by raky01** [comment]
I found the same problem on 
Ubunti 15.10 which code name is willy

**Comment by zeroSteiner** [comment]
Can you post the contents of /etc/issue then?

**Comment by zeroSteiner** [comment]
Yeah I just tried with a fresh install of Ubuntu 15.10 GNOME and the install completed without any apparent issues. The contents of /etc/issue are `Ubuntu 15.10 \n \l`. If your contents are different then that would be a contributing factor to your problem.
