### ISSUE TITLE
Landing page Probleme

### ISSUE THREAD

**Issue by Itrustsecurity** [securestate/king-phisher#94]
## Issue Description
Hi,
I install king-phsiher and hoste landing page (Shell - Anti-Virus_Update (from king-phisher templates) on /var/www/html

## Reproduction Steps
1. Start King Phisher
2. configure phishing compaign
3. enter web server Url --> verify Url send successful message
4. send landing page to users,

## Error Details / Stack Trace

Attached image
KP doesn't get  compaign parameters  ( companu name ...)
![landinf page antivirus update](https://cloud.githubusercontent.com/assets/18242158/14231673/d681b11e-f983-11e5-8010-6bfe77f6dbf1.PNG)

the KP doesnt get users visits and credentials

Copy details from the logs or client dialog here.
```

**Comment by wolfthefallen** [comment]
After copying a website from [King Phisher Templates](https://github.com/securestate/king-phisher-templates) you need to update the website according to the websites README.md file. 

For this case please update accordingly to the Anti-virus Update templates [README.md](https://github.com/securestate/king-phisher-templates/blob/master/Website_Templates/Credentials/Anti-Virus_Update/README.md). For further issues on templates please open the issue on the appropriate repository. 

Also make sure you are copying the entire templates website files to your King Phishers /var/www path, and you are using the correct landing page of the site. As the information you are looking for is collected by the King Phisher Server when the phished user is redirected to another page.

**Comment by Itrustsecurity** [comment]
i've deploy the template on the appropriate folder /var/www 
The url is accessible 
but when users click on the link , visit de web page , and insert credentials , king-Phisher doesn't display those statistics on the dashbord,
C'an' t get  Compagn visits, credentials , Os information
cant you help me to troublshoot this probleme

**Comment by zeroSteiner** [comment]
If your page isn't rendering it looks like a problem with the server. You do have the server running correct? I would start out by looking through the server logs and verifying:
1) You see a request for the template page coming in
2) You don't see any kind of template rendering error

The fact that the templates are not rendering is indicative of a larger problem with your setup.

**Comment by Itrustsecurity** [comment]
but i think the setup is simple :
- website on /var/www/html
- require_id  enabled
- vhost_directories to false
is there another configuration to do ??

**Comment by zeroSteiner** [comment]
The setup is simple, but there is obviously something is not working. Please review and post the logs if you think everything is correct. Without the logs and additional details we can not provide further insight into the issue.

**Comment by wolfthefallen** [comment]
@Itrustsecurity is the landing page rendering correctly when you do a test email phish to yourself?
also please provide the logs from your king phisher server, it is normally located  /var/log/king-phisher.log of you trying to visit the website with your test phish.

**Comment by Itrustsecurity** [comment]
hello,
No , the same page is displayed  the variables parameteres are not displayed, i've see on logs i think the probleme is that King-phisher doesnt bind apach with port 80
and the KP doesnt know the  server adrss althought it's specified on the config file
see attached the logs

**Comment by wolfthefallen** [comment]
@Itrustsecurity 

From what i'm currently seeing it appears that you have a different web server to hosting your landing page for the assessment, and thus King Phisher will not be able to track the information. King Phisher Server hosts its own pages for the assessments so it can gather the information as users click links and open emails. 

With your current configuration you would need to adjust your WebServer URL to use port 8081 (IE: http://<host>:8081/<landing page> ) for King Phisher to collect the information for the campaign. I would recommend shutting down the other web server and moving King Phisher back to port 80.

**Comment by Itrustsecurity** [comment]
@wolfthefallen 

If i adjust the webserver url to use port 80  i can't run KP on port 80 ( i mean if i start apache on port 80  i cant run KP to use port80
let you know yhant i've start KP on the recommended port 80, but the probleme can't start apach on port 80
Do you have any suggestion about this point ???

**Comment by Itrustsecurity** [comment]
@wolfthefallen 

i 've run KP on port 80
i've read that "The King Phisher Server runs a self contained HTTP server and does not require an additional one such as Apache, or Nginx."
can you tell me how to run this HTTP server 
i try to access the landing page by running apache, if i stop apach the landing page will be inaccessible 
Can you give me some information about the HTTP server of king phisher and how to use it

**Comment by wolfthefallen** [comment]
@Itrustsecurity 

[Configuring the web root](https://github.com/securestate/king-phisher/wiki/Creating-Server-Content#configuring-the-web-root) provides you the information you are seeking. If you have additional questions please let me know.

**Comment by zeroSteiner** [comment]
As @wolfthefallen suggested the wiki has all of the details you need to setup the King Phisher web server. You can also see the INSTALL.md file in the project root for installation instructions if you have not already done so.

**Comment by Itrustsecurity** [comment]
@wolfthefallen 

I've read the documentations WIKI, i want just to know , if i must  use apache server and start it on port 80 or , user KP HTTP server , i didnt find many information about his last one HTTP server  "The King Phisher Server runs a self contained HTTP server and does not require an additional one such as Apache, or Nginx."
sorry but i 'm always refering to the wiki but i didnt find info about it

**Comment by zeroSteiner** [comment]
You do not need apache or nginx at all. You can completely uninstall them if you'd like but at the very least they need to be not running and their respective services disabled. The idea is that you run the King Phiser Server in place of apache or nginx meaning they are not necessary and must not conflict.

**Comment by Itrustsecurity** [comment]
Thank you, 
i've intall KP successfully , run it on port 80, but i can't access the landing page 
what can i do to trouble shoot this probleme

**Comment by wolfthefallen** [comment]
@Itrustsecurity 

are you getting an error page, stating 404 page not found?

**Comment by Itrustsecurity** [comment]
yes exactly error (Error 404: Page Not Found

Sorry, the page you were looking for doesn't exist.),

juste another : can you tell me what are the contents of kp.js script

**Comment by wolfthefallen** [comment]
Under your current configuration you must have an ID that is issued when you send out a phishing email to view a web page in the King Phisher Server's www directory. This is the require_id setting in your server_config file. I recommend you send your self a test email for your current campaign and click the link for testing. Since your server is up and running I recommend watching the [video guides](https://securestate.wistia.com/projects/laevqz2p29).

**Comment by Itrustsecurity** [comment]
@wolfthefallen 

I've install KP and it works good,
connecting remotly ,
create phoshing compaign and send phishing test emails
i click on the links but its not accessible until i start (kp on port 8081 and apache on 80) then the web landing page become accessible
the probleme is that i can't access KP landing page  without apache , HTTP server  of KP doesn't work correctly
the second probleme : i didn't receive infos about , link click and visits , ....credentials

---> can you please tell me where to find the kp.js script , i've add the (script src="/kp.js" type="text/javascript"></script>) to wrb pages headers, but i can't find the script , i want to put the script on the directory (/kp.js) and run apache  to see if it works 
i hope you've undrstand my probleme, if you want i'll explane differently

thanks

**Comment by zeroSteiner** [comment]
**Stop running Apache, uninstall it and do not use it again while trying to use King Phisher.**

You probably need to update your links and resend emails with the correct configuration using port 80. This thread is approaching the level of support that we can not provide. Please attempt to troubleshoot the problem on your end and follow our instructions coupled with those provided in the wiki.

**Comment by Itrustsecurity** [comment]
@zeroSteiner 
i stop apache , but the landing page is not accessible ??
/var/www ??
can you give me a help about kp.js script ( read the previous msg)

**Comment by zeroSteiner** [comment]
`/kp.js` is provided by the King Phisher server, it's a special resource that is loaded from a template file. This means that there isn't a kp.js file on disk, it's created dynamically with each request by the server.

**Comment by Itrustsecurity** [comment]
Thank you for this information,
if you want more details about my configuration i 'll give u all the informations to help me troubleshoot  the probleme,
Becuz i think that the deployement is simple and not hard , 

i m waiting for your help and looking for a solution on the KP doc

**Comment by Itrustsecurity** [comment]
Hi, 

Finally KP worked good, i've juste change require_id value  to false , and it woked good, 


Thank you very well

**Comment by zeroSteiner** [comment]
Excellent, glad to hear that you were able to fix your issues.
