### ISSUE TITLE
Send Message with a fake e-mail address

### ISSUE THREAD

**Issue by Itrustsecurity** [securestate/king-phisher#96]
## Issue Description
Hi;
i wanted to know if it's possible to send phishing email with a fake e-mail address
ex: send email with addresse@gmail.com and a fake email address addresse2@mycompany.com will appear on email  ( to test users attention ) 

if it's possible please tell me how to do it with KP

**Comment by zeroSteiner** [comment]
Yes it is possible, just change the corresponding fields and hope it doesn't get picked off as spam.

**Comment by Itrustsecurity** [comment]
i've change the corresponding fields ( SMTP, MIME)  but the original ( gmail ) email address appear and not the fake email , is there any solution for this ??
