### ISSUE TITLE
IR : about http capacity request

### ISSUE THREAD

**Issue by Itrustsecurity** [securestate/king-phisher#97]
hello ,
i'm going to test KP and send emails to a big number of users , can you tell me more about the capacity of http server, to be sur that there will not be interupptions during to this operation

**Comment by zeroSteiner** [comment]
It will be fine, we've run campaigns of over 35,000 emails without any issues. The client will slow down a bit as it loads all the data but the server itself will be fine. Also I highly recommend using the PostgreSQL database backend for multiple reasons.

In the future please try to obtain the answer to simple questions through experimentation or by asking in the IRC channel.
