### ISSUE TITLE
Failed to authenticate to the SMTP server

### ISSUE THREAD

**Issue by cyopk** [securestate/king-phisher#98]
Hey, thanks for developing king-phisher it looks really cool. 

I haven't managed to connect to the SMTP server when I enter my password after starting to send out the phishing emails. Is there anyway you could advise me on what I might be doing wrong? I'm using my gmail account as the SMTP username. 

Hope you guys can help and thanks in advance - would love to get king-phisher up and running :)

**Comment by zeroSteiner** [comment]
You're not the first person to ask so I decided it's time this got some details in the wiki. You can now find the recommended settings and some other details for using Gmail in the [FAQ](https://github.com/securestate/king-phisher/wiki/Frequently-Asked-Questions#how-do-i-send-messages-through-gmail).

Be warned though that the GMail servers are pretty picky about identifying messages as spam and dropping them. You'll probably have to craft your email configuration (including attachments) carefully.

**Comment by cyopk** [comment]
Thank you so much for your quick response. I definitely didn't configure the settings as you've shown so im sure it will work but I'll give this a try tonight and let you know if it's all working! 

Cool, thats good to know. I'll keep that in mind about using gmail. Thanks again!

**Comment by cyopk** [comment]
Yeah the info in the wiki was perfect - working all good now thanks again so much :)

**Comment by Olanxx** [comment]
failed to authenticate to the smtp server
